### ISSUE TITLE
runtime error: can't set qtscheduler attribute 'next_job'

### ISSUE THREAD

**Issue by kaymmm** [borgbase/vorta#1]
Tried running it on my Arch Linux machine and am getting the following error:

```
Traceback (most recent call last):
  File "/home/kmiyake/miniconda3/envs/vorta/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/kmiyake/miniconda3/envs/vorta/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/mnt/ostrich/kmiyake/Developer/vorta/src/vorta/__main__.py", line 23, in <module>
    app = VortaApp(sys.argv)
  File "/mnt/ostrich/kmiyake/Developer/vorta/src/vorta/application.py", line 20, in __init__
    self.scheduler = VortaScheduler(self)
  File "/mnt/ostrich/kmiyake/Developer/vorta/src/vorta/scheduler.py", line 14, in __init__
    self.reload()
  File "/mnt/ostrich/kmiyake/Developer/vorta/src/vorta/scheduler.py", line 19, in reload
    self.next_job = 'Manual Backups'
AttributeError: can't set attribute
```

I have no experience using apscheduler/qtscheduler so I'm not much help with pinpointing or debugging, but hopefully this is something simple.

Also worth noting that I had to manually add apscheduler since it wasn't one of the anaconda deps, as well as sentry_sdk, which I had to do manually since it doesn't appear to have an anaconda package.

**Comment by m3nu** [comment]
Hi, thanks a lot for testing. That's just an error on my side after I changed the `next_job` attribute. I'll fix it with the next release.

It should be cross-platform EXCEPT for the Wifi network list. I'll make sure this doesn't break it.

**Comment by m3nu** [comment]
Fixed.
