### ISSUE TITLE
Issues with Keyring Service on Linux

### ISSUE THREAD

**Issue by bpereto** [borgbase/vorta#10]
Vorta Version: Master Branch (0.3.1)
Linux: Arch Linux

```
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
Traceback (most recent call last):
  File "/home/beni/devel/git/vorta/.venv/lib/python3.7/site-packages/vorta/borg/borg_thread.py", line 149, in run
    self.process_result(result)
  File "/home/beni/devel/git/vorta/.venv/lib/python3.7/site-packages/vorta/borg/info.py", line 57, in process_result
    keyring.set_password("vorta-repo", new_repo.url, result['params']['password'])
  File "/home/beni/devel/git/vorta/.venv/lib/python3.7/site-packages/keyring/core.py", line 64, in set_password
    _keyring_backend.set_password(service_name, username, password)
  File "/home/beni/devel/git/vorta/.venv/lib/python3.7/site-packages/keyring/backends/SecretService.py", line 80, in set_password
    collection = self.get_preferred_collection()
  File "/home/beni/devel/git/vorta/.venv/lib/python3.7/site-packages/keyring/backends/SecretService.py", line 49, in get_preferred_collection
    bus = secretstorage.dbus_init()
  File "/home/beni/devel/git/vorta/.venv/lib/python3.7/site-packages/secretstorage/__init__.py", line 37, in dbus_init
    connection = connect_and_authenticate()
  File "/home/beni/devel/git/vorta/.venv/lib/python3.7/site-packages/jeepney/integrate/blocking.py", line 82, in connect_and_authenticate
    conn = DBusConnection(sock)
  File "/home/beni/devel/git/vorta/.venv/lib/python3.7/site-packages/jeepney/integrate/blocking.py", line 20, in __init__
    hello_reply = self.bus_proxy.Hello()
  File "/home/beni/devel/git/vorta/.venv/lib/python3.7/site-packages/jeepney/integrate/blocking.py", line 64, in inner
    return self._connection.send_and_get_reply(msg)
  File "/home/beni/devel/git/vorta/.venv/lib/python3.7/site-packages/jeepney/integrate/blocking.py", line 45, in send_and_get_reply
    future = self.send_message(message)
  File "/home/beni/devel/git/vorta/.venv/lib/python3.7/site-packages/jeepney/integrate/blocking.py", line 24, in send_message
    future = self.router.outgoing(message)
  File "/home/beni/devel/git/vorta/.venv/lib/python3.7/site-packages/jeepney/routing.py", line 26, in outgoing
    self.awaiting_reply[msg.header.serial] = handle = self.handle_factory()
  File "/usr/lib/python3.7/asyncio/events.py", line 644, in get_event_loop
    % threading.current_thread().name)
RuntimeError: There is no current event loop in thread 'Dummy-1'.
```
Seems to be an issue with threading and adding the passwort to the keyring?
Manual add the secret is working:
```
>>> import keyring
>>> from keyring.backends import SecretService
>>> keyring.set_keyring(SecretService.Keyring())
>>> keyring.set_password("vorta-repo", 'test', 'test')
```

**Comment by m3nu** [comment]
Will test this in my Ubuntu VM.

**Comment by bpereto** [comment]
Same kind of exception when running a scheduled backup.
To eliminate python problems, I runned it with python3.6 instead of 3.7 like above.

Reproduce:
* Open Vorta
* Go to schedule tab
* set daily backup to +1 minute and click apply
* keep open vorta

```
Job "VortaScheduler.create_backup (trigger: cron[hour='15', minute='26'], next run at: 2018-11-10 15:26:00 CET)" raised an exception
Traceback (most recent call last):
  File "/home/beni/devel/git/vorta/.venv36/lib/python3.6/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/home/beni/devel/git/vorta/src/vorta/scheduler.py", line 50, in create_backup
    msg = BorgCreateThread.prepare(self.profile())
  File "/home/beni/devel/git/vorta/src/vorta/borg/create.py", line 51, in prepare
    ret = super().prepare(profile)
  File "/home/beni/devel/git/vorta/src/vorta/borg/borg_thread.py", line 93, in prepare
    ret['password'] = keyring.get_password("vorta-repo", profile.repo.url)  # None if no password.
  File "/home/beni/devel/git/vorta/.venv36/lib/python3.6/site-packages/keyring/core.py", line 58, in get_password
    return _keyring_backend.get_password(service_name, username)
  File "/home/beni/devel/git/vorta/.venv36/lib/python3.6/site-packages/keyring/backends/SecretService.py", line 67, in get_password
    collection = self.get_preferred_collection()
  File "/home/beni/devel/git/vorta/.venv36/lib/python3.6/site-packages/keyring/backends/SecretService.py", line 49, in get_preferred_collection
    bus = secretstorage.dbus_init()
  File "/home/beni/devel/git/vorta/.venv36/lib/python3.6/site-packages/secretstorage/__init__.py", line 37, in dbus_init
    connection = connect_and_authenticate()
  File "/home/beni/devel/git/vorta/.venv36/lib/python3.6/site-packages/jeepney/integrate/blocking.py", line 82, in connect_and_authenticate
    conn = DBusConnection(sock)
  File "/home/beni/devel/git/vorta/.venv36/lib/python3.6/site-packages/jeepney/integrate/blocking.py", line 20, in __init__
    hello_reply = self.bus_proxy.Hello()
  File "/home/beni/devel/git/vorta/.venv36/lib/python3.6/site-packages/jeepney/integrate/blocking.py", line 64, in inner
    return self._connection.send_and_get_reply(msg)
  File "/home/beni/devel/git/vorta/.venv36/lib/python3.6/site-packages/jeepney/integrate/blocking.py", line 45, in send_and_get_reply
    future = self.send_message(message)
  File "/home/beni/devel/git/vorta/.venv36/lib/python3.6/site-packages/jeepney/integrate/blocking.py", line 24, in send_message
    future = self.router.outgoing(message)
  File "/home/beni/devel/git/vorta/.venv36/lib/python3.6/site-packages/jeepney/routing.py", line 26, in outgoing
    self.awaiting_reply[msg.header.serial] = handle = self.handle_factory()
  File "/usr/lib/python3.6/asyncio/events.py", line 694, in get_event_loop
    return get_event_loop_policy().get_event_loop()
  File "/usr/lib/python3.6/asyncio/events.py", line 602, in get_event_loop
    % threading.current_thread().name)
RuntimeError: There is no current event loop in thread 'ThreadPoolExecutor-0_0'.
```

**Comment by m3nu** [comment]
That's a shame. I was hoping the `keyring` package would just abstract it.

**Comment by m3nu** [comment]
Example of an error: https://sentry.io/share/issue/50cccbf74d3142aca4d0fb7f7b2a4059/

This tells me a fallback is needed if the password store isn't available/doesn't work.

**Comment by m3nu** [comment]
I added a fallback keychain that will save the password to the database.

First it will test if `SecretService` is working and use that if possible. Let me know if this fixes the problem. I only have Ubuntu around to test it.
