### ISSUE TITLE
ImportError: /usr/lib/libgssapi_krb5.so.2: undefined symbol: k5_cc_store_primary_cred, version krb5_3_MIT

### ISSUE THREAD

**Issue by verenaHeusser** [borgbase/vorta#1035]
**Describe the bug**

vorta does not start, it throws this exception immediately:

```
2021-07-13 21:29:20,544 - root - CRITICAL - Uncaught exception, file a report at https://github.com/borgbase/vorta/issues/new
Traceback (most recent call last):
  File "/home/veheu/.local/bin/vorta", line 8, in <module>
    sys.exit(main())
  File "/home/veheu/.local/lib/python3.8/site-packages/vorta/__main__.py", line 57, in main
    from vorta.application import VortaApp
  File "/home/veheu/.local/lib/python3.8/site-packages/vorta/application.py", line 16, in <module>
    from vorta.qt_single_application import QtSingleApplication
  File "/home/veheu/.local/lib/python3.8/site-packages/vorta/qt_single_application.py", line 2, in <module>
    from PyQt5.QtNetwork import QLocalSocket, QLocalServer
ImportError: /usr/lib/libgssapi_krb5.so.2: undefined symbol: k5_cc_store_primary_cred, version krb5_3_MIT
```

**To Reproduce**

Happens when just starting `vorta`

**Environment (please complete the following information):**
- OS: Manjaro
- Vorta version: 0.7.7
- Installed from: pip

**Comment by olivierlemoal** [comment]
Is your distro packages up-to-date ? What's the output of `pacman -Qi krb5 python-pyqt5` ?

**Comment by verenaHeusser** [comment]
Yes, the system is fully up to date.
```
pacman -Qi krb5 python-pyqt5
Name            : krb5
Version         : 1.19.1-1
Description     : The Kerberos network authentication system
Architecture    : x86_64
URL             : https://web.mit.edu/kerberos/
Licenses        : custom
Groups          : None
Provides        : libgssapi_krb5.so=2-64  libgssrpc.so=4-64  libk5crypto.so=3-64  libkadm5clnt_mit.so=12-64  libkadm5srv_mit.so=12-64  libkdb5.so=10-64  libkdb_ldap.so=1-64  libkrad.so=0-64  libkrb5.so=3-64  libkrb5support.so=0-64  libverto.so=0-64
Depends On      : glibc  e2fsprogs  libss.so=2-64  libcom_err.so=2-64  libldap  keyutils
Optional Deps   : None
Required By     : audit  cifs-utils  curl  evolution-data-server  gnome-online-accounts  gssproxy  lib32-krb5  libcups  libsoup  libtirpc  neon  nfsidmap  openconnect  openssh  s-nail
Optional For    : None
Conflicts With  : None
Replaces        : None
Installed Size  : 4,50 MiB
Packager        : Levente Polyak <anthraxx@archlinux.org>
Build Date      : So 21 Mär 2021 14:16:12 CET
Install Date    : Di 13 Apr 2021 12:52:18 CEST
Install Reason  : Installed as a dependency for another package
Install Script  : No
Validated By    : Signature

Name            : python-pyqt5
Version         : 5.15.4-1
Description     : A set of Python bindings for the Qt5 toolkit
Architecture    : x86_64
URL             : https://riverbankcomputing.com/software/pyqt/intro
Licenses        : GPL
Groups          : pyqt5
Provides        : qt5-python-bindings
Depends On      : python-pyqt5-sip  qt5-base
Optional Deps   : python-opengl: enable OpenGL 3D graphics in PyQt applications [installed]
                  python-dbus: for python-dbus mainloop support [installed]
                  qt5-multimedia: QtMultimedia, QtMultimediaWidgets [installed]
                  qt5-tools: QtHelp, QtDesigner [installed]
                  qt5-svg: QtSvg [installed]
                  qt5-webkit: QtWebKit, QtWebKitWidgets [installed]
                  qt5-xmlpatterns: QtXmlPatterns
                  qt5-declarative: QtQml, qmlplugin [installed]
                  qt5-serialport: QtSerialPort
                  qt5-websockets: QtWebSockets [installed]
                  qt5-connectivity: QtNfc, QtBluetooth
                  qt5-x11extras: QtX11Extras [installed]
                  qt5-remoteobjects: QtRemoteObjects
                  qt5-speech: QtTextToSpeech [installed]
                  qt5-quick3d: QtQuick3D
Required By     : anki  manjaro-printer  pulseaudio-equalizer  python-pyqt5-webengine  vorta
Optional For    : hplip  kauth  kcodecs  kcompletion  kconfig  kconfigwidgets  kcoreaddons  kdbusaddons  kguiaddons  ki18n  kitemmodels  kitemviews  kjobwidgets  kwidgetsaddons  python-pandas  python-pillow
Conflicts With  : pyqt5-common
Replaces        : None
Installed Size  : 26,65 MiB
Packager        : Antonio Rojas <arojas@archlinux.org>
Build Date      : Mi 10 Mär 2021 17:50:20 CET
Install Date    : So 21 Mär 2021 12:08:42 CET
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : Signature

```

The above error happened when I installed vorta within conda (hence the python3.8 version).  If I install it in the manjaro python3.9 I get a different issue:

```
$ pip install vorta
Defaulting to user installation because normal site-packages is not writeable
WARNING: Keyring is skipped due to an exception: Failed to unlock the collection!
Collecting vorta
  Using cached vorta-0.7.7.tar.gz (622 kB)
  WARNING: Generating metadata for package vorta produced metadata for project name unknown. Fix your #egg=vorta fragments.
Requirement already satisfied (use --upgrade to upgrade): unknown from https://files.pythonhosted.org/packages/61/4a/970dc208850fa453f3ba14b843a13feac1ad34000005ff76d647e6627001/vorta-0.7.7.tar.gz#sha256=0c75609d71b733251791de4f8e8c64893cf8d98b21d315104399ef47eb2d952f in /home/veheu/.local/lib/python3.9/site-packages
Building wheels for collected packages: unknown, unknown
  Building wheel for unknown (setup.py) ... done
  Created wheel for unknown: filename=UNKNOWN-0.0.0-py3-none-any.whl size=490280 sha256=b9b924e55d64bf3bcf9cf77e1d414c781544bdf1d004670663b51eaaf062cba7
  Stored in directory: /home/veheu/.cache/pip/wheels/eb/65/f6/6f6acd3601a09689a0ba5e7a6509d80c8a1ecaa11871300d0a
  Building wheel for unknown (setup.py) ... done
  Created wheel for unknown: filename=UNKNOWN-0.0.0-py3-none-any.whl size=490280 sha256=b9b924e55d64bf3bcf9cf77e1d414c781544bdf1d004670663b51eaaf062cba7
  Stored in directory: /home/veheu/.cache/pip/wheels/de/47/40/40f0b318c7a7a561d81db9d375c76e7dcbb6053c36b073d300
Successfully built unknown unknown

$ vorta
zsh: command not found: vorta

```

**Comment by bastiencyr** [comment]
Hello @verenaHeusser , 
Installed vorta with pip is not the preferred way. The problem you encountered should not be happened with an official package from your distribution. 
If you really want to use pip (but for some reason, its not a good idea), it seems that vorta is not in your path. You can list the binaries folders in your path with : `echo $PATH` . Try to temprarly add the bin folder of .local to your path with the command `PATH=$PATH:/home/veheu/.local/bin . Retry to lunch vorta after.

**Comment by verenaHeusser** [comment]
I searched for the line `Generating metadata for package vorta produced metadata for project name unknown.` from the pip install and found [this issue](https://github.com/lief-project/LIEF/issues/108).


After installing setuptools it works:
```
$ pip install setuptools --upgrade
Defaulting to user installation because normal site-packages is not writeable
Collecting setuptools
  Using cached setuptools-57.2.0-py3-none-any.whl (818 kB)
Installing collected packages: setuptools
  Attempting uninstall: setuptools
    Found existing installation: setuptools 28.6.1
    Uninstalling setuptools-28.6.1:
      Successfully uninstalled setuptools-28.6.1
Successfully installed setuptools-57.2.0
```

```
$ pip install vorta
$ vorta
2021-07-16 15:25:40,591 - vorta.i18n - DEBUG - Loading translation succeeded for ['en', 'en-US', 'en-Latn-US'].
```

So apparently it's some interaction with setuptools. No idea if fixing this better requires action on your side or if my setup was just weird.

**Comment by vv111y** [comment]
I had more trouble than that. There might also be conflict issues with `Anaconda`  
I used `pipx` and even then it wouldn't work until I specified deps and the system python:   
```
pipx install --include-deps --python /usr/bin/python3 vorta
```   
You may also need to `deactivate` anaconda `base` environment if you have you are using anaconda.  
Finally with all that vorta was installed in its own environment with its own deps
