### ISSUE TITLE
Vorta won't start - Uncaught exception

### ISSUE THREAD

**Issue by elman22** [borgbase/vorta#1040]
When I try start vorta GUI is not shown and instead I have uncaught exception in console. I moved with my notebook from one timezone to another, so there might be some obsolete configuration from previous location.

```
2021-07-20 10:30:25,464 - root - CRITICAL - Uncaught exception, file a report at https://github.com/borgbase/vorta/issues/new
Traceback (most recent call last):
  File "/usr/bin/vorta", line 33, in <module>
    sys.exit(load_entry_point('vorta==0.7.7', 'gui_scripts', 'vorta')())
  File "/usr/lib/python3.9/site-packages/vorta/__main__.py", line 58, in main
    app = VortaApp(sys.argv, single_app=args.profile is None)
  File "/usr/lib/python3.9/site-packages/vorta/application.py", line 61, in __init__
    self.scheduler = VortaScheduler(self)
  File "/usr/lib/python3.9/site-packages/vorta/scheduler.py", line 22, in __init__
    super().__init__()
  File "/usr/lib/python3.9/site-packages/apscheduler/schedulers/base.py", line 87, in __init__
    self.configure(gconfig, **options)
  File "/usr/lib/python3.9/site-packages/apscheduler/schedulers/base.py", line 131, in configure
    self._configure(config)
  File "/usr/lib/python3.9/site-packages/apscheduler/schedulers/base.py", line 702, in _configure
    self.timezone = astimezone(config.pop('timezone', None)) or get_localzone()
  File "/usr/lib/python3.9/site-packages/tzlocal/unix.py", line 165, in get_localzone
    _cache_tz = _get_localzone()
  File "/usr/lib/python3.9/site-packages/tzlocal/unix.py", line 90, in _get_localzone
    utils.assert_tz_offset(tz)
  File "/usr/lib/python3.9/site-packages/tzlocal/utils.py", line 46, in assert_tz_offset
    raise ValueError(msg)
ValueError: Timezone offset does not match system offset: 43200 != 7200. Please, check your config files.

```

I'm using Manjaro testing and vorta 0.7.7-1.

If you need more logs or configuration, let me know.

**Comment by m3nu** [comment]
`ValueError: Timezone offset does not match system offset: 43200 != 7200.`

Looks like an issue with timezone settings in another package, `apscheduler`. That's another project/library we use. Maybe they have more details on this.

**Comment by elman22** [comment]
Thank you. That issue gave me good pointers. I had to manually change timezone in `/etc/timezone` because it contained timezone where I installed Manjaro, but wasn't updated when I changed timezone via GUI.

**Comment by elman22** [comment]
So I will close this issue as duplicity to #78.
