### ISSUE TITLE
Schedule time divided by 24

### ISSUE THREAD

**Issue by amiroslaw** [borgbase/vorta#106]
vorta 0.6.3-1

When you fixed the bug [#101](https://github.com/borgbase/vorta/issues/101), you made new one. 
Now if a user change backup schedule to a number which is divided by 24, he will get: 

```python
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/vorta/views/schedule_tab.py", line 112, in on_scheduler_apply
    self.app.scheduler.reload()
  File "/usr/lib/python3.7/site-packages/vorta/scheduler.py", line 33, in reload
    minute=profile.schedule_interval_minutes)
  File "/usr/lib/python3.7/site-packages/apscheduler/triggers/cron/__init__.py", line 82, in __init__
    field = field_class(field_name, exprs, is_default)
  File "/usr/lib/python3.7/site-packages/apscheduler/triggers/cron/fields.py", line 33, in __init__
    self.compile_expressions(exprs)
  File "/usr/lib/python3.7/site-packages/apscheduler/triggers/cron/fields.py", line 58, in compile_expressions
    self.compile_expression(expr)
  File "/usr/lib/python3.7/site-packages/apscheduler/triggers/cron/fields.py", line 64, in compile_expression
    compiled_expr = compiler(**match.groupdict())
  File "/usr/lib/python3.7/site-packages/apscheduler/triggers/cron/expressions.py", line 22, in __init__
    raise ValueError('Increment must be higher than 0')
ValueError: Increment must be higher than 0
```

**Comment by m3nu** [comment]
Already fixed for v0.6.4. https://github.com/borgbase/vorta/pull/104

This solution isn't great either, so I may change the interface a bit to support entering days at a later time.
