### ISSUE TITLE
Unable to add repo

### ISSUE THREAD

**Issue by xLogiiCx** [borgbase/vorta#1067]
```
Traceback (most recent call last):
  File "/app/lib/python3.7/site-packages/peewee.py", line 6665, in get
    return clone.execute(database)[0]
  File "/app/lib/python3.7/site-packages/peewee.py", line 4121, in __getitem__
    return self.row_cache[item]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/lib/python3.7/site-packages/vorta/application.py", line 221, in react_to_log
    profile = BackupProfileModel.get(name=context['profile_name'])
  File "/app/lib/python3.7/site-packages/peewee.py", line 6242, in get
    return sq.get()
  File "/app/lib/python3.7/site-packages/peewee.py", line 6670, in get
    (clone.model, sql, params))
vorta.models.BackupProfileModelDoesNotExist: <Model: BackupProfileModel> instance matching query does not exist:
SQL: SELECT "t1"."id", "t1"."name", "t1"."added_at", "t1"."repo_id", "t1"."ssh_key", "t1"."compression", "t1"."exclude_patterns", "t1"."exclude_if_present", "t1"."schedule_mode", "t1"."schedule_interval_hours", "t1"."schedule_interval_minutes", "t1"."schedule_fixed_hour", "t1"."schedule_fixed_minute", "t1"."validation_on", "t1"."validation_weeks", "t1"."prune_on", "t1"."prune_hour", "t1"."prune_day", "t1"."prune_week", "t1"."prune_month", "t1"."prune_year", "t1"."prune_keep_within", "t1"."new_archive_name", "t1"."prune_prefix", "t1"."pre_backup_cmd", "t1"."post_backup_cmd", "t1"."dont_run_on_metered_networks" FROM "backupprofilemodel" AS "t1" WHERE ("t1"."name" = ?) LIMIT ? OFFSET ?
Params: ['New Repo', 1, 0]
```

**Comment by m3nu** [comment]
If this is still an issue, please add some more details. Like steps to reproduce. Thanks!

**Comment by Tamschi** [comment]
I got this too just now:

```
Uncaught exception, please file a report with this text at
https://github.com/borgbase/vorta/issues/new
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/peewee.py", line 7077, in get
    return clone.execute(database)[0]
  File "/usr/lib/python3.10/site-packages/peewee.py", line 4441, in __getitem__
    return self.row_cache[item]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/vorta/application.py", line 224, in react_to_log
    profile = BackupProfileModel.get(name=context['profile_name'])
  File "/usr/lib/python3.10/site-packages/peewee.py", line 6629, in get
    return sq.get()
  File "/usr/lib/python3.10/site-packages/peewee.py", line 7080, in get
    raise self.model.DoesNotExist('%s instance matching query does '
vorta.store.models.BackupProfileModelDoesNotExist: <Model: BackupProfileModel> instance matching query does not exist:
SQL: SELECT "t1"."id", "t1"."name", "t1"."added_at", "t1"."repo_id", "t1"."ssh_key", "t1"."compression", "t1"."exclude_patterns", "t1"."exclude_if_present", "t1"."schedule_mode", "t1"."schedule_interval_count", "t1"."schedule_interval_unit", "t1"."schedule_fixed_hour", "t1"."schedule_fixed_minute", "t1"."schedule_interval_hours", "t1"."schedule_interval_minutes", "t1"."schedule_make_up_missed", "t1"."validation_on", "t1"."validation_weeks", "t1"."prune_on", "t1"."prune_hour", "t1"."prune_day", "t1"."prune_week", "t1"."prune_month", "t1"."prune_year", "t1"."prune_keep_within", "t1"."new_archive_name", "t1"."prune_prefix", "t1"."pre_backup_cmd", "t1"."post_backup_cmd", "t1"."dont_run_on_metered_networks" FROM "backupprofilemodel" AS "t1" WHERE ("t1"."name" = ?) LIMIT ? OFFSET ?
Params: ['New Repo', 1, 0]
```

I created the repository and ran the backup as root on my tablet onto and SD card and shut the system down there after validating it. On my main PC, I gave everyone read and write permissions recursively and tried to open the repository as normal user. I'm also unable to open the repository as root, with the same error.

**Comment by m3nu** [comment]
This is a Vorta error about some profile and won't affect your Borg repo. Would be best to debug this Vorta error. Though I've never managed to reproduce it.
