### ISSUE TITLE
Vorta does not launch

### ISSUE THREAD

**Issue by fdagnat** [borgbase/vorta#1069]
Hello,

Vorta seems great and I wanted to give it a try (I'm current a terminal borg user). But unfortunately the app does not launch.

Starting from terminal, I get

```
<...:573> /Applications/Vorta.app/Contents/MacOS/vorta-darwin
2021-09-28 10:57:53,560 - vorta.i18n - DEBUG - Loading translation succeeded for ['fr', 'fr-FR', 'fr-Latn-FR'].
2021-09-28 10:57:53,585 - apscheduler.scheduler - INFO - Scheduler started
2021-09-28 10:57:53,674 - root - CRITICAL - Uncaught exception, file a report at https://github.com/borgbase/vorta/issues/new
Traceback (most recent call last):
  File "__main__.py", line 65, in <module>
  File "__main__.py", line 58, in main
  File "application.py", line 69, in __init__
  File "views/main_window.py", line 52, in __init__
  File "views/repo_tab.py", line 54, in __init__
  File "views/repo_tab.py", line 109, in init_ssh
  File "utils.py", line 136, in get_private_keys
  File "paramiko/pkey.py", line 235, in from_private_key_file
  File "paramiko/ecdsakey.py", line 126, in __init__
  File "paramiko/ecdsakey.py", line 279, in _from_private_key_file
  File "paramiko/ecdsakey.py", line 289, in _decode_key
  File "cryptography/hazmat/primitives/serialization/base.py", line 37, in load_der_private_key
  File "cryptography/hazmat/backends/openssl/backend.py", line 1269, in load_der_private_key
  File "cryptography/hazmat/backends/openssl/backend.py", line 686, in _evp_pkey_to_private_key
  File "cryptography/hazmat/backends/openssl/ec.py", line 158, in __init__
  File "cryptography/hazmat/backends/openssl/ec.py", line 54, in _ec_key_curve_sn
NotImplementedError: ECDSA keys with unnamed curves are unsupported at this time
```

I have not been able to find any hint about what to do. I'm on macos Mojave.

Have a good day

**Comment by m3nu** [comment]
You have an unusual key in your `~/.ssh` folder. Usually it should be ignored, but it looks like we dont' catch this particular exception yet. I fixed this in #1070.

Until this is released, you could move that key out of your `~/.ssh` folder.

**Comment by fdagnat** [comment]
Indeed, it fixes the problem. Thanks
