### ISSUE TITLE
Missing UI element may trigger crash when recalculating folder sizes

### ISSUE THREAD

**Issue by m3nu** [borgbase/vorta#1080]
**Describe the bug**
Vorta may crash in rare situations, while calculating source folder sizes. First reported [here](https://github.com/borgbase/vorta/commit/9bad152a8006710f42e4bf95e7fca96a28b7ffa3#commitcomment-58205419)

**To Reproduce**
Steps to reproduce the behavior: (not verified)
1. Go to source tab
2. Add folder
3. Do "Recalculate"
4. Remove folder right away
5. Maybe see error

**Environment (please complete the following information):**
- OS: macOS
- Vorta version: master branch, 0.8, Oct 2021
- Installed from: Git

Vorta and Borg versions can be found in Main Window > Misc Tab.

**Additional context**
Updated on my system and got this when trying to add a new folder and recalculating. I think it might be related to this
```
021-10-18 14:35:37,480 - vorta.borg.borg_job - INFO - Running command /usr/bin/borg --version
2021-10-18 14:36:15,675 - root - CRITICAL - Uncaught exception, file a report at https://github.com/borgbase/vorta/issues/new
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/vorta/views/source_tab.py", line 156, in sources_update
    self.update_path_info(row)  # Update data for each entry
  File "/usr/lib/python3.9/site-packages/vorta/views/source_tab.py", line 100, in update_path_info
    self.sourceFilesWidget.item(index_row, SourceColumn.Type).setText(self.tr("Calculating..."))
AttributeError: 'NoneType' object has no attribute 'setText'

```

**Comment by real-yfprojects** [comment]
It shouldn't be possible that the error given relates to a source being deleted since the method is called immediately after clicking the button and as far as I know before any other window events are processed.
https://github.com/borgbase/vorta/blob/461ea0521092091bfb03b8293c6bb7e13a2c9ebd/src/vorta/views/source_tab.py#L95

Deleting a source while calculating shouldn't be a problem as well. The result are handled by `set_path_info` which searches for the source path in the source table. In case the source isn't found any more the for loop changing the entries won't process any lines.
https://github.com/borgbase/vorta/blob/461ea0521092091bfb03b8293c6bb7e13a2c9ebd/src/vorta/views/source_tab.py#L66-L72

**Comment by delfino-nunez** [comment]
Can't reproduce it on Vorta 0.8.3.
It works for me on Vorta 0.8.3 from Github,

Steps

1. Got to "Sources" tab.
2. Add folder.
3. Recalculate sizes - size is displayed correctly
![image](https://user-images.githubusercontent.com/770967/159113045-8c60256c-ed19-428f-be18-a9a130b7ffa9.png)

5. Remove the folder at the OS level
6. Recalculate sizes again - size is 0 Bytes and no error displayed.
![image](https://user-images.githubusercontent.com/770967/159113102-fe22a38f-72e4-4bea-9d42-cebfa46d4300.png)

**Comment by m3nu** [comment]
Were you able to reproduce the crash in the latest master version?

**Comment by ebuzerdrmz44** [comment]
> Were you able to reproduce the crash in the latest master version?

Yes, the original `AttributeError: 'NoneType' object has no attribute 'setText' `mentioned in this issue no longer seems to occur . but I could still reproduce . I added large folder and waited for it to calculate, and then I clicked Recalculate . While it was recalculating, I removed it. This causes: `QThread: Destroyed while thread is still running`, which crashes the app. I might have a solution for this and I want to open a PR if that's okay.

**Comment by m3nu** [comment]
ok. then it's yours.
