### ISSUE TITLE
Schedule "Backup daily" throws Exception

### ISSUE THREAD

**Issue by bpereto** [borgbase/vorta#11]
```
Job "VortaScheduler.create_backup (trigger: cron[hour='15', minute='7'], next run at: 2018-11-10 15:07:00 CET)" raised an exception
Traceback (most recent call last):
  File "/home/beni/devel/git/vorta/.venv/lib/python3.7/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/home/beni/devel/git/vorta/.venv/lib/python3.7/site-packages/vorta/scheduler.py", line 49, in create_backup
    notifier = VortaNotifications.pick()()
TypeError: 'NoneType' object is not callable
```

Same Error is thrown when I click on "apply" in the Schedule Tab.

**Comment by m3nu** [comment]
yeah. this is related to notifications, which aren't implemented in Linux. I'll add some kind of exception. Not sure if it's easy to implement notifications for Linux.

**Comment by bpereto** [comment]
got it:
```
>>> import sys
>>> sys.platform
'linux'
```
