### ISSUE TITLE
Cancel jobs when deleting profile (without APSchedulder)

### ISSUE THREAD

**Issue by nrbeaton** [borgbase/vorta#1101]
**Describe the bug**
Tried to delete a profile, got the error message.

Note (as you can see from the logs below) I was trying to delete the profile because Vorta was unable to connect to BorgBase. So I was going to delete it and try to create it again.

```
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/vorta/views/main_window.py", line 168, in profile_delete_action
    if self.app.scheduler.get_job(to_delete_id):
AttributeError: 'VortaScheduler' object has no attribute 'get_job'
```

**To Reproduce**
1. Click "Delete Profile" button.

**Environment (please complete the following information):**
- OS: Arch
- Vorta version: 0.8.0
- Installed from: Arch User Repository

**Additional context**
```
2021-11-08 09:57:35,780 - vorta.keyring.abc - DEBUG - Only available on macOS
2021-11-08 09:57:35,785 - asyncio - DEBUG - Using selector: EpollSelector
2021-11-08 09:57:35,788 - vorta.borg.borg_job - DEBUG - Using VortaSecretStorageKeyring keyring to store passwords.
2021-11-08 09:57:35,794 - asyncio - DEBUG - Using selector: EpollSelector
2021-11-08 09:57:35,800 - root - DEBUG - Found 1 passwords matching repo URL.
2021-11-08 09:57:35,911 - vorta.borg.borg_job - INFO - Running command /usr/bin/borg create --list --progress --info --log-json --json --filter=AM -C lz4 CENSORED@CENSORED.repo.borgbase.com:repo::archthinkpad-2021-11-08-095735 /home/nrbeaton
2021-11-08 09:57:39,072 - vorta.borg.borg_job - WARNING - Remote: sign_and_send_pubkey: signing failed for ED25519 "/home/nrbeaton/.ssh/id_ed25519" from agent: agent refused operation
2021-11-08 09:57:39,073 - vorta.borg.borg_job - WARNING - Remote: CENSORED@CENSORED.repo.borgbase.com: Permission denied (publickey).
2021-11-08 09:57:39,077 - vorta.borg.borg_job - ERROR - Connection closed by remote host. Is borg working on the server?
2021-11-08 09:57:47,264 - root - CRITICAL - Uncaught exception, file a report at https://github.com/borgbase/vorta/issues/new
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/vorta/views/main_window.py", line 168, in profile_delete_action
    if self.app.scheduler.get_job(to_delete_id):
AttributeError: 'VortaScheduler' object has no attribute 'get_job'
2021-11-08 09:58:17,392 - vorta.scheduler - DEBUG - Refreshing all scheduler timers
```

**Comment by m3nu** [comment]
Good find! I removed this part in #1096. After we are happing with the scheduling, we should put this fuctionality back again

![Screen Shot 2021-11-08 at 09 08 41](https://user-images.githubusercontent.com/3916435/140687509-1164dca4-9635-46c1-8714-37b55f3e996b.jpg)

**Comment by sten0** [comment]
Hi @m3nu !

I'm going to wait to update the Debian/Ubuntu package until this issue is resolved, because my team members very reliably find bugs and complain ;-)  Also, for the next release, would you please fix this dangling reference to apscheduler? (found with The Silver Searcher):

src/vorta/log.py
20:    logging.getLogger('apscheduler').setLevel(logging.INFO)

**Comment by m3nu** [comment]
Yes, please wait. The 0.8 branch isn't stable yet. We will keep collecting feedback and making larger changes. I just did a pre-release, since very recent distros like Fedora and Arch benefit from it and we get more feedback that way.

**Comment by sten0** [comment]
Manu ***@***.***> writes:

> Yes, please wait. The 0.8 branch isn't stable yet. We will keep collecting feedback and making larger changes. I just did a pre-release, since very recent distros like Fedora and Arch benefit from it and we get more feedback that way.
>

Thank you for this info, I didn't realise that 0.8 was a pre-release :-)
I'll put an invalid-syntax-type note in the Debian changelog for other
team members to insure that that build fails and that no one
accidentally uploads.

Thanks again for your continued work, and I'm looking forward to the
next release!
