### ISSUE TITLE
Can't see Tray Icon after launching (Ubuntu 18.04)

### ISSUE THREAD

**Issue by step21** [borgbase/vorta#111]
**Describe the bug**
Error on start.

**To Reproduce**
1. Install with system python but `--user` on Ubuntu 18.04.1 LTS
2. Start from bash

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04.1 LTS with Gnome

**Additional context**
```
Error initializing plugin EntryPoint('Windows (alt)', 'keyrings.alt.Windows', None, Distribution('keyrings.alt', '3.0')).
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.6/site-packages/keyring/backend.py", line 194, in _load_plugins
    init_func = ep.load()
  File "/home/user/.local/lib/python3.6/site-packages/entrypoints.py", line 77, in load
    mod = import_module(self.module_name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/python3/dist-packages/keyrings/alt/Windows.py", line 9, in <module>
    from . import file_base
  File "/usr/lib/python3/dist-packages/keyrings/alt/file_base.py", line 13, in <module>
    from keyring.util.escape import escape as escape_for_ini
ModuleNotFoundError: No module named 'keyring.util.escape'
Error initializing plugin EntryPoint('file', 'keyrings.alt.file', None, Distribution('keyrings.alt', '3.0')).
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.6/site-packages/keyring/backend.py", line 194, in _load_plugins
    init_func = ep.load()
  File "/home/user/.local/lib/python3.6/site-packages/entrypoints.py", line 77, in load
    mod = import_module(self.module_name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/python3/dist-packages/keyrings/alt/file.py", line 11, in <module>
    from keyring.util.escape import escape as escape_for_ini
ModuleNotFoundError: No module named 'keyring.util.escape'
Error initializing plugin EntryPoint('pyfs', 'keyrings.alt.pyfs', None, Distribution('keyrings.alt', '3.0')).
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.6/site-packages/keyring/backend.py", line 194, in _load_plugins
    init_func = ep.load()
  File "/home/user/.local/lib/python3.6/site-packages/entrypoints.py", line 77, in load
    mod = import_module(self.module_name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/python3/dist-packages/keyrings/alt/pyfs.py", line 8, in <module>
    from keyring.util.escape import escape as escape_for_ini
ModuleNotFoundError: No module named 'keyring.util.escape'

```

**Comment by step21** [comment]
Should I try to install these manually? I was under the impression Python 3.6 was recent enough and that all modules were pulled on install.

**Comment by ThomasWaldmann** [comment]
Looks like you have `keyring` stuff in your home dir as well as at the system location in /usr/lib/python3.

**Comment by step21** [comment]
Mmmh. Installed to virtualenv there is no error, but still no gui ^^
Oh well....

**Comment by m3nu** [comment]
> Mmmh. Installed to virtualenv there is no error, but still no gui 
No GUI will be there on startup. You will only get the system tray icon. From there you can start the GUI. Or start it with `--foreground`

About `keyring`: It looks like there were 2 `keyring` installs in different places. TBH, the `keyring` package is somewhat of a mess and I already replaced it with my own Pyobjc implementation for macOS for that reason. If the same can be done for Linux, we can remove the dependency completely.

**Comment by m3nu** [comment]
(Fixed a small issue that prevented forking. This doesn't change that it goes to the system tray and can't be exited with ctr-c.)

**Comment by m3nu** [comment]
If any special instructions are needed on Linux to get system tray icons in the desktop env, I'd like to add them to the install instructions. E.g.: https://extensions.gnome.org/extension/1031/topicons/
