### ISSUE TITLE
sqlite3.OperationalError: no such column: t1.end_time

### ISSUE THREAD

**Issue by stephensrmmartin** [borgbase/vorta#1114]
**Describe the bug**
Vorta fails to start.

**To Reproduce**

Open Vorta

**Environment (please complete the following information):**
- OS: Arch Linux
- Vorta version: 0.8.0-1
- Installed from: Arch User Repository
- Borg version: 1.1.17-2

**Additional context**

```
2021-11-16 17:21:47,208 - vorta.i18n - DEBUG - Loading translation succeeded for ['en', 'en-US', 'en-Latn-US'].
Icon theme "gnome" not found.
2021-11-16 17:21:47,431 - root - INFO - Using NullNetworkStatusMonitor NetworkStatusMonitor implementation.
2021-11-16 17:21:47,433 - root - CRITICAL - Uncaught exception, file a report at https://github.com/borgbase/vorta/issues/new
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/peewee.py", line 3160, in execute_sql
    cursor.execute(sql, params or ())
sqlite3.OperationalError: no such column: t1.end_time

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/vorta", line 33, in <module>
    sys.exit(load_entry_point('vorta==0.8.0', 'gui_scripts', 'vorta')())
  File "/usr/lib/python3.9/site-packages/vorta/__main__.py", line 58, in main
    app = VortaApp(sys.argv, single_app=args.profile is None)
  File "/usr/lib/python3.9/site-packages/vorta/application.py", line 69, in __init__
    self.main_window = MainWindow(self)
  File "/usr/lib/python3.9/site-packages/vorta/views/main_window.py", line 54, in __init__
    self.scheduleTab = ScheduleTab(self.scheduleTabSlot)
  File "/usr/lib/python3.9/site-packages/vorta/views/schedule_tab.py", line 49, in __init__
    self.populate_from_profile()
  File "/usr/lib/python3.9/site-packages/vorta/views/schedule_tab.py", line 136, in populate_from_profile
    self.populate_logs()
  File "/usr/lib/python3.9/site-packages/vorta/views/schedule_tab.py", line 171, in populate_logs
    event_logs = [s for s in EventLogModel.select().order_by(EventLogModel.start_time.desc())]
  File "/usr/lib/python3.9/site-packages/peewee.py", line 6923, in __iter__
    self.execute()
  File "/usr/lib/python3.9/site-packages/peewee.py", line 1911, in inner
    return method(self, database, *args, **kwargs)
  File "/usr/lib/python3.9/site-packages/peewee.py", line 1982, in execute
    return self._execute(database)
  File "/usr/lib/python3.9/site-packages/peewee.py", line 2155, in _execute
    cursor = database.execute(self)
  File "/usr/lib/python3.9/site-packages/peewee.py", line 3173, in execute
    return self.execute_sql(sql, params, commit=commit)
  File "/usr/lib/python3.9/site-packages/peewee.py", line 3167, in execute_sql
    self.commit()
  File "/usr/lib/python3.9/site-packages/peewee.py", line 2933, in __exit__
    reraise(new_type, new_type(exc_value, *exc_args), traceback)
  File "/usr/lib/python3.9/site-packages/peewee.py", line 191, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3.9/site-packages/peewee.py", line 3160, in execute_sql
    cursor.execute(sql, params or ())
peewee.OperationalError: no such column: t1.end_time

```

**Comment by m3nu** [comment]
Looks like you are missing a DB migration. Could happen if you ran the Github version at random times.

Solution would be to open the settings database and change `version` in the `schemaversion` table to 17. Then it will upgrade to version 18 automatically on the next startup.

Or just make sure you have the 4 new columns that were added with schema version 18: https://github.com/borgbase/vorta/blob/master/src/vorta/models.py#L432

**Comment by m3nu** [comment]
Looks like a one-off issue when using dev versions. Should be easy to fix by adjusting the schema version, if needed. See also #1117
