### ISSUE TITLE
Refreshing archives failed on Python 3.6

### ISSUE THREAD

**Issue by pbtsrc** [borgbase/vorta#1175]
Vorta 0.8.2
```
2022-01-25 15:48:57,572 - vorta.borg.borg_job - INFO - Running command /usr/bin/borg list --info json --json bak@server:/media/hdd/bak
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/site-packages/vorta/borg/jobs_manager.py", line 57, in run
    job.run()
  File "/usr/lib/python3.6/site-packages/vorta/borg/borg_job.py", line 291, in run
    self.process_result(result)
  File "/usr/lib/python3.6/site-packages/vorta/borg/list_repo.py", line 52, in process_result
    'time': dt.fromisoformat(archive['time'])
AttributeError: type object 'datetime.datetime' has no attribute 'fromisoformat'
```

**Comment by m3nu** [comment]
We don't support Python 3.6 any more, since it's EOL. ☹️
