### ISSUE TITLE
Vorta for Windows

### ISSUE THREAD

**Issue by MatejKovacic** [borgbase/vorta#1207]
Sorry, this is not really a bug, but I would really like to see Vorta (and Borg) on Windows. I found Vorta for Linux really reliable and useful, but for Windows I have constant problems with backuping solutions. I am using free version of Veeam, but on one machine network link is failing quite often and when that happens, Veeam cannot finish the backup (to the SMB shared folder).

Using ssh and Borg in that case would be much useful and reliable, but unfortunately there are no really good instructions how to setup Vorta and Borg on Windows (10).

Anyone willing to start working on this (instructions and especially porting client to Windows directly)?

Anyway, many thanks for your work!

**Comment by real-yfprojects** [comment]
Before this is an option for *vorta*, *borg* must run on windows. There is an [entry](https://borgbackup.readthedocs.io/en/stable/installation.html#windows-10-s-linux-subsystem) on installing borg in the *wsl*. But this is very experimental and FUSE isn't expected to work. As an alternative one could also try to install borg using pip but I doubt that all the [dependencies](https://borgbackup.readthedocs.io/en/stable/installation.html#from-source) are available on windows.

Vorta itself should work on windows for the main part.

**Comment by m3nu** [comment]
Someone published Windows binaries for Borg for a while. So it's possible.

I'm not touching Windows with a 5ft pole, but would be up to packaging Vorta for Windows, once Borg runs.

Vorta is in pure Qt and Python, which already runs on Windows. For packaging we use Pyinstaller, which also supports Windows.

**Comment by m3nu** [comment]
https://github.com/borgbackup/borg/issues?q=is%3Aissue+is%3Aopen+label%3A%22os%3A+windows%22+

**Comment by bhlevca** [comment]
I managed to compile borg on windows using visual studio compiler and modifying the `__init__.py` to include the  dependent dlls. 

**Borg works fine for me on windows.** 

The big remaining problem is vorta.  which seems to work on local folders but has problems with network shares and sockets. 
 for example:

```
Traceback (most recent call last):
  File "C:\MECP\WebGnome\WebGnomeEnv\lib\site-packages\vorta-0.8.3-py3.10.egg\vorta\views\repo_add_dialog.py", line 235, in run
    self.thread.run()
  File "C:\MECP\WebGnome\WebGnomeEnv\lib\site-packages\vorta-0.8.3-py3.10.egg\vorta\borg\borg_job.py", line 222, in run
    os.set_blocking(p.stdout.fileno(), False)
AttributeError: module 'os' has no attribute 'set_blocking
```

**Comment by real-yfprojects** [comment]
Vorta uses some functions of python's `os` module that are only available on unix.

**Comment by m3nu** [comment]
Good news! There shouldn’t be many Unix-specific functions.

First prio would be to upstream the changes in Borg and start publishing official binaries.

**Comment by bhlevca** [comment]
> Vorta uses some functions of python's `os` module that are only available on unix.

That was the reason or opening this issue: To make it compatible with windows. Now that borg runs well on windows it makes even more sense

**Comment by bhlevca** [comment]
> Good news! There shouldn’t be many Unix-specific functions.
> 
> First prio would be to upstream the changes in Borg and start publishing official binaries.

Vorta does not need binaries as it is only based on python.  Borg already works on windows, either get it form those who released it on windows or if you have the skill you can compile it yourself. I tried vorta on windows but it has some os calls that are not available on Windows and the code should be checking on the platform and use the call appropriate calls for that platform. Vorta is tested only on linux on intel platform. Support for aarch64 is also lacking.

**Comment by m3nu** [comment]
We would include Borg binaries with Vorta so users don't need to compile them again.

Where can I find Windows binaries using the latest version? I just updated Borg's install scripts and from what I saw, some parts still need adjustments for Windows. I could be wrong of course, since I didn't try myself.

**Comment by alfredonodo** [comment]
Hi,
is there any update on this? At least a version for ubuntu 22.04 LTS?

**Comment by m3nu** [comment]
What stops you from installing it on Ubuntu?

**Comment by alfredonodo** [comment]
[Vorta windows](https://vorta.borgbase.com/install/windows/)
_Then upgrade Ubuntu version. Vorta is is [packaged](https://packages.ubuntu.com/search?keywords=vorta) for Ubuntu (Debian) starting with Ubuntu 21.04. If it is before April 21, 2022 and Ubuntu 22.04 is not yet available, you will need to upgrade to a [non-Long Term Support](https://wiki.ubuntu.com/Releases) (non-LTS) version of Ubuntu_

**Comment by m3nu** [comment]
I see. You mean a virtual Ubuntu running on Windows? Does the PyPi version work in that case? Desktop apps on VMs are tricky though.

https://vorta.borgbase.com/install/linux/

**Comment by alfredonodo** [comment]
It works well on GNU/linux. I am asking about WSL on windows.

**Comment by m3nu** [comment]
Sorry, but I have very limited to no experience with WSL myself. Do let me know if you get it working and I'll update the docs accordingly.

Should be possible to build Vorta with PyInstaller on Windows natively. It would still need a way to call Vorta in WSL though. This may be easier then running Vorta in WSL too.

**Comment by real-yfprojects** [comment]
> [Vorta windows](https://vorta.borgbase.com/install/windows/)
> 
> _Then upgrade Ubuntu version. Vorta is is [packaged](https://packages.ubuntu.com/search?keywords=vorta) for Ubuntu (Debian) starting with Ubuntu 21.04. If it is before April 21, 2022 and Ubuntu 22.04 is not yet available, you will need to upgrade to a [non-Long Term Support](https://wiki.ubuntu.com/Releases) (non-LTS) version of Ubuntu_

Reading the quote you will find that it only applies before the 21.04.
In fact, there is a vorta package for the current Ubuntu versions in their official repository.

**Comment by alfredonodo** [comment]
> > [Vorta windows](https://vorta.borgbase.com/install/windows/)
> > _Then upgrade Ubuntu version. Vorta is is [packaged](https://packages.ubuntu.com/search?keywords=vorta) for Ubuntu (Debian) starting with Ubuntu 21.04. If it is before April 21, 2022 and Ubuntu 22.04 is not yet available, you will need to upgrade to a [non-Long Term Support](https://wiki.ubuntu.com/Releases) (non-LTS) version of Ubuntu_
> 
> Reading the quote you will find that it only applies before the 21.04. In fact, there is a vorta package for the current Ubuntu versions in their official repository.

[Right](https://packages.ubuntu.com/search?keywords=vorta) and so it should be updated.

**Comment by MatejKovacic** [comment]
Sorry, guys, but here we are talking about Borgbackup/Vorta running on the Windows natively not through WSL or some kind of virtualisation.

I mean, what is the point of installing the whole Ubuntu to then run Borg and Vorta on the top of it...

**Comment by real-yfprojects** [comment]
@alfredonodo Head to borgbase/vorta.borgbase.com#26

**Comment by ThomasWaldmann** [comment]
See PR #1592.

**Comment by HanslettTheDev** [comment]
Hello there, after reading the different Pull requests and issues on this topic, I don't seem to understand something

What needs to be ported for Windows? is it Vorta and BorgBackup or both?

**Comment by HanslettTheDev** [comment]
Are there any binaries for Vorta already? I saw an issue discussion about making the binaries available as a resource when running the GH actions

**Comment by m3nu** [comment]
Yes, we use Pyinstaller to build binaries for macOS. In theory Pyinstaller can also build for Windows.

**Comment by HanslettTheDev** [comment]
Alright, I'll just test that. Right now, I'm on windows, so I'll try to make a build for windows and run it and see how it goes
