### ISSUE TITLE
Build fails on Debian 10 aarch64

### ISSUE THREAD

**Issue by ilg-ul** [borgbase/vorta#1217]
**Describe the bug**

A build from sources fails on Debian 10 aarch64.

**To Reproduce**

```
git clone https://github.com/borgbase/vorta
cd vorta
python3 setup.py build
sudo python3 setup.py install
...
Installed /usr/local/lib/python3.7/dist-packages/SecretStorage-3.3.1-py3.7.egg
Searching for pyqt5
Reading https://pypi.org/simple/pyqt5/
Downloading https://files.pythonhosted.org/packages/3b/27/fd81188a35f37be9b3b4c2db1654d9439d1418823916fe702ac3658c9c41/PyQt5-5.15.6.tar.gz#sha256=80343bcab95ffba619f2ed2467fd828ffeb0a251ad7225be5fc06dcc333af452
Best match: PyQt5 5.15.6
Processing PyQt5-5.15.6.tar.gz
error: Couldn't find a setup script in /tmp/easy_install-qutzapqt/PyQt5-5.15.6.tar.gz
ilg@rock:~/Work/vorta$
```

**Environment (please complete the following information):**
- OS:

```
ilg@rock:~/Work/vorta$ uname -a
Linux rock 4.4.154-113-rockchip-gdb9dfc2cdd25 #1 SMP Sat Aug 14 09:26:12 UTC 2021 aarch64 GNU/Linux
ilg@rock:~/Work/vorta$ lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 10 (buster)
Release:	10
Codename:	buster
```

- Vorta version: Git HEAD
- Installed from: GitHub

**Comment by ilg-ul** [comment]
Same behaviour on a Raspberry Pi OS 64-bit:

```
...
Installed /usr/local/lib/python3.7/dist-packages/vorta-0.8.3-py3.7.egg
Processing dependencies for vorta==0.8.3
Searching for pyqt5
Reading https://pypi.org/simple/pyqt5/
Downloading https://files.pythonhosted.org/packages/3b/27/fd81188a35f37be9b3b4c2db1654d9439d1418823916fe702ac3658c9c41/PyQt5-5.15.6.tar.gz#sha256=80343bcab95ffba619f2ed2467fd828ffeb0a251ad7225be5fc06dcc333af452
Best match: PyQt5 5.15.6
Processing PyQt5-5.15.6.tar.gz
error: Couldn't find a setup script in /tmp/easy_install-cbz_o47b/PyQt5-5.15.6.tar.gz
ilg@berry:~/Work/vorta $ 
```

**Comment by real-yfprojects** [comment]
This seems to be a problem with installing vorta's dependency `pyqt5`.
Does installing it manually work?

```bash
> pip install pyqt5  # or if already installed
> pip install -U pyqt5
```

This in turn might be due to an outdated version of `pip` or `setuptools`. Try the following to update them:

```bash
> pip install -U pip
> pip install -U setuptools wheel  # wheel is always handy when using pip
```

**Comment by ilg-ul** [comment]
```
ilg@rock:~$ pip3 install -U pyqt5
Collecting pyqt5
  Using cached https://files.pythonhosted.org/packages/3b/27/fd81188a35f37be9b3b4c2db1654d9439d1418823916fe702ac3658c9c41/PyQt5-5.15.6.tar.gz
  Installing build dependencies ... done
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/lib/python3.7/tokenize.py", line 447, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-cop94egj/pyqt5/setup.py'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-cop94egj/pyqt5/
ilg@rock:~$ pip3 install -U pip
Collecting pip
  Downloading https://files.pythonhosted.org/packages/4d/16/0a14ca596f30316efd412a60bdfac02a7259bf8673d4d917dc60b9a21812/pip-22.0.4-py3-none-any.whl (2.1MB)
    100% |████████████████████████████████| 2.1MB 211kB/s 
Installing collected packages: pip
Successfully installed pip-22.0.4
ilg@rock:~$ pip3 install -U setuptool wheel
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not find a version that satisfies the requirement setuptool (from versions: none)
ERROR: No matching distribution found for setuptool
ilg@rock:~$ pip3 install -U pyqt5
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
Defaulting to user installation because normal site-packages is not writeable
Collecting pyqt5
  Using cached PyQt5-5.15.6.tar.gz (3.2 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [29 lines of output]
      Traceback (most recent call last):
        File "/home/ilg/.local/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 156, in prepare_metadata_for_build_wheel
          hook = backend.prepare_metadata_for_build_wheel
      AttributeError: module 'sipbuild.api' has no attribute 'prepare_metadata_for_build_wheel'
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "/home/ilg/.local/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/home/ilg/.local/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/ilg/.local/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 160, in prepare_metadata_for_build_wheel
          whl_basename = backend.build_wheel(metadata_directory, config_settings)
        File "/tmp/pip-build-env-858w6zws/overlay/lib/python3.7/site-packages/sipbuild/api.py", line 51, in build_wheel
          project = AbstractProject.bootstrap('pep517')
        File "/tmp/pip-build-env-858w6zws/overlay/lib/python3.7/site-packages/sipbuild/abstract_project.py", line 83, in bootstrap
          project.setup(pyproject, tool, tool_description)
        File "/tmp/pip-build-env-858w6zws/overlay/lib/python3.7/site-packages/sipbuild/project.py", line 594, in setup
          self.apply_user_defaults(tool)
        File "project.py", line 63, in apply_user_defaults
          super().apply_user_defaults(tool)
        File "/tmp/pip-build-env-858w6zws/overlay/lib/python3.7/site-packages/pyqtbuild/project.py", line 70, in apply_user_defaults
          super().apply_user_defaults(tool)
        File "/tmp/pip-build-env-858w6zws/overlay/lib/python3.7/site-packages/sipbuild/project.py", line 241, in apply_user_defaults
          self.builder.apply_user_defaults(tool)
        File "/tmp/pip-build-env-858w6zws/overlay/lib/python3.7/site-packages/pyqtbuild/builder.py", line 68, in apply_user_defaults
          "specify a working qmake or add it to PATH")
      sipbuild.pyproject.PyProjectOptionException
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
ilg@rock:~$ 
```

**Comment by real-yfprojects** [comment]
Its `setuptools` with an *s*.

**Comment by ilg-ul** [comment]
```
ilg@rock:~$ pip3 install -U setuptools wheel
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: setuptools in /usr/lib/python3/dist-packages (40.8.0)
Collecting setuptools
  Using cached setuptools-60.9.3-py3-none-any.whl (1.1 MB)
Collecting wheel
  Using cached wheel-0.37.1-py2.py3-none-any.whl (35 kB)
Installing collected packages: wheel, setuptools
  WARNING: The script wheel is installed in '/home/ilg/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
vorta 0.8.3 requires appdirs, which is not installed.
vorta 0.8.3 requires paramiko, which is not installed.
vorta 0.8.3 requires peewee, which is not installed.
vorta 0.8.3 requires pyqt5, which is not installed.
Successfully installed setuptools-60.9.3 wheel-0.37.1
ilg@rock:~$ pip3 install -U pyqt5
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
Defaulting to user installation because normal site-packages is not writeable
Collecting pyqt5
  Using cached PyQt5-5.15.6.tar.gz (3.2 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [29 lines of output]
      Traceback (most recent call last):
        File "/home/ilg/.local/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 156, in prepare_metadata_for_build_wheel
          hook = backend.prepare_metadata_for_build_wheel
      AttributeError: module 'sipbuild.api' has no attribute 'prepare_metadata_for_build_wheel'
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "/home/ilg/.local/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/home/ilg/.local/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/ilg/.local/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 160, in prepare_metadata_for_build_wheel
          whl_basename = backend.build_wheel(metadata_directory, config_settings)
        File "/tmp/pip-build-env-vdk90tyy/overlay/lib/python3.7/site-packages/sipbuild/api.py", line 51, in build_wheel
          project = AbstractProject.bootstrap('pep517')
        File "/tmp/pip-build-env-vdk90tyy/overlay/lib/python3.7/site-packages/sipbuild/abstract_project.py", line 83, in bootstrap
          project.setup(pyproject, tool, tool_description)
        File "/tmp/pip-build-env-vdk90tyy/overlay/lib/python3.7/site-packages/sipbuild/project.py", line 594, in setup
          self.apply_user_defaults(tool)
        File "project.py", line 63, in apply_user_defaults
          super().apply_user_defaults(tool)
        File "/tmp/pip-build-env-vdk90tyy/overlay/lib/python3.7/site-packages/pyqtbuild/project.py", line 70, in apply_user_defaults
          super().apply_user_defaults(tool)
        File "/tmp/pip-build-env-vdk90tyy/overlay/lib/python3.7/site-packages/sipbuild/project.py", line 241, in apply_user_defaults
          self.builder.apply_user_defaults(tool)
        File "/tmp/pip-build-env-vdk90tyy/overlay/lib/python3.7/site-packages/pyqtbuild/builder.py", line 68, in apply_user_defaults
          "specify a working qmake or add it to PATH")
      sipbuild.pyproject.PyProjectOptionException
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
ilg@rock:~$ 
```

**Comment by real-yfprojects** [comment]
I actually don't know why this doesn't work but it might due to `~/.local/bin` not being in `PATH`.

You can fix this for the current user:
```bash
> echo 'export PATH=$PATH:"~/.local/bin"' >> ~/.bashrc  # you can also replace ~ by /home/ilg
> source ~/.bashrc
```

Additionally your pip states that you should use `python3 -m pip` instead of `pip3`.

Short disclaimer, I just read that one should not upgrade the system wide pip manually and leave that to the package manager. I always did it any ways and nothing broke yet. :shrug:

**Comment by real-yfprojects** [comment]
Maybe pip tries to build the *sdist* (source) version of the package and therefore needs `qmake` which you have to install using apt in that case.

**Comment by ilg-ul** [comment]
> I actually don't know why this doesn't work

Probably it is the first time someone tries it on a Debian 10 aarch64?

**Comment by ilg-ul** [comment]
> needs qmake which you have to install using apt in that case.

Same error after installing qt5-qmake.

**Comment by real-yfprojects** [comment]
> Probably it is the first time someone tries it on a Debian 10 aarch64?

I don't know how common aarch64 is. But pyqt5 was certainly used on a RaspberryPi before.

**Comment by Hofer-Julian** [comment]
> > Probably it is the first time someone tries it on a Debian 10 aarch64?
> 
> I don't know how common aarch64 is. But pyqt5 was certainly used on a RaspberryPi before.
> 
> Edit: aarch64 is the same as arm64

People also use it with flatpak.

**Comment by ilg-ul** [comment]
> People also use it with flatpak.

I tried it, it failed too.

**Comment by ilg-ul** [comment]
FYI: Amongst other projects, I also make releases of a Python application (meson), but I handle the dependencies myself, pack everything as a standalone archive, and test the binaries on all relevant platforms, for example:

- https://github.com/xpack-dev-tools/meson-build-xpack/actions/runs/1360679283 (one run for each platform)
- https://github.com/xpack-dev-tools/meson-build-xpack/actions/runs/1546216848 (runs on multiple Intel Linux distros)
- https://github.com/xpack-dev-tools/meson-build-xpack/actions/runs/1546216947 (runs on multiple Arm Linux distros)

Perhaps you should consider such a route too.

**Comment by ilg-ul** [comment]
https://github.com/PyQt5/PyQt/issues/150

**Comment by real-yfprojects** [comment]
Have you tried to install `pyqt5` using apt?

**Comment by ilg-ul** [comment]
> Have you tried to install pyqt5 using apt?

Sorry, but I'm not sure I can follow you, the question was related to using vorta on an aarch64 machine, which failed. 

If vorta has dependencies, they either have to be satisfied automatically, or must be mentioned as prerequisites to be installed using a given procedure.
