### ISSUE TITLE
Add white icon for menu bar MacOS

### ISSUE THREAD

**Issue by ph00lt0** [borgbase/vorta#1220]
**Describe the bug**
Please add a white icon to conform with the design standard of menu bar icons in Monterey / Big Sur

**Environment (please complete the following information):**
- OS: MacOS
- Vorta version: 0.8.3
- Installed from: Brew

Vorta and Borg versions can be found in Main Window > Misc Tab.

**Comment by real-yfprojects** [comment]
@m3nu You are more familiar with MacOS.

**Comment by Brawl345** [comment]
> Currently it uses an icon that works on dark and light themes

<img width="332" alt="image" src="https://user-images.githubusercontent.com/5049892/210285644-b5fb31de-e7e1-4ad5-97b5-3af39add6cd9.png">

This does not look good though :/

**Comment by diivi** [comment]
I made two [alternatives](https://www.figma.com/file/WHe8SAB7vv8dpnPSC1tNpX/Untitled?node-id=0%3A1&t=L18gUWgduhrReYZP-0).
![image](https://user-images.githubusercontent.com/41837037/225361735-635cd78a-e899-4a18-9ce2-c1740f715bee.png)
I prefer the second one, which one do you think might be better? @m3nu

**Comment by m3nu** [comment]
4 icons are needed in total: dark/light x normal/active

I'm also not sure if Qt gets the signal regarding the theme change, if it's in the background only. That's why I didn't implement this and went for a simple icon that works for all cases. If you can make it work, it would be a nice addition though.

**Comment by diivi** [comment]
> 4 icons are needed in total: dark/light x normal/active
> I'm also not sure if Qt gets the signal regarding the theme change, if it's in the background only. 

I am on a Linux machine running Ubuntu 22.04 so I won't be able to test how Vorta responds to changes to the system's theme on MacOS. But I feel like a transparent body for the hdd icon might be more suitable than the current black body. Let me know what you think, otherwise maybe I'll try to get this running on a friend's Mac later.

**Comment by real-yfprojects** [comment]
The other icons use solid shapes instead of contours. So maybe your first option is better @diivi.

**Comment by Brawl345** [comment]
I would also prefer the first option.

**Comment by diivi** [comment]
Feel free to use the designs I shared, just request access so I can allow you to export the icons!

**Comment by i1sm3ky** [comment]
> I wondered why detecting via QPalette doesn't work. Or maybe it does...

It does! I'm using `self.app.paletteChanged.connect(self.set_tray_icon)` along with darkdetect to detect and change the icon for light or dark mode.

But I'm having problems importing the module, It says its installed but when run it gives a module not found error.

**Comment by real-yfprojects** [comment]
Can you enclose relevant output including the error message?

**Comment by i1sm3ky** [comment]
> Can you enclose relevant output including the error message?

It's a normal module not found error: 
```
2023-04-01 13:37:38,971 - root - CRITICAL - Uncaught exception, file a report at https://github.com/borgbase/vorta/issues/new/choose
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/bin/vorta", line 8, in <module>
    sys.exit(main())
  File "/Users/1tsm3ky/Desktop/Vorta/vorta/src/vorta/__main__.py", line 69, in main
    from vorta.application import VortaApp
  File "/Users/1tsm3ky/Desktop/Vorta/vorta/src/vorta/application.py", line 20, in <module>
    from vorta.tray_menu import TrayMenu
  File "/Users/1tsm3ky/Desktop/Vorta/vorta/src/vorta/tray_menu.py", line 3, in <module>
    import darkdetect
ModuleNotFoundError: No module named 'darkdetect'
```

But as suggested by @m3nu, adding a new dependency just for correcting the icon colour isn't something we are willing to do. So I think a white icon for both light and dark modes on GNOME and MacOS and rest could have the original black/dark one?

**Comment by real-yfprojects** [comment]
What about https://github.com/borgbase/vorta/blob/e0fe766051e521396d7d58f973d1f8002ff749ad/src/vorta/utils.py#L374-L379

Can this be used to determine the colour of the tray icon?

**Comment by m3nu** [comment]
> Can this be used to determine the colour of the tray icon?

It should be used. It may not change the icon right away, but eventually. Not sure if it triggers with the app in the BG or no window open.

**Comment by i1sm3ky** [comment]
> What about https://github.com/borgbase/vorta/blob/e0fe766051e521396d7d58f973d1f8002ff749ad/src/vorta/utils.py#L374-L379
> 
> 
> 
> Can this be used to determine the colour of the tray icon?

I guess, Yes. Let me check if this works. BTW thanks for the snippet.

**Comment by i1sm3ky** [comment]
> https://github.com/borgbase/vorta/blob/e0fe766051e521396d7d58f973d1f8002ff749ad/src/vorta/utils.py#L374-L379

I tried this, but it didn't worked reliably, It returns `False` even when in dark mode.

For now I've implemented the white icons for GNOME and MacOS(I think the white one fits better with the rest of MacOS's solid icons) and for rest it uses the previous black ones.

I've opened a PR #1676  for this as well, please someone verify the implementation.

**Comment by real-yfprojects** [comment]
> I tried this, but it didn't worked reliably, It returns `False` even when in dark mode.

Which attribute of the MacOS palette is the cause of this?

**Comment by i1sm3ky** [comment]
> Which attribute of the MacOS palette is the cause of this?

The `uses_dark_modes` works on the principle of checking the contrast between text colour and window colour but on MacOS when used inside the `tray_menu.py` it returns the same lightness values for both the theme modes. But when used on a separate file it outputs the correct values, I think it only works with the default palette of PyQt.

**Comment by real-yfprojects** [comment]
> when used inside the `tray_menu.py` it returns the same lightness values for both the theme modes

Did you call it after `QApplication` was initialized completely?

**Comment by i1sm3ky** [comment]
> Did you call it after `QApplication` was initialized completely?

Yes, it was called after QApplication was completely initialized.

**Comment by real-yfprojects** [comment]
I just found these two things that are worth testing for solving this issue. The background being the template feature of [`NSImage`](https://developer.apple.com/documentation/appkit/nsimage/1520017-template?language=objc) that native apps use to display their icon in the correct colour.

https://doc.qt.io/qt-6/qicon.html#setIsMask

https://stackoverflow.com/questions/38039262/creating-a-template-image-dynamically-for-osx-menu-bar
> The system will automatically mark an image loaded from a file as a template image if its filename-minus-extension ends with "Template". So, for example, fooTemplate.png or barTemplate.pdf.

**Comment by flying-x** [comment]
![image](https://github.com/borgbase/vorta/assets/22962929/381faf5a-eba5-4158-b5ba-b894a24fc0ba)

When I use vorta on gnome with the "blur my shell" extension, the icon isn't transparent as you can see above. I am using manjaro/arch linux and should be on the latest version. Is this the correct place to report this issue?

**Comment by m3nu** [comment]
Resolved in [#2091](https://github.com/borgbase/vorta/pull/2091)
