### ISSUE TITLE
Error in `secretstorage` when unlocking collection.

### ISSUE THREAD

**Issue by Carcinogen72** [borgbase/vorta#1267]
```pytb
Traceback (most recent call last):
  File "/app/lib/python3.9/site-packages/vorta/application.py", line 185, in set_borg_details_result
    self.scheduler.reload_all_timers()  # Start timer after Borg version is set.
  File "/app/lib/python3.9/site-packages/vorta/scheduler.py", line 121, in reload_all_timers
    self.set_timer_for_profile(profile.id)
  File "/app/lib/python3.9/site-packages/vorta/scheduler.py", line 85, in set_timer_for_profile
    self.create_backup(profile.id)
  File "/app/lib/python3.9/site-packages/vorta/scheduler.py", line 165, in create_backup
    msg = BorgCreateJob.prepare(profile)
  File "/app/lib/python3.9/site-packages/vorta/borg/create.py", line 74, in prepare
    ret = super().prepare(profile)
  File "/app/lib/python3.9/site-packages/vorta/borg/borg_job.py", line 151, in prepare
    ret['password'] = cls.keyring.get_password('vorta-repo', profile.repo.url)
  File "/app/lib/python3.9/site-packages/vorta/keyring/secretstorage.py", line 35, in get_password
    if self.is_unlocked:
  File "/app/lib/python3.9/site-packages/vorta/keyring/secretstorage.py", line 50, in is_unlocked
    collection.unlock()
  File "/app/lib/python3.9/site-packages/secretstorage/collection.py", line 67, in unlock
    return unlock_objects(self.connection, [self.collection_path])
  File "/app/lib/python3.9/site-packages/secretstorage/util.py", line 151, in unlock_objects
    dismissed, (signature, unlocked) = exec_prompt(connection, prompt)
  File "/app/lib/python3.9/site-packages/secretstorage/util.py", line 138, in exec_prompt
    assert dismissed is not None
AssertionError
```

**Comment by m3nu** [comment]
Maybe fixed in #1255
