### ISSUE TITLE
Request: SMB Support for Repository

### ISSUE THREAD

**Issue by 53c70r** [borgbase/vorta#1268]
I would like to have the option to add SMB shares with login credentials directly as repository.

**Comment by real-yfprojects** [comment]
With some restriction you can use the pre and post backup commands to mount the samba shares as far as I know.

**Comment by DSDV** [comment]
So as i have truenas running and would like to use my nas as backuplocation i support this request :D

**Comment by ThomasWaldmann** [comment]
If pre/post commands work for this, this issue should be closed.

Also, this is not about "SMB Support", but just abount mounting a cifs/smbfs (or any other network or local filesystem).

**Comment by DSDV** [comment]
I dont think so. 
The SMB/CIFS is successfully mounted. 
But Vorta does not work with it.

**Comment by DSDV** [comment]
Because as i said mounting the SMD/CIFS works great in the OS just not in Vorta. 
ergo Vorta needs support for SMB Shares so we can create and use backup repositorys over the network (:

**Comment by ThomasWaldmann** [comment]
https://github.com/borgbase/vorta/issues/1268#issuecomment-1105506311 what exactly does not work with this?

**Comment by DSDV** [comment]
If you click on add new repository and choose a smb share the program freezes. 
If you write the path by hand its says "unable to create repository" 

i am no developer therefor i sadly cannot tell you what does not work or how to fix it :(

**Comment by ThomasWaldmann** [comment]
You must give a normal filesystem path.

**Comment by DSDV** [comment]
1) so the menu is broken since it cant pick the correct path?
2) what is the "normal filesystem path" for SMB/CIFS in your opinion?

**Comment by ThomasWaldmann** [comment]
```
/mnt/samba
```
or where ever you mounted the `cifs`.

**Comment by DSDV** [comment]
according to terminal the path is "/run/us/1/gvfs/smb-share:server=10.0.0.15,share=sharename"
which also does not work. 

anyways when the open dialogue of a program does not work and freezes the program its a bug in my book ;) 
therefor this issue should not be closed as suggested by you. The UI does not work and even crashes vorta!

**Comment by ThomasWaldmann** [comment]
You didn't do what was suggested above.

pre-command something like:
```
sudo mount -t cifs -o username=...,password=... //10.0.0.15/sharename /mnt/samba 
```

post-command something like:
```
sudo umount /mnt/samba 
```

I didn't try it, you might need to tweak the options a bit. See also: https://wiki.ubuntuusers.de/mount.cifs/ and the man page.

There is no reason why borg would not work with a repo in some local or remote filesystem IF the filesystem behaves normally (and permissions are set up correctly).

**Comment by DSDV** [comment]
As i said i am no developer!
If it is truly desired behavior that a program crashes when you use tho open dialog i cant trust that program with my backups. 
Simple as that. 
If i somehow missed that this program is early access i am deeply sorry. 

otherwise pls add a note that its only meant for people who are devs. 
(i now don't wonder anymore where "the Linux reputation" comes from :( ).

as i stated above i expect a open dialog not to crash a program and work as expected and described by the program itself.
i have nothing to add here.

**Comment by real-yfprojects** [comment]
AFAIK borg supports cvfs mounted sambashares. The logs might help debugging this. I suggest you open a new issue and fill in the report form.

**Comment by ThomasWaldmann** [comment]
@DSDV This is not about development, but it requires familiarity with linux cli commands.

The goal of this is to reduce layers (== remove gvfs from the equation) and simplify (have a very simple path) by directly using a mounted cifs.

I agree it would be simpler if it "just worked" with the GUI dialogues, but that involves additional stuff and we still do not know what exactly is going wrong, not enough information.

**Comment by Flemmli97** [comment]
some things that might help with this too (on my system):

If using gvfs selecting an smb mounted folder redirects to `/run/user/1000/doc` instead of `/run/user/1000/gvfs` which throws a no permission error
```
2026-01-11 18:02:28,273 - vorta.borg.borg_job - ERROR - Failed to create/acquire the lock /run/user/1000/doc/3b57dcd/Test/lock.exclusive ([Errno 13] Permission denied: '/run/user/1000/doc/3b57dcd/Test/lock.exclusive.dg29blzk.tmp').
2026-01-11 18:02:28,275 - vorta.borg.borg_job - ERROR - Traceback (most recent call last):
  File "/app/lib/python3.12/site-packages/borg/archiver.py", line 5743, in main
    exit_code = archiver.run(args)
                ^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.12/site-packages/borg/archiver.py", line 5661, in run
    rc = func(args)
         ^^^^^^^^^^
  File "/app/lib/python3.12/site-packages/borg/archiver.py", line 185, in wrapper
    with repository:
         ^^^^^^^^^^
  File "/app/lib/python3.12/site-packages/borg/repository.py", line 217, in __enter__
    self.open(self.path, bool(self.exclusive), lock_wait=self.lock_wait, lock=self.do_lock)
  File "/app/lib/python3.12/site-packages/borg/repository.py", line 465, in open
    self.lock = Lock(os.path.join(path, 'lock'), exclusive, timeout=lock_wait).acquire()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.12/site-packages/borg/locking.py", line 398, in acquire
    with self._lock:
         ^^^^^^^^^^
  File "/app/lib/python3.12/site-packages/borg/locking.py", line 121, in __enter__
    return self.acquire()
           ^^^^^^^^^^^^^^
  File "/app/lib/python3.12/site-packages/borg/locking.py", line 143, in acquire
    raise LockFailed(self.path, str(err)) from None
borg.locking.LockFailed: Failed to create/acquire the lock /run/user/1000/doc/3b57dcd/Test/lock.exclusive ([Errno 13] Permission denied: '/run/user/1000/doc/3b57dcd/Test/lock.exclusive.dg29blzk.tmp').

Platform: Linux pop-os 6.16.3-76061603-generic #202508231538~1758561135~22.04~171c8de SMP PREEMPT_DYNAMIC Mon S x86_64
Linux: Unknown Linux  
Borg: 1.4.3  Python: CPython 3.12.12 msgpack: 1.1.2 fuse: pyfuse3 3.4.0 [pyfuse3,llfuse]
```

i would say if vorta would select the correct directory an smb attached volume should simply work out of the box.
in fact trying it with plain borg itself i can select and use the attached volume fine so i believe this problem lies with vorta.

> You didn't do what was suggested above.
> 
> pre-command something like:
> 
> ```
> sudo mount -t cifs -o username=...,password=... //10.0.0.15/sharename /mnt/samba 
> ```
> 
> post-command something like:
> 
> ```
> sudo umount /mnt/samba 
> ```

while this can atm do as a work around a better integration with the file system would be preferred

**Comment by ThomasWaldmann** [comment]
I guess you rather want to avoid gvfs: https://github.com/borgbackup/borg/issues/8120
