### ISSUE TITLE
Uncaught exception

### ISSUE THREAD

**Issue by technimad** [borgbase/vorta#1305]
I'm on macOS 10.14.6 installed vorta via brew. Manual run gives this exception:

```
Traceback (most recent call last):
  File "application.py", line 125, in create_backup_action
  File "borg/create.py", line 74, in prepare
  File "borg/borg_job.py", line 151, in prepare
  File "keyring/darwin.py", line 75, in get_password
  File "keyring/darwin.py", line 103, in _resolve_password
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "ctypes/__init__.py", line 8, in <module>
ImportError: dlopen(/Applications/Vorta.app/Contents/MacOS/lib-dynload/_ctypes.cpython-39-darwin.so, 2): Symbol not found: _ffi_closure_alloc
  Referenced from: /Applications/Vorta.app/Contents/MacOS/lib-dynload/_ctypes.cpython-39-darwin.so (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libffi.dylib
 in /Applications/Vorta.app/Contents/MacOS/lib-dynload/_ctypes.cpython-39-darwin.so
```

**Comment by m3nu** [comment]
macOS binary releases are built on the current "latest" version Github Actions use and often don't work on older versions.

You can still use install it via PyPi or build it locally using the steps in the Makefile or Github workflow.

**Comment by m3nu** [comment]
Small correction here: we currently build on the last supported version of macOS, if it's available from Github.

Currently this is macOS 10.15: https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners

The version you are using is already end of life and doesn't receive security updates any more.
