### ISSUE TITLE
"Uncaught exception" after update to latest version

### ISSUE THREAD

**Issue by AxleKirk** [borgbase/vorta#1318]
**Describe the bug**
Fatal Error at startup

**To Reproduce**
Start the program

**Environment (please complete the following information):**

- OS: Manjaro Linux 21.2.6 / Kernel Linux 5.17.9-1-MANJARO x86_64 / MATE 1.26.0
- Vorta version: 0.8.5 / Borg: 1.2.0
- Installed from:  Flathub (I guess)

**Additional context**
Traceback (most recent call last):

  File "/app/lib/python3.9/site-packages/vorta/views/schedule_tab.py", line 97, in <lambda>
    self.app.scheduler.schedule_changed.connect(lambda pid: self.draw_next_scheduled_backup())
  File "/app/lib/python3.9/site-packages/vorta/views/schedule_tab.py", line 164, in draw_next_scheduled_backup
    text = get_locale().toString(time, QLocale.FormatType.LongFormat)
  File "/app/lib/python3.9/site-packages/vorta/i18n/__init__.py", line 75, in get_locale
    return QLocale(translator.language())
AttributeError: 'QTranslator' object has no attribute 'language'

**Comment by real-yfprojects** [comment]
#1317
