### ISSUE TITLE
Something wrong )))

### ISSUE THREAD

**Issue by kepler273** [borgbase/vorta#1320]
Traceback (most recent call last):
  File "/app/lib/python3.9/site-packages/vorta/views/schedule_tab.py", line 97, in <lambda>
    self.app.scheduler.schedule_changed.connect(lambda pid: self.draw_next_scheduled_backup())
  File "/app/lib/python3.9/site-packages/vorta/views/schedule_tab.py", line 164, in draw_next_scheduled_backup
    text = get_locale().toString(time, QLocale.FormatType.LongFormat)
  File "/app/lib/python3.9/site-packages/vorta/i18n/__init__.py", line 75, in get_locale
    return QLocale(translator.language())
AttributeError: 'QTranslator' object has no attribute 'language'

**Comment by m3nu** [comment]
See #1317
