### ISSUE TITLE
AttributeError: 'QTranslator' object has no attribute 'language'

### ISSUE THREAD

**Issue by plamkas** [borgbase/vorta#1328]
After upgrading to version 0.8.5 the following error appears at launch:

Traceback (most recent call last):
  File "/home/XXX/.local/lib/python3.8/site-packages/vorta/views/schedule_tab.py", line 97, in <lambda>
    self.app.scheduler.schedule_changed.connect(lambda pid: self.draw_next_scheduled_backup())
  File "/home/XXX/.local/lib/python3.8/site-packages/vorta/views/schedule_tab.py", line 164, in draw_next_scheduled_backup
    text = get_locale().toString(time, QLocale.FormatType.LongFormat)
  File "/home/XXX/.local/lib/python3.8/site-packages/vorta/i18n/__init__.py", line 75, in get_locale
    return QLocale(translator.language())
AttributeError: 'QTranslator' object has no attribute 'language'

**Comment by jayp112** [comment]
Same error here as well.

**Comment by m3nu** [comment]
Already fixed in `master`. See other related issues for more.
