### ISSUE TITLE
Uncaught exception in draw_next_scheduled_backup

### ISSUE THREAD

**Issue by osandum** [borgbase/vorta#1331]
```
Traceback (most recent call last):
  File "/app/lib/python3.9/site-packages/vorta/views/schedule_tab.py", line 97, in <lambda>
    self.app.scheduler.schedule_changed.connect(lambda pid: self.draw_next_scheduled_backup())
  File "/app/lib/python3.9/site-packages/vorta/views/schedule_tab.py", line 164, in draw_next_scheduled_backup
    text = get_locale().toString(time, QLocale.FormatType.LongFormat)
  File "/app/lib/python3.9/site-packages/vorta/i18n/__init__.py", line 75, in get_locale
    return QLocale(translator.language())
AttributeError: 'QTranslator' object has no attribute 'language
```

**Describe the bug**
Appears in popup **Fatal Error** message dialog on startup, and again on backup completion.

**To Reproduce**

1. Launch Vorta
2. Error message appears

**Environment (please complete the following information):**
- OS: Fedora Linux 36 (Workstation Edition)
- Vorta version: v0.8.5
- Installed from: dl.flathub.org

**Comment by m3nu** [comment]
Fixed in release 0.8.6

See the many duplicates for more details.
