### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by miltonics** [borgbase/vorta#1332]
Uncaught exception, please file a report with this text at
https://github.com/borgbase/vorta/issues/new
Traceback (most recent call last):
  File "/app/lib/python3.9/site-packages/vorta/views/schedule_tab.py", line 97, in <lambda>
    self.app.scheduler.schedule_changed.connect(lambda pid: self.draw_next_scheduled_backup())
  File "/app/lib/python3.9/site-packages/vorta/views/schedule_tab.py", line 164, in draw_next_scheduled_backup
    text = get_locale().toString(time, QLocale.FormatType.LongFormat)
  File "/app/lib/python3.9/site-packages/vorta/i18n/__init__.py", line 75, in get_locale
    return QLocale(translator.language())
AttributeError: 'QTranslator' object has no attribute 'language

**Comment by real-yfprojects** [comment]
#1317

**Comment by miltonics** [comment]
So what happened? What can I do to prevent it happening again.

I got this error 2x in about 15 minutes.
