### ISSUE TITLE
'QTranslator' exception during backup

### ISSUE THREAD

**Issue by AyupMike** [borgbase/vorta#1333]
**Describe the bug**
Whenever Vorta starts a backup an exception is throw: `AttributeError: 'QTranslator' object has no attribute 'language'`

**To Reproduce**
Unknown

**Environment (please complete the following information):**
- OS: Fedora 36 Workstation Edition
- Vorta version: 0.8.5
- Borg version: 1.2.0
- Installed from: Flathub via "Software" app

**Additional context**
```
2022-05-25 17:52:04,081 - root - CRITICAL - Uncaught exception, file a report at https://github.com/borgbase/vorta/issues/new
Traceback (most recent call last):
  File "/app/lib/python3.9/site-packages/vorta/views/schedule_tab.py", line 97, in <lambda>
    self.app.scheduler.schedule_changed.connect(lambda pid: self.draw_next_scheduled_backup())
  File "/app/lib/python3.9/site-packages/vorta/views/schedule_tab.py", line 164, in draw_next_scheduled_backup
    text = get_locale().toString(time, QLocale.FormatType.LongFormat)
  File "/app/lib/python3.9/site-packages/vorta/i18n/__init__.py", line 75, in get_locale
    return QLocale(translator.language())
AttributeError: 'QTranslator' object has no attribute 'language'
```

**Comment by AyupMike** [comment]
Sorry - just seen this is a duplicate of #1317
