### ISSUE TITLE
Uncaught exception, please file a report with this text at

### ISSUE THREAD

**Issue by myfirstnameispaul** [borgbase/vorta#1341]
With nothing configured, I get the following when clicking link (break link? - I'm new here) button on the Repository tab:

> Uncaught exception, please file a report with this text at
> https://github.com/borgbase/vorta/issues/new
> Traceback (most recent call last):
>   File "/app/lib/python3.9/site-packages/peewee.py", line 6665, in get
>     return clone.execute(database)[0]
>   File "/app/lib/python3.9/site-packages/peewee.py", line 4121, in __getitem__
>     return self.row_cache[item]
> IndexError: list index out of range
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/app/lib/python3.9/site-packages/vorta/views/repo_tab.py", line 254, in repo_unlink_action
>     repo = RepoModel.get(id=selected_repo_id)
>   File "/app/lib/python3.9/site-packages/peewee.py", line 6242, in get
>     return sq.get()
>   File "/app/lib/python3.9/site-packages/peewee.py", line 6668, in get
>     raise self.model.DoesNotExist('%s instance matching query does '
> vorta.store.models.RepoModelDoesNotExist: <Model: RepoModel> instance matching query does not exist:
> SQL: SELECT "t1"."id", "t1"."url", "t1"."added_at", "t1"."encryption", "t1"."unique_size", "t1"."unique_csize", "t1"."total_size", "t1"."total_unique_chunks", "t1"."create_backup_cmd", "t1"."extra_borg_arguments" FROM "repomodel" AS "t1" WHERE ("t1"."id" IS ?) LIMIT ? OFFSET ?
> Params: [None, 1, 0]

Linux Mint 20.3 and installed from flatpak version 0.8.6.

**Comment by m3nu** [comment]
We're passing `None` as repo ID somewhere. Should be quick fix. Saw this a few times in other contexts.

**Comment by real-yfprojects** [comment]
> With nothing configured, I get the following when clicking link (break link? - I'm new here) button on the Repository tab:

So you don't have any repo's in the combo box next to the unlink button?

**Comment by myfirstnameispaul** [comment]
Correct. I just installed the package without anything being configured.
