### ISSUE TITLE
error while backing up with exclude folders

### ISSUE THREAD

**Issue by gillesdeloustal** [borgbase/vorta#1343]
Hi
I run vorta 0.8.3.1 installed from ubuntu 22.04 repository.
I backup windows folders accessed through samba.
After making several backups, I added excluded folders by their name without telling smb address.
Since this time I'm not anymore able to backup any vorta. I suppress the suppress excluded folders and get this error : 
ERROR: Traceback, (most recent call last):
File "usr/lib/python3/dist-packages/borg/archive.py, line 264, in OsOpen fd=os_open(path=path,parent_fd=parent_fr, name=name, flags=flags, noatime=noatime)
File "usr/lib/python3/dist-packages/borg/helpers/fs.py", line 290, in os_open, fd=os.open(fname,_flags_noatime, dir_fr=parent_fd)
FileNotFoundError: [Errno 2] No suche file or directory:'run/user/1000/gvfs/smb-share:server=annetregloze,share=f/a-Anne
The above exception was the direct cause of the following exception:
Traceback, (most recent call last):
File "usr/lib/python3/dist-packages/borg/archive.py, line 5089 in main

After re-doing it, I got following popup:

https://github.com/borgbase/vorta/issues/new
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/vorta/views/import_window.py", line 69, in run
    new_profile = self.profile_export.to_db(
  File "/usr/lib/python3/dist-packages/vorta/profile_export.py", line 74, in to_db
    profile_schema = self._profile_dict['SchemaVersion']['version']
KeyError: 'SchemaVersion'

Re-importing a profile, I now get the error 

Erreur non prise en charge, veuillez remplir un rapport de bug avec ce texte à l'adresse suivante
https://github.com/borgbase/vorta/issues/new
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/vorta/views/import_window.py", line 69, in run
    new_profile = self.profile_export.to_db(
  File "/usr/lib/python3/dist-packages/vorta/profile_export.py", line 74, in to_db
    profile_schema = self._profile_dict['SchemaVersion']['version']
KeyError: 'SchemaVersion'

**Comment by gillesdeloustal** [comment]
I set the complete remote address and everything run correctly again
