### ISSUE TITLE
Issue with database migration

### ISSUE THREAD

**Issue by pcj52** [borgbase/vorta#1364]
I get the following when trying to use Vorta:

~$ /usr/bin/flatpak run --branch=stable --arch=x86_64 --command=vorta com.borgbase.Vorta
2022-06-22 07:09:21,137 - root - CRITICAL - Uncaught exception, file a report at https://github.com/borgbase/vorta/issues/new
Traceback (most recent call last):
  File "/app/lib/python3.9/site-packages/peewee.py", line 3005, in execute_sql
    cursor.execute(sql, params or ())
sqlite3.OperationalError: duplicate column name: group

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/bin/vorta", line 8, in <module>
    sys.exit(main())
  File "/app/lib/python3.9/site-packages/vorta/__main__.py", line 54, in main
    init_db(sqlite_db)
  File "/app/lib/python3.9/site-packages/vorta/store/connection.py", line 66, in init_db
    run_migrations(current_schema, con)
  File "/app/lib/python3.9/site-packages/vorta/store/migrations.py", line 144, in run_migrations
    _apply_schema_update(
  File "/app/lib/python3.9/site-packages/vorta/store/migrations.py", line 153, in _apply_schema_update
    migrate(*operations)
  File "/app/lib/python3.9/site-packages/playhouse/migrate.py", line 823, in migrate
    operation.run()
  File "/app/lib/python3.9/site-packages/playhouse/migrate.py", line 160, in run
    self._handle_result(method(*self.args, **kwargs))
  File "/app/lib/python3.9/site-packages/playhouse/migrate.py", line 154, in _handle_result
    self._handle_result(item)
  File "/app/lib/python3.9/site-packages/playhouse/migrate.py", line 151, in _handle_result
    result.run()
  File "/app/lib/python3.9/site-packages/playhouse/migrate.py", line 160, in run
    self._handle_result(method(*self.args, **kwargs))
  File "/app/lib/python3.9/site-packages/playhouse/migrate.py", line 149, in _handle_result
    self.execute(result)
  File "/app/lib/python3.9/site-packages/playhouse/migrate.py", line 145, in execute
    self.migrator.database.execute(node)
  File "/app/lib/python3.9/site-packages/peewee.py", line 3018, in execute
    return self.execute_sql(sql, params, commit=commit)
  File "/app/lib/python3.9/site-packages/peewee.py", line 3012, in execute_sql
    self.commit()
  File "/app/lib/python3.9/site-packages/peewee.py", line 2783, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "/app/lib/python3.9/site-packages/peewee.py", line 183, in reraise
    raise value.with_traceback(tb)
  File "/app/lib/python3.9/site-packages/peewee.py", line 3005, in execute_sql
    cursor.execute(sql, params or ())
peewee.OperationalError: duplicate column name: group

**Comment by m3nu** [comment]
You somehow messed up your database. Find the sqlite DB, table version (or similar) and set the version to 19 or maybe even 20.

**Comment by real-yfprojects** [comment]
I use [sqlbrowser](https://sqlitebrowser.org/) for editing sql databases through a GUI.

**Comment by pcj52** [comment]
> If you don't have any settings in the database, you could also move or delete it. Since you didn't fill in the bug template I don't know which system or install method is used. You would need to find a folder called `Vorta` and move or delete `settings.db` there.

Thanks for the reply. I found and renamed "settings.db"  and Vorta started right up and I was able to recover my backup successfully. 

This is my first ever "bug" report. My apologies, I didn't  (still don't) see the bug template. I'll try to do it correctly next time, if there is a next time.

Thanks again.

**Comment by m3nu** [comment]
Glad you got it working. Would still like to know why the migration failed, since it generally shouldn't.

**Comment by pcj52** [comment]
Well, I'm not sure this will help but here is exactly what happened:  I had not performed a backup on my computer for several months (too long). My operating system is Linux Mint Cinnamon 19.3. The Vorta version is 0.8.7, the Borg version is 1.2.0. The install is flatpak. I did NOT do a migration (not even sure what that is). I simply clicked on the application shortcut and received no response at all. So I looked at the properties of the shortcut and copied and entered the command into a terminal window with the hope of getting a hint  as to what was going on. The output in my original comment was produced. That's it in it's entirety.  I hope that helps..........

**Comment by m3nu** [comment]
Maybe your DB version was very old and we did some breaking change. Good to know.

No migration is needed for Borg repos. Vorta just adds tables and columns to the DB sometimes. That's just about the stuff inside Vorta and doesn't affect your backup data at all.

**Comment by Solusway** [comment]
Hello,
I post recently a problem with Vorta (using on Linux Solus 4.3 fortitude). It looks same.
https://discuss.getsol.us/d/9017-vorta-doesnt-start-uncaught-critical-exception
So I renam the file settings.db (in .local/share/Vorta)
Then Vorta start again, but without my saving configuration.
I open settings.db in "DB Browser for SQLite", but I don't know anything about that, so I don't know how to get back my settings.

Then, when I wanted to close Vorta, I had this message :
`https://github.com/borgbase/vorta/issues/new
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/peewee.py", line 3237, in execute_sql
    cursor.execute(sql, params or ())
sqlite3.OperationalError: no such table: settingsmodel

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/vorta/views/main_window.py", line 272, in closeEvent
    ).execute()
  File "/usr/lib/python3.10/site-packages/peewee.py", line 1962, in inner
    return method(self, database, *args, **kwargs)
  File "/usr/lib/python3.10/site-packages/peewee.py", line 2033, in execute
    return self._execute(database)
  File "/usr/lib/python3.10/site-packages/peewee.py", line 2551, in _execute
    cursor = database.execute(self)
  File "/usr/lib/python3.10/site-packages/peewee.py", line 3250, in execute
    return self.execute_sql(sql, params, commit=commit)
  File "/usr/lib/python3.10/site-packages/peewee.py", line 3234, in execute_sql
    with __exception_wrapper__:
  File "/usr/lib/python3.10/site-packages/peewee.py", line 3010, in __exit__
    reraise(new_type, new_type(exc_value, *exc_args), traceback)
  File "/usr/lib/python3.10/site-packages/peewee.py", line 192, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3.10/site-packages/peewee.py", line 3237, in execute_sql
    cursor.execute(sql, params or ())
peewee.OperationalError: no such table: settingsmodel`

Thanks for help
