### ISSUE TITLE
Backup Exception: KeyError 'nfiles'

### ISSUE THREAD

**Issue by greenbourne277** [borgbase/vorta#1370]
Hey,
I just wanted to do my weekly backup and got this error on the console:
```
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/home/username/.local/lib/python3.10/site-packages/vorta/borg/jobs_manager.py", line 57, in run
    job.run()
  File "/home/username/.local/lib/python3.10/site-packages/vorta/borg/borg_job.py", line 257, in run
    f"{translate('BorgJob','Files')}: {parsed['nfiles']}, "
KeyError: 'nfiles'
```

The backup doesn't proceed after this error.

Vorta Version. 0.8.2
OS: Arch Linux
Python Version: 3.10.5

Best,
Christian

**Comment by greenbourne277** [comment]
@m3nu  I just tested it with 0.8.7 same error. Can we reopen it?
