### ISSUE TITLE
ConnectionClosed Exception shown in GUI

### ISSUE THREAD

**Issue by fain182** [borgbase/vorta#1373]
**Describe the bug**

An error with stacktrace is shown at the bottom of this screen.

![Schermata del 2022-07-08 15-23-45](https://user-images.githubusercontent.com/5879/178001573-67968d96-f5cd-40c6-a188-e0f3e33cc817.png)

**To Reproduce**
I have done nothing, everything happened automatically.

**Environment (please complete the following information):**
- OS: fedora 36
- Vorta version: 0.8.7 
- Installed from: flathub

Vorta and Borg versions can be found in Main Window > Misc Tab.

**Additional context**
If appropriate include logs. Can be found in Main Window > Misc Tab > Log.

**Comment by real-yfprojects** [comment]
Can you include the logs please?

**Comment by fain182** [comment]
```
2022-07-08 15:06:31,512 - vorta.scheduler - INFO - Starting background backup for Default
2022-07-08 15:06:31,514 - vorta.notifications - DEBUG - success notifications suppressed
2022-07-08 15:06:31,515 - vorta.keyring.abc - DEBUG - Only available on macOS
2022-07-08 15:06:31,603 - asyncio - DEBUG - Using selector: EpollSelector
2022-07-08 15:06:31,604 - vorta.keyring.abc - DEBUG - Using VortaSecretStorageKeyring
2022-07-08 15:06:31,604 - vorta.borg.borg_job - DEBUG - Using VortaSecretStorageKeyring keyring to store passwords.
2022-07-08 15:06:31,605 - asyncio - DEBUG - Using selector: EpollSelector
2022-07-08 15:06:31,606 - vorta.keyring.secretstorage - DEBUG - Found 1 passwords matching repo URL.
2022-07-08 15:06:31,607 - vorta.keyring.secretstorage - DEBUG - Retrieved password for repo shery5b8@shery5b8.repo.borgbase.com:repo
2022-07-08 15:06:31,627 - vorta.scheduler - INFO - Preparation for backup successful.
2022-07-08 15:06:31,627 - vorta.borg.jobs_manager - DEBUG - Add job for site 1
2022-07-08 15:06:31,628 - vorta.borg.jobs_manager - DEBUG - Start job on site: 1
2022-07-08 15:06:31,639 - vorta.borg.borg_job - INFO - Running command /app/bin/borg create --list --progress --info --log-json --json --filter=AM -C lz4 shery5b8@shery5b8.repo.borgbase.com:repo::fedora-2022-07-08-150631 /home/fain182
2022-07-08 15:06:33,907 - vorta.borg.borg_job - INFO - Creating archive at "shery5b8@shery5b8.repo.borgbase.com:repo::fedora-2022-07-08-150631"
2022-07-08 15:06:40,955 - vorta.borg.borg_job - INFO - Remote: Storage quota: 258.87 GB out of 400.00 GB used.
2022-07-08 15:11:37,487 - vorta.scheduler - DEBUG - Refreshing all scheduler timers
2022-07-08 15:11:37,494 - vorta.scheduler - INFO - Setting timer for profile 1
2022-07-08 15:11:37,496 - vorta.scheduler - DEBUG - Scheduling next run for 2022-07-08 20:06:31.632138
2022-07-08 15:23:07,760 - vorta.borg.borg_job - WARNING - Remote: client_loop: send disconnect: Broken pipe
2022-07-08 15:23:07,820 - vorta.borg.borg_job - ERROR - Local Exception
2022-07-08 15:23:07,820 - vorta.borg.borg_job - ERROR - Traceback (most recent call last):
  File "borg/archiver.py", line 183, in wrapper
  File "borg/archiver.py", line 668, in do_create
  File "borg/archiver.py", line 605, in create_inner
  File "borg/archiver.py", line 813, in _rec_walk
  File "borg/archiver.py", line 813, in _rec_walk
  File "borg/archiver.py", line 813, in _rec_walk
  [Previous line repeated 1 more time]
  File "borg/archiver.py", line 779, in _rec_walk
  File "borg/archiver.py", line 681, in _process_any
  File "borg/archive.py", line 1407, in process_file
  File "borg/archive.py", line 1234, in process_file_chunks
  File "borg/archive.py", line 1222, in chunk_processor
  File "borg/cache.py", line 947, in add_chunk
  File "borg/remote.py", line 476, in do_rpc
  File "borg/remote.py", line 709, in call
  File "borg/remote.py", line 826, in call_many
borg.remote.ConnectionClosed: Connection closed by remote host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "borg/archiver.py", line 5089, in main
  File "borg/archiver.py", line 5020, in run
  File "borg/archiver.py", line 183, in wrapper
  File "borg/remote.py", line 634, in __exit__
  File "borg/remote.py", line 476, in do_rpc
  File "borg/remote.py", line 709, in call
  File "borg/remote.py", line 779, in call_many
  File "borg/remote.py", line 719, in send_buffer
  File "borg/remote.py", line 417, in write
BrokenPipeError: [Errno 32] Broken pipe

Platform: Linux fedora 5.18.9-200.fc36.x86_64 #1 SMP PREEMPT_DYNAMIC Sat Jul 2 15:56:43 UTC 2022 x86_64
Linux: Unknown Linux  
Borg: 1.2.0  Python: CPython 3.9.10 msgpack: 1.0.3 fuse: llfuse 1.4.1 [pyfuse3,llfuse]
PID: 28  CWD: /home/fain182
sys.argv: ['/app/bin/borg', 'create', '--list', '--progress', '--info', '--log-json', '--json', '--filter=AM', '-C', 'lz4', 'shery5b8@shery5b8.repo.borgbase.com:repo::fedora-2022-07-08-150631', '/home/fain182']
SSH_ORIGINAL_COMMAND: None

2022-07-08 15:23:07,985 - vorta.borg.jobs_manager - DEBUG - Finish job for site: 1
2022-07-08 15:23:07,985 - vorta.borg.jobs_manager - DEBUG - No more jobs for site: 1
```

**Comment by real-yfprojects** [comment]
Thanks! I censored your repo url since it contains personal information in some way.

It seems like the connection to the borgbase server broke during a scheduled (automatic) backup and `borg` didn't handle it nicely. If this doesn't repeat too often there is no real issue. However, you could report this error message at the [borg repository](https://github.com/borgbackup/borg/issues) with the request to handle such exceptions more nicely in their code.

**Comment by fain182** [comment]
No, it happened only once if I remember correctly. Thank you.
