### ISSUE TITLE
fatal error due to missing dbus interface?

### ISSUE THREAD

**Issue by raingloom** [borgbase/vorta#1377]
First of all, in light of [not so recent news](https://sfconservancy.org/GiveUpGitHub/), is there any other avenue for submitting issues?

Second, the issue itself:
```
Uncaught exception, please file a report with this text at
https://github.com/borgbase/vorta/issues/new
Traceback (most recent call last):
  File "/gnu/store/lwhm1yhb6lzdn27x40c1zpq6n30wh3ma-vorta-0.8.3/lib/python3.9/site-packages/vorta/views/repo_add_dialog.py", line 221, in run
    self.thread.run()
  File "/gnu/store/lwhm1yhb6lzdn27x40c1zpq6n30wh3ma-vorta-0.8.3/lib/python3.9/site-packages/vorta/borg/borg_job.py", line 298, in run
    self.process_result(result)
  File "/gnu/store/lwhm1yhb6lzdn27x40c1zpq6n30wh3ma-vorta-0.8.3/lib/python3.9/site-packages/vorta/borg/info_repo.py", line 65, in process_result
    self.keyring.set_password("vorta-repo", new_repo.url, result['params']['password'])
  File "/gnu/store/lwhm1yhb6lzdn27x40c1zpq6n30wh3ma-vorta-0.8.3/lib/python3.9/site-packages/vorta/keyring/secretstorage.py", line 30, in set_password
    collection.create_item(repo_url, attributes, password, replace=True)
  File "/gnu/store/n7p2wi2cpd1vn62g461gbq93yp3rnrzf-python-secretstorage-3.3.1/lib/python3.9/site-packages/secretstorage/collection.py", line 125, in create_item
    return Item(self.connection, new_item, self.session)
  File "/gnu/store/n7p2wi2cpd1vn62g461gbq93yp3rnrzf-python-secretstorage-3.3.1/lib/python3.9/site-packages/secretstorage/item.py", line 31, in __init__
    self._item.get_property('Label')
  File "/gnu/store/n7p2wi2cpd1vn62g461gbq93yp3rnrzf-python-secretstorage-3.3.1/lib/python3.9/site-packages/secretstorage/util.py", line 64, in get_property
    (signature, value), = self.send_and_get_reply(msg)
  File "/gnu/store/n7p2wi2cpd1vn62g461gbq93yp3rnrzf-python-secretstorage-3.3.1/lib/python3.9/site-packages/secretstorage/util.py", line 46, in send_and_get_reply
    return self._connection.send_and_get_reply(msg, unwrap=True)
  File "/gnu/store/y1i9zdfiiki94j87zfb5wlkmbkl92pg0-python-jeepney-0.6.0/lib/python3.9/site-packages/jeepney/io/blocking.py", line 140, in send_and_get_reply
    return unwrap_msg(msg_in)
  File "/gnu/store/y1i9zdfiiki94j87zfb5wlkmbkl92pg0-python-jeepney-0.6.0/lib/python3.9/site-packages/jeepney/wrappers.py", line 214, in unwrap_msg
    raise DBusErrorResponse(msg)
jeepney.wrappers.DBusErrorResponse: [org.freedesktop.DBus.Error.UnknownInterface] ("No such interface 'org.freedesktop.DBus.Properties' at object path '/'",)
```

System is Guix.

Also I saw a warning about too many parameters being passed to something.  Not sure what that was about but I am using **passphrase** with spaces in it, so I wouldn't be surprised if Vorta fell into the decades old trap of not quoting something before passing it into `/bin/sh -c`.

**Comment by real-yfprojects** [comment]
I don't think this is a problem with vorta or your password containing spaces but a problem of your DBus configuration. 
Look up on the `qdbus` command line tool and use it to check whether the interface `org.freedesktop.DBus.Properties` exists.
Also consider opening an issue at the upstream `secretstorage` or the `jeepney` repo.

**Comment by raingloom** [comment]
yfprojects ***@***.***> writes:

> I don't think this is a problem with vorta or your password containing spaces but a problem of your DBus configuration.
> Look up on the qdbus command line tool and use it to check whether the interface org.freedesktop.DBus.Properties exists.
> Also consider opening an issue at the upstream secretstorage or the jeepney repo.

It does look like the open(2) related warning is already known and
documented as not really a bug.

I assume the property does not exist, but is it necessary for using the
secret storage?  Other packages that integrate with it (Nheko comes to
mind) never complained about it.  I'd like to understand if the presence
of that property is a hard requirement and if not, could Vorta handle
its absence more gracefully?
The password manager is KeepassXC by the way.

**Comment by real-yfprojects** [comment]
> It does look like the open(2) related warning is already known and documented as not really a bug. 

What warning do you mean?

> I'd like to understand if the presence of that property is a hard requirement and if not, could Vorta handle its absence more gracefully? 

The error is passed to vorta through `secretstorage`. You should open an issue including the questions there. 
From the perspective of the vorta dev's it is a hard requirement. Vorta could catch the error but I don't think there would be a point in that since this is a severe error that should be reported.

> The password manager is KeepassXC by the way.

KeePassXC is reported to work fine (usually).
