### ISSUE TITLE
NameError: name 'open' is not defined when backing up on remote pCloud device

### ISSUE THREAD

**Issue by alci63** [borgbase/vorta#1442]
#### Description

Initial backup with Vorta fails after some time when using a pCloud remote directory as destination.

I _was_ able to reproduce the issue each time I tried to make an initial backup of my home directory, but it failed at different time (once after 5Mb and a few second, one after 350Mb and several tens of minutes.

#### Environment

- OS: Kubuntu 22.10
- Vorta version: 0.8.7
- Installed from: ubuntu repository
- Borg version: 1.2.2

#### Logs

```
2022-10-28 08:51:52,657 - vorta.borg.borg_job - INFO - Running command /usr/bin/borg create --list --progress --info --log-json --json --filter=AM -C lz4 --exclude-from /tmp/tmpftyhqkji /home/franck/pCloudDrive/pcloud-tibook-backup::tibook-2022-10-28-085152 /home/franck
2022-10-28 08:51:52,753 - vorta.borg.borg_job - WARNING - /usr/lib/python3/dist-packages/trio/_core/_multierror.py:511: RuntimeWarning: You seem to already have a custom sys.excepthook handler installed. I'll skip installing Trio's custom handler, but this means MultiErrors will not show full tracebacks.
2022-10-28 08:51:52,754 - vorta.borg.borg_job - WARNING - warnings.warn(
2022-10-28 08:51:52,883 - vorta.borg.borg_job - INFO - Creating archive at "/home/franck/pCloudDrive/pcloud-tibook-backup::tibook-2022-10-28-085152"
2022-10-28 08:54:37,627 - vorta.borg.borg_job - WARNING - /home/franck/.local/share/baloo/index: file changed while we backed it up
2022-10-28 08:55:33,055 - vorta.borg.borg_job - ERROR - Failed to release the lock /home/franck/pCloudDrive/pcloud-tibook-backup/lock.exclusive (was not locked).
2022-10-28 08:55:33,056 - vorta.borg.borg_job - ERROR - Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 183, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 675, in do_create
    create_inner(archive, cache, fso)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 608, in create_inner
    self._rec_walk(path=path, parent_fd=parent_fd, name=name,
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 820, in _rec_walk
    self._rec_walk(
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 820, in _rec_walk
    self._rec_walk(
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 820, in _rec_walk
    self._rec_walk(
  [Previous line repeated 3 more times]
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 786, in _rec_walk
    status = self._process_any(path=path, parent_fd=parent_fd, name=name, st=st, fso=fso, cache=cache,
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 688, in _process_any
    return fso.process_file(path=path, parent_fd=parent_fd, name=name, st=st, cache=cache)
  File "/usr/lib/python3/dist-packages/borg/archive.py", line 1434, in process_file
    self.process_file_chunks(item, cache, self.stats, self.show_progress, backup_io_iter(self.chunker.chunkify(None, fd)))
  File "/usr/lib/python3/dist-packages/borg/archive.py", line 1261, in process_file_chunks
    item.chunks.append(chunk_processor(chunk))
  File "/usr/lib/python3/dist-packages/borg/archive.py", line 1249, in chunk_processor
    chunk_entry = cache.add_chunk(chunk_id, data, stats, wait=False)
  File "/usr/lib/python3/dist-packages/borg/cache.py", line 949, in add_chunk
    data = self.key.encrypt(chunk)
  File "/usr/lib/python3/dist-packages/borg/crypto/key.py", line 370, in encrypt
    next_iv = self.nonce_manager.ensure_reservation(self.cipher.next_iv(),
  File "/usr/lib/python3/dist-packages/borg/crypto/nonces.py", line 79, in ensure_reservation
    repo_free_nonce = self.get_repo_free_nonce()
  File "/usr/lib/python3/dist-packages/borg/crypto/nonces.py", line 38, in get_repo_free_nonce
    return self.repository.get_free_nonce()
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 347, in get_free_nonce
    raise AssertionError("bug in code, exclusive lock should exist here")
AssertionError: bug in code, exclusive lock should exist here

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 5159, in main
    exit_code = archiver.run(args)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 5090, in run
    return set_ec(func(args))
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 168, in wrapper
    with repository:
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 214, in __exit__
    self.close()
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 478, in close
    self.lock.release()
  File "/usr/lib/python3/dist-packages/borg/locking.py", line 420, in release
    self._lock.release()
  File "/usr/lib/python3/dist-packages/borg/locking.py", line 167, in release
    raise NotLocked(self.path)
borg.locking.NotLocked: Failed to release the lock /home/franck/pCloudDrive/pcloud-tibook-backup/lock.exclusive (was not locked).
```

**Comment by real-yfprojects** [comment]
This is an internal error of borg, please open an issue [at their repo](https://github.com/borgbackup/borg/issues). However they might not be able to fix it. To me it seems like the pCloud client syncs the local and remote drive in a way that doesn't allow consistent lock files.
