### ISSUE TITLE
Unhandled Exception while stopping backup task

### ISSUE THREAD

**Issue by RubenKelevra** [borgbase/vorta#1446]
### Description

I had a backup running and wanted to restart the backup process with other settings. So I stopped it.

After hitting stop (around one second after it) Vorta showed an unhandled exception.
![Screenshot from 2022-10-31 08-28-59](https://user-images.githubusercontent.com/614929/198954817-ce451426-0b97-464a-b298-d18c2c6f4ec3.png)

### Reproduction

- [X] I tried to reproduce the issue.
- [ ] I was able to reproduce the issue.

### OS

ArchLinux latest

### Version of Vorta

0.8.7

### What did you install Vorta with?

Other

### Version of Borg

1.2.2

### Logs

```pytb
2022-10-31 07:36:17,196 - vorta.borg.borg_job - INFO - Creating archive at "anubis:~/backups/borg-backups::i5.local-2022-10-31-073615"
2022-10-31 07:45:46,953 - vorta.scheduler - DEBUG - Refreshing all scheduler timers
2022-10-31 07:45:46,955 - vorta.scheduler - INFO - Setting timer for profile 1
2022-10-31 07:45:46,956 - vorta.scheduler - DEBUG - Scheduling next run for 2022-10-31 10:36:15.916634
2022-10-31 08:00:46,953 - vorta.scheduler - DEBUG - Refreshing all scheduler timers
2022-10-31 08:00:46,955 - vorta.scheduler - INFO - Setting timer for profile 1
2022-10-31 08:00:46,956 - vorta.scheduler - DEBUG - Scheduling next run for 2022-10-31 10:36:15.916634
2022-10-31 08:15:46,953 - vorta.scheduler - DEBUG - Refreshing all scheduler timers
2022-10-31 08:15:46,956 - vorta.scheduler - INFO - Setting timer for profile 1
2022-10-31 08:15:46,957 - vorta.scheduler - DEBUG - Scheduling next run for 2022-10-31 10:36:15.916634
2022-10-31 08:28:18,487 - vorta.borg.borg_job - DEBUG - Cancel job on site default
2022-10-31 08:28:18,488 - vorta.borg.borg_job - DEBUG - Cancel job on site 2
2022-10-31 08:28:18,510 - vorta.borg.borg_job - INFO - checkpoint requested: starting checkpoint creation...
2022-10-31 08:28:21,136 - vorta.borg.borg_job - INFO - checkpoint requested: finished checkpoint creation!
2022-10-31 08:28:21,488 - vorta.borg.jobs_manager - INFO - Finished cancelling all jobs
2022-10-31 08:28:21,500 - vorta.borg.borg_job - ERROR - Local Exception
2022-10-31 08:28:21,500 - vorta.borg.borg_job - ERROR - Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/borg/archiver.py", line 183, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/usr/lib/python3.10/site-packages/borg/archiver.py", line 675, in do_create
    create_inner(archive, cache, fso)
  File "/usr/lib/python3.10/site-packages/borg/archiver.py", line 608, in create_inner
    self._rec_walk(path=path, parent_fd=parent_fd, name=name,
  File "/usr/lib/python3.10/site-packages/borg/archiver.py", line 820, in _rec_walk
    self._rec_walk(
  File "/usr/lib/python3.10/site-packages/borg/archiver.py", line 820, in _rec_walk
    self._rec_walk(
  File "/usr/lib/python3.10/site-packages/borg/archiver.py", line 820, in _rec_walk
    self._rec_walk(
  [Previous line repeated 3 more times]
  File "/usr/lib/python3.10/site-packages/borg/archiver.py", line 786, in _rec_walk
    status = self._process_any(path=path, parent_fd=parent_fd, name=name, st=st, fso=fso, cache=cache,
  File "/usr/lib/python3.10/site-packages/borg/archiver.py", line 688, in _process_any
    return fso.process_file(path=path, parent_fd=parent_fd, name=name, st=st, cache=cache)
  File "/usr/lib/python3.10/site-packages/borg/archive.py", line 1434, in process_file
    self.process_file_chunks(item, cache, self.stats, self.show_progress, backup_io_iter(self.chunker.chunkify(None, fd)))
  File "/usr/lib/python3.10/site-packages/borg/archive.py", line 1261, in process_file_chunks
    item.chunks.append(chunk_processor(chunk))
  File "/usr/lib/python3.10/site-packages/borg/archive.py", line 1249, in chunk_processor
    chunk_entry = cache.add_chunk(chunk_id, data, stats, wait=False)
  File "/usr/lib/python3.10/site-packages/borg/cache.py", line 951, in add_chunk
    self.repository.put(id, data, wait=wait)
  File "/usr/lib/python3.10/site-packages/borg/remote.py", line 476, in do_rpc
    return self.call(f.__name__, named, **extra)
  File "/usr/lib/python3.10/site-packages/borg/remote.py", line 711, in call
    for resp in self.call_many(cmd, [args], **kw):
  File "/usr/lib/python3.10/site-packages/borg/remote.py", line 821, in call_many
    r, w, x = select.select(self.r_fds, w_fds, self.x_fds, 1)
  File "/usr/lib/python3.10/site-packages/borg/helpers/process.py", line 180, in handler
    raise exc_cls
borg.helpers.process.SigTerm

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/borg/archiver.py", line 5159, in main
    exit_code = archiver.run(args)
  File "/usr/lib/python3.10/site-packages/borg/archiver.py", line 5090, in run
    return set_ec(func(args))
  File "/usr/lib/python3.10/site-packages/borg/archiver.py", line 168, in wrapper
    with repository:
  File "/usr/lib/python3.10/site-packages/borg/remote.py", line 636, in __exit__
    self.rollback()
  File "/usr/lib/python3.10/site-packages/borg/remote.py", line 476, in do_rpc
    return self.call(f.__name__, named, **extra)
  File "/usr/lib/python3.10/site-packages/borg/remote.py", line 711, in call
    for resp in self.call_many(cmd, [args], **kw):
  File "/usr/lib/python3.10/site-packages/borg/remote.py", line 781, in call_many
    send_buffer()  # Try to send data, as some cases (async_response) will never try to send data otherwise.
  File "/usr/lib/python3.10/site-packages/borg/remote.py", line 721, in send_buffer
    written = self.ratelimit.write(self.stdin_fd, self.to_send.peek_front())
  File "/usr/lib/python3.10/site-packages/borg/remote.py", line 417, in write
    written = os.write(fd, to_send)
BrokenPipeError: [Errno 32] Broken pipe
```

**Comment by m3nu** [comment]
Dupe of #1444
