### ISSUE TITLE
Uncaught exception

### ISSUE THREAD

**Issue by Tom-H-L** [borgbase/vorta#1458]
#### Description

```pytb
Uncaught exception, please file a report with this text at
https://github.com/borgbase/vorta/issues/new
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/vorta/views/source_tab.py", line 156, in sources_update
    self.update_path_info(row)  # Update data for each entry
  File "/usr/lib/python3/dist-packages/vorta/views/source_tab.py", line 100, in update_path_info
    self.sourceFilesWidget.item(index_row, SourceColumn.Type).setText(self.tr("Calculating..."))
AttributeError: 'NoneType' object has no attribute 'setText'
```

This happened when I did the following while doing the settings for initializing a new repo:

1. Sources > Path: I deleted a path from the list
2. Sources > Path: I re-added the same path again to the list
3. Sources > Path: Since Type, Size and File Count remained empty, I clicked "Recalculate sizes" > Fatal Error

I _was_/_wasn't_ able to reproduce the issue.

#### Environment

- OS: Ubuntu 22.04.1 LTS
- Vorta version: 0.8.3
- Installed from: Ubuntu Universe repository (=Debian repos, not Ubuntu Snap repos)
- Borg version: 1.2.0

#### Logs

```
*paste logs here*
```

**Comment by real-yfprojects** [comment]
What about logs? @Tom-H-L 
That would be very helpful.

**Comment by real-yfprojects** [comment]
ping @Tom-H-L

**Comment by tio-trom** [comment]
I got a similar one too:

```
Uncaught exception, please file a report with this text at
https://github.com/borgbase/vorta/issues/new
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/peewee.py", line 7072, in get
    return clone.execute(database)[0]
  File "/usr/lib/python3.10/site-packages/peewee.py", line 4436, in __getitem__
    return self.row_cache[item]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/vorta/application.py", line 219, in react_to_log
    profile = BackupProfileModel.get(name=context['profile_name'])
  File "/usr/lib/python3.10/site-packages/peewee.py", line 6624, in get
    return sq.get()
  File "/usr/lib/python3.10/site-packages/peewee.py", line 7075, in get
    raise self.model.DoesNotExist('%s instance matching query does '
vorta.store.models.BackupProfileModelDoesNotExist: <Model: BackupProfileModel> instance matching query does not exist:
SQL: SELECT "t1"."id", "t1"."name", "t1"."added_at", "t1"."repo_id", "t1"."ssh_key", "t1"."compression", "t1"."exclude_patterns", "t1"."exclude_if_present", "t1"."schedule_mode", "t1"."schedule_interval_count", "t1"."schedule_interval_unit", "t1"."schedule_fixed_hour", "t1"."schedule_fixed_minute", "t1"."schedule_interval_hours", "t1"."schedule_interval_minutes", "t1"."schedule_make_up_missed", "t1"."validation_on", "t1"."validation_weeks", "t1"."prune_on", "t1"."prune_hour", "t1"."prune_day", "t1"."prune_week", "t1"."prune_month", "t1"."prune_year", "t1"."prune_keep_within", "t1"."new_archive_name", "t1"."prune_prefix", "t1"."pre_backup_cmd", "t1"."post_backup_cmd", "t1"."dont_run_on_metered_networks" FROM "backupprofilemodel" AS "t1" WHERE ("t1"."name" = ?) LIMIT ? OFFSET ?
Params: ['New Repo', 1, 0]
```

I am trying to add my massive repos again after I reinstalled my OS. They are added with the message: done. But Vorta freezes and I have to nuke the process. After I reopen there is no repo added. When I try to add it again I got that message. I have some 4TB of backups I need to urgently add to my Vorta but I cannot make it work.

**Comment by real-yfprojects** [comment]
@tio-trom Your error is fairly far from similar to OPs. Yours is probably the same as #1449. However we would need the logs to confirm that.

**Comment by tio-trom** [comment]
> @tio-trom Your error is fairly far from similar to OPs. Yours is probably the same as #1449. However we would need the logs to confirm that.

I understand sorry. Eventually it worked so mine can be ignored.
