### ISSUE TITLE
Vorta doesn't save configuration of ssh key and compression.

### ISSUE THREAD

**Issue by mightyBroccoli** [borgbase/vorta#1495]
### Description

The Vorta client "forgets" the associated SSH Key and compression related to the selected profile.

The key is functional and hasn't change in quite a while. Additionally the key is also used with borgmatic on the cli without any issues.

Steps to reproduce:
- install Vorta and all accessories
- configure Vorta profile with an SSH key and compression
- restart Vorta / reboot e.g. 

### Reproduction

- [X] I tried to reproduce the issue.
- [X] I was able to reproduce the issue.

### OS

ArchLinux latest, xfce 4.16

### Version of Vorta

0.8.9

### What did you install Vorta with?

Other

### Version of Borg

1.2.2

### Logs

```pytb
2022-11-21 10:04:18,490 - root - DEBUG - Expected error parsing file in .ssh: id_backupspace (You can safely ignore this)
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/paramiko/pkey.py", line 525, in _uint32_cstruct_unpack
    s_size = struct.unpack(">L", data[idx : idx + 4])[0]
struct.error: unpack requires a buffer of 4 bytes

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/vorta/utils.py", line 195, in get_private_keys
    parsed_key = key_format.from_private_key_file(key_file)
  File "/usr/lib/python3.10/site-packages/paramiko/pkey.py", line 249, in from_private_key_file
    key = cls(filename=filename, password=password)
  File "/usr/lib/python3.10/site-packages/paramiko/rsakey.py", line 64, in __init__
    self._from_private_key_file(filename, password)
  File "/usr/lib/python3.10/site-packages/paramiko/rsakey.py", line 195, in _from_private_key_file
    self._decode_key(data)
  File "/usr/lib/python3.10/site-packages/paramiko/rsakey.py", line 211, in _decode_key
    n, e, d, iqmp, p, q = self._uint32_cstruct_unpack(data, "iiiiii")
  File "/usr/lib/python3.10/site-packages/paramiko/pkey.py", line 545, in _uint32_cstruct_unpack
    raise SSHException(str(e))
paramiko.ssh_exception.SSHException: unpack requires a buffer of 4 bytes
2022-11-21 10:04:18,490 - root - DEBUG - Expected error parsing file in .ssh: id_backupspace (You can safely ignore this)
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/paramiko/ecdsakey.py", line 301, in _decode_key
    curve_name = msg.get_text()
  File "/usr/lib/python3.10/site-packages/paramiko/message.py", line 178, in get_text
    return u(self.get_string())
  File "/usr/lib/python3.10/site-packages/paramiko/py3compat.py", line 161, in u
    return s.decode(encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa7 in position 0: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/vorta/utils.py", line 195, in get_private_keys
    parsed_key = key_format.from_private_key_file(key_file)
  File "/usr/lib/python3.10/site-packages/paramiko/pkey.py", line 249, in from_private_key_file
    key = cls(filename=filename, password=password)
  File "/usr/lib/python3.10/site-packages/paramiko/ecdsakey.py", line 126, in __init__
    self._from_private_key_file(filename, password)
  File "/usr/lib/python3.10/site-packages/paramiko/ecdsakey.py", line 278, in _from_private_key_file
    self._decode_key(data)
  File "/usr/lib/python3.10/site-packages/paramiko/ecdsakey.py", line 314, in _decode_key
    raise SSHException(str(e))
paramiko.ssh_exception.SSHException: 'utf-8' codec can't decode byte 0xa7 in position 0: invalid start byte
```

**Comment by mightyBroccoli** [comment]
I attached the complete startup logs, I noticed that Vorta even tries to parse the authorized_keys file failing in the process.
I have 3 working ssh keys on this machine.
[vorta_debug.log](https://github.com/borgbase/vorta/files/10082136/vorta_debug.log)

**Comment by real-yfprojects** [comment]
I found the bug :point_up:

**Comment by real-yfprojects** [comment]
This is just a GUI  (display) bug that doesn't affect the backups. While the compression and key set are correctly saved and used, they aren't shown correctly after restart.
