### ISSUE TITLE
Database problem? - CRITICAL - Uncaught exception

### ISSUE THREAD

**Issue by Solusway** [borgbase/vorta#1501]
Hi,
I post recently a problem with Vorta (using on Linux Solus 4.3 fortitude). 
https://discuss.getsol.us/d/9017-vorta-doesnt-start-uncaught-critical-exception

```
root - CRITICAL - Uncaught exception, file a report at https://github.com/borgbase/vorta/issues/new/choose
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/peewee.py", line 3237, in execute_sql
    cursor.execute(sql, params or ())
sqlite3.OperationalError: duplicate column name: group

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/vorta", line 33, in <module>
    sys.exit(load_entry_point('vorta==0.8.9', 'gui_scripts', 'vorta')())
  File "/usr/lib/python3.10/site-packages/vorta/__main__.py", line 66, in main
    init_db(sqlite_db)
  File "/usr/lib/python3.10/site-packages/vorta/store/connection.py", line 83, in init_db
    run_migrations(current_schema, con)
  File "/usr/lib/python3.10/site-packages/vorta/store/migrations.py", line 216, in run_migrations
    _apply_schema_update(
  File "/usr/lib/python3.10/site-packages/vorta/store/migrations.py", line 225, in _apply_schema_update
    migrate(*operations)
  File "/usr/lib/python3.10/site-packages/playhouse/migrate.py", line 886, in migrate
    operation.run()
  File "/usr/lib/python3.10/site-packages/playhouse/migrate.py", line 164, in run
    self._handle_result(method(*self.args, **kwargs))
  File "/usr/lib/python3.10/site-packages/playhouse/migrate.py", line 158, in _handle_result
    self._handle_result(item)
  File "/usr/lib/python3.10/site-packages/playhouse/migrate.py", line 155, in _handle_result
    result.run()
  File "/usr/lib/python3.10/site-packages/playhouse/migrate.py", line 164, in run
    self._handle_result(method(*self.args, **kwargs))
  File "/usr/lib/python3.10/site-packages/playhouse/migrate.py", line 153, in _handle_result
    self.execute(result)
  File "/usr/lib/python3.10/site-packages/playhouse/migrate.py", line 149, in execute
    self.migrator.database.execute(node)
  File "/usr/lib/python3.10/site-packages/peewee.py", line 3250, in execute
    return self.execute_sql(sql, params, commit=commit)
  File "/usr/lib/python3.10/site-packages/peewee.py", line 3234, in execute_sql
    with __exception_wrapper__:
  File "/usr/lib/python3.10/site-packages/peewee.py", line 3010, in __exit__
    reraise(new_type, new_type(exc_value, *exc_args), traceback)
  File "/usr/lib/python3.10/site-packages/peewee.py", line 192, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3.10/site-packages/peewee.py", line 3237, in execute_sql
    cursor.execute(sql, params or ())
peewee.OperationalError: duplicate column name: group
```

So I renam the file settings.db (in .local/share/Vorta)
Then Vorta start again, but without my saving configuration.
I open settings.db in "DB Browser for SQLite" (my settings seems to be inside), but I don't know anything about that, so I don't know how to get back my settings.

Then, when I wanted to close Vorta, I had this message :

```
Traceback (most recent call last):
File "/usr/lib/python3.10/site-packages/peewee.py", line 3237, in execute_sql
cursor.execute(sql, params or ())
sqlite3.OperationalError: no such table: settingsmodel

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/lib/python3.10/site-packages/vorta/views/main_window.py", line 272, in closeEvent
).execute()
File "/usr/lib/python3.10/site-packages/peewee.py", line 1962, in inner
return method(self, database, *args, **kwargs)
File "/usr/lib/python3.10/site-packages/peewee.py", line 2033, in execute
return self._execute(database)
File "/usr/lib/python3.10/site-packages/peewee.py", line 2551, in _execute
cursor = database.execute(self)
File "/usr/lib/python3.10/site-packages/peewee.py", line 3250, in execute
return self.execute_sql(sql, params, commit=commit)
File "/usr/lib/python3.10/site-packages/peewee.py", line 3234, in execute_sql
with exception_wrapper:
File "/usr/lib/python3.10/site-packages/peewee.py", line 3010, in exit
reraise(new_type, new_type(exc_value, *exc_args), traceback)
File "/usr/lib/python3.10/site-packages/peewee.py", line 192, in reraise
raise value.with_traceback(tb)
File "/usr/lib/python3.10/site-packages/peewee.py", line 3237, in execute_sql
cursor.execute(sql, params or ())
peewee.OperationalError: no such table: settingsmodel`
```

I hope it is usefull

**Comment by Solusway** [comment]
..After re-restart, no more error message.
And if I use again my file settings.db, my old settings are coming back.
So it seems to be ok now.

**Comment by real-yfprojects** [comment]
duplicated of #1364.

**Comment by sysdbugfactory** [comment]
> ..After re-restart, no more error message. And if I use again my file settings.db, my old settings are coming back. So it seems to be ok now.

I tried your workaround fix: after renaming settings.db vorta does launch with no settings as expected, but after closing vorta and putting back the old settings file, vorta now starts but fails to find the settings.

Sadly this fix did not work for me, but it helped to better diagnose my situation and I now know that vorta fails before going through the db migration process as it generated two new settings files:  .db-shm and and  .db-wal. This suggests that manually editing the database as suggested might cause other unexpected issue.
Deleting these two files is required to revert to state the machine was in before trying this workaround.

If I could find a way to extract the settings from the actual database, I might be able to recreate them in the blank but actually launching vorta, to be able to automate the process for the other user profiles affected by this issue, and for later use when it will happen again.
