### ISSUE TITLE
Error Launching Vorta - Fedora RPM

### ISSUE THREAD

**Issue by hagenman** [borgbase/vorta#1512]
### Description

Encountered issue launching Vorta

Traceback (most recent call last):
  File "/usr/lib64/python3.11/site-packages/peewee.py", line 3237, in execute_sql
    cursor.execute(sql, params or ())
sqlite3.OperationalError: duplicate column name: group

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/bin/vorta", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3.11/site-packages/vorta/__main__.py", line 66, in main
    init_db(sqlite_db)
  File "/usr/lib/python3.11/site-packages/vorta/store/connection.py", line 83, in init_db
    run_migrations(current_schema, con)
  File "/usr/lib/python3.11/site-packages/vorta/store/migrations.py", line 216, in run_migrations
    _apply_schema_update(
  File "/usr/lib/python3.11/site-packages/vorta/store/migrations.py", line 225, in _apply_schema_update
    migrate(*operations)
  File "/usr/lib64/python3.11/site-packages/playhouse/migrate.py", line 886, in migrate
    operation.run()
  File "/usr/lib64/python3.11/site-packages/playhouse/migrate.py", line 164, in run
    self._handle_result(method(*self.args, **kwargs))
  File "/usr/lib64/python3.11/site-packages/playhouse/migrate.py", line 158, in _handle_result
    self._handle_result(item)
  File "/usr/lib64/python3.11/site-packages/playhouse/migrate.py", line 155, in _handle_result
    result.run()
  File "/usr/lib64/python3.11/site-packages/playhouse/migrate.py", line 164, in run
    self._handle_result(method(*self.args, **kwargs))
  File "/usr/lib64/python3.11/site-packages/playhouse/migrate.py", line 153, in _handle_result
    self.execute(result)
  File "/usr/lib64/python3.11/site-packages/playhouse/migrate.py", line 149, in execute
    self.migrator.database.execute(node)
  File "/usr/lib64/python3.11/site-packages/peewee.py", line 3250, in execute
    return self.execute_sql(sql, params, commit=commit)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/peewee.py", line 3234, in execute_sql
    with __exception_wrapper__:
  File "/usr/lib64/python3.11/site-packages/peewee.py", line 3010, in __exit__
    reraise(new_type, new_type(exc_value, *exc_args), traceback)
  File "/usr/lib64/python3.11/site-packages/peewee.py", line 192, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib64/python3.11/site-packages/peewee.py", line 3237, in execute_sql
    cursor.execute(sql, params or ())
peewee.OperationalError: duplicate column name: group

### Reproduction

- [X] I tried to reproduce the issue.
- [X] I was able to reproduce the issue.

### OS

Fedora 37

### Version of Vorta

vorta-0.8.9-1.fc37.noarch

### What did you install Vorta with?

Distribution package

### Version of Borg

1.2.1-12

### Logs

```pytb
Can't get into the program to gather logs.
```

**Comment by m3nu** [comment]
Looks like a failed DB migration. You can try opening the `settings.db` file with SQLite and increase the number in `schemaversion` by +1. Or remove that file and start over.

**Comment by hagenman** [comment]
Incrementing +1 worked!  Thank you!
