### ISSUE TITLE
Symbol not found: _ffi_closure_alloc

### ISSUE THREAD

**Issue by SlashLP97** [borgbase/vorta#1525]
#### Description

This issue happens any time I try to create a repository

```pytb
Traceback (most recent call last):
  File "views/repo_add_dialog.py", line 98, in set_password
  File "keyring/darwin.py", line 96, in get_password
  File "keyring/darwin.py", line 124, in _resolve_password
  File "PyInstaller/loader/pyimod02_importers.py", line 499, in exec_module
  File "ctypes/__init__.py", line 8, in <module>
ImportError: dlopen(/Applications/Vorta.app/Contents/MacOS/lib-dynload/_ctypes.cpython-310-darwin.so, 2): Symbol not found: _ffi_closure_alloc
  Referenced from: /Applications/Vorta.app/Contents/MacOS/lib-dynload/_ctypes.cpython-310-darwin.so (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libffi.dylib
 in /Applications/Vorta.app/Contents/MacOS/lib-dynload/_ctypes.cpython-310-darwin.so
```

#### Environment

- OS: macOS Mojave 10.14.6
- Vorta version: 0.8.9
- Installed from: Homebrew
- Borg version: 1.2.2 (1.2.3 is installed according to 'brew info borgbackup' but the Misc tab shows 1.2.2)

#### Logs

```pytb
2023-01-03 09:39:57,580 - root - DEBUG - Expected error parsing file in .ssh: id_rsa (You can safely ignore this)
Traceback (most recent call last):
  File "paramiko/ecdsakey.py", line 301, in _decode_key
  File "paramiko/message.py", line 178, in get_text
  File "paramiko/py3compat.py", line 161, in u
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xaa in position 1: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "utils.py", line 195, in get_private_keys
  File "paramiko/pkey.py", line 249, in from_private_key_file
  File "paramiko/ecdsakey.py", line 126, in __init__
  File "paramiko/ecdsakey.py", line 278, in _from_private_key_file
  File "paramiko/ecdsakey.py", line 314, in _decode_key
paramiko.ssh_exception.SSHException: 'utf-8' codec can't decode byte 0xaa in position 1: invalid start byte
2023-01-03 09:39:57,581 - root - DEBUG - Expected error parsing file in .ssh: id_rsa (You can safely ignore this)
Traceback (most recent call last):
  File "utils.py", line 195, in get_private_keys
  File "paramiko/pkey.py", line 249, in from_private_key_file
  File "paramiko/ed25519key.py", line 63, in __init__
  File "paramiko/ed25519key.py", line 112, in _parse_signing_key_data
paramiko.ssh_exception.SSHException: Invalid key
2023-01-03 09:39:57,581 - root - DEBUG - Expected error parsing file in .ssh: id_rsa.pub (You can safely ignore this)
Traceback (most recent call last):
  File "utils.py", line 195, in get_private_keys
  File "paramiko/pkey.py", line 249, in from_private_key_file
  File "paramiko/rsakey.py", line 64, in __init__
  File "paramiko/rsakey.py", line 194, in _from_private_key_file
  File "paramiko/pkey.py", line 322, in _read_private_key_file
  File "paramiko/pkey.py", line 340, in _read_private_key
paramiko.ssh_exception.SSHException: not a valid RSA private key file
2023-01-03 09:39:57,582 - root - DEBUG - Expected error parsing file in .ssh: id_rsa.pub (You can safely ignore this)
Traceback (most recent call last):
  File "utils.py", line 195, in get_private_keys
  File "paramiko/pkey.py", line 249, in from_private_key_file
  File "paramiko/ecdsakey.py", line 126, in __init__
  File "paramiko/ecdsakey.py", line 277, in _from_private_key_file
  File "paramiko/pkey.py", line 322, in _read_private_key_file
  File "paramiko/pkey.py", line 340, in _read_private_key
paramiko.ssh_exception.SSHException: not a valid EC private key file
2023-01-03 09:39:57,582 - root - DEBUG - Expected error parsing file in .ssh: id_rsa.pub (You can safely ignore this)
Traceback (most recent call last):
  File "utils.py", line 195, in get_private_keys
  File "paramiko/pkey.py", line 249, in from_private_key_file
  File "paramiko/ed25519key.py", line 58, in __init__
  File "paramiko/pkey.py", line 340, in _read_private_key
paramiko.ssh_exception.SSHException: not a valid OPENSSH private key file
2023-01-03 09:39:57,582 - root - DEBUG - Expected error parsing file in .ssh: known_hosts (You can safely ignore this)
Traceback (most recent call last):
  File "utils.py", line 195, in get_private_keys
  File "paramiko/pkey.py", line 249, in from_private_key_file
  File "paramiko/rsakey.py", line 64, in __init__
  File "paramiko/rsakey.py", line 194, in _from_private_key_file
  File "paramiko/pkey.py", line 322, in _read_private_key_file
  File "paramiko/pkey.py", line 340, in _read_private_key
paramiko.ssh_exception.SSHException: not a valid RSA private key file
2023-01-03 09:39:57,583 - root - DEBUG - Expected error parsing file in .ssh: known_hosts (You can safely ignore this)
Traceback (most recent call last):
  File "utils.py", line 195, in get_private_keys
  File "paramiko/pkey.py", line 249, in from_private_key_file
  File "paramiko/ecdsakey.py", line 126, in __init__
  File "paramiko/ecdsakey.py", line 277, in _from_private_key_file
  File "paramiko/pkey.py", line 322, in _read_private_key_file
  File "paramiko/pkey.py", line 340, in _read_private_key
paramiko.ssh_exception.SSHException: not a valid EC private key file
2023-01-03 09:39:57,583 - root - DEBUG - Expected error parsing file in .ssh: known_hosts (You can safely ignore this)
Traceback (most recent call last):
  File "utils.py", line 195, in get_private_keys
  File "paramiko/pkey.py", line 249, in from_private_key_file
  File "paramiko/ed25519key.py", line 58, in __init__
  File "paramiko/pkey.py", line 340, in _read_private_key
paramiko.ssh_exception.SSHException: not a valid OPENSSH private key file
2023-01-03 09:39:57,592 - vorta.keyring.abc - DEBUG - No module named 'secretstorage'
2023-01-03 09:39:57,592 - vorta.keyring.abc - DEBUG - Using VortaDarwinKeyring
2023-01-03 09:40:02,763 - vorta.keyring.abc - DEBUG - No module named 'secretstorage'
2023-01-03 09:40:02,763 - vorta.keyring.abc - DEBUG - Using VortaDarwinKeyring
2023-01-03 09:40:02,771 - root - CRITICAL - Uncaught exception, file a report at https://github.com/borgbase/vorta/issues/new/choose
Traceback (most recent call last):
  File "views/repo_add_dialog.py", line 98, in set_password
  File "keyring/darwin.py", line 96, in get_password
  File "keyring/darwin.py", line 124, in _resolve_password
  File "PyInstaller/loader/pyimod02_importers.py", line 499, in exec_module
  File "ctypes/__init__.py", line 8, in <module>
ImportError: dlopen(/Applications/Vorta.app/Contents/MacOS/lib-dynload/_ctypes.cpython-310-darwin.so, 2): Symbol not found: _ffi_closure_alloc
  Referenced from: /Applications/Vorta.app/Contents/MacOS/lib-dynload/_ctypes.cpython-310-darwin.so (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libffi.dylib
 in /Applications/Vorta.app/Contents/MacOS/lib-dynload/_ctypes.cpython-310-darwin.so
```

**Comment by real-yfprojects** [comment]
We need more information to help with issues. That's why I pasted our bug report form into your post. Pls complete the form.

**Comment by SlashLP97** [comment]
Sorry about that! I figured there was a bug report format but I couldn't find one before. Updated with all requested information.

**Comment by warmup72** [comment]
Same with Ventura - I couldn´t create a new Archiv anymore. Same Error-Message. The Repository is created but after doing some more savings the archives were destroyed - no Errormessage during Backup. After that doing any action (e.g. list) leads to the Error Message: vorta.borg.borg_job - ERROR - Data integrity error: Invalid segment entry size 0 - too small [segment 168, offset 24237737]

Since Saturday I´ve tried 3 times to Backup - allways the same Error

**Comment by m3nu** [comment]
You describe 2 different errors here. For the data error, you'll just want to run `borg check`. There were some rare reports of harmless integrity errors with Borg 1.2. They don't seem to happen very often, but maybe you got lucky.

The other is a library error. Using Ventura and the version before myself, I never saw this. So maybe a very special setup. You could try this local unsigned build I made for another issue. This may take care of the library issues.
Building the macOS app isn't always straightforward when one wants to support multiple versions. So currently we just build on the latest supported version GH Actions has.

https://files.qmax.us/vorta/Vorta-0.8.10pre.zip

**Comment by SlashLP97** [comment]
When I try to run the unsigned version I get a pop-up that says "“Vorta” is damaged and can’t be opened. You should move it to the Trash."

If Vorta is only built for the newest version of macOS I'm guessing I won't have much luck running it on Mojave. Is there an older version that was verified to work with Mojave I could use?

**Comment by warmup72** [comment]
Apologies for my unstructured post. I was a little annoyed by the days of testing without a light at the end of the tunnel.
First the information that with the pre-release under Ventura no more error messages appear in the log.

An important note for other Ventura users who back up their data via SMB. For me, the stick is attached to a Fritzbox 7490.
There is obviously a Ventura bug here. It's probably not uncommon for SMB to cause problems after a macOS update (just google it).

In any case, I could now understand that everything runs super well with a local backup.
If I access Ventura via SMB, the backups are destroyed again and again.
A simple archive update or requesting differences is enough for this :-(

**Comment by warmup72** [comment]
Apologies for my unstructured post. I was a little annoyed by the days of testing without a light at the end of the tunnel.
First the information that with the pre-release under Ventura no more error messages appear in the log.

An important note for other Ventura users who back up their data via SMB. For me, the stick is attached to a Fritzbox 7490.
There is obviously a Ventura bug here. It's probably not uncommon for SMB to cause problems after a macOS update (just google it).

In any case, I could now understand that everything runs super well with a local backup.
If I access Ventura via SMB, the backups are destroyed again and again.
A simple archive update or requesting differences is enough for this :-(

**Comment by m3nu** [comment]
SMB was never supported as backend for Borg.

Good the pre-release works as expected. You may need to confirm a prompt before running it because it's not signed.

**Comment by SlashLP97** [comment]
Is the issue @warmup72 is reporting at all related to mine? I'm trying to do a local backup and no data errors (since I can't even get to that step). I get all manner of errors when I try and do anything that interfaces to the repository or any archives in it (that I created using the Borg CLI - so I know Borg is working correctly). I am unable to run the prerelease build as macOS just says it's damaged and should be moved to the trash.

**Comment by real-yfprojects** [comment]
The error says:
> (which was built for Mac OS X 10.15)

and you are using 10.14, so maybe that's the problem.

I also found these resources on the internet:
https://github.com/AcidWeb/CurseBreaker/issues/266 -> maybe increasing bundled python version to 3.11 helps :shrug: 
https://stackoverflow.com/questions/63267667/dyld-symbol-not-found-ffi-prep-closure-loc-on-mac

**Comment by m3nu** [comment]
I set Python to 3.11 for the local build I did. IIRC.

Since this is built on the latest macOS, it may not work on the versions before that.

That's why Github actions is better, since it allows for older macOS versions. Though they dropped support for some older one in Dec or so.
