### ISSUE TITLE
Archive extraction fails due to temporary file not found for --patterns-from borg command flag

### ISSUE THREAD

**Issue by AlessandroPerazzetta** [borgbase/vorta#1540]
### Description

The extraction of the chosen archive fails with the following error: 
```FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpXXXXX'``` 

despite the message :
```'Restored files from archive.' ```

Steps to reproduce:
1. Create backup archive
2. Try to restore archive from a fresh new os install (with vorta and borg backup same version, repository and profile imported correctly)

NB: 
Tried multiple times on a virtual machine, same results.
Archive are also mountable and are fine

Temporary fix is commenting out line:

cmd.extend(['--patterns-from', pattern_file.name])

on:

/usr/local/lib/python3.8/dist-packages/vorta/borg/extract.py

After a little search delete of temporary file cause the problem.

As reported by the doc function NamedTemporaryFile temporary file is deleted as soon as it is closed, change param delete=True to False on /usr/local/lib/python3.8/dist-packages/vorta/borg/extract.py:

From:
pattern_file = tempfile.NamedTemporaryFile('w', delete=True)

To:
pattern_file = tempfile.NamedTemporaryFile('w', delete=False)

Temporary files need to be deleted after extraction.

### Reproduction

- [X] I tried to reproduce the issue.
- [X] I was able to reproduce the issue.

### OS

Linux Mint 20.3 Una, Cinnamon

### Version of Vorta

0.8.9

### What did you install Vorta with?

Pip

### Version of Borg

1.1.15-1~ubuntu1.20.04.1 amd

### Logs

```pytb
2023-01-10 18:01:54,640 - vorta.keyring.secretstorage - DEBUG - Found 1 passwords matching repo URL.
2023-01-10 18:01:54,640 - vorta.keyring.secretstorage - DEBUG - Retrieved password for repo /storage/backup
2023-01-10 18:01:55,276 - vorta.borg.jobs_manager - DEBUG - Add job for site 1
2023-01-10 18:01:55,276 - vorta.borg.jobs_manager - DEBUG - Start job on site: 1
2023-01-10 18:01:55,292 - vorta.borg.borg_job - INFO - Running command /usr/bin/borg extract --list --info --log-json /storage/backup::mint-2023-01-10-123206 --patterns-from /tmp/tmp20whpmrl
2023-01-10 18:01:55,912 - vorta.borg.borg_job - WARNING - Traceback (most recent call last):
2023-01-10 18:01:55,912 - vorta.borg.borg_job - WARNING - File "/usr/bin/borg", line 11, in <module>
2023-01-10 18:01:55,913 - vorta.borg.borg_job - WARNING - load_entry_point('borgbackup==1.1.15', 'console_scripts', 'borg')()
2023-01-10 18:01:55,915 - vorta.borg.borg_job - WARNING - File "/usr/lib/python3/dist-packages/borg/archiver.py", line 4610, in main
2023-01-10 18:01:55,916 - vorta.borg.borg_job - WARNING - args = archiver.get_args(sys.argv, os.environ.get('SSH_ORIGINAL_COMMAND'))
2023-01-10 18:01:55,918 - vorta.borg.borg_job - WARNING - File "/usr/lib/python3/dist-packages/borg/archiver.py", line 4407, in get_args
2023-01-10 18:01:55,918 - vorta.borg.borg_job - WARNING - result = self.parse_args(argv[1:])
2023-01-10 18:01:55,920 - vorta.borg.borg_job - WARNING - File "/usr/lib/python3/dist-packages/borg/archiver.py", line 4453, in parse_args
2023-01-10 18:01:55,922 - vorta.borg.borg_job - WARNING - args = parser.parse_args(args or ['-h'])
2023-01-10 18:01:55,922 - vorta.borg.borg_job - WARNING - File "/usr/lib/python3.8/argparse.py", line 1780, in parse_args
2023-01-10 18:01:55,922 - vorta.borg.borg_job - WARNING - args, argv = self.parse_known_args(args, namespace)
2023-01-10 18:01:55,923 - vorta.borg.borg_job - WARNING - File "/usr/lib/python3.8/argparse.py", line 1812, in parse_known_args
2023-01-10 18:01:55,926 - vorta.borg.borg_job - WARNING - namespace, args = self._parse_known_args(args, namespace)
2023-01-10 18:01:55,926 - vorta.borg.borg_job - WARNING - File "/usr/lib/python3.8/argparse.py", line 2000, in _parse_known_args
2023-01-10 18:01:55,927 - vorta.borg.borg_job - WARNING - positionals_end_index = consume_positionals(start_index)
2023-01-10 18:01:55,929 - vorta.borg.borg_job - WARNING - File "/usr/lib/python3.8/argparse.py", line 1977, in consume_positionals
2023-01-10 18:01:55,931 - vorta.borg.borg_job - WARNING - take_action(action, args)
2023-01-10 18:01:55,931 - vorta.borg.borg_job - WARNING - File "/usr/lib/python3.8/argparse.py", line 1886, in take_action
2023-01-10 18:01:55,931 - vorta.borg.borg_job - WARNING - action(self, namespace, argument_values, option_string)
2023-01-10 18:01:55,932 - vorta.borg.borg_job - WARNING - File "/usr/lib/python3.8/argparse.py", line 1171, in __call__
2023-01-10 18:01:55,932 - vorta.borg.borg_job - WARNING - subnamespace, arg_strings = parser.parse_known_args(arg_strings, None)
2023-01-10 18:01:55,932 - vorta.borg.borg_job - WARNING - File "/usr/lib/python3.8/argparse.py", line 1812, in parse_known_args
2023-01-10 18:01:55,932 - vorta.borg.borg_job - WARNING - namespace, args = self._parse_known_args(args, namespace)
2023-01-10 18:01:55,932 - vorta.borg.borg_job - WARNING - File "/usr/lib/python3.8/argparse.py", line 2018, in _parse_known_args
2023-01-10 18:01:55,933 - vorta.borg.borg_job - WARNING - start_index = consume_optional(start_index)
2023-01-10 18:01:55,933 - vorta.borg.borg_job - WARNING - File "/usr/lib/python3.8/argparse.py", line 1958, in consume_optional
2023-01-10 18:01:55,933 - vorta.borg.borg_job - WARNING - take_action(action, args, option_string)
2023-01-10 18:01:55,933 - vorta.borg.borg_job - WARNING - File "/usr/lib/python3.8/argparse.py", line 1886, in take_action
2023-01-10 18:01:55,934 - vorta.borg.borg_job - WARNING - action(self, namespace, argument_values, option_string)
2023-01-10 18:01:55,934 - vorta.borg.borg_job - WARNING - File "/usr/lib/python3/dist-packages/borg/patterns.py", line 56, in __call__
2023-01-10 18:01:55,934 - vorta.borg.borg_job - WARNING - with open(filename) as f:
2023-01-10 18:01:55,934 - vorta.borg.borg_job - WARNING - FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmp20whpmrl'
2023-01-10 18:01:55,934 - vorta.borg.borg_job - WARNING - Error in sys.excepthook:
2023-01-10 18:01:55,935 - vorta.borg.borg_job - WARNING - Traceback (most recent call last):
2023-01-10 18:01:55,935 - vorta.borg.borg_job - WARNING - File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 153, in apport_excepthook
2023-01-10 18:01:55,944 - vorta.borg.borg_job - WARNING - with os.fdopen(os.open(pr_filename,
2023-01-10 18:01:55,945 - vorta.borg.borg_job - WARNING - FileNotFoundError: [Errno 2] No such file or directory: '/var/crash/_usr_bin_borg.1000.crash'
2023-01-10 18:01:55,946 - vorta.borg.borg_job - WARNING - Original exception was:
2023-01-10 18:01:55,947 - vorta.borg.borg_job - WARNING - Traceback (most recent call last):
2023-01-10 18:01:55,950 - vorta.borg.borg_job - WARNING - File "/usr/bin/borg", line 11, in <module>
2023-01-10 18:01:55,952 - vorta.borg.borg_job - WARNING - load_entry_point('borgbackup==1.1.15', 'console_scripts', 'borg')()
2023-01-10 18:01:55,952 - vorta.borg.borg_job - WARNING - File "/usr/lib/python3/dist-packages/borg/archiver.py", line 4610, in main
2023-01-10 18:01:55,953 - vorta.borg.borg_job - WARNING - args = archiver.get_args(sys.argv, os.environ.get('SSH_ORIGINAL_COMMAND'))
2023-01-10 18:01:55,956 - vorta.borg.borg_job - WARNING - File "/usr/lib/python3/dist-packages/borg/archiver.py", line 4407, in get_args
2023-01-10 18:01:55,957 - vorta.borg.borg_job - WARNING - result = self.parse_args(argv[1:])
2023-01-10 18:01:55,957 - vorta.borg.borg_job - WARNING - File "/usr/lib/python3/dist-packages/borg/archiver.py", line 4453, in parse_args
2023-01-10 18:01:55,959 - vorta.borg.borg_job - WARNING - args = parser.parse_args(args or ['-h'])
2023-01-10 18:01:55,961 - vorta.borg.borg_job - WARNING - File "/usr/lib/python3.8/argparse.py", line 1780, in parse_args
2023-01-10 18:01:55,963 - vorta.borg.borg_job - WARNING - args, argv = self.parse_known_args(args, namespace)
2023-01-10 18:01:55,965 - vorta.borg.borg_job - WARNING - File "/usr/lib/python3.8/argparse.py", line 1812, in parse_known_args
2023-01-10 18:01:55,967 - vorta.borg.borg_job - WARNING - namespace, args = self._parse_known_args(args, namespace)
2023-01-10 18:01:55,968 - vorta.borg.borg_job - WARNING - File "/usr/lib/python3.8/argparse.py", line 2000, in _parse_known_args
2023-01-10 18:01:55,970 - vorta.borg.borg_job - WARNING - positionals_end_index = consume_positionals(start_index)
2023-01-10 18:01:55,970 - vorta.borg.borg_job - WARNING - File "/usr/lib/python3.8/argparse.py", line 1977, in consume_positionals
2023-01-10 18:01:55,970 - vorta.borg.borg_job - WARNING - take_action(action, args)
2023-01-10 18:01:55,971 - vorta.borg.borg_job - WARNING - File "/usr/lib/python3.8/argparse.py", line 1886, in take_action
2023-01-10 18:01:55,972 - vorta.borg.borg_job - WARNING - action(self, namespace, argument_values, option_string)
2023-01-10 18:01:55,973 - vorta.borg.borg_job - WARNING - File "/usr/lib/python3.8/argparse.py", line 1171, in __call__
2023-01-10 18:01:55,974 - vorta.borg.borg_job - WARNING - subnamespace, arg_strings = parser.parse_known_args(arg_strings, None)
2023-01-10 18:01:55,977 - vorta.borg.borg_job - WARNING - File "/usr/lib/python3.8/argparse.py", line 1812, in parse_known_args
2023-01-10 18:01:55,979 - vorta.borg.borg_job - WARNING - namespace, args = self._parse_known_args(args, namespace)
2023-01-10 18:01:55,981 - vorta.borg.borg_job - WARNING - File "/usr/lib/python3.8/argparse.py", line 2018, in _parse_known_args
2023-01-10 18:01:55,983 - vorta.borg.borg_job - WARNING - start_index = consume_optional(start_index)
2023-01-10 18:01:55,984 - vorta.borg.borg_job - WARNING - File "/usr/lib/python3.8/argparse.py", line 1958, in consume_optional
2023-01-10 18:01:55,985 - vorta.borg.borg_job - WARNING - take_action(action, args, option_string)
2023-01-10 18:01:55,985 - vorta.borg.borg_job - WARNING - File "/usr/lib/python3.8/argparse.py", line 1886, in take_action
2023-01-10 18:01:55,987 - vorta.borg.borg_job - WARNING - action(self, namespace, argument_values, option_string)
2023-01-10 18:01:55,988 - vorta.borg.borg_job - WARNING - File "/usr/lib/python3/dist-packages/borg/patterns.py", line 56, in __call__
2023-01-10 18:01:55,989 - vorta.borg.borg_job - WARNING - with open(filename) as f:
2023-01-10 18:01:55,991 - vorta.borg.borg_job - WARNING - FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmp20whpmrl'
2023-01-10 18:01:56,105 - vorta.borg.jobs_manager - DEBUG - Finish job for site: 1
2023-01-10 18:01:56,106 - vorta.borg.jobs_manager - DEBUG - No more jobs for site: 1
```

**Comment by m3nu** [comment]
Duplicate and already fixed in the current master. Will be released soon.
