### ISSUE TITLE
error after rename set

### ISSUE THREAD

**Issue by saiballo** [borgbase/vorta#1553]
#### Environment

- OS: ubuntu 20.04
- Vorta version: 0.7.5
- Installed from: repo
- Borg version: 1.1.15

#### Logs

```
Uncaught exception, please file a report with this text at
https://github.com/borgbase/vorta/issues/new
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/peewee.py", line 5911, in get
    return clone.execute(database)[0]
  File "/usr/lib/python3/dist-packages/peewee.py", line 3652, in __getitem__
    return self.row_cache[item]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/vorta/views/main_window.py", line 124, in profile_select_action
    self.current_profile = BackupProfileModel.get(id=self.profileSelector.currentData())
  File "/usr/lib/python3/dist-packages/peewee.py", line 5513, in get
    return sq.get()
  File "/usr/lib/python3/dist-packages/peewee.py", line 5914, in get
    raise self.model.DoesNotExist('%s instance matching query does '
vorta.models.BackupProfileModelDoesNotExist: <Model: BackupProfileModel> instance matching query does not exist:
SQL: SELECT "t1"."id", "t1"."name", "t1"."added_at", "t1"."repo_id", "t1"."ssh_key", "t1"."compression", "t1"."exclude_patterns", "t1"."exclude_if_present", "t1"."schedule_mode", "t1"."schedule_interval_hours", "t1"."schedule_interval_minutes", "t1"."schedule_fixed_hour", "t1"."schedule_fixed_minute", "t1"."validation_on", "t1"."validation_weeks", "t1"."prune_on", "t1"."prune_hour", "t1"."prune_day", "t1"."prune_week", "t1"."prune_month", "t1"."prune_year", "t1"."prune_keep_within", "t1"."new_archive_name", "t1"."prune_prefix", "t1"."pre_backup_cmd", "t1"."post_backup_cmd", "t1"."dont_run_on_metered_networks" FROM "backupprofilemodel" AS "t1" WHERE ("t1"."id" = ?) LIMIT ? OFFSET ?
Params: [7, 1, 0]
```

**Comment by m3nu** [comment]
Thanks for taking the time to file a report? Does this still happen on the latest version? And what are the steps to reproduce?

**Comment by saiballo** [comment]
yes last version.

step to reproduce:

1) create a full set
2) rename a set with other name
3) you still have both sets in dropdown
4) try to delete first set

**Comment by real-yfprojects** [comment]
With *set* you mean profile?

**Comment by saiballo** [comment]
yes, profiles

**Comment by real-yfprojects** [comment]
I can't reproduce, we will need the full logs which you can find through *Misc* > *Logs*.

**Comment by saiballo** [comment]
`2023-01-20 09:11:28,381 - vorta.borg.borg_thread - INFO - Creating archive at "/media/ripostiglio/backup server/home-software::saibal-server-2023-01-20-091127"
2023-01-20 09:12:23,593 - apscheduler.scheduler - INFO - Removed job 7
2023-01-20 09:12:23,623 - root - CRITICAL - Uncaught exception, file a report at https://github.com/borgbase/vorta/issues/new
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/peewee.py", line 5911, in get
    return clone.execute(database)[0]
  File "/usr/lib/python3/dist-packages/peewee.py", line 3652, in __getitem__
    return self.row_cache[item]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/vorta/views/main_window.py", line 124, in profile_select_action
    self.current_profile = BackupProfileModel.get(id=self.profileSelector.currentData())
  File "/usr/lib/python3/dist-packages/peewee.py", line 5513, in get
    return sq.get()
  File "/usr/lib/python3/dist-packages/peewee.py", line 5914, in get
    raise self.model.DoesNotExist('%s instance matching query does '
vorta.models.BackupProfileModelDoesNotExist: <Model: BackupProfileModel> instance matching query does not exist:
SQL: SELECT "t1"."id", "t1"."name", "t1"."added_at", "t1"."repo_id", "t1"."ssh_key", "t1"."compression", "t1"."exclude_patterns", "t1"."exclude_if_present", "t1"."schedule_mode", "t1"."schedule_interval_hours", "t1"."schedule_interval_minutes", "t1"."schedule_fixed_hour", "t1"."schedule_fixed_minute", "t1"."validation_on", "t1"."validation_weeks", "t1"."prune_on", "t1"."prune_hour", "t1"."prune_day", "t1"."prune_week", "t1"."prune_month", "t1"."prune_year", "t1"."prune_keep_within", "t1"."new_archive_name", "t1"."prune_prefix", "t1"."pre_backup_cmd", "t1"."post_backup_cmd", "t1"."dont_run_on_metered_networks" FROM "backupprofilemodel" AS "t1" WHERE ("t1"."id" = ?) LIMIT ? OFFSET ?
Params: [7, 1, 0]
2023-01-20 09:12:30,771 - root - CRITICAL - Uncaught exception, file a report at https://github.com/borgbase/vorta/issues/new
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/peewee.py", line 5911, in get
    return clone.execute(database)[0]
  File "/usr/lib/python3/dist-packages/peewee.py", line 3652, in __getitem__
    return self.row_cache[item]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/vorta/views/main_window.py", line 156, in profile_delete_action
    self.profile_select_action(0)
  File "/usr/lib/python3/dist-packages/vorta/views/main_window.py", line 124, in profile_select_action
    self.current_profile = BackupProfileModel.get(id=self.profileSelector.currentData())
  File "/usr/lib/python3/dist-packages/peewee.py", line 5513, in get
    return sq.get()
  File "/usr/lib/python3/dist-packages/peewee.py", line 5914, in get
    raise self.model.DoesNotExist('%s instance matching query does '
vorta.models.BackupProfileModelDoesNotExist: <Model: BackupProfileModel> instance matching query does not exist:
SQL: SELECT "t1"."id", "t1"."name", "t1"."added_at", "t1"."repo_id", "t1"."ssh_key", "t1"."compression", "t1"."exclude_patterns", "t1"."exclude_if_present", "t1"."schedule_mode", "t1"."schedule_interval_hours", "t1"."schedule_interval_minutes", "t1"."schedule_fixed_hour", "t1"."schedule_fixed_minute", "t1"."validation_on", "t1"."validation_weeks", "t1"."prune_on", "t1"."prune_hour", "t1"."prune_day", "t1"."prune_week", "t1"."prune_month", "t1"."prune_year", "t1"."prune_keep_within", "t1"."new_archive_name", "t1"."prune_prefix", "t1"."pre_backup_cmd", "t1"."post_backup_cmd", "t1"."dont_run_on_metered_networks" FROM "backupprofilemodel" AS "t1" WHERE ("t1"."id" = ?) LIMIT ? OFFSET ?
Params: [7, 1, 0]
2023-01-20 09:12:37,802 - root - CRITICAL - Uncaught exception, file a report at https://github.com/borgbase/vorta/issues/new
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/peewee.py", line 5911, in get
    return clone.execute(database)[0]
  File "/usr/lib/python3/dist-packages/peewee.py", line 3652, in __getitem__
    return self.row_cache[item]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/vorta/views/schedule_tab.py", line 140, in _draw_next_scheduled_backup
    self.nextBackupDateTimeLabel.setText(self.app.scheduler.next_job_for_profile(self.profile().id))
  File "/usr/lib/python3/dist-packages/vorta/models.py", line 188, in profile
    return BackupProfileModel.get(id=self.window().current_profile.id)
  File "/usr/lib/python3/dist-packages/peewee.py", line 5513, in get
    return sq.get()
  File "/usr/lib/python3/dist-packages/peewee.py", line 5914, in get
    raise self.model.DoesNotExist('%s instance matching query does '
vorta.models.BackupProfileModelDoesNotExist: <Model: BackupProfileModel> instance matching query does not exist:
SQL: SELECT "t1"."id", "t1"."name", "t1"."added_at", "t1"."repo_id", "t1"."ssh_key", "t1"."compression", "t1"."exclude_patterns", "t1"."exclude_if_present", "t1"."schedule_mode", "t1"."schedule_interval_hours", "t1"."schedule_interval_minutes", "t1"."schedule_fixed_hour", "t1"."schedule_fixed_minute", "t1"."validation_on", "t1"."validation_weeks", "t1"."prune_on", "t1"."prune_hour", "t1"."prune_day", "t1"."prune_week", "t1"."prune_month", "t1"."prune_year", "t1"."prune_keep_within", "t1"."new_archive_name", "t1"."prune_prefix", "t1"."pre_backup_cmd", "t1"."post_backup_cmd", "t1"."dont_run_on_metered_networks" FROM "backupprofilemodel" AS "t1" WHERE ("t1"."id" = ?) LIMIT ? OFFSET ?
Params: [7, 1, 0]
2023-01-20 09:12:50,067 - root - CRITICAL - Uncaught exception, file a report at https://github.com/borgbase/vorta/issues/new
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/peewee.py", line 5911, in get
    return clone.execute(database)[0]
  File "/usr/lib/python3/dist-packages/peewee.py", line 3652, in __getitem__
    return self.row_cache[item]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/vorta/views/main_window.py", line 124, in profile_select_action
    self.current_profile = BackupProfileModel.get(id=self.profileSelector.currentData())
  File "/usr/lib/python3/dist-packages/peewee.py", line 5513, in get
    return sq.get()
  File "/usr/lib/python3/dist-packages/peewee.py", line 5914, in get
    raise self.model.DoesNotExist('%s instance matching query does '
vorta.models.BackupProfileModelDoesNotExist: <Model: BackupProfileModel> instance matching query does not exist:
SQL: SELECT "t1"."id", "t1"."name", "t1"."added_at", "t1"."repo_id", "t1"."ssh_key", "t1"."compression", "t1"."exclude_patterns", "t1"."exclude_if_present", "t1"."schedule_mode", "t1"."schedule_interval_hours", "t1"."schedule_interval_minutes", "t1"."schedule_fixed_hour", "t1"."schedule_fixed_minute", "t1"."validation_on", "t1"."validation_weeks", "t1"."prune_on", "t1"."prune_hour", "t1"."prune_day", "t1"."prune_week", "t1"."prune_month", "t1"."prune_year", "t1"."prune_keep_within", "t1"."new_archive_name", "t1"."prune_prefix", "t1"."pre_backup_cmd", "t1"."post_backup_cmd", "t1"."dont_run_on_metered_networks" FROM "backupprofilemodel" AS "t1" WHERE ("t1"."id" = ?) LIMIT ? OFFSET ?
Params: [7, 1, 0]`
