### ISSUE TITLE
Error with large cryptic message when aborting a backup

### ISSUE THREAD

**Issue by RubenKelevra** [borgbase/vorta#1557]
### Description

I pressed abort to stop a backup. Then I got this message:

![Screenshot from 2023-01-21 06-33-48](https://user-images.githubusercontent.com/614929/213845295-58805faf-b7d3-4d3a-a3bf-9f7f26b518e8.png)

### Reproduction

- [X] I tried to reproduce the issue.
- [X] I was able to reproduce the issue.

### OS

ArchLinux latest

### Version of Vorta

0.8.9

### What did you install Vorta with?

Other

### Version of Borg

1.2.3

### Logs

```pytb
2023-01-21 06:33:05,874 - vorta.borg.borg_job - DEBUG - Cancel job on site default
2023-01-21 06:33:05,874 - vorta.borg.borg_job - DEBUG - Cancel job on site 2
2023-01-21 06:33:06,531 - vorta.borg.borg_job - INFO - checkpoint requested: starting checkpoint creation...
2023-01-21 06:33:08,874 - vorta.borg.jobs_manager - INFO - Finished cancelling all jobs
2023-01-21 06:33:08,902 - vorta.borg.borg_job - ERROR - Local Exception
2023-01-21 06:33:08,902 - vorta.borg.borg_job - ERROR - Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/borg/archiver.py", line 183, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/usr/lib/python3.10/site-packages/borg/archiver.py", line 675, in do_create
    create_inner(archive, cache, fso)
  File "/usr/lib/python3.10/site-packages/borg/archiver.py", line 608, in create_inner
    self._rec_walk(path=path, parent_fd=parent_fd, name=name,
  File "/usr/lib/python3.10/site-packages/borg/archiver.py", line 823, in _rec_walk
    self._rec_walk(
  File "/usr/lib/python3.10/site-packages/borg/archiver.py", line 823, in _rec_walk
    self._rec_walk(
  File "/usr/lib/python3.10/site-packages/borg/archiver.py", line 823, in _rec_walk
    self._rec_walk(
  [Previous line repeated 4 more times]
  File "/usr/lib/python3.10/site-packages/borg/archiver.py", line 786, in _rec_walk
    status = self._process_any(path=path, parent_fd=parent_fd, name=name, st=st, fso=fso, cache=cache,
  File "/usr/lib/python3.10/site-packages/borg/archiver.py", line 688, in _process_any
    return fso.process_file(path=path, parent_fd=parent_fd, name=name, st=st, cache=cache)
  File "/usr/lib/python3.10/site-packages/borg/archive.py", line 1443, in process_file
    self.process_file_chunks(item, cache, self.stats, self.show_progress, backup_io_iter(self.chunker.chunkify(None, fd)))
  File "/usr/lib/python3.10/site-packages/borg/archive.py", line 1273, in process_file_chunks
    from_chunk, part_number = self.maybe_checkpoint(item, from_chunk, part_number, forced=False)
  File "/usr/lib/python3.10/site-packages/borg/archive.py", line 1247, in maybe_checkpoint
    from_chunk, part_number = self.write_part_file(item, from_chunk, part_number)
  File "/usr/lib/python3.10/site-packages/borg/archive.py", line 1238, in write_part_file
    self.write_checkpoint()
  File "/usr/lib/python3.10/site-packages/borg/archive.py", line 605, in write_checkpoint
    self.save(self.checkpoint_name)
  File "/usr/lib/python3.10/site-packages/borg/archive.py", line 613, in save
    self.items_buffer.flush(flush=True)
  File "/usr/lib/python3.10/site-packages/borg/archive.py", line 385, in flush
    self.chunks.append(self.write_chunk(chunk))
  File "/usr/lib/python3.10/site-packages/borg/archive.py", line 401, in write_chunk
    id_, _, _ = self.cache.add_chunk(self.key.id_hash(chunk), chunk, self.stats, wait=False)
  File "/usr/lib/python3.10/site-packages/borg/cache.py", line 951, in add_chunk
    self.repository.put(id, data, wait=wait)
  File "/usr/lib/python3.10/site-packages/borg/remote.py", line 476, in do_rpc
    return self.call(f.__name__, named, **extra)
  File "/usr/lib/python3.10/site-packages/borg/remote.py", line 711, in call
    for resp in self.call_many(cmd, [args], **kw):
  File "/usr/lib/python3.10/site-packages/borg/remote.py", line 821, in call_many
    r, w, x = select.select(self.r_fds, w_fds, self.x_fds, 1)
  File "/usr/lib/python3.10/site-packages/borg/helpers/process.py", line 180, in handler
    raise exc_cls
borg.helpers.process.SigTerm

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/borg/archiver.py", line 5168, in main
    exit_code = archiver.run(args)
  File "/usr/lib/python3.10/site-packages/borg/archiver.py", line 5099, in run
    return set_ec(func(args))
  File "/usr/lib/python3.10/site-packages/borg/archiver.py", line 168, in wrapper
    with repository:
  File "/usr/lib/python3.10/site-packages/borg/remote.py", line 636, in __exit__
    self.rollback()
  File "/usr/lib/python3.10/site-packages/borg/remote.py", line 476, in do_rpc
    return self.call(f.__name__, named, **extra)
  File "/usr/lib/python3.10/site-packages/borg/remote.py", line 711, in call
    for resp in self.call_many(cmd, [args], **kw):
  File "/usr/lib/python3.10/site-packages/borg/remote.py", line 781, in call_many
    send_buffer()  # Try to send data, as some cases (async_response) will never try to send data otherwise.
  File "/usr/lib/python3.10/site-packages/borg/remote.py", line 721, in send_buffer
    written = self.ratelimit.write(self.stdin_fd, self.to_send.peek_front())
  File "/usr/lib/python3.10/site-packages/borg/remote.py", line 417, in write
    written = os.write(fd, to_send)
BrokenPipeError: [Errno 32] Broken pipe

Platform: Linux i5.local 6.1.7-x64v1-xanmod1-1 #1 SMP PREEMPT_DYNAMIC Thu, 19 Jan 2023 15:42:33 +0000 x86_64
Linux: Unknown Linux  
Borg: 1.2.3  Python: CPython 3.10.9 msgpack: 1.0.4 fuse: llfuse 1.4.2 [pyfuse3,llfuse]
PID: 109643  CWD: /home/rubenk
sys.argv: ['/usr/bin/borg', 'create', '--list', '--progress', '--info', '--log-json', '--json', '--filter=AM', '-C', 'zstd,8', '--exclude-from', '/tmp/tmpktz8334k', 'anubis:~/backups/borg-backups::i5.local-2023-01-21-060501', '/home/rubenk']
SSH_ORIGINAL_COMMAND: None

2023-01-21 06:33:09,047 - vorta.borg.jobs_manager - DEBUG - Finish job for site: 2
2023-01-21 06:33:09,047 - vorta.borg.jobs_manager - DEBUG - No more jobs for site: 2
```

**Comment by real-yfprojects** [comment]
This is a borg problem: it doesn't exit cleanly when aborting it. I don't think this affects you backups. And I also don't think that vorta can handle such error messages better. 
There is borgbackup/borg#7016. You can add this case to the thread. (I can't because I was blocked by the author)
