### ISSUE TITLE
Vorta 8.10  sqlite3.OperationError: no such column: t1.group 

### ISSUE THREAD

**Issue by goebbe** [borgbase/vorta#1566]
### Description

Installing Vorta 8.10 via pip3 (as a user)  let to an Error when trying to start Vorta. 

2023-01-26 08:47:51,166 - root - CRITICAL - Uncaught exception, file a report at https://github.com/borgbase/vorta/issues/new/choose
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.10/site-packages/peewee.py", line 3237, in execute_sql
    cursor.execute(sql, params or ())
sqlite3.OperationalError: no such column: t1.group

IMPORTANT note: This is likely to be caused by an old local install of Vorta in my user account. 

### Reproduction

- [X] I tried to reproduce the issue.
- [ ] I was able to reproduce the issue.

### OS

Linux Mint CE 21.1  (based on Ubuntu 22.04)

### Version of Vorta

8.10

### What did you install Vorta with?

Pip

### Version of Borg

1.2.3

### Logs

```pytb
1) terminal output from pip3 installation (as a user) 
2) terminal output (with the resulting error message) when trying to start vorta (as a usepir from the same terminal session) 

~$ pip3 install vorta
Defaulting to user installation because normal site-packages is not writeable
Collecting vorta
  Downloading vorta-0.8.10.tar.gz (726 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 726.2/726.2 KB 6.0 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting paramiko
  Downloading paramiko-3.0.0-py3-none-any.whl (210 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 210.8/210.8 KB 8.2 MB/s eta 0:00:00
Requirement already satisfied: secretstorage in /usr/lib/python3/dist-packages (from vorta) (3.3.1)
Requirement already satisfied: psutil in /usr/lib/python3/dist-packages (from vorta) (5.9.0)
Requirement already satisfied: pyqt5 in /usr/lib/python3/dist-packages (from vorta) (5.15.6)
Requirement already satisfied: setuptools in /usr/lib/python3/dist-packages (from vorta) (59.6.0)
Collecting peewee
  Downloading peewee-3.15.4.tar.gz (860 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 860.9/860.9 KB 28.2 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: appdirs in /usr/lib/python3/dist-packages (from vorta) (1.4.4)
Requirement already satisfied: cryptography>=3.3 in /usr/lib/python3/dist-packages (from paramiko->vorta) (3.4.8)
Requirement already satisfied: bcrypt>=3.2 in /usr/lib/python3/dist-packages (from paramiko->vorta) (3.2.0)
Requirement already satisfied: pynacl>=1.5 in /usr/lib/python3/dist-packages (from paramiko->vorta) (1.5.0)
Requirement already satisfied: PyQt5-sip<13,>=12.8 in /usr/lib/python3/dist-packages (from pyqt5->vorta) (12.9.1)
Collecting cffi>=1.4.1
  Downloading cffi-1.15.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (441 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 441.8/441.8 KB 21.9 MB/s eta 0:00:00
Collecting pycparser
  Using cached pycparser-2.21-py2.py3-none-any.whl (118 kB)
Building wheels for collected packages: vorta, peewee
  Building wheel for vorta (pyproject.toml) ... done
  Created wheel for vorta: filename=vorta-0.8.10-py3-none-any.whl size=721351 sha256=9c62cdf27be64bf8f5a107f114fbc3b8444ca6fc7d46e46bdbc1c54c05aa4bcb
  Stored in directory: /home/user/.cache/pip/wheels/36/9a/7c/30217b07d4e15206d44828821d94157b0912210284bc388114
  Building wheel for peewee (setup.py) ... done
  Created wheel for peewee: filename=peewee-3.15.4-cp310-cp310-linux_x86_64.whl size=739649 sha256=8bd5eaf0c325ba4eaf87becda8b987cd37176fa8492ad8e430bc480cb67735f6
  Stored in directory: /home/user/.cache/pip/wheels/72/a0/c1/1ab3863142cdd8fa279be076811f2a47e571dcebe408d5e45e
Successfully built vorta peewee
Installing collected packages: peewee, pycparser, cffi, paramiko, vorta
Successfully installed cffi-1.15.1 paramiko-3.0.0 peewee-3.15.4 pycparser-2.21 vorta-0.8.10

2) Starting Vorta with the resulting error message: 
~$ vorta
2023-01-26 08:47:51,166 - root - CRITICAL - Uncaught exception, file a report at https://github.com/borgbase/vorta/issues/new/choose
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.10/site-packages/peewee.py", line 3237, in execute_sql
    cursor.execute(sql, params or ())
sqlite3.OperationalError: no such column: t1.group

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/.local/bin/vorta", line 8, in <module>
    sys.exit(main())
  File "/home/user/.local/lib/python3.10/site-packages/vorta/__main__.py", line 66, in main
    init_db(sqlite_db)
  File "/home/user/.local/lib/python3.10/site-packages/vorta/store/connection.py", line 88, in init_db
    s, created = SettingsModel.get_or_create(key=setting['key'], defaults=setting)
  File "/home/user/.local/lib/python3.10/site-packages/peewee.py", line 6657, in get_or_create
    return query.get(), False
  File "/home/user/.local/lib/python3.10/site-packages/peewee.py", line 7072, in get
    return clone.execute(database)[0]
  File "/home/user/.local/lib/python3.10/site-packages/peewee.py", line 1962, in inner
    return method(self, database, *args, **kwargs)
  File "/home/user/.local/lib/python3.10/site-packages/peewee.py", line 2033, in execute
    return self._execute(database)
  File "/home/user/.local/lib/python3.10/site-packages/peewee.py", line 2206, in _execute
    cursor = database.execute(self)
  File "/home/user/.local/lib/python3.10/site-packages/peewee.py", line 3250, in execute
    return self.execute_sql(sql, params, commit=commit)
  File "/home/user/.local/lib/python3.10/site-packages/peewee.py", line 3234, in execute_sql
    with __exception_wrapper__:
  File "/home/user/.local/lib/python3.10/site-packages/peewee.py", line 3010, in __exit__
    reraise(new_type, new_type(exc_value, *exc_args), traceback)
  File "/home/user/.local/lib/python3.10/site-packages/peewee.py", line 192, in reraise
    raise value.with_traceback(tb)
  File "/home/user/.local/lib/python3.10/site-packages/peewee.py", line 3237, in execute_sql
    cursor.execute(sql, params or ())
peewee.OperationalError: no such column: t1.group
```

**Comment by goebbe** [comment]
This error is very likely the result of an old local Vorta installation - where I messed around in the code.  
Sorry for the noise - I'm closing this issue.

**Comment by m3nu** [comment]
No worries. We need more people to break stuff.
