### ISSUE TITLE
Cannot add remote repository using borg serve

### ISSUE THREAD

**Issue by ghost** [borgbase/vorta#1596]
### Description

Adding a remote repository like borg@backuprpi:/home/borg/mounts/core/computer fails validation:
```
2023-02-17 11:20:53,500 - vorta.borg.borg_job - INFO - Running command /usr/bin/borg info --info --json --log-json borg@backuprpi:/home/borg/mounts/core/hookish
2023-02-17 11:20:56,984 - vorta.borg.borg_job - ERROR - Traceback (most recent call last):

  File "/usr/lib/python3/dist-packages/borg/remote.py", line 247, in serve
    res = f(**args)

  File "/usr/lib/python3/dist-packages/borg/remote.py", line 375, in open
    self.repository.__enter__()  # clean exit handled by serve() method

  File "/usr/lib/python3/dist-packages/borg/repository.py", line 190, in __enter__
    self.open(self.path, bool(self.exclusive), lock_wait=self.lock_wait, lock=self.do_lock)

  File "/usr/lib/python3/dist-packages/borg/repository.py", line 415, in open
    st = os.stat(path)

OSError: [Errno 5] Input/output error: '/home/borg/mounts/core/hookish'

2023-02-17 11:20:56,988 - vorta.borg.borg_job - ERROR - Borg server: Platform: Linux backuprpi 5.15.32-v7+ #1538 SMP Thu Mar 31 19:38:48 BST 2022 armv7l
Borg server: Linux: Unknown Linux  
Borg server: Borg: 1.1.16  Python: CPython 3.9.2 msgpack: 0.5.6.+borg1
Borg server: PID: 21220  CWD: /home/borg
Borg server: sys.argv: ['/usr/bin/borg', 'serve', '--restrict-to-path', '/home/borg/mounts']
Borg server: SSH_ORIGINAL_COMMAND: 'borg serve --info'
Platform: Linux hookish 5.15.0-60-generic #66-Ubuntu SMP Fri Jan 20 14:29:49 UTC 2023 x86_64
Linux: Unknown Linux  
Borg: 1.2.0  Python: CPython 3.10.6 msgpack: 1.0.3 fuse: pyfuse3 3.2.0 [pyfuse3,llfuse]
PID: 250981  CWD: /home/simon
sys.argv: ['/usr/bin/borg', 'info', '--info', '--json', '--log-json', 'borg@backuprpi:/home/borg/mounts/core/hookish']
SSH_ORIGINAL_COMMAND: None
```

### Reproduction

- [X] I tried to reproduce the issue.
- [X] I was able to reproduce the issue.

### OS

Ubuntu 22.04

### Version of Vorta

0.8.3

### What did you install Vorta with?

Distribution package

### Version of Borg

1.2.0

### Logs

```pytb
2023-02-17 11:20:48,775 - root - DEBUG - Found 0 passwords matching repo URL.
2023-02-17 11:20:48,891 - vorta.keyring.abc - DEBUG - Only available on macOS
2023-02-17 11:20:48,896 - asyncio - DEBUG - Using selector: EpollSelector
2023-02-17 11:20:48,904 - asyncio - DEBUG - Using selector: EpollSelector
2023-02-17 11:20:48,909 - root - DEBUG - Found 0 passwords matching repo URL.
2023-02-17 11:20:48,970 - vorta.keyring.abc - DEBUG - Only available on macOS
2023-02-17 11:20:48,975 - asyncio - DEBUG - Using selector: EpollSelector
2023-02-17 11:20:48,984 - asyncio - DEBUG - Using selector: EpollSelector
2023-02-17 11:20:49,007 - root - DEBUG - Found 0 passwords matching repo URL.
2023-02-17 11:20:49,146 - vorta.keyring.abc - DEBUG - Only available on macOS
2023-02-17 11:20:49,152 - asyncio - DEBUG - Using selector: EpollSelector
2023-02-17 11:20:49,160 - asyncio - DEBUG - Using selector: EpollSelector
2023-02-17 11:20:49,165 - root - DEBUG - Found 0 passwords matching repo URL.
2023-02-17 11:20:53,468 - vorta.keyring.abc - DEBUG - Only available on macOS
2023-02-17 11:20:53,472 - asyncio - DEBUG - Using selector: EpollSelector
2023-02-17 11:20:53,475 - vorta.borg.borg_job - DEBUG - Using VortaSecretStorageKeyring keyring to store passwords.
2023-02-17 11:20:53,481 - asyncio - DEBUG - Using selector: EpollSelector
2023-02-17 11:20:53,486 - root - DEBUG - Found 0 passwords matching repo URL.
2023-02-17 11:20:53,486 - vorta.borg.borg_job - DEBUG - Password not found in primary keyring. Falling back to VortaDBKeyring.
2023-02-17 11:20:53,500 - vorta.borg.borg_job - INFO - Running command /usr/bin/borg info --info --json --log-json borg@backuprpi:/home/borg/mounts/core/hookish
2023-02-17 11:20:56,984 - vorta.borg.borg_job - ERROR - Traceback (most recent call last):

  File "/usr/lib/python3/dist-packages/borg/remote.py", line 247, in serve
    res = f(**args)

  File "/usr/lib/python3/dist-packages/borg/remote.py", line 375, in open
    self.repository.__enter__()  # clean exit handled by serve() method

  File "/usr/lib/python3/dist-packages/borg/repository.py", line 190, in __enter__
    self.open(self.path, bool(self.exclusive), lock_wait=self.lock_wait, lock=self.do_lock)

  File "/usr/lib/python3/dist-packages/borg/repository.py", line 415, in open
    st = os.stat(path)

OSError: [Errno 5] Input/output error: '/home/borg/mounts/core/hookish'

2023-02-17 11:20:56,988 - vorta.borg.borg_job - ERROR - Borg server: Platform: Linux backuprpi 5.15.32-v7+ #1538 SMP Thu Mar 31 19:38:48 BST 2022 armv7l
Borg server: Linux: Unknown Linux  
Borg server: Borg: 1.1.16  Python: CPython 3.9.2 msgpack: 0.5.6.+borg1
Borg server: PID: 21220  CWD: /home/borg
Borg server: sys.argv: ['/usr/bin/borg', 'serve', '--restrict-to-path', '/home/borg/mounts']
Borg server: SSH_ORIGINAL_COMMAND: 'borg serve --info'
Platform: Linux hookish 5.15.0-60-generic #66-Ubuntu SMP Fri Jan 20 14:29:49 UTC 2023 x86_64
Linux: Unknown Linux  
Borg: 1.2.0  Python: CPython 3.10.6 msgpack: 1.0.3 fuse: pyfuse3 3.2.0 [pyfuse3,llfuse]
PID: 250981  CWD: /home/simon
sys.argv: ['/usr/bin/borg', 'info', '--info', '--json', '--log-json', 'borg@backuprpi:/home/borg/mounts/core/hookish']
SSH_ORIGINAL_COMMAND: None
```

**Comment by m3nu** [comment]
This error is remote and not from Vorta. You're still welcome to ask for help in the discussion forum.
