### ISSUE TITLE
Error when running pre-commit run on a fresh dev install after following the contributing guidelines

### ISSUE THREAD

**Issue by ratchek** [borgbase/vorta#1600]
### Description

When following the contributing guidelines for a fresh dev install, `pre-commit run` returns and error message.

```
An unexpected error has occurred: CalledProcessError: command: ('/home/thomas/.cache/pre-commit/repom_7ae4q4/py_env-python3/bin/python', '-mpip', 'install', '.')
return code: 1
stdout:
    Processing /home/thomas/.cache/pre-commit/repom_7ae4q4
      Installing build dependencies: started
      Installing build dependencies: finished with status 'done'
      Getting requirements to build wheel: started
      Getting requirements to build wheel: finished with status 'done'
      Preparing metadata (pyproject.toml): started
      Preparing metadata (pyproject.toml): finished with status 'error'
    
stderr:
      error: subprocess-exited-with-error
      
      × Preparing metadata (pyproject.toml) did not run successfully.
      │ exit code: 1
      ╰─> [14 lines of output]
          Traceback (most recent call last):
            File "/home/thomas/.cache/pre-commit/repom_7ae4q4/py_env-python3/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
              main()
            File "/home/thomas/.cache/pre-commit/repom_7ae4q4/py_env-python3/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
              json_out['return_val'] = hook(**hook_input['kwargs'])
            File "/home/thomas/.cache/pre-commit/repom_7ae4q4/py_env-python3/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 149, in prepare_metadata_for_build_wheel
              return hook(metadata_directory, config_settings)
            File "/tmp/pip-build-env-qfavyawe/overlay/lib/python3.10/site-packages/poetry/core/masonry/api.py", line 40, in prepare_metadata_for_build_wheel
              poetry = Factory().create_poetry(Path(".").resolve(), with_groups=False)
            File "/tmp/pip-build-env-qfavyawe/overlay/lib/python3.10/site-packages/poetry/core/factory.py", line 57, in create_poetry
              raise RuntimeError("The Poetry configuration is invalid:\n" + message)
          RuntimeError: The Poetry configuration is invalid:
            - [extras.pipfile_deprecated_finder.2] 'pip-shims<=0.3.4' does not match '^[a-zA-Z-_.0-9]+$'
          
          [end of output]
      
      note: This error originates from a subprocess, and is likely not a problem with pip.
    error: metadata-generation-failed
    
    × Encountered error while generating package metadata.
    ╰─> See above for output.
    
    note: This is an issue with the package mentioned above, not pip.
    hint: See above for details.
    
Check the log at /home/thomas/.cache/pre-commit/pre-commit.log

```

### Reproduction

- [X] I tried to reproduce the issue.
- [X] I was able to reproduce the issue.

### OS

Ubuntu 22.04.1 LTS, GNOME 42.5

### Version of Vorta

0.8.10

### What did you install Vorta with?

Homebrew

### Version of Borg

1.2.0

**Comment by ratchek** [comment]
Turns out the issue was because a new version of Poetry broke isort. All that is needed is to update
