### ISSUE TITLE
Failed to list connections

### ISSUE THREAD

**Issue by MartinX3** [borgbase/vorta#1607]
### Description

I can't backup my stuff, because I don't run the NetworkManager

I use `systemd-networkd` and `systemd-resolved` for my internet access and `iwd` for the wireless network handling.

I disabled the NetworkManager.service because it interrupts my internet with `ERR_NETWORK_CHANGED` regularly.

### Reproduction

- [X] I tried to reproduce the issue.
- [X] I was able to reproduce the issue.

### OS

Arch Linux

### Version of Vorta

0.8.10

### What did you install Vorta with?

Distribution package

### Version of Borg

1.2.3

### Logs

```pytb
vorta.network_status.network_manager - ERROR - Failed to list connections
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/vorta/network_status/network_manager.py", line 46, in get_known_wifis
    connections_paths = self._nm.get_connections_paths()
  File "/usr/lib/python3.10/site-packages/vorta/network_status/network_manager.py", line 139, in get_connections_paths
    return get_result(settings_manager.call('ListConnections'))
  File "/usr/lib/python3.10/site-packages/vorta/network_status/network_manager.py", line 167, in get_result
    raise DBusException("DBus call failed: {}".format(msg.arguments()))
vorta.network_status.network_manager.DBusException: DBus call failed: ['The name org.freedesktop.NetworkManager was not provided by any .service files']
```

**Comment by MartinX3** [comment]
I'm sorry for the noise.
The stacktrace wasn't the cause of the connection issue tothe borg server.
