### ISSUE TITLE
Linking Repository (again) shows invalid information

### ISSUE THREAD

**Issue by 21Kingshill** [borgbase/vorta#1608]
### Description

I assume a bug here.

I linked an existing Borg backup in Vorta. 

- The Archive list is shown with empty size information (which is a known behaviour)
- Refreshing the oldest entries (2nd of Feb) returns for all entries on this day a size of 4kB
![_1](https://user-images.githubusercontent.com/107434848/221028287-68e58d06-69b4-4e43-85e7-8baa03c208b8.png)

- looking into the target directory I can see all entries from that day with the expected size (a few GB):

![_2](https://user-images.githubusercontent.com/107434848/221028382-1f74223e-da36-4e8b-9e68-782f7ee7d25e.png)

- comparing any 4k entry with another 4k entry doesn't show any content:
![_3](https://user-images.githubusercontent.com/107434848/221029649-bb2a60ec-415f-41b6-bfec-c03986396791.png)
--> Log entry

However, comparing any 4k entry with a newer archive entry works as expected.

### Reproduction

- [X] I tried to reproduce the issue.
- [X] I was able to reproduce the issue.

### OS

macOS Ventura 13.3

### Version of Vorta

0.8.10

### What did you install Vorta with?

Binary

### Version of Borg

1.2.3

### Logs

```pytb
2023-02-23 22:00:55,635 - vorta.i18n - DEBUG - Loading translation succeeded for ['de-DE', 'en-DE'].
2023-02-23 22:00:55,638 - vorta.scheduler - WARNING - Failed to connect to DBUS interface to detect sleep/resume events
2023-02-23 22:00:55,707 - root - DEBUG - Expected error parsing file in .ssh: known_hosts.old (You can safely ignore this)
Traceback (most recent call last):
  File "utils.py", line 195, in get_private_keys
  File "paramiko/pkey.py", line 232, in from_private_key_file
  File "paramiko/rsakey.py", line 63, in __init__
  File "paramiko/rsakey.py", line 186, in _from_private_key_file
  File "paramiko/pkey.py", line 305, in _read_private_key_file
  File "paramiko/pkey.py", line 323, in _read_private_key
paramiko.ssh_exception.SSHException: not a valid RSA private key file
2023-02-23 22:00:55,707 - root - DEBUG - Expected error parsing file in .ssh: known_hosts.old (You can safely ignore this)
Traceback (most recent call last):
  File "utils.py", line 195, in get_private_keys
  File "paramiko/pkey.py", line 232, in from_private_key_file
  File "paramiko/ecdsakey.py", line 126, in __init__
  File "paramiko/ecdsakey.py", line 277, in _from_private_key_file
  File "paramiko/pkey.py", line 305, in _read_private_key_file
  File "paramiko/pkey.py", line 323, in _read_private_key
paramiko.ssh_exception.SSHException: not a valid EC private key file
2023-02-23 22:00:55,708 - root - DEBUG - Expected error parsing file in .ssh: known_hosts.old (You can safely ignore this)
Traceback (most recent call last):
  File "utils.py", line 195, in get_private_keys
  File "paramiko/pkey.py", line 232, in from_private_key_file
  File "paramiko/ed25519key.py", line 58, in __init__
  File "paramiko/pkey.py", line 323, in _read_private_key
paramiko.ssh_exception.SSHException: not a valid OPENSSH private key file
2023-02-23 22:00:55,708 - root - DEBUG - Expected error parsing file in .ssh: known_hosts (You can safely ignore this)
Traceback (most recent call last):
  File "utils.py", line 195, in get_private_keys
  File "paramiko/pkey.py", line 232, in from_private_key_file
  File "paramiko/rsakey.py", line 63, in __init__
  File "paramiko/rsakey.py", line 186, in _from_private_key_file
  File "paramiko/pkey.py", line 305, in _read_private_key_file
  File "paramiko/pkey.py", line 323, in _read_private_key
paramiko.ssh_exception.SSHException: not a valid RSA private key file
2023-02-23 22:00:55,708 - root - DEBUG - Expected error parsing file in .ssh: known_hosts (You can safely ignore this)
Traceback (most recent call last):
  File "utils.py", line 195, in get_private_keys
  File "paramiko/pkey.py", line 232, in from_private_key_file
  File "paramiko/ecdsakey.py", line 126, in __init__
  File "paramiko/ecdsakey.py", line 277, in _from_private_key_file
  File "paramiko/pkey.py", line 305, in _read_private_key_file
  File "paramiko/pkey.py", line 323, in _read_private_key
paramiko.ssh_exception.SSHException: not a valid EC private key file
2023-02-23 22:00:55,709 - root - DEBUG - Expected error parsing file in .ssh: known_hosts (You can safely ignore this)
Traceback (most recent call last):
  File "utils.py", line 195, in get_private_keys
  File "paramiko/pkey.py", line 232, in from_private_key_file
  File "paramiko/ed25519key.py", line 58, in __init__
  File "paramiko/pkey.py", line 323, in _read_private_key
paramiko.ssh_exception.SSHException: not a valid OPENSSH private key file
2023-02-23 22:00:55,752 - vorta.views.source_tab - DEBUG - Added item number 0 from 1
2023-02-23 22:00:55,907 - root - INFO - Using DarwinNetworkStatus NetworkStatusMonitor implementation.
2023-02-23 22:00:56,017 - vorta.borg.jobs_manager - DEBUG - Add job for site default
2023-02-23 22:00:56,017 - vorta.borg.jobs_manager - DEBUG - Start job on site: default
2023-02-23 22:00:56,018 - vorta.borg.borg_job - INFO - Running command /Applications/Vorta.app/Contents/Resources/borg-dir/borg.exe --version
2023-02-23 22:00:56,659 - vorta.borg.jobs_manager - DEBUG - Finish job for site: default
2023-02-23 22:00:56,659 - vorta.borg.jobs_manager - DEBUG - No more jobs for site: default
2023-02-23 22:00:56,666 - vorta.scheduler - DEBUG - Refreshing all scheduler timers
2023-02-23 22:00:56,667 - vorta.scheduler - DEBUG - Scheduler for profile 1 is disabled.
2023-02-23 22:00:56,668 - vorta.scheduler - INFO - Setting timer for profile 2
2023-02-23 22:00:56,669 - vorta.scheduler - DEBUG - Scheduling next run for 2023-02-23 23:49:02.013428
2023-02-23 22:01:07,374 - vorta.keyring.abc - DEBUG - No module named 'secretstorage'
2023-02-23 22:01:07,374 - vorta.keyring.abc - DEBUG - Using VortaDarwinKeyring
2023-02-23 22:01:07,374 - vorta.borg.borg_job - DEBUG - Using VortaDarwinKeyring keyring to store passwords.
2023-02-23 22:01:07,402 - vorta.keyring.darwin - DEBUG - Retrieved password for repo /Users/tom/.CMVolumes/CM_GoogleDrive/Vorta_Eigene
2023-02-23 22:01:07,409 - vorta.borg.jobs_manager - DEBUG - Add job for site 1
2023-02-23 22:01:07,410 - vorta.borg.jobs_manager - DEBUG - Start job on site: 1
2023-02-23 22:01:07,411 - vorta.borg.borg_job - INFO - Running command /Applications/Vorta.app/Contents/Resources/borg-dir/borg.exe info --log-json --json /Users/tom/.CMVolumes/CM_GoogleDrive/Vorta_Eigene::Toms-MBP.local-2023-02-02-091949
2023-02-23 22:01:15,934 - vorta.borg.jobs_manager - DEBUG - Finish job for site: 1
2023-02-23 22:01:15,935 - vorta.borg.jobs_manager - DEBUG - No more jobs for site: 1
2023-02-23 22:01:15,936 - vorta.scheduler - INFO - Setting timer for profile 2
2023-02-23 22:01:15,937 - vorta.scheduler - DEBUG - Scheduling next run for 2023-02-23 23:49:02.013428
2023-02-23 22:01:25,453 - vorta.keyring.abc - DEBUG - No module named 'secretstorage'
2023-02-23 22:01:25,453 - vorta.keyring.abc - DEBUG - Using VortaDarwinKeyring
2023-02-23 22:01:25,454 - vorta.borg.borg_job - DEBUG - Using VortaDarwinKeyring keyring to store passwords.
2023-02-23 22:01:25,460 - vorta.keyring.darwin - DEBUG - Retrieved password for repo /Users/tom/.CMVolumes/CM_GoogleDrive/Vorta_Eigene
2023-02-23 22:01:25,483 - vorta.borg.jobs_manager - DEBUG - Add job for site 1
2023-02-23 22:01:25,484 - vorta.borg.jobs_manager - DEBUG - Start job on site: 1
2023-02-23 22:01:25,487 - vorta.borg.borg_job - INFO - Running command /Applications/Vorta.app/Contents/Resources/borg-dir/borg.exe diff --info --log-json --json-lines /Users/tom/.CMVolumes/CM_GoogleDrive/Vorta_Eigene::Toms-MBP.local-2023-02-02-091949 Toms-MBP.local-2023-02-02-143015
2023-02-23 22:01:35,414 - vorta.borg.jobs_manager - DEBUG - Finish job for site: 1
2023-02-23 22:01:35,414 - vorta.borg.jobs_manager - DEBUG - No more jobs for site: 1
2023-02-23 22:01:35,415 - vorta.scheduler - INFO - Setting timer for profile 2
2023-02-23 22:01:35,415 - vorta.scheduler - DEBUG - Scheduling next run for 2023-02-23 23:49:02.013428
```

**Comment by real-yfprojects** [comment]
Thank you for you bug report! This is an odd behaviour indeed. Regarding your statement about the target directory, I don't think that borg creates a new file or a new folder for each archive. Can you provide the output of 
```
borg info --log-json --json /Users/tom/.CMVolumes/CM_GoogleDrive/Vorta_Eigene::Toms-MBP.local-2023-02-02-091949
```
,
```
borg info --log-json --json /Users/tom/.CMVolumes/CM_GoogleDrive/Vorta_Eigene::Toms-MBP.local-2023-02-02-143015
```
and
```
borg diff --info --log-json --json-lines /Users/tom/.CMVolumes/CM_GoogleDrive/Vorta_Eigene::Toms-MBP.local-2023-02-02-091949 Toms-MBP.local-2023-02-02-143015
```
?

**Comment by 21Kingshill** [comment]
Thanks for your reply.

I'm not sure, what exactly you mean by "provide the output of" that files.

- The second screenshot provided above, shows the Finder window
- Files are stored on GoogleDrive (I do not use the google app, but CloudMounter to mount google as a share
- I'm not 100% able to identify the corresponding file from the log entry (e.g. 09:19:49 could be more than one file)
- Due to the sensitive information within the files I can't send them around. Maybe I need to reproduce the issue by using any other random files.

**Comment by real-yfprojects** [comment]
> I'm not sure, what exactly you mean by "provide the output of" that files.

I am interested in the out put of these commands when being run in a cmd with borg on the PATH. This will help identify whether the issue is rooted in the borg backed or in vorta itself.

**Comment by 21Kingshill** [comment]
Stupid me. I didn't look closely and thought that was a log entry.
However, I'm not able to run that in the terminal since I can't find "borg". There is "Varta.app" available only. Did I point to the wrong installation, maybe?

**Comment by real-yfprojects** [comment]
> There is "Varta.app" available only. Did I point to the wrong installation, maybe?

I am not a MacOS user and I don't know how MacOS application bundles work exactly. But I think they can be treated like directories. Try running `/Applications/Vorta.app/Contents/Resources/borg-dir/borg.exe`.

**Comment by 21Kingshill** [comment]
There is a borg.exe in the container as you mentioned. But I'm not aware of a way executing an *.exe file under MacOS (I tried, but MacOS tells me there is noch such command)

In case searching for the root cause is too complex, I might close the issue. Please advise.

**Comment by real-yfprojects** [comment]
I think vorta just runs it borg any other executable. I will refer you to @m3nu. He is the MacOS guy.

**Comment by m3nu** [comment]
borg.exe is just due to historic reasons. It's built over at the Borg project, not here. No relation to Windows.

**Comment by 21Kingshill** [comment]
> borg.exe is just due to historic reasons. It's built over at the Borg project, not here. No relation to Windows.

Thanks for clarification. What I tried to say is that I'm not able to get the information that **_real-yfprojects_** suggested:
borg info --log-json --json /Users/tom/.CMVolumes/CM_GoogleDrive/Vorta_Eigene::Toms-MBP.local-2023-02-02-091949

Pointing to the path of  borg.exe (/Applications/Vorta.app/Contents/Resources/borg-dir/borg.exe) returns error "no such command"

**Comment by m3nu** [comment]
Maybe you didn't install Vorta in this path? Works fine here:

```
 $ brew install vorta
...
==> Installing Cask vorta
==> Moving App 'Vorta.app' to '/Applications/Vorta.app'
🍺  vorta was successfully installed!

$ /Applications/Vorta.app/Contents/Resources/borg-dir/borg.exe --version
borg.exe 1.2.3
```

**Comment by 21Kingshill** [comment]
I used the DMG file from here: https://github.com/borgbase/vorta/releases/download/v0.8.10/vorta-0.8.10.dmg, no brew.

The VORTA app is in the application folder:
![image](https://user-images.githubusercontent.com/107434848/221974866-c3cadacc-4a6c-4b47-afd4-5b7b4b43def3.png)
