### ISSUE TITLE
"[67]  Failed to execute script '__main__' due to unhandled exception!" when trying to extract backup

### ISSUE THREAD

**Issue by metalfoxdev** [borgbase/vorta#1623]
#### Description

I created a Vorta backup of my /home directory on an external usb drive. I then reinstall Manjaro Linux due to an issue unrelated to Vorta and install Vorta on the new installation. I add the existing repository from the aforementioned drive and select the latest archive, press extract and then set it to extract to the new /home. When I press extract, it returns "[67]  Failed to execute script '__main__' due to unhandled exception!"

I was able to reproduce the issue.

![Screenshot_20230304_210808](https://user-images.githubusercontent.com/92944520/222928962-697d54c1-fe30-4f09-88f8-21583710122d.png)

#### Environment

- OS: Manjaro Linux 22 (Sikaris)
- Vorta version: 0.8.10
- Installed from: Flathub
- Borg version: 1.2.3

#### Logs

```
2023-03-04 20:47:08,873 - vorta.keyring.kwallet - DEBUG - Retrieved password for repo /run/media/myuser/TOSHIBA
2023-03-04 20:47:23,721 - vorta.borg.jobs_manager - DEBUG - Add job for site 1
2023-03-04 20:47:23,721 - vorta.borg.jobs_manager - DEBUG - Start job on site: 1
2023-03-04 20:47:23,740 - vorta.borg.borg_job - INFO - Running command /app/bin/borg extract --list --info --log-json /run/media/myuser/TOSHIBA::myuser-modelnumber-2023-03-04-200705 --patterns-from /tmp/tmpy8mstzjc
2023-03-04 20:47:25,882 - vorta.borg.borg_job - WARNING - Traceback (most recent call last):
2023-03-04 20:47:25,884 - vorta.borg.borg_job - WARNING - File "borg/__main__.py", line 15, in <module>
2023-03-04 20:47:25,886 - vorta.borg.borg_job - WARNING - File "borg/archiver.py", line 5156, in main
2023-03-04 20:47:25,887 - vorta.borg.borg_job - WARNING - File "borg/archiver.py", line 4948, in get_args
2023-03-04 20:47:25,888 - vorta.borg.borg_job - WARNING - File "borg/archiver.py", line 4994, in parse_args
2023-03-04 20:47:25,889 - vorta.borg.borg_job - WARNING - File "argparse.py", line 1825, in parse_args
2023-03-04 20:47:25,891 - vorta.borg.borg_job - WARNING - File "argparse.py", line 1858, in parse_known_args
2023-03-04 20:47:25,892 - vorta.borg.borg_job - WARNING - File "argparse.py", line 2049, in _parse_known_args
2023-03-04 20:47:25,892 - vorta.borg.borg_job - WARNING - File "argparse.py", line 2026, in consume_positionals
2023-03-04 20:47:25,893 - vorta.borg.borg_job - WARNING - File "argparse.py", line 1935, in take_action
2023-03-04 20:47:25,894 - vorta.borg.borg_job - WARNING - File "argparse.py", line 1214, in __call__
2023-03-04 20:47:25,895 - vorta.borg.borg_job - WARNING - File "argparse.py", line 1858, in parse_known_args
2023-03-04 20:47:25,897 - vorta.borg.borg_job - WARNING - File "argparse.py", line 2067, in _parse_known_args
2023-03-04 20:47:25,897 - vorta.borg.borg_job - WARNING - File "argparse.py", line 2007, in consume_optional
2023-03-04 20:47:25,899 - vorta.borg.borg_job - WARNING - File "argparse.py", line 1935, in take_action
2023-03-04 20:47:25,900 - vorta.borg.borg_job - WARNING - File "borg/patterns.py", line 59, in __call__
2023-03-04 20:47:25,901 - vorta.borg.borg_job - WARNING - File "borg/patterns.py", line 64, in parse
2023-03-04 20:47:25,902 - vorta.borg.borg_job - WARNING - File "borg/patterns.py", line 32, in load_pattern_file
2023-03-04 20:47:25,902 - vorta.borg.borg_job - WARNING - File "borg/patterns.py", line 17, in parse_patternfile_line
2023-03-04 20:47:25,902 - vorta.borg.borg_job - WARNING - File "borg/patterns.py", line 401, in parse_inclexcl_command
2023-03-04 20:47:25,903 - vorta.borg.borg_job - WARNING - File "borg/patterns.py", line 354, in parse_pattern
2023-03-04 20:47:25,905 - vorta.borg.borg_job - WARNING - File "borg/patterns.py", line 187, in __init__
2023-03-04 20:47:25,907 - vorta.borg.borg_job - WARNING - File "borg/patterns.py", line 266, in _prepare
2023-03-04 20:47:25,908 - vorta.borg.borg_job - WARNING - File "re.py", line 252, in compile
2023-03-04 20:47:25,909 - vorta.borg.borg_job - WARNING - File "re.py", line 304, in _compile
2023-03-04 20:47:25,912 - vorta.borg.borg_job - WARNING - File "sre_compile.py", line 788, in compile
2023-03-04 20:47:25,912 - vorta.borg.borg_job - WARNING - File "sre_parse.py", line 955, in parse
2023-03-04 20:47:25,913 - vorta.borg.borg_job - WARNING - File "sre_parse.py", line 444, in _parse_sub
2023-03-04 20:47:25,914 - vorta.borg.borg_job - WARNING - File "sre_parse.py", line 841, in _parse
2023-03-04 20:47:25,917 - vorta.borg.borg_job - WARNING - File "sre_parse.py", line 444, in _parse_sub
2023-03-04 20:47:25,918 - vorta.borg.borg_job - WARNING - File "sre_parse.py", line 599, in _parse
2023-03-04 20:47:25,920 - vorta.borg.borg_job - WARNING - re.error: bad character range h-U at position 94
2023-03-04 20:47:25,923 - vorta.borg.borg_job - WARNING - [67] Failed to execute script '__main__' due to unhandled exception!
```

**Comment by real-yfprojects** [comment]
That is unfortunate! Is there a path you want to extract containing `[h-U]` or similar?

**Comment by diivi** [comment]
How do I configure dark mode on vorta? 😅

**Comment by real-yfprojects** [comment]
That is the power of qt theming and KDE Plasma combined. On KDE it will only work with the native pyqt from distribution's package index. On Gnome I recommend Kvantum.

**Comment by metalfoxdev** [comment]
@real-yfprojects what do you mean by "h-U"

**Comment by real-yfprojects** [comment]
> @real-yfprojects what do you mean by "h-U"

An H, a dash and a U.

**Comment by metalfoxdev** [comment]
No, I don't think so

**Comment by real-yfprojects** [comment]
> No, I don't think so

You can check with

```bash
$ flatpak run --command=bash --devel com.borgbase.Vorta
$ borg list /run/media/myuser/TOSHIBA::myuser-modelnumber-2023-03-04-200705 | grep -i 'h-u'
```

**Comment by metalfoxdev** [comment]
Ok, I'll do that

**Comment by metalfoxdev** [comment]
@real-yfprojects it returns "Archive myuser-modelnumber-2023-03-04-200705 does not exist" but I checked in Vorta and the archive is there.

**Comment by real-yfprojects** [comment]
> it returns "Archive myuser-modelnumber-2023-03-04-200705 does not exist" but I checked in Vorta and the archive is there.

You must have included a typo. That wouldn't make much sense.

**Comment by metalfoxdev** [comment]
no typos so maybe it's on my end

**Comment by real-yfprojects** [comment]
@metalfoxdev Can you check whether this error still occurs when extracting the **same** archive with the latest version of Vorta?

**Comment by metalfoxdev** [comment]
Sorry for taking ages to reply. Thanks, the error is not there now! :)
