### ISSUE TITLE
Can't create a data backup - ERROR - Traceback (most recent call last):   File "/usr/lib/python3/dist-packages/borg/archiver.py", line 4690, in main

### ISSUE THREAD

**Issue by ptech2009** [borgbase/vorta#1661]
### Description

If i click on "Start data backup" i get immediately a traceback error. Just a few days ago everything was working fine. 

![Errorvortaborg](https://user-images.githubusercontent.com/128221549/226099952-db024835-b1be-42b0-9cbb-489aa66e9e86.png)

### Reproduction

- [X] I tried to reproduce the issue.
- [X] I was able to reproduce the issue.

### OS

Platform: Linux mx 5.10.0-21-amd64 #1 SMP Debian 5.10.162-1 (2023-01-21) x86_64

### Version of Vorta

0.7.5

### What did you install Vorta with?

Flatpak

### Version of Borg

Borg: 1.1.16  Python: CPython 3.9.2 msgpack: 0.5.6.+borg1

### Logs

```pytb
2023-03-18 10:13:58,765 - vorta.borg.borg_thread - ERROR - Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 4690, in main
    exit_code = archiver.run(args)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 4622, in run
    return set_ec(func(args))
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 177, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 586, in do_create
    with Cache(repository, key, manifest, do_files=args.cache_files, progress=args.progress,
  File "/usr/lib/python3/dist-packages/borg/cache.py", line 387, in __new__
    return local()
  File "/usr/lib/python3/dist-packages/borg/cache.py", line 379, in local
    return LocalCache(repository=repository, key=key, manifest=manifest, path=path, sync=sync,
  File "/usr/lib/python3/dist-packages/borg/cache.py", line 464, in __init__
    self.open()
  File "/usr/lib/python3/dist-packages/borg/cache.py", line 511, in open
    self.cache_config.open()
  File "/usr/lib/python3/dist-packages/borg/cache.py", line 269, in open
    self.load()
  File "/usr/lib/python3/dist-packages/borg/cache.py", line 273, in load
    with open(self.config_path) as fd:
FileNotFoundError: [Errno 2] No such file or directory: '/home/paul/.cache/borg/76177d2822fb7d58f4e78e5764e246d1734cd3cb17bf583894c90d0e73e0d8d7/config'
```

**Comment by m3nu** [comment]
That's an error in Borg related to your local cache. We can't help you with that. Just the error message is a bit large, which is being worked on in another issue.

I'd recommend you to move or remove the mentioned cache folder. It will simple be recreated from the remote repo. Could also be a permission issue with that file if you mixed users previously.

**Comment by ptech2009** [comment]
> That's an error in Borg related to your local cache. We can't help you with that. Just the error message is a bit large, which is being worked on in another issue.
> 
> I'd recommend you to move or remove the mentioned cache folder. It will simple be recreated from the remote repo. Could also be a permission issue with that file if you mixed users previously.

So i can just delete the whole "__pycache__" folder?

**Comment by ptech2009** [comment]
Issue can be closed, I installed the flatpak of vorta version 0.8.10 and everything works again.
