### ISSUE TITLE
diff causes critical error/crash

### ISSUE THREAD

**Issue by Orko79** [borgbase/vorta#1668]
### Description

Hi!
When I try to view the differences between two archives, Vorta crashes with a critical error. This always happens in all repositories I use, with all archives. Running the borg diff command in terminal works fine. I know that it worked with borg version 1.2.3 and Vorta 0.8.9.

I've tried a reinstallation of borg and Vorta (using yay/AUR as well as pacman/Chaotic-AUR), reconnecting the repo and refreshing all archives, but this didn't solve the issue.

Repos and archives don't have any issues (I have checked them all, result is the same for all):
`2023-03-27 13:04:06,100 - vorta.borg.borg_job - INFO - Finished full repository check, no problems found.`
`2023-03-27 13:05:22,591 - vorta.borg.borg_job - INFO - Archive consistency check complete, no problems found.`
![grafik](https://user-images.githubusercontent.com/62895670/227917119-60dc051e-cdca-4baa-b15d-33ad1bc29ebe.png)

### Reproduction

- [X] I tried to reproduce the issue.
- [X] I was able to reproduce the issue.

### OS

EndeavourOS , Kernel: 6.2.8-zen1-1-zen, KDE Plasma 5.27.3

### Version of Vorta

0.8.10

### What did you install Vorta with?

Distribution package

### Version of Borg

1.2.4

### Logs

```pytb
2023-03-27 12:13:24,663 - vorta.borg.borg_job - INFO - Running command /usr/bin/borg diff --info --log-json --json-lines /my/repos/::archive 1 archive 2
2023-03-27 12:13:36,949 - vorta.borg.jobs_manager - DEBUG - Finish job for site: 3
2023-03-27 12:13:36,949 - vorta.borg.jobs_manager - DEBUG - No more jobs for site: 3
2023-03-27 12:13:36,953 - vorta.scheduler - INFO - Setting timer for profile 1
2023-03-27 12:13:36,961 - vorta.scheduler - DEBUG - Scheduling next run for 2023-03-27 13:39:54.916219
2023-03-27 12:13:38,009 - root - CRITICAL - Uncaught exception, file a report at https://github.com/borgbase/vorta/issues/new/choose
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/vorta/views/diff_result.py", line 50, in run
    parse_diff_json(lines, self.model)
  File "/usr/lib/python3.10/site-packages/vorta/views/diff_result.py", line 273, in parse_diff_json
    raise Exception('Unknown change type: {}'.format(change['type']))
Exception: Unknown change type: ctime
```

**Comment by m3nu** [comment]
Maybe this type of change isn't on our list of possible changes yet. Should be a simple fix.

**Comment by jetchirag** [comment]
@m3nu Can you assign this to me? I'd like to reproduce this first.

**Comment by m3nu** [comment]
Done! Thanks for checking it out!

**Comment by m3nu** [comment]
Good job debugging this. If we don't have a mechanism to deal with this, it's best to add this flag right away.

Then we have time to consider this in detail.

**Comment by jetchirag** [comment]
Possible future implementation idea: tootltip on change column. 

------------------------
| Modified Time: XYZ |
| Creation Time: XYZ  |
------------------------
