### ISSUE TITLE
Mac OS Ventura: paramiko.ssh_exception.SSHException: not a valid OPENSSH private key file

### ISSUE THREAD

**Issue by wbeck77** [borgbase/vorta#1680]
Hi all,

many thanks for your great SW! I would love to use it, but it does not work on my Macbook.

borg ist running properly on the command line (installed via home brew)
So I verified my ssh connected repo is working properly (Its on BorgBase)

But adding the repo in Volta end with this log (I hided my repo url manually with xxx in this log)

Any ideas?

Best regards

Wolfgang Beck

```pytb
2023-04-03 14:54:30,642 - root - DEBUG - Expected error parsing file in .ssh: known_hosts (You can safely ignore this)
Traceback (most recent call last):
  File "utils.py", line 195, in get_private_keys
  File "paramiko/pkey.py", line 232, in from_private_key_file
  File "paramiko/rsakey.py", line 63, in __init__
  File "paramiko/rsakey.py", line 186, in _from_private_key_file
  File "paramiko/pkey.py", line 305, in _read_private_key_file
  File "paramiko/pkey.py", line 323, in _read_private_key
paramiko.ssh_exception.SSHException: not a valid RSA private key file
2023-04-03 14:54:30,642 - root - DEBUG - Expected error parsing file in .ssh: known_hosts (You can safely ignore this)
Traceback (most recent call last):
  File "utils.py", line 195, in get_private_keys
  File "paramiko/pkey.py", line 232, in from_private_key_file
  File "paramiko/ecdsakey.py", line 126, in __init__
  File "paramiko/ecdsakey.py", line 277, in _from_private_key_file
  File "paramiko/pkey.py", line 305, in _read_private_key_file
  File "paramiko/pkey.py", line 323, in _read_private_key
paramiko.ssh_exception.SSHException: not a valid EC private key file
2023-04-03 14:54:30,643 - root - DEBUG - Expected error parsing file in .ssh: known_hosts (You can safely ignore this)
Traceback (most recent call last):
  File "utils.py", line 195, in get_private_keys
  File "paramiko/pkey.py", line 232, in from_private_key_file
  File "paramiko/ed25519key.py", line 58, in __init__
  File "paramiko/pkey.py", line 323, in _read_private_key
paramiko.ssh_exception.SSHException: not a valid OPENSSH private key file
2023-04-03 14:54:30,652 - vorta.keyring.abc - DEBUG - No module named 'secretstorage'
2023-04-03 14:54:30,653 - vorta.keyring.abc - DEBUG - Using VortaDarwinKeyring
2023-04-03 14:54:32,271 - vorta.keyring.abc - DEBUG - No module named 'secretstorage'
2023-04-03 14:54:32,271 - vorta.keyring.abc - DEBUG - Using VortaDarwinKeyring
2023-04-03 14:54:32,279 - vorta.keyring.darwin - DEBUG - Retrieved password for repo Bz3z8UO2BhfcQ6DF134
2023-04-03 14:54:40,251 - vorta.keyring.abc - DEBUG - No module named 'secretstorage'
2023-04-03 14:54:40,252 - vorta.keyring.abc - DEBUG - Using VortaDarwinKeyring
2023-04-03 14:54:40,253 - vorta.keyring.darwin - DEBUG - Retrieved password for repo ssh://xxxxxxxxxxxx.repo.borgbase.com/./repo
2023-04-03 14:54:42,544 - vorta.keyring.abc - DEBUG - No module named 'secretstorage'
2023-04-03 14:54:42,544 - vorta.keyring.abc - DEBUG - Using VortaDarwinKeyring
2023-04-03 14:54:42,544 - vorta.borg.borg_job - DEBUG - Using VortaDarwinKeyring keyring to store passwords.
2023-04-03 14:54:42,545 - vorta.keyring.darwin - DEBUG - Retrieved password for repo ssh://xxxxxxxxxxx.repo.borgbase.com/./repo
2023-04-03 14:54:42,545 - vorta.borg.borg_job - DEBUG - Password not found in primary keyring. Falling back to VortaDBKeyring.
2023-04-03 14:54:42,551 - vorta.borg.borg_job - INFO - Running command /opt/homebrew/bin/borg info --info --json --log-json ssh://xxxxxxxxx.repo.borgbase.com/./repo
2023-04-03 14:54:43,010 - vorta.borg.borg_job - WARNING - Remote: ssh_askpass: exec(/usr/X11R6/bin/ssh-askpass): No such file or directory
2023-04-03 14:54:43,012 - vorta.borg.borg_job - WARNING - Remote: xxxxxxxxx.repo.borgbase.com: Permission denied (publickey,gssapi-keyex,gssapi-with-mic).
2023-04-03 14:54:43,013 - vorta.borg.borg_job - ERROR - Connection closed by remote host. Is borg working on the server?
```

**Comment by real-yfprojects** [comment]
These warnings are the cause of your problem: 
```
Remote: ssh_askpass: exec(/usr/X11R6/bin/ssh-askpass): No such file or directory
Remote: xxxxxxxxx.repo.borgbase.com: Permission denied (publickey,gssapi-keyex,gssapi-with-mic).
```

#1604 suggest checking the permissions and ownership of the `know_hosts` file.
Also have a look at #1530 and #1393.

**Comment by wbeck77** [comment]
thank you for these hints.

my known_host file is accessible and has the entries to the repos. looks good. 
not really surprising because borg in the terminal works well.

i also read #1530 and #1393. maybe I missed something but I can't see how these two can help me, sorry.

**Comment by m3nu** [comment]
The issue is definitely with your SSH keys. Maybe you specified a non-standard key while using it in the terminal?

**Comment by wbeck77** [comment]
Maybe. But borg in the terminal is working by default with the right key. It asks for the passphrase of my local ssh key and it works after I enter the right passphrase properly. 

So if there is something wrong with my key I´m really wondering what .... :-/
Looks like that something is different only if Vorta is using the keys...

**Comment by m3nu** [comment]
Maybe we should add a note or alert on encrypted keys. It's a regular problem.

**Comment by wbeck77** [comment]
Thanks for your support! A new SSH key without passphrase works now.

Maybe some ideas on how Vorta could be improved:
- report the usage of an SSH key having a passphrase with a note or alert (as you propose)
- handle SSH keys with passphrase by storing the passphrase in a safe way (e.g. system key chain of macOS)

and also helpful:
- fix "add existing repository" dialog if for the very first usage:
- On my Macbook I had no choice to select another than the "default ssh key" in this dialog (its German in my case)

<img width="734" alt="Bildschirm­foto 2023-04-04 um 08 22 09" src="https://user-images.githubusercontent.com/56505039/229705848-7adc0c2f-a206-49a7-a8ad-c3a5bf1c291a.png">

- now that I added (and removed) a repo the very first time the dialog works as expected

But now I´m looking forward to use your SW! Many thanks for supporting me :-)

**Comment by diivi** [comment]
another related issue: #928

**Comment by real-yfprojects** [comment]
> * fix "add existing repository" dialog if for the very first usage

Do you mean this issue #1579?

> report the usage of an SSH key having a passphrase with a note or alert (as you propose)

For that we need a way to detect encrypted keys. Any ideas?
