### ISSUE TITLE
Linux Mint - Unexpected crash during diff

### ISSUE THREAD

**Issue by YunitoMH** [borgbase/vorta#1684]
### Description

After removing a folder from the source directory and conducting a backup with Vorta, the program crashes when running the diff command. This issue persists any new backups as well. Howver, the crashes only occur with archives involving the recent folder deletion, while older archives function properly. 

As additional information, I'm running my repo in Append Only Mode in Borgbase 

To recreate the problem:

    Delete a folder within the source directory.
    Perform a backup using Vorta.
    Attempt to run Diff.

### Reproduction

- [X] I tried to reproduce the issue.
- [X] I was able to reproduce the issue.

### OS

Linux Mint 21 Cinnamon - Kernel 5.19

### Version of Vorta

0..8.10

### What did you install Vorta with?

Flatpak

### Version of Borg

1.2.4

### Logs

```pytb
2023-04-07 23:22:40,414 - vorta.borg.jobs_manager - DEBUG - Finish job for site: 4
2023-04-07 23:22:40,415 - vorta.borg.jobs_manager - DEBUG - No more jobs for site: 4
2023-04-07 23:22:40,419 - vorta.scheduler - INFO - Setting timer for profile 5
2023-04-07 23:22:40,422 - vorta.scheduler - DEBUG - Scheduling next run for 2023-04-08 03:42:00
2023-04-07 23:22:40,653 - root - CRITICAL - Uncaught exception, file a report at https://github.com/borgbase/vorta/issues/new/choose
Traceback (most recent call last):
  File "/app/lib/python3.10/site-packages/vorta/views/diff_result.py", line 50, in run
    parse_diff_json(lines, self.model)
  File "/app/lib/python3.10/site-packages/vorta/views/diff_result.py", line 273, in parse_diff_json
    raise Exception('Unknown change type: {}'.format(change['type']))
Exception: Unknown change type: ctime
```

**Comment by YunitoMH** [comment]
Fixed in [#1675[](url)](https://github.com/borgbase/vorta/issues/1675)
