### ISSUE TITLE
Crash on backup network share

### ISSUE THREAD

**Issue by pcace** [borgbase/vorta#1688]
### Description

Hi there, i am getting this error everytime i am trying to back up a network share (smb share, connected to osx 13.3 via finder:

<img width="1552" alt="Bildschirmfoto 2023-04-09 um 16 02 03" src="https://user-images.githubusercontent.com/1011875/230777386-b86c67f7-8be7-4762-836a-ffb0c61138fa.png">

what is the issue here? 
thanks a lot for help

### Reproduction

- [X] I tried to reproduce the issue.
- [x] I was able to reproduce the issue.

### OS

OSX 13.3

### Version of Vorta

0.8.10

### What did you install Vorta with?

Homebrew

### Version of Borg

1.2.3

### Logs

```pytb
2023-04-09 15:36:36,048 - vorta.scheduler - DEBUG - Refreshing all scheduler timers
2023-04-09 15:36:36,057 - vorta.scheduler - INFO - Setting timer for profile 1
2023-04-09 15:36:36,059 - vorta.scheduler - DEBUG - Scheduling next run for 2023-04-09 18:20:53.814401
2023-04-09 15:36:36,065 - vorta.scheduler - INFO - Setting timer for profile 2
2023-04-09 15:36:36,068 - vorta.scheduler - DEBUG - Scheduling next run for 2023-04-10 03:42:00
2023-04-09 15:44:18,622 - vorta.borg.borg_job - ERROR - Local Exception
2023-04-09 15:44:18,624 - vorta.borg.borg_job - ERROR - Traceback (most recent call last):
  File "/opt/homebrew/Cellar/borgbackup-fuse/1.2.3/libexec/lib/python3.10/site-packages/borg/archive.py", line 232, in backup_io_iter
    item = next(iterator)
  File "src/borg/chunker.pyx", line 270, in borg.chunker.Chunker.__next__
OSError: [Errno 22] Invalid argument

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/homebrew/Cellar/borgbackup-fuse/1.2.3/libexec/lib/python3.10/site-packages/borg/archive.py", line 269, in OsOpen
    yield fd
  File "/opt/homebrew/Cellar/borgbackup-fuse/1.2.3/libexec/lib/python3.10/site-packages/borg/archive.py", line 1443, in process_file
    self.process_file_chunks(item, cache, self.stats, self.show_progress, backup_io_iter(self.chunker.chunkify(None, fd)))
  File "/opt/homebrew/Cellar/borgbackup-fuse/1.2.3/libexec/lib/python3.10/site-packages/borg/archive.py", line 1269, in process_file_chunks
    for chunk in chunk_iter:
  File "/opt/homebrew/Cellar/borgbackup-fuse/1.2.3/libexec/lib/python3.10/site-packages/borg/archive.py", line 230, in backup_io_iter
    with backup_io:
  File "/opt/homebrew/Cellar/borgbackup-fuse/1.2.3/libexec/lib/python3.10/site-packages/borg/archive.py", line 221, in __exit__
    raise BackupOSError(self.op, exc_val) from exc_val
borg.archive.BackupOSError: read: [Errno 22] Invalid argument

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/Cellar/borgbackup-fuse/1.2.3/libexec/lib/python3.10/site-packages/borg/archiver.py", line 5168, in main
    exit_code = archiver.run(args)
  File "/opt/homebrew/Cellar/borgbackup-fuse/1.2.3/libexec/lib/python3.10/site-packages/borg/archiver.py", line 5099, in run
    return set_ec(func(args))
  File "/opt/homebrew/Cellar/borgbackup-fuse/1.2.3/libexec/lib/python3.10/site-packages/borg/archiver.py", line 183, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/opt/homebrew/Cellar/borgbackup-fuse/1.2.3/libexec/lib/python3.10/site-packages/borg/archiver.py", line 675, in do_create
    create_inner(archive, cache, fso)
  File "/opt/homebrew/Cellar/borgbackup-fuse/1.2.3/libexec/lib/python3.10/site-packages/borg/archiver.py", line 608, in create_inner
    self._rec_walk(path=path, parent_fd=parent_fd, name=name,
  File "/opt/homebrew/Cellar/borgbackup-fuse/1.2.3/libexec/lib/python3.10/site-packages/borg/archiver.py", line 823, in _rec_walk
    self._rec_walk(
  File "/opt/homebrew/Cellar/borgbackup-fuse/1.2.3/libexec/lib/python3.10/site-packages/borg/archiver.py", line 823, in _rec_walk
    self._rec_walk(
  File "/opt/homebrew/Cellar/borgbackup-fuse/1.2.3/libexec/lib/python3.10/site-packages/borg/archiver.py", line 823, in _rec_walk
    self._rec_walk(
  [Previous line repeated 5 more times]
  File "/opt/homebrew/Cellar/borgbackup-fuse/1.2.3/libexec/lib/python3.10/site-packages/borg/archiver.py", line 786, in _rec_walk
    status = self._process_any(path=path, parent_fd=parent_fd, name=name, st=st, fso=fso, cache=cache,
  File "/opt/homebrew/Cellar/borgbackup-fuse/1.2.3/libexec/lib/python3.10/site-packages/borg/archiver.py", line 688, in _process_any
    return fso.process_file(path=path, parent_fd=parent_fd, name=name, st=st, cache=cache)
  File "/opt/homebrew/Cellar/borgbackup-fuse/1.2.3/libexec/lib/python3.10/site-packages/borg/archive.py", line 1402, in process_file
    with OsOpen(path=path, parent_fd=parent_fd, name=name, flags=flags, noatime=True) as fd:
  File "/opt/homebrew/Cellar/python@3.10/3.10.10_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/opt/homebrew/Cellar/borgbackup-fuse/1.2.3/libexec/lib/python3.10/site-packages/borg/archive.py", line 273, in OsOpen
    os.close(fd)
OSError: [Errno 22] Invalid argument

Platform: Darwin MB-Air.fritz.box 22.4.0 Darwin Kernel Version 22.4.0: Mon Mar  6 21:00:41 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T8103 arm64
Borg: 1.2.3  Python: CPython 3.10.10 msgpack: 1.0.4 fuse: llfuse 1.4.2 [pyfuse3,llfuse]
PID: 80240  CWD: /
sys.argv: ['/opt/homebrew/bin/borg', 'create', '--list', '--progress', '--info', '--log-json', '--json', '--filter=AM', '-C', 'lz4', 'ssh://user@your-storagebox.de:23/./hugo_user::MB-Air.fritz.box-2023-04-09-152703', '/Volumes/hugo/hugoData/Hugo/H']
SSH_ORIGINAL_COMMAND: None
```

**Comment by real-yfprojects** [comment]
This error seems to occur when an invalid file path is passed to the OS. However I can't tell you which path the Error is raised for. Maybe @ThomasWaldmann can help?

**Comment by ThomasWaldmann** [comment]
@pcace That's interesting, but I need some more infos:

- where does the smb share come from / configuration of the smb share server side.
- how is it mounted client side, anything special?
- is that error fatal (terminating borg) or does the remainder of files get backed up?
- could you run borg directly, so we better see all its output? leave away the --filter=AM.

It might be a problem below borg, but sadly, there is not much information besides `read: [Errno 22] Invalid argument`.
