### ISSUE TITLE
Repo Create in mint 19.1 gets stuck on refresh

### ISSUE THREAD

**Issue by dragon2611** [borgbase/vorta#173]
**Describe the bug**
When creating a local repo on mint 19.1 the UI hangs on refreshing, the following is printed to the terminal (if running in forground)
```

Gtk-Message: 18:31:42.952: GtkDialog mapped without a transient parent. This is discouraged.
2019-01-30 18:31:52,378 - vorta.borg.borg_thread - INFO - Running command borg init --info --log-json --encryption=repokey-blake2 /mnt/hdd2/Blah/Blah/dtopbackup
2019-01-30 18:31:52,759 - vorta.borg.borg_thread - INFO - Running command borg list --info --log-json --json /mnt/hdd2/Blah/Blah/dtopbackup
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.6/site-packages/vorta/borg/borg_thread.py", line 203, in run
    self.process_result(result)
  File "/home/user/.local/lib/python3.6/site-packages/vorta/borg/list_repo.py", line 41, in process_result
    remote_archives = result['data'].get('archives', [])
AttributeError: 'str' object has no attribute 'get'
```
Note I did do a find/replace on the path names

Mint 19.1 with xfce 

LZ4 compression, repokey stored in repo and blake2 selected.

**Comment by dragon2611** [comment]
Ah i think it's related to https://github.com/borgbase/vorta/issues/172 seems pip3 install condor isn't a good idea.

**Comment by dragon2611** [comment]
This was an issue with the python envrioment/linux mint rather than a bug in vorta (i think)
