### ISSUE TITLE
Error when trying to use a repo I've already added

### ISSUE THREAD

**Issue by gwerbin** [borgbase/vorta#1731]
I am using Vorta 0.8.12 on EndeavourOS. I added a remote BorgBase repository, but it maybe got stuck part-way through adding. I later tried to re-use the added repository, but I got an error message.

I don't see a way to delete this repository and re-add it in the app.

However I am well versed in Python and SQL, so if I can manually hack around in the database to clear it manually, I'm happy to do that as long as I have clear instructions for doing so. I haven't made many backups yet, so if there's also some way to reset the app cleanly, I can do that too.

Here's the full Python traceback that popped up:

<details>

```text
Uncaught exception, please file a report with this text at
https://github.com/borgbase/vorta/issues/new
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/peewee.py", line 7117, in get
    return clone.execute(database)[0]
           ~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/usr/lib/python3.11/site-packages/peewee.py", line 4481, in __getitem__
    return self.row_cache[item]
           ~~~~~~~~~~~~~~^^^^^^
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/vorta/application.py", line 224, in react_to_log
    profile = BackupProfileModel.get(name=context['profile_name'])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/peewee.py", line 6669, in get
    return sq.get()
           ^^^^^^^^
  File "/usr/lib/python3.11/site-packages/peewee.py", line 7120, in get
    raise self.model.DoesNotExist('%s instance matching query does '
vorta.store.models.BackupProfileModelDoesNotExist: <Model: BackupProfileModel> instance matching query does not exist:
SQL: SELECT "t1"."id", "t1"."name", "t1"."added_at", "t1"."repo_id", "t1"."ssh_key", "t1"."compression", "t1"."exclude_patterns", "t1"."exclude_if_present", "t1"."schedule_mode", "t1"."schedule_interval_count", "t1"."schedule_interval_unit", "t1"."schedule_fixed_hour", "t1"."schedule_fixed_minute", "t1"."schedule_interval_hours", "t1"."schedule_interval_minutes", "t1"."schedule_make_up_missed", "t1"."validation_on", "t1"."validation_weeks", "t1"."prune_on", "t1"."prune_hour", "t1"."prune_day", "t1"."prune_week", "t1"."prune_month", "t1"."prune_year", "t1"."prune_keep_within", "t1"."new_archive_name", "t1"."prune_prefix", "t1"."pre_backup_cmd", "t1"."post_backup_cmd", "t1"."dont_run_on_metered_networks" FROM "backupprofilemodel" AS "t1" WHERE ("t1"."name" = ?) LIMIT ? OFFSET ?
Params: ['New Repo', 1, 0]
```

</details>

**Comment by real-yfprojects** [comment]
could this be a duplicate of #1449 ?
Try `borg break-lock <repo>`.

**Comment by gwerbin** [comment]
The issue seems to have resolved itself after some time (maybe a few PC restarts?), but this is useful to know in the future. Closing because I can no longer reproduce my own issue.
