### ISSUE TITLE
uncaught exception

### ISSUE THREAD

**Issue by paolobenve** [borgbase/vorta#1743]
running  vorta with sudo I got this:

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/vorta/application.py", line 185, in set_borg_details_result
    self.scheduler.reload_all_timers()  # Start timer after Borg version is set.
  File "/usr/lib/python3/dist-packages/vorta/scheduler.py", line 121, in reload_all_timers
    self.set_timer_for_profile(profile.id)
  File "/usr/lib/python3/dist-packages/vorta/scheduler.py", line 111, in set_timer_for_profile
    timer.setInterval(int(timer_ms))
OverflowError: argument 1 overflowed: value must be in the range -2147483648 to 2147483647
```

**Comment by m3nu** [comment]
We don't really support running as root, since settings and such are tied to your user profile.

For the error, did you set an unusually long interval in the scheduler maybe? Would be more than 24 days. (we may want to check for this case though)

**Comment by m3nu** [comment]
If so, please use the latest release or `master` branch and let us know here, if it still happens and we'll reopen.

Thanks for the report!
