### ISSUE TITLE
Uncaught exception: IndexError: list index out of range

### ISSUE THREAD

**Issue by hagenest** [borgbase/vorta#1744]
When trying to connect to my existing borg repository at hetzner I receive the following Traceback:

```
 File "/app/lib/python3.10/site-packages/peewee.py", line 7117, in get
    return clone.execute(database)[0]
  File "/app/lib/python3.10/site-packages/peewee.py", line 4481, in __getitem__
    return self.row_cache[item]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/lib/python3.10/site-packages/vorta/application.py", line 224, in react_to_log
    profile = BackupProfileModel.get(name=context['profile_name'])
  File "/app/lib/python3.10/site-packages/peewee.py", line 6669, in get
    return sq.get()
  File "/app/lib/python3.10/site-packages/peewee.py", line 7120, in get
    raise self.model.DoesNotExist('%s instance matching query does '
vorta.store.models.BackupProfileModelDoesNotExist: <Model: BackupProfileModel> instance matching query does not exist:
SQL: SELECT "t1"."id", "t1"."name", "t1"."added_at", "t1"."repo_id", "t1"."ssh_key", "t1"."compression", "t1"."exclude_patterns", "t1"."exclude_if_present", "t1"."schedule_mode", "t1"."schedule_interval_count", "t1"."schedule_interval_unit", "t1"."schedule_fixed_hour", "t1"."schedule_fixed_minute", "t1"."schedule_interval_hours", "t1"."schedule_interval_minutes", "t1"."schedule_make_up_missed", "t1"."validation_on", "t1"."validation_weeks", "t1"."prune_on", "t1"."prune_hour", "t1"."prune_day", "t1"."prune_week", "t1"."prune_month", "t1"."prune_year", "t1"."prune_keep_within", "t1"."new_archive_name", "t1"."prune_prefix", "t1"."pre_backup_cmd", "t1"."post_backup_cmd", "t1"."dont_run_on_metered_networks" FROM "backupprofilemodel" AS "t1" WHERE ("t1"."name" = ?) LIMIT ? OFFSET ?
Params: ['New Repo', 1, 0]
```

Adding the repo to Pika-Backup does work though.

I'm using vorta as a flatpak on openSUSE Aeon

**Comment by hagenest** [comment]
After trying it for a third time with exactly the same path and password it suddenly worked. Maybe it was just a problem with my connection :thinking:

**Comment by real-yfprojects** [comment]
This can be traced back to the same underlying bug as #1449. Thank you for reporting!
