### ISSUE TITLE
[Flatpak + KWallet] Unable to connect / add repo on borgbase

### ISSUE THREAD

**Issue by andreaippo** [borgbase/vorta#1753]
### Description

My Vorta backups stopped around the 8th of July. I'm using the Flatpak app and my repo is hosted by borgbase.com

Suddenly all my scheduled backups started to fail with error code 2.

I tried to remove and re-add the repo to Vorta, and I always get the same error as per screenshot attached. Log also attached.

Spoiler: it seems to be a problem accessing KWallet to retrieve my borg passphrase. I have even tried enabling all permissions for this package using Flatseal, but still I get the same error.

I have ended up installing the packaged version from my distro, and that one works fine.

### Reproduction

- [X] I tried to reproduce the issue.
- [X] I was able to reproduce the issue.

### OS

openSuse Tumbleweed

### Version of Vorta

0.8.12

### What did you install Vorta with?

Flatpak

### Version of Borg

1.2.4

### Logs

```pytb
2023-07-14 15:49:43,919 - vorta.i18n - DEBUG - Loading translation succeeded for ['en', 'en-US', 'en-Latn-US'].
2023-07-14 15:49:43,921 - vorta.scheduler - WARNING - Failed to connect to DBUS interface to detect sleep/resume events
2023-07-14 15:49:44,128 - root - INFO - Using NetworkManagerMonitor NetworkStatusMonitor implementation.
2023-07-14 15:49:44,136 - vorta.network_status.network_manager - WARNING - Couldn't load settings for /org/freedesktop/NetworkManager/Settings/5
Traceback (most recent call last):
  File "/app/lib/python3.10/site-packages/vorta/network_status/network_manager.py", line 53, in get_known_wifis
    settings = self._nm.get_settings(connection_path)
  File "/app/lib/python3.10/site-packages/vorta/network_status/network_manager.py", line 143, in get_settings
    return get_result(settings.call('GetSettings'))
  File "/app/lib/python3.10/site-packages/vorta/network_status/network_manager.py", line 167, in get_result
    raise DBusException("DBus call failed: {}".format(msg.arguments()))
vorta.network_status.network_manager.DBusException: DBus call failed: ['uid 1000 has no permission to perform this operation']
2023-07-14 15:49:44,137 - vorta.network_status.network_manager - WARNING - Couldn't load settings for /org/freedesktop/NetworkManager/Settings/6
Traceback (most recent call last):
  File "/app/lib/python3.10/site-packages/vorta/network_status/network_manager.py", line 53, in get_known_wifis
    settings = self._nm.get_settings(connection_path)
  File "/app/lib/python3.10/site-packages/vorta/network_status/network_manager.py", line 143, in get_settings
    return get_result(settings.call('GetSettings'))
  File "/app/lib/python3.10/site-packages/vorta/network_status/network_manager.py", line 167, in get_result
    raise DBusException("DBus call failed: {}".format(msg.arguments()))
vorta.network_status.network_manager.DBusException: DBus call failed: ['uid 1000 has no permission to perform this operation']
2023-07-14 15:49:44,208 - vorta.borg.jobs_manager - DEBUG - Add job for site default
2023-07-14 15:49:44,209 - vorta.borg.jobs_manager - DEBUG - Start job on site: default
2023-07-14 15:49:44,212 - vorta.borg.borg_job - INFO - Running command /app/bin/borg --version
2023-07-14 15:49:44,686 - vorta.borg.jobs_manager - DEBUG - Finish job for site: default
2023-07-14 15:49:44,686 - vorta.borg.jobs_manager - DEBUG - No more jobs for site: default
2023-07-14 15:49:44,687 - vorta.scheduler - DEBUG - Refreshing all scheduler timers
2023-07-14 15:49:44,692 - vorta.scheduler - DEBUG - Nothing scheduled for profile 1 because of unset repo.
2023-07-14 15:49:50,975 - vorta.keyring.abc - DEBUG - Only available on macOS
2023-07-14 15:49:51,040 - vorta.keyring.abc - DEBUG - Using VortaKWallet5Keyring
2023-07-14 15:50:04,795 - vorta.keyring.abc - DEBUG - Only available on macOS
2023-07-14 15:50:04,797 - vorta.keyring.abc - DEBUG - Using VortaKWallet5Keyring
2023-07-14 15:50:10,124 - vorta.keyring.abc - DEBUG - Only available on macOS
2023-07-14 15:50:10,126 - vorta.keyring.abc - DEBUG - Using VortaKWallet5Keyring
2023-07-14 15:50:10,126 - vorta.borg.borg_job - DEBUG - Using VortaKWallet5Keyring keyring to store passwords.
2023-07-14 15:50:10,128 - vorta.borg.borg_job - DEBUG - Password not found in primary keyring. Falling back to VortaDBKeyring.
2023-07-14 15:50:10,135 - vorta.borg.borg_job - INFO - Running command /app/bin/borg info --info --json --log-json ssh://p6su75vy@p6su75vy.repo.borgbase.com/./repo
2023-07-14 15:50:11,341 - vorta.borg.borg_job - WARNING - Remote: p6su75vy@p6su75vy.repo.borgbase.com: Permission denied (publickey,gssapi-keyex,gssapi-with-mic).
2023-07-14 15:50:11,344 - vorta.borg.borg_job - ERROR - Connection closed by remote host. Is borg working on the server?
2023-07-14 15:50:27,755 - vorta.keyring.abc - DEBUG - Only available on macOS
2023-07-14 15:50:27,758 - vorta.keyring.abc - DEBUG - Using VortaKWallet5Keyring
2023-07-14 15:50:27,758 - vorta.borg.borg_job - DEBUG - Using VortaKWallet5Keyring keyring to store passwords.
2023-07-14 15:50:27,763 - vorta.borg.borg_job - DEBUG - Password not found in primary keyring. Falling back to VortaDBKeyring.
2023-07-14 15:50:27,773 - vorta.borg.borg_job - INFO - Running command /app/bin/borg info --info --json --log-json ssh://p6su75vy@p6su75vy.repo.borgbase.com/./repo
2023-07-14 15:50:28,928 - vorta.borg.borg_job - WARNING - Remote: p6su75vy@p6su75vy.repo.borgbase.com: Permission denied (publickey,gssapi-keyex,gssapi-with-mic).
2023-07-14 15:50:28,932 - vorta.borg.borg_job - ERROR - Connection closed by remote host. Is borg working on the server?
2023-07-14 15:50:32,965 - vorta.keyring.abc - DEBUG - Only available on macOS
2023-07-14 15:50:32,968 - vorta.keyring.abc - DEBUG - Using VortaKWallet5Keyring
2023-07-14 15:50:32,968 - vorta.borg.borg_job - DEBUG - Using VortaKWallet5Keyring keyring to store passwords.
2023-07-14 15:50:32,970 - vorta.borg.borg_job - DEBUG - Password not found in primary keyring. Falling back to VortaDBKeyring.
2023-07-14 15:50:32,977 - vorta.borg.borg_job - INFO - Running command /app/bin/borg info --info --json --log-json ssh://p6su75vy@p6su75vy.repo.borgbase.com/./repo
2023-07-14 15:50:34,288 - vorta.borg.borg_job - WARNING - Remote: p6su75vy@p6su75vy.repo.borgbase.com: Permission denied (publickey,gssapi-keyex,gssapi-with-mic).
2023-07-14 15:50:34,292 - vorta.borg.borg_job - ERROR - Connection closed by remote host. Is borg working on the server?
2023-07-14 15:50:34,683 - vorta.keyring.abc - DEBUG - Only available on macOS
2023-07-14 15:50:34,685 - vorta.keyring.abc - DEBUG - Using VortaKWallet5Keyring
2023-07-14 15:50:34,686 - vorta.borg.borg_job - DEBUG - Using VortaKWallet5Keyring keyring to store passwords.
2023-07-14 15:50:34,690 - vorta.borg.borg_job - DEBUG - Password not found in primary keyring. Falling back to VortaDBKeyring.
2023-07-14 15:50:34,701 - vorta.borg.borg_job - INFO - Running command /app/bin/borg info --info --json --log-json ssh://p6su75vy@p6su75vy.repo.borgbase.com/./repo
2023-07-14 15:50:36,129 - vorta.borg.borg_job - WARNING - Remote: p6su75vy@p6su75vy.repo.borgbase.com: Permission denied (publickey,gssapi-keyex,gssapi-with-mic).
2023-07-14 15:50:36,133 - vorta.borg.borg_job - ERROR - Connection closed by remote host. Is borg working on the server?
2023-07-14 15:54:07,985 - vorta.borg.borg_job - DEBUG - Cancel job on site default
2023-07-14 15:54:07,985 - vorta.borg.jobs_manager - INFO - Finished cancelling all jobs
```

**Comment by andreaippo** [comment]
![image](https://github.com/borgbase/vorta/assets/801070/ccc2377b-ed8b-42b1-92ce-7910627ef19b)

And this is what kwallet looks like:

![image](https://github.com/borgbase/vorta/assets/801070/d44b61b1-5fe8-4586-bb8c-50dc6075c1d2)

**Comment by andreaippo** [comment]
Ok I have tried to disable the option to use the system wallet to retrieve the repo password, and let Vorta store it somewhere in plaintext.

Now it still fails but one step further:

2023-07-14 16:08:02,163 - vorta.i18n - DEBUG - Loading translation succeeded for ['en', 'en-US', 'en-Latn-US'].
2023-07-14 16:08:02,404 - root - INFO - Using NetworkManagerMonitor NetworkStatusMonitor implementation.
2023-07-14 16:08:02,410 - vorta.network_status.network_manager - WARNING - Couldn't load settings for /org/freedesktop/NetworkManager/Settings/5
Traceback (most recent call last):
  File "/app/lib/python3.10/site-packages/vorta/network_status/network_manager.py", line 53, in get_known_wifis
    settings = self._nm.get_settings(connection_path)
  File "/app/lib/python3.10/site-packages/vorta/network_status/network_manager.py", line 143, in get_settings
    return get_result(settings.call('GetSettings'))
  File "/app/lib/python3.10/site-packages/vorta/network_status/network_manager.py", line 167, in get_result
    raise DBusException("DBus call failed: {}".format(msg.arguments()))
vorta.network_status.network_manager.DBusException: DBus call failed: ['uid 1000 has no permission to perform this operation']
2023-07-14 16:08:02,411 - vorta.network_status.network_manager - WARNING - Couldn't load settings for /org/freedesktop/NetworkManager/Settings/6
Traceback (most recent call last):
  File "/app/lib/python3.10/site-packages/vorta/network_status/network_manager.py", line 53, in get_known_wifis
    settings = self._nm.get_settings(connection_path)
  File "/app/lib/python3.10/site-packages/vorta/network_status/network_manager.py", line 143, in get_settings
    return get_result(settings.call('GetSettings'))
  File "/app/lib/python3.10/site-packages/vorta/network_status/network_manager.py", line 167, in get_result
    raise DBusException("DBus call failed: {}".format(msg.arguments()))
vorta.network_status.network_manager.DBusException: DBus call failed: ['uid 1000 has no permission to perform this operation']
2023-07-14 16:08:02,488 - vorta.borg.jobs_manager - DEBUG - Add job for site default
2023-07-14 16:08:02,489 - vorta.borg.jobs_manager - DEBUG - Start job on site: default
2023-07-14 16:08:02,496 - vorta.borg.borg_job - INFO - Running command /app/bin/borg --version
2023-07-14 16:08:02,900 - vorta.borg.jobs_manager - DEBUG - Finish job for site: default
2023-07-14 16:08:02,901 - vorta.borg.jobs_manager - DEBUG - No more jobs for site: default
2023-07-14 16:08:02,901 - vorta.scheduler - DEBUG - Refreshing all scheduler timers
2023-07-14 16:08:02,906 - vorta.scheduler - DEBUG - Nothing scheduled for profile 1 because of unset repo.
2023-07-14 16:08:06,092 - vorta.keyring.abc - DEBUG - Only available on macOS
2023-07-14 16:08:06,153 - vorta.keyring.abc - DEBUG - Using VortaKWallet5Keyring
2023-07-14 16:08:09,801 - vorta.keyring.abc - DEBUG - Only available on macOS
2023-07-14 16:08:09,803 - vorta.keyring.abc - DEBUG - Using VortaKWallet5Keyring
2023-07-14 16:08:09,807 - vorta.keyring.kwallet - DEBUG - Retrieved password for repo ssh://p6su75vy@p6su75vy.repo.borgbase.com/./repo
2023-07-14 16:08:15,339 - vorta.keyring.abc - DEBUG - Only available on macOS
2023-07-14 16:08:15,341 - vorta.keyring.abc - DEBUG - Using VortaKWallet5Keyring
2023-07-14 16:08:15,341 - vorta.borg.borg_job - DEBUG - Using VortaKWallet5Keyring keyring to store passwords.
2023-07-14 16:08:15,344 - vorta.keyring.kwallet - DEBUG - Retrieved password for repo ssh://p6su75vy@p6su75vy.repo.borgbase.com/./repo
2023-07-14 16:08:15,349 - vorta.borg.borg_job - INFO - Running command /app/bin/borg info --info --json --log-json ssh://p6su75vy@p6su75vy.repo.borgbase.com/./repo
2023-07-14 16:08:16,562 - vorta.borg.borg_job - WARNING - Remote: p6su75vy@p6su75vy.repo.borgbase.com: Permission denied (publickey,gssapi-keyex,gssapi-with-mic).
2023-07-14 16:08:16,566 - vorta.borg.borg_job - ERROR - Connection closed by remote host. Is borg working on the server?
2023-07-14 16:08:23,932 - vorta.keyring.abc - DEBUG - Only available on macOS
2023-07-14 16:08:23,932 - vorta.keyring.abc - DEBUG - Using VortaDBKeyring
2023-07-14 16:08:25,431 - vorta.keyring.abc - DEBUG - Only available on macOS
2023-07-14 16:08:25,431 - vorta.keyring.abc - DEBUG - Using VortaDBKeyring
2023-07-14 16:08:29,475 - vorta.keyring.abc - DEBUG - Only available on macOS
2023-07-14 16:08:29,475 - vorta.keyring.abc - DEBUG - Using VortaDBKeyring
2023-07-14 16:08:29,475 - vorta.borg.borg_job - DEBUG - Using VortaDBKeyring keyring to store passwords.
2023-07-14 16:08:29,484 - vorta.borg.borg_job - INFO - Running command /app/bin/borg info --info --json --log-json ssh://p6su75vy@p6su75vy.repo.borgbase.com/./repo
2023-07-14 16:08:30,716 - vorta.borg.borg_job - WARNING - Remote: p6su75vy@p6su75vy.repo.borgbase.com: Permission denied (publickey,gssapi-keyex,gssapi-with-mic).
2023-07-14 16:08:30,720 - vorta.borg.borg_job - ERROR - Connection closed by remote host. Is borg working on the server?
2023-07-14 16:08:36,358 - vorta.keyring.abc - DEBUG - Only available on macOS
2023-07-14 16:08:36,359 - vorta.keyring.abc - DEBUG - Using VortaDBKeyring
2023-07-14 16:08:36,359 - vorta.borg.borg_job - DEBUG - Using VortaDBKeyring keyring to store passwords.
2023-07-14 16:08:36,366 - vorta.borg.borg_job - INFO - Running command /app/bin/borg info --info --json --log-json ssh://p6su75vy@p6su75vy.repo.borgbase.com/./repo
2023-07-14 16:08:37,572 - vorta.borg.borg_job - WARNING - Remote: p6su75vy@p6su75vy.repo.borgbase.com: Permission denied (publickey,gssapi-keyex,gssapi-with-mic).
2023-07-14 16:08:37,575 - vorta.borg.borg_job - ERROR - Connection closed by remote host. Is borg working on the server?

**Comment by m3nu** [comment]
This sounds more like a support request and you should write to hello @ borgbase.com

Upon checking, I don't see login errors for your user. Last login was 1h ago.

Since Flatpak is sandboxed, it may not use the correct key right away? We have an FAQ on it [here](https://docs.borgbase.com/faq/#all-connections-to-a-borgbase-repo-fail-with-an-error-immediately).

```
Jul 14 14:20:46 box-eu28.borgbase.com sshd[381142]: Accepted publickey for p6su75vy from 93.67.22.89 port 47226 ssh2: ED25519 SHA256:SdHD/Ya9/QIWTUjb8f0uW955ei/Ii3l58IEuZ869R4k
Jul 14 14:20:46 box-eu28.borgbase.com sshd[381142]: pam_unix(sshd:session): session opened for user p6su75vy(uid=1947) by (uid=0)
```

**Comment by real-yfprojects** [comment]
Yeah I would guess that this is an issue with permissions of an ssh key.

**Comment by andreaippo** [comment]
I could reproduce this again today with the flatpak version of vorta.

My keypair does not have a default name, it's called "personal"

My ~/.ssh/config however mentions the following:

```
Host *.repo.borgbase.com
    IdentityFile ~/.ssh/personal
    AddKeysToAgent  yes
```

I also have my private key's passphrase stored in kwallet under ksshaskpass, and this setup works very well for me as I won't be prompted for my passphrase anymore (my kwallet passphrase is the same as my linux account password, that's why the kwallet is auto-unlocked at logon).

If I do a git pull on a git project associated to my personal key pair, I'm not prompted for my pk's passphrase.

However, vorta flatpak somehow seems unable to get the needed credential.

I have also tried to manually cleaning credentials from the ssh agent via `ssh-add -D` to start fresh.

Tried to refresh backup archives from vorta -> fails

Then added my identity manually via `ssh-add ~/.ssh/personal`, confirmed with `ssh-add -l` that the identity had been added

Tried to refresh backup archives from vorta -> works

So the problem here is the fact that the correct identity doesn't get loaded in the ssh agent, and I wonder why since the ssh config I pasted before works fine for vorta non-flatpak.

Could you guys please check again?

Thanks

**Comment by andreaippo** [comment]
Well I may have an idea of what's going on.

According to:

https://pointieststick.com/2024/04/26/this-week-in-kde-megabytes-and-gigabytes-for-all/

_Implemented support for the org.freedesktop.impl.portal.Secret portal for KWallet, which lets Flatpak apps use it (Nicolas Fella, Frameworks 6.2. Link)_

So it seems that this issue is caused by that.

I'll close this issue for now, as I'm confident things will work out fine once that KWallet update is released.

**Comment by andreaippo** [comment]
Reopening this, as I just tested again with KDE Frameworks 6.2 but the issue persists following the steps to reproduce above.

I dunno if the flatpak app's manifest file should include more permissions to talk to this "Secret Portal":

https://docs.flatpak.org/fr/latest/portal-api-reference.html#gdbus-org.freedesktop.portal.Secret

**Comment by Hofer-Julian** [comment]
You shouldn't need to poke holes in the sandbox in order to talk to portals. To my knowledge that's the whole point of portals. Maybe a KDE person can help here?

**Comment by xalt7x** [comment]
@andreaippo ,
Flatpak works for me since KDE Plasma 6.1 Beta (tested on Fedora 41/Rawhide). Unfortunately, the issue is still reproducible with [your instructions](https://github.com/borgbase/vorta/issues/1753#issuecomment-2063246437).
However, if I run the ksshaskpass script (below) and unlock the keys, the repository is added successfully.
```
#!/bin/sh
if [ -f /usr/bin/ksshaskpass ]; then
export SSH_ASKPASS="/usr/bin/ksshaskpass"
grep -slR "PRIVATE" ~/.ssh/ | xargs ssh-add
fi
```

**Comment by andreaippo** [comment]
Hi @xalt7x , if you're facing the same on gnome, I suppose that this is less of a KDE issue, and more of a vorta (as flatpak) or flatpak2ssh issue, WDYT?

Maybe we could check with another flatpak app needing access to ssh keys, I'm thinking an ssh client for example...
If it works, the vorta flatpak maintainer could take inspiration from there (aka Ctrl C/V 😄)

**Comment by xalt7x** [comment]
Hi @andreaippo
> if you're facing the same on gnome, I suppose that this is less of a KDE issue
I've checked GNOME (on Fedora Silverblue). Somehow it works and shows some native dialog (not `/usr/libexec/openssh/gnome-ssh-askpass` which doesn't even exists on a system at the moment).
![image](https://github.com/borgbase/vorta/assets/44649402/85a47105-6b9d-4823-b2ab-a8157302286a)

**Comment by andreaippo** [comment]
Update after quite some time. I had to move from opensuse tumbleweed to fedora (for other reasons), and when reinstalling the OS I gave vorta flatpak another try. And it works fine, it stored the ssh keys for my repos inside my KWallet without any problem.

**Comment by m3nu** [comment]
Awesome! Glad this is resolved.
