### ISSUE TITLE
UI tests fail on MacOS

### ISSUE THREAD

**Issue by Plastix** [borgbase/vorta#178]
**Describe the bug**
10 of Vorta's UI tests fail by default on MacOS. Am I doing something wrong?

**To Reproduce**
1. Clone `master` on a MacOS machine.
1. Run `pytest`.

**Desktop:**
 - OS: MacOS `10.14.3` and `master`.

**Additional context**
```
❯ pytest
====================================================== test session starts =======================================================
platform darwin -- Python 3.7.2, pytest-4.2.0, py-1.7.0, pluggy-0.8.1 -- /usr/local/opt/python/bin/python3.7
cachedir: .pytest_cache
PyQt5 5.11.3 -- Qt runtime 5.11.2 -- Qt compiled 5.11.2
rootdir: /Users/plastix/Projects/vorta, inifile: setup.cfg
plugins: xdist-1.26.1, qt-3.2.2, mock-1.10.0, forked-1.0.1, faulthandler-1.5.0
collected 17 items                                                                                                               

tests/test_archives.py::test_prune_intervals PASSED
tests/test_archives.py::test_repo_list FAILED
tests/test_archives.py::test_repo_prune FAILED
tests/test_archives.py::test_check FAILED
tests/test_archives.py::test_archive_mount FAILED
tests/test_archives.py::test_archive_extract FAILED
tests/test_borg.py::test_borg_prune FAILED
tests/test_notifications.py::test_linux_background_notifications SKIPPED
tests/test_repo.py::test_repo_add_failures PASSED
tests/test_repo.py::test_repo_add_success FAILED
tests/test_repo.py::test_repo_unlink FAILED
tests/test_repo.py::test_ssh_dialog PASSED
tests/test_repo.py::test_create FAILED
tests/test_schedule.py::test_schedule_tab PASSED
tests/test_scheduler.py::test_scheduler_create_backup FAILED
tests/test_source.py::test_add_folder PASSED
tests/test_utils.py::test_keyring PASSED

============================================================ FAILURES ============================================================
_________________________________________________________ test_repo_list _________________________________________________________
app = <vorta.application.VortaApp object at 0x110d205e8>
qtbot = <pytestqt.qtbot.QtBot object at 0x10b779eb8>
mocker = <pytest_mock.MockFixture object at 0x110c0fc18>
borg_json_output = <function borg_json_output.<locals>._read_json at 0x119ea2488>

    def test_repo_list(app, qtbot, mocker, borg_json_output):
        main = app.main_window
        tab = main.archiveTab
        main.tabWidget.setCurrentIndex(3)
        tab.list_action()
>       assert not tab.checkButton.isEnabled()
E       assert not True
E        +  where True = <built-in method isEnabled of QPushButton object at 0x114418708>()
E        +    where <built-in method isEnabled of QPushButton object at 0x114418708> = <PyQt5.QtWidgets.QPushButton object at 0x114418708>.isEnabled
E        +      where <PyQt5.QtWidgets.QPushButton object at 0x114418708> = <vorta.views.archive_tab.ArchiveTab object at 0x110d8fdc8>.checkButton

tests/test_archives.py:36: AssertionError
________________________________________________________ test_repo_prune _________________________________________________________
app = <vorta.application.VortaApp object at 0x110d225e8>
qtbot = <pytestqt.qtbot.QtBot object at 0x10b779f98>
mocker = <pytest_mock.MockFixture object at 0x110c1f908>
borg_json_output = <function borg_json_output.<locals>._read_json at 0x119ea2488>

    def test_repo_prune(app, qtbot, mocker, borg_json_output):
        main = app.main_window
        tab = main.archiveTab
        main.tabWidget.setCurrentIndex(3)
        tab.populate_from_profile()
        stdout, stderr = borg_json_output('prune')
        popen_result = mocker.MagicMock(stdout=stdout, stderr=stderr, returncode=0)
        mocker.patch.object(vorta.borg.borg_thread, 'Popen', return_value=popen_result)
    
        qtbot.mouseClick(tab.pruneButton, QtCore.Qt.LeftButton)
    
>       qtbot.waitUntil(lambda: main.createProgressText.text().startswith('Refreshing archives done.'), timeout=5000)
E       AssertionError: waitUntil timed out in 5000 miliseconds
E       assert not True
E        +  where True = <function QtBot.waitUntil.<locals>.timed_out at 0x119ea2510>()

tests/test_archives.py:59: AssertionError
___________________________________________________________ test_check ___________________________________________________________
CALL ERROR: Qt exceptions in virtual methods:
________________________________________________________________________________
Traceback (most recent call last):
  File "/Users/plastix/Projects/vorta/src/vorta/views/archive_tab.py", line 147, in check_action
    self._set_status(translate(params['message']))
  File "/Users/plastix/Projects/vorta/src/vorta/i18n/__init__.py", line 64, in translate
    return application.translate(*args, **kwargs)
TypeError: translate(str, str, disambiguation: str = None, n: int = -1): not enough arguments
________________________________________________________________________________

_______________________________________________________ test_archive_mount _______________________________________________________
CALL ERROR: Qt exceptions in virtual methods:
________________________________________________________________________________
Traceback (most recent call last):
  File "/Users/plastix/Projects/vorta/src/vorta/views/archive_tab.py", line 217, in mount_action
    self._set_status(translate(params['message']))
  File "/Users/plastix/Projects/vorta/src/vorta/i18n/__init__.py", line 64, in translate
    return application.translate(*args, **kwargs)
TypeError: translate(str, str, disambiguation: str = None, n: int = -1): not enough arguments
________________________________________________________________________________

______________________________________________________ test_archive_extract ______________________________________________________
CALL ERROR: Qt exceptions in virtual methods:
________________________________________________________________________________
Traceback (most recent call last):
  File "/Users/plastix/Projects/vorta/src/vorta/views/archive_tab.py", line 304, in list_archive_action
    self._set_status(translate(params['message']))
  File "/Users/plastix/Projects/vorta/src/vorta/i18n/__init__.py", line 64, in translate
    return application.translate(*args, **kwargs)
TypeError: translate(str, str, disambiguation: str = None, n: int = -1): not enough arguments
________________________________________________________________________________

________________________________________________________ test_borg_prune _________________________________________________________
app = <vorta.application.VortaApp object at 0x110d225e8>
qtbot = <pytestqt.qtbot.QtBot object at 0x10b7912b0>
mocker = <pytest_mock.MockFixture object at 0x110c1dc50>
borg_json_output = <function borg_json_output.<locals>._read_json at 0x119ea5488>

    def test_borg_prune(app, qtbot, mocker, borg_json_output):
        stdout, stderr = borg_json_output('prune')
        popen_result = mocker.MagicMock(stdout=stdout, stderr=stderr, returncode=0)
        mocker.patch.object(vorta.borg.borg_thread, 'Popen', return_value=popen_result)
    
        params = BorgPruneThread.prepare(vorta.models.BackupProfileModel.select().first())
>       thread = BorgPruneThread(params['cmd'], params, app)
E       KeyError: 'cmd'

tests/test_borg.py:12: KeyError
_____________________________________________________ test_repo_add_success ______________________________________________________
CALL ERROR: Qt exceptions in virtual methods:
________________________________________________________________________________
Traceback (most recent call last):
  File "/Users/plastix/Projects/vorta/src/vorta/views/repo_add_dialog.py", line 71, in run
    self._set_status(translate(params['message']))
  File "/Users//Projects/vorta/src/vorta/i18n/__init__.py", line 64, in translate
    return application.translate(*args, **kwargs)
TypeError: translate(str, str, disambiguation: str = None, n: int = -1): not enough arguments
________________________________________________________________________________

________________________________________________________ test_repo_unlink ________________________________________________________
app = <vorta.application.VortaApp object at 0x110d3c5e8>
qtbot = <pytestqt.qtbot.QtBot object at 0x10b78e588>
monkeypatch = <_pytest.monkeypatch.MonkeyPatch object at 0x108584da0>

    def test_repo_unlink(app, qtbot, monkeypatch):
        monkeypatch.setattr(QMessageBox, "exec_", lambda *args: QMessageBox.Yes)
        main = app.main_window
        tab = main.repoTab
        main.tabWidget.setCurrentIndex(0)
        qtbot.mouseClick(tab.repoRemoveToolbutton, QtCore.Qt.LeftButton)
    
        qtbot.waitUntil(lambda: tab.repoSelector.count() == 4, timeout=5000)
        assert RepoModel.select().count() == 0
    
        qtbot.mouseClick(main.createStartBtn, QtCore.Qt.LeftButton)
>       assert main.createProgressText.text() == 'Add a backup repository first.'
E       AssertionError: assert 'Borg binary was not found.' == 'Add a backup repository first.'
E         - Borg binary was not found.
E         + Add a backup repository first.

tests/test_repo.py:69: AssertionError
__________________________________________________________ test_create ___________________________________________________________
app = <vorta.application.VortaApp object at 0x110d265e8>
borg_json_output = <function borg_json_output.<locals>._read_json at 0x119ea4488>
mocker = <pytest_mock.MockFixture object at 0x110d25470>
qtbot = <pytestqt.qtbot.QtBot object at 0x10b78f780>

    def test_create(app, borg_json_output, mocker, qtbot):
        main = app.main_window
        stdout, stderr = borg_json_output('create')
        popen_result = mocker.MagicMock(stdout=stdout, stderr=stderr, returncode=0)
        mocker.patch.object(vorta.borg.borg_thread, 'Popen', return_value=popen_result)
    
        qtbot.mouseClick(main.createStartBtn, QtCore.Qt.LeftButton)
>       qtbot.waitUntil(lambda: main.createProgressText.text().startswith('Backup finished.'), timeout=3000)
E       AssertionError: waitUntil timed out in 3000 miliseconds
E       assert not True
E        +  where True = <function QtBot.waitUntil.<locals>.timed_out at 0x119ea4620>()

tests/test_repo.py:100: AssertionError
__________________________________________________ test_scheduler_create_backup __________________________________________________
app = <vorta.application.VortaApp object at 0x110d275e8>
qtbot = <pytestqt.qtbot.QtBot object at 0x10b78d940>
mocker = <pytest_mock.MockFixture object at 0x108584da0>
borg_json_output = <function borg_json_output.<locals>._read_json at 0x119ea5488>

    def test_scheduler_create_backup(app, qtbot, mocker, borg_json_output):
        stdout, stderr = borg_json_output('create')
        popen_result = mocker.MagicMock(stdout=stdout, stderr=stderr, returncode=0)
        mocker.patch.object(vorta.borg.borg_thread, 'Popen', return_value=popen_result)
    
        app.scheduler.create_backup(1)
    
>       qtbot.waitUntil(lambda: vorta.models.EventLogModel.select().count() == 2, timeout=5000)
E       AssertionError: waitUntil timed out in 5000 miliseconds
E       assert not True
E        +  where True = <function QtBot.waitUntil.<locals>.timed_out at 0x119ea56a8>()

tests/test_scheduler.py:12: AssertionError
------------------------------------------------------- Captured log call --------------------------------------------------------
scheduler.py               118 ERROR    Conditions for backup not met. Aborting.
scheduler.py               119 ERROR    Borg binary was not found.
======================================== 10 failed, 6 passed, 1 skipped in 59.70 seconds =========================================
```
[log.txt](https://github.com/borgbase/vorta/files/2825678/log.txt)

**Comment by m3nu** [comment]
I think you didn't install the Borg binary. See bottom of your log output:

```
Borg binary was not found.
```

The fat binary (can be downloaded under Releases) has Borg already integrated. If you install Vorta via Pip, you need to install Borg yourself. On macOS you can do that via Homebrew or Pip. The former is slightly easier because you don't need to take care of having the dependencies.

- `$ brew install borgbackup`
- `$ pip install borgbackup`

**Comment by m3nu** [comment]
No silly. I was thinking about adding Borg to the requirements. But then there are so many different ways to install it and users may want to use a special version. So for now it's installed extra, but maybe that's not the best solution.
