### ISSUE TITLE
Crash every time I try a diff between two backups

### ISSUE THREAD

**Issue by tomchiverton** [borgbase/vorta#1789]
### Description

1. open vorta
2. select 'archives' 
3. select last two backups
4. press diff
5. crashes

console output :

### Reproduction

- [X] I tried to reproduce the issue.
- [X] I was able to reproduce the issue.

### OS

Ubuntu 23.04

### Version of Vorta

Vorta 0.8.10 Borg 1.2.4

### What did you install Vorta with?

Homebrew

### Logs

```pytb
2023-08-26 17:16:02,278 - vorta.borg.borg_job - INFO - Running command /usr/bin/borg info --log-json --json falken@ssh.falkensweb.com:/home/falken/borg/laptop::wopr-falken-2023-08-26T16:15:29
2023-08-26 17:16:05,433 - vorta.borg.jobs_manager - DEBUG - Finish job for site: 3
2023-08-26 17:16:05,434 - vorta.borg.jobs_manager - DEBUG - No more jobs for site: 3
2023-08-26 17:16:05,435 - vorta.scheduler - DEBUG - Scheduler for profile 2 is disabled.
2023-08-26 17:16:05,657 - vorta.network_status.network_manager - WARNING - Couldn't load settings for /org/freedesktop/NetworkManager/Settings/30
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/vorta/network_status/network_manager.py", line 53, in get_known_wifis
    settings = self._nm.get_settings(connection_path)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/vorta/network_status/network_manager.py", line 143, in get_settings
    return get_result(settings.call('GetSettings'))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/vorta/network_status/network_manager.py", line 167, in get_result
    raise DBusException("DBus call failed: {}".format(msg.arguments()))
vorta.network_status.network_manager.DBusException: DBus call failed: ['uid 1000 has no permission to perform this operation']
2023-08-26 17:16:08,005 - vorta.keyring.abc - DEBUG - Only available on macOS
2023-08-26 17:16:08,007 - vorta.keyring.abc - DEBUG - Using VortaKWallet5Keyring
2023-08-26 17:16:08,008 - vorta.borg.borg_job - DEBUG - Using VortaKWallet5Keyring keyring to store passwords.
2023-08-26 17:16:08,011 - vorta.borg.borg_job - DEBUG - Password not found in primary keyring. Falling back to VortaDBKeyring.
2023-08-26 17:16:08,031 - vorta.borg.jobs_manager - DEBUG - Add job for site 3
2023-08-26 17:16:08,032 - vorta.borg.jobs_manager - DEBUG - Start job on site: 3
2023-08-26 17:16:08,061 - vorta.borg.borg_job - INFO - Running command /usr/bin/borg diff --info --log-json --json-lines falken@ssh.falkensweb.com:/home/falken/borg/laptop::wopr-falken-2023-08-25T22:28:02 wopr-falken-2023-08-26T16:15:29
2023-08-26 17:16:10,645 - vorta.borg.jobs_manager - DEBUG - Finish job for site: 3
2023-08-26 17:16:10,646 - vorta.borg.jobs_manager - DEBUG - No more jobs for site: 3
2023-08-26 17:16:10,648 - vorta.scheduler - DEBUG - Scheduler for profile 2 is disabled.
2023-08-26 17:16:10,921 - vorta.network_status.network_manager - WARNING - Couldn't load settings for /org/freedesktop/NetworkManager/Settings/30
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/vorta/network_status/network_manager.py", line 53, in get_known_wifis
    settings = self._nm.get_settings(connection_path)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/vorta/network_status/network_manager.py", line 143, in get_settings
    return get_result(settings.call('GetSettings'))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/vorta/network_status/network_manager.py", line 167, in get_result
    raise DBusException("DBus call failed: {}".format(msg.arguments()))
vorta.network_status.network_manager.DBusException: DBus call failed: ['uid 1000 has no permission to perform this operation']
2023-08-26 17:16:11,083 - root - CRITICAL - Uncaught exception, file a report at https://github.com/borgbase/vorta/issues/new/choose
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/vorta/views/diff_result.py", line 50, in run
    parse_diff_json(lines, self.model)
  File "/usr/lib/python3/dist-packages/vorta/views/diff_result.py", line 273, in parse_diff_json
    raise Exception('Unknown change type: {}'.format(change['type']))
Exception: Unknown change type: ctime
QObject: Cannot create children for a parent that is in a different thread.
(Parent is Breeze::WidgetStateEngine(0x1f06a90), parent's thread is QThread(0x15f33b0), current thread is ParseThread(0x29cfb20)
QObject: Cannot create children for a parent that is in a different thread.
(Parent is Breeze::WidgetStateEngine(0x1f06a90), parent's thread is QThread(0x15f33b0), current thread is ParseThread(0x29cfb20)
QObject: Cannot create children for a parent that is in a different thread.
(Parent is Breeze::WidgetStateEngine(0x183bd90), parent's thread is QThread(0x15f33b0), current thread is ParseThread(0x29cfb20)
QObject: Cannot create children for a parent that is in a different thread.
(Parent is Breeze::WidgetStateEngine(0x183bd90), parent's thread is QThread(0x15f33b0), current thread is ParseThread(0x29cfb20)
QObject: Cannot create children for a parent that is in a different thread.
(Parent is Breeze::WidgetStateEngine(0x1f06a90), parent's thread is QThread(0x15f33b0), current thread is ParseThread(0x29cfb20)
QObject::installEventFilter(): Cannot filter events for objects in a different thread.
QObject: Cannot create children for a parent that is in a different thread.
(Parent is Breeze::WidgetStateEngine(0x1f06a90), parent's thread is QThread(0x15f33b0), current thread is ParseThread(0x29cfb20)
QObject: Cannot create children for a parent that is in a different thread.
(Parent is Breeze::WidgetStateEngine(0x1f06a90), parent's thread is QThread(0x15f33b0), current thread is ParseThread(0x29cfb20)
QBackingStore::endPaint() called with active painter; did you forget to destroy it or call QPainter::end() on it?
Segmentation fault
```
```

**Comment by tomchiverton** [comment]
GUI image (GitHub doesn't allow attaching images from FireFox) : https://ibb.co/C6cSHr0

**Comment by real-yfprojects** [comment]
Thank you for reporting, this was already fixed in #1675.

**Comment by tomchiverton** [comment]
What Vorta version contains this fix?
-- 
†øღ

**Comment by jetchirag** [comment]
[v0.8.11](https://github.com/borgbase/vorta/releases/tag/v0.8.11)

**Comment by tomchiverton** [comment]
That was a while ago. Is it winding through Debian/Ubuntu release process still ?

**Comment by real-yfprojects** [comment]
Probably I think there were some issues with the licenses of our icons. There should be an issue about it in this repo. Finding something like that on github mobile is a pain.

**Comment by tomchiverton** [comment]
I looked and could not find one here. The maintainer seems to be ubuntu-devel-discuss@lists.ubuntu.com

I checked https://launchpad.net/ubuntu/+source/vorta and v0.8.12 is available for newer releases. 

I added a bug to back port : https://bugs.launchpad.net/ubuntu/+source/vorta/+bug/2035080
