### ISSUE TITLE
Backup with warnings. Half done.

### ISSUE THREAD

**Issue by coffseducation** [borgbase/vorta#1808]
### Description

Hello.

Vorta backed up, but crashed out twice with:
   Nameerror: name ‘open’ is not defined

It then completed with backup finished with warnings. See logs for details.

1.3TB expected to backup. 750 GB backed up.

### Reproduction

- [X] I tried to reproduce the issue.
- [ ] I was able to reproduce the issue.

### OS

Operating System: Kubuntu 23.04 KDE Plasma Version: 5.27.7 KDE Frameworks Version: 5.109.0 Qt Version: 5.15.8 Kernel Version: 6.2.0-27-generic (64-bit) Graphics Platform: X11 Processors: 8 × Intel® Core™ i7-7820HQ CPU @ 2.90GHz Memory: 31.2 GiB of RAM Graphics Processor: Quadro M1200/PCIe/SSE2 Manufacturer: Dell Inc. Product Name: Precision 5520

### Version of Vorta

0.8.10

### What did you install Vorta with?

Distribution package

### Version of Borg

1.2.4

### Logs

```pytb
2023-08-15 20:29:05,091 - vorta.i18n - DEBUG - Loading translation failed for ['en-AU', 'en-Latn-AU'].
2023-08-15 20:29:05,388 - root - DEBUG - Expected error parsing file in .ssh: known_hosts.old (You can safely ignore this)
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/vorta/utils.py", line 195, in get_private_keys
    parsed_key = key_format.from_private_key_file(key_file)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/paramiko/pkey.py", line 249, in from_private_key_file
    key = cls(filename=filename, password=password)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/paramiko/rsakey.py", line 64, in __init__
    self._from_private_key_file(filename, password)
  File "/usr/lib/python3/dist-packages/paramiko/rsakey.py", line 194, in _from_private_key_file
    data = self._read_private_key_file("RSA", filename, password)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/paramiko/pkey.py", line 322, in _read_private_key_file
    data = self._read_private_key(tag, f, password)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/paramiko/pkey.py", line 340, in _read_private_key
    raise SSHException("not a valid {} private key file".format(tag))
paramiko.ssh_exception.SSHException: not a valid RSA private key file
2023-08-15 20:29:05,392 - root - DEBUG - Expected error parsing file in .ssh: known_hosts.old (You can safely ignore this)
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/vorta/utils.py", line 195, in get_private_keys
    parsed_key = key_format.from_private_key_file(key_file)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/paramiko/pkey.py", line 249, in from_private_key_file
    key = cls(filename=filename, password=password)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/paramiko/ecdsakey.py", line 126, in __init__
    self._from_private_key_file(filename, password)
  File "/usr/lib/python3/dist-packages/paramiko/ecdsakey.py", line 277, in _from_private_key_file
    data = self._read_private_key_file("EC", filename, password)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/paramiko/pkey.py", line 322, in _read_private_key_file
    data = self._read_private_key(tag, f, password)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/paramiko/pkey.py", line 340, in _read_private_key
    raise SSHException("not a valid {} private key file".format(tag))
paramiko.ssh_exception.SSHException: not a valid EC private key file
2023-08-15 20:29:05,395 - root - DEBUG - Expected error parsing file in .ssh: known_hosts.old (You can safely ignore this)
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/vorta/utils.py", line 195, in get_private_keys
    parsed_key = key_format.from_private_key_file(key_file)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/paramiko/pkey.py", line 249, in from_private_key_file
    key = cls(filename=filename, password=password)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/paramiko/ed25519key.py", line 58, in __init__
    pkformat, data = self._read_private_key("OPENSSH", f)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/paramiko/pkey.py", line 340, in _read_private_key
    raise SSHException("not a valid {} private key file".format(tag))
paramiko.ssh_exception.SSHException: not a valid OPENSSH private key file
2023-08-15 20:29:05,397 - root - DEBUG - Expected error parsing file in .ssh: known_hosts (You can safely ignore this)
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/vorta/utils.py", line 195, in get_private_keys
    parsed_key = key_format.from_private_key_file(key_file)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/paramiko/pkey.py", line 249, in from_private_key_file
    key = cls(filename=filename, password=password)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/paramiko/rsakey.py", line 64, in __init__
    self._from_private_key_file(filename, password)
  File "/usr/lib/python3/dist-packages/paramiko/rsakey.py", line 194, in _from_private_key_file
    data = self._read_private_key_file("RSA", filename, password)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/paramiko/pkey.py", line 322, in _read_private_key_file
    data = self._read_private_key(tag, f, password)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/paramiko/pkey.py", line 340, in _read_private_key
    raise SSHException("not a valid {} private key file".format(tag))
paramiko.ssh_exception.SSHException: not a valid RSA private key file
2023-08-15 20:29:05,399 - root - DEBUG - Expected error parsing file in .ssh: known_hosts (You can safely ignore this)
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/vorta/utils.py", line 195, in get_private_keys
    parsed_key = key_format.from_private_key_file(key_file)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/paramiko/pkey.py", line 249, in from_private_key_file
    key = cls(filename=filename, password=password)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/paramiko/ecdsakey.py", line 126, in __init__
    self._from_private_key_file(filename, password)
  File "/usr/lib/python3/dist-packages/paramiko/ecdsakey.py", line 277, in _from_private_key_file
    data = self._read_private_key_file("EC", filename, password)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/paramiko/pkey.py", line 322, in _read_private_key_file
    data = self._read_private_key(tag, f, password)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/paramiko/pkey.py", line 340, in _read_private_key
    raise SSHException("not a valid {} private key file".format(tag))
paramiko.ssh_exception.SSHException: not a valid EC private key file
2023-08-15 20:29:05,401 - root - DEBUG - Expected error parsing file in .ssh: known_hosts (You can safely ignore this)
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/vorta/utils.py", line 195, in get_private_keys
    parsed_key = key_format.from_private_key_file(key_file)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/paramiko/pkey.py", line 249, in from_private_key_file
    key = cls(filename=filename, password=password)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/paramiko/ed25519key.py", line 58, in __init__
    pkformat, data = self._read_private_key("OPENSSH", f)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/paramiko/pkey.py", line 340, in _read_private_key
    raise SSHException("not a valid {} private key file".format(tag))
paramiko.ssh_exception.SSHException: not a valid OPENSSH private key file
2023-08-15 20:29:05,841 - root - INFO - Using NetworkManagerMonitor NetworkStatusMonitor implementation.
2023-08-15 20:29:06,124 - vorta.borg.jobs_manager - DEBUG - Add job for site default
2023-08-15 20:29:06,126 - vorta.borg.jobs_manager - DEBUG - Start job on site: default
2023-08-15 20:29:06,135 - vorta.borg.borg_job - INFO - Running command /usr/bin/borg --version
2023-08-15 20:29:07,717 - vorta.borg.jobs_manager - DEBUG - Finish job for site: default
2023-08-15 20:29:07,718 - vorta.scheduler - DEBUG - Refreshing all scheduler timers
2023-08-15 20:29:07,718 - vorta.borg.jobs_manager - DEBUG - No more jobs for site: default
2023-08-15 20:29:07,724 - vorta.scheduler - DEBUG - Nothing scheduled for profile 1 because of unset repo.
2023-08-15 20:44:05,092 - vorta.scheduler - DEBUG - Refreshing all scheduler timers
2023-08-15 20:44:05,098 - vorta.scheduler - DEBUG - Nothing scheduled for profile 1 because of unset repo.
2023-08-15 20:59:05,189 - vorta.scheduler - DEBUG - Refreshing all scheduler timers
2023-08-15 20:59:05,196 - vorta.scheduler - DEBUG - Nothing scheduled for profile 1 because of unset repo.
2023-08-15 21:14:05,189 - vorta.scheduler - DEBUG - Refreshing all scheduler timers
2023-08-15 21:14:05,198 - vorta.scheduler - DEBUG - Nothing scheduled for profile 1 because of unset repo.
2023-08-15 21:29:05,191 - vorta.scheduler - DEBUG - Refreshing all scheduler timers
2023-08-15 21:29:05,196 - vorta.scheduler - DEBUG - Nothing scheduled for profile 1 because of unset repo.
2023-08-15 21:44:05,093 - vorta.scheduler - DEBUG - Refreshing all scheduler timers
2023-08-15 21:44:05,098 - vorta.scheduler - DEBUG - Nothing scheduled for profile 1 because of unset repo.
2023-08-15 21:59:05,093 - vorta.scheduler - DEBUG - Refreshing all scheduler timers
2023-08-15 21:59:05,102 - vorta.scheduler - DEBUG - Nothing scheduled for profile 1 because of unset repo.
2023-08-15 22:14:05,129 - vorta.scheduler - DEBUG - Refreshing all scheduler timers
2023-08-15 22:14:05,135 - vorta.scheduler - DEBUG - Nothing scheduled for profile 1 because of unset repo.
2023-08-15 22:29:05,189 - vorta.scheduler - DEBUG - Refreshing all scheduler timers
2023-08-15 22:29:05,194 - vorta.scheduler - DEBUG - Nothing scheduled for profile 1 because of unset repo.
2023-08-15 22:44:05,135 - vorta.scheduler - DEBUG - Refreshing all scheduler timers
2023-08-15 22:44:05,143 - vorta.scheduler - DEBUG - Nothing scheduled for profile 1 because of unset repo.
2023-08-15 22:59:05,129 - vorta.scheduler - DEBUG - Refreshing all scheduler timers
2023-08-15 22:59:05,136 - vorta.scheduler - DEBUG - Nothing scheduled for profile 1 because of unset repo.
2023-08-15 23:14:05,093 - vorta.scheduler - DEBUG - Refreshing all scheduler timers
2023-08-15 23:14:05,099 - vorta.scheduler - DEBUG - Nothing scheduled for profile 1 because of unset repo.
2023-08-15 23:29:05,091 - vorta.scheduler - DEBUG - Refreshing all scheduler timers
2023-08-15 23:29:05,096 - vorta.scheduler - DEBUG - Nothing scheduled for profile 1 because of unset repo.
2023-08-15 23:44:05,091 - vorta.scheduler - DEBUG - Refreshing all scheduler timers
2023-08-15 23:44:05,097 - vorta.scheduler - DEBUG - Nothing scheduled for profile 1 because of unset repo.
2023-08-15 23:57:12,231 - vorta.borg.borg_job - DEBUG - Cancel job on site default
2023-08-15 23:57:12,232 - vorta.borg.jobs_manager - INFO - Finished cancelling all jobs
```

**Comment by m3nu** [comment]
The version you are using is pretty old. Does the issue still happen with the current master branch?

**Comment by coffseducation** [comment]
I now tried the flatpak:
Vorta version 0.8.12
Borg version 1.2.4

[DEFAULT] ERROR: Failed to create/acquire the lock /media/user/vorta/vorta/lock (timeout).

2023-09-06 20:28:34,126 - vorta.i18n - DEBUG - Loading translation failed for ['en-AU', 'en-Latn-AU'].
2023-09-06 20:28:34,132 - vorta.scheduler - WARNING - Failed to connect to DBUS interface to detect sleep/resume events
2023-09-06 20:28:34,821 - root - INFO - Using NetworkManagerMonitor NetworkStatusMonitor implementation.
2023-09-06 20:28:35,035 - vorta.borg.jobs_manager - DEBUG - Add job for site default
2023-09-06 20:28:35,036 - vorta.borg.jobs_manager - DEBUG - Start job on site: default
2023-09-06 20:28:35,042 - vorta.borg.borg_job - INFO - Running command /app/bin/borg --version
2023-09-06 20:28:35,653 - vorta.borg.jobs_manager - DEBUG - Finish job for site: default
2023-09-06 20:28:35,653 - vorta.scheduler - DEBUG - Refreshing all scheduler timers
2023-09-06 20:28:35,654 - vorta.borg.jobs_manager - DEBUG - No more jobs for site: default
2023-09-06 20:28:35,662 - vorta.scheduler - DEBUG - Nothing scheduled for profile 1 because of unset repo.
2023-09-06 20:29:59,105 - vorta.keyring.abc - DEBUG - Only available on macOS
2023-09-06 20:29:59,167 - vorta.keyring.abc - DEBUG - Using VortaKWallet5Keyring
2023-09-06 20:30:15,831 - vorta.keyring.abc - DEBUG - Only available on macOS
2023-09-06 20:30:15,832 - vorta.keyring.abc - DEBUG - Using VortaKWallet5Keyring
2023-09-06 20:30:15,836 - vorta.keyring.kwallet - DEBUG - Retrieved password for repo /media/anarcho/Vorta/Vorta
2023-09-06 20:30:27,311 - vorta.keyring.abc - DEBUG - Only available on macOS
2023-09-06 20:30:27,313 - vorta.keyring.abc - DEBUG - Using VortaKWallet5Keyring
2023-09-06 20:30:27,313 - vorta.borg.borg_job - DEBUG - Using VortaKWallet5Keyring keyring to store passwords.
2023-09-06 20:30:27,316 - vorta.keyring.kwallet - DEBUG - Retrieved password for repo /media/anarcho/Vorta/Vorta
2023-09-06 20:30:27,326 - vorta.borg.borg_job - INFO - Running command /app/bin/borg info --info --json --log-json /media/anarcho/Vorta/Vorta
2023-09-06 20:30:29,364 - vorta.borg.borg_job - INFO - Synchronizing chunks cache...
2023-09-06 20:30:29,368 - vorta.borg.borg_job - INFO - Archives: 4, w/ cached Idx: 0, w/ outdated Idx: 0, w/o cached Idx: 4.
2023-09-06 20:30:29,416 - vorta.borg.borg_job - INFO - Fetching and building archive index for LuNoHo-default-2023-09-05T20:58:59.checkpoint ...
2023-09-06 20:30:30,194 - vorta.borg.borg_job - INFO - Merging into master chunks index ...
2023-09-06 20:30:30,230 - vorta.borg.borg_job - INFO - Fetching and building archive index for LuNoHo-default-2023-09-05T22:23:40.checkpoint ...
2023-09-06 20:30:32,511 - vorta.borg.borg_job - INFO - Merging into master chunks index ...
2023-09-06 20:30:32,629 - vorta.borg.borg_job - INFO - Fetching and building archive index for LuNoHo-default-2023-09-06T00:26:55 ...
2023-09-06 20:30:35,585 - vorta.borg.borg_job - INFO - Merging into master chunks index ...
2023-09-06 20:30:35,678 - vorta.borg.borg_job - INFO - Fetching and building archive index for LuNoHo-default-2023-09-06T09:54:39 ...
2023-09-06 20:30:37,889 - vorta.borg.borg_job - INFO - Merging into master chunks index ...
2023-09-06 20:30:37,951 - vorta.borg.borg_job - INFO - Done.
2023-09-06 20:30:38,271 - vorta.keyring.kwallet - DEBUG - Saved password for repo /media/anarcho/Vorta/Vorta
2023-09-06 20:30:38,488 - vorta.keyring.abc - DEBUG - Only available on macOS
2023-09-06 20:30:38,489 - vorta.keyring.abc - DEBUG - Using VortaKWallet5Keyring
2023-09-06 20:30:38,489 - vorta.borg.borg_job - DEBUG - Using VortaKWallet5Keyring keyring to store passwords.
2023-09-06 20:30:38,492 - vorta.keyring.kwallet - DEBUG - Retrieved password for repo /media/anarcho/Vorta/Vorta
2023-09-06 20:30:38,500 - vorta.borg.jobs_manager - DEBUG - Add job for site 1
2023-09-06 20:30:38,500 - vorta.borg.jobs_manager - DEBUG - Start job on site: 1
2023-09-06 20:30:38,505 - vorta.borg.borg_job - INFO - Running command /app/bin/borg list --info --log-json --json /media/anarcho/Vorta/Vorta
2023-09-06 20:30:39,222 - vorta.borg.jobs_manager - DEBUG - Finish job for site: 1
2023-09-06 20:30:39,222 - vorta.borg.jobs_manager - DEBUG - No more jobs for site: 1
2023-09-06 20:30:39,224 - vorta.scheduler - DEBUG - Scheduler for profile 1 is disabled.
2023-09-06 20:31:19,153 - vorta.views.source_tab - DEBUG - Added item number 0 from 1
2023-09-06 20:31:19,153 - vorta.views.source_tab - DEBUG - Updating source in row 0.
2023-09-06 20:31:19,156 - vorta.views.source_tab - DEBUG - Updated info for previously added item.
2023-09-06 20:31:24,785 - vorta.keyring.abc - DEBUG - Only available on macOS
2023-09-06 20:31:24,786 - vorta.keyring.abc - DEBUG - Using VortaKWallet5Keyring
2023-09-06 20:31:24,786 - vorta.borg.borg_job - DEBUG - Using VortaKWallet5Keyring keyring to store passwords.
2023-09-06 20:31:24,789 - vorta.keyring.kwallet - DEBUG - Retrieved password for repo /media/anarcho/Vorta/Vorta
2023-09-06 20:31:24,801 - vorta.borg.jobs_manager - DEBUG - Add job for site 1
2023-09-06 20:31:24,802 - vorta.borg.jobs_manager - DEBUG - Start job on site: 1
2023-09-06 20:31:24,827 - vorta.borg.borg_job - INFO - Running command /app/bin/borg create --list --progress --info --log-json --json --filter=AM -C lz4 /media/anarcho/Vorta/Vorta::LuNoHo-2023-09-06-203124 /home/anarcho
2023-09-06 20:31:26,231 - vorta.borg.borg_job - ERROR - Failed to create/acquire the lock /media/anarcho/Vorta/Vorta/lock (timeout).
2023-09-06 20:31:26,372 - vorta.borg.jobs_manager - DEBUG - Finish job for site: 1
2023-09-06 20:31:26,372 - vorta.borg.jobs_manager - DEBUG - No more jobs for site: 1
2023-09-06 20:31:26,375 - vorta.scheduler - DEBUG - Scheduler for profile 1 is disabled.
2023-09-06 20:32:15,777 - vorta.keyring.abc - DEBUG - Only available on macOS
2023-09-06 20:32:15,779 - vorta.keyring.abc - DEBUG - Using VortaKWallet5Keyring
2023-09-06 20:32:15,779 - vorta.borg.borg_job - DEBUG - Using VortaKWallet5Keyring keyring to store passwords.
2023-09-06 20:32:15,781 - vorta.keyring.kwallet - DEBUG - Retrieved password for repo /media/anarcho/Vorta/Vorta
2023-09-06 20:32:15,791 - vorta.borg.jobs_manager - DEBUG - Add job for site 1
2023-09-06 20:32:15,792 - vorta.borg.jobs_manager - DEBUG - Start job on site: 1
2023-09-06 20:32:15,807 - vorta.borg.borg_job - INFO - Running command /app/bin/borg create --list --progress --info --log-json --json --filter=AM -C lz4 /media/anarcho/Vorta/Vorta::LuNoHo-2023-09-06-203215 /home/anarcho
2023-09-06 20:32:17,213 - vorta.borg.borg_job - ERROR - Failed to create/acquire the lock /media/anarcho/Vorta/Vorta/lock (timeout).
2023-09-06 20:32:17,362 - vorta.borg.jobs_manager - DEBUG - Finish job for site: 1
2023-09-06 20:32:17,363 - vorta.borg.jobs_manager - DEBUG - No more jobs for site: 1
2023-09-06 20:32:17,364 - vorta.scheduler - DEBUG - Scheduler for profile 1 is disabled.

**Comment by real-yfprojects** [comment]
Additionally the logs you provided do not show the error message you were reporting.

**Comment by coffseducation** [comment]
Ok, after excluding a directory it runs now without errors!
Will there be another deb package? It looks prettier!  😁

Thanks for the fantastic software and support!
Closing

**Comment by real-yfprojects** [comment]
> Will there be another deb package?

We don't manage the debian package directly. The debian packages are maintained by @sten0.

**Comment by sten0** [comment]
yfprojects ***@***.***> writes:

>> Will there be another deb package?
>
> We don't manage the debian package directly. The debian packages are maintained by @sten0.
>

@coffseducation

As a Kubuntu user, you'll need to ask someone in Kubuntu (or Ubuntu) to
import a newer release from Debian, and/or to backport it to whatever
Kubuntu release you're using.  Currently 0.8.12 is available in Debian
sid/unstable, as well as testing/trixie, and 0.9.0 (which is actually a
prelease) is in experimental.

Alternatively, anyone may download the Debian "source package" (which is
a dsc file, an orig.tar, and a debian.tar), add the Ubuntu-suffix with
their invocation of "dch", and then upload the package to Launchpad's
PPA building system.  I'm pretty sure that I've also provided
instructions for how to do this in another Vorta issue, if you want to
do it yourself.  I think Samuel participated in that issue, but it was a
long time ago.
