### ISSUE TITLE
Vorta trying to fast after resume

### ISSUE THREAD

**Issue by felixoi** [borgbase/vorta#1815]
### Description

After waking up from suspension vorta is instantly trying to backup, as it needs to due to my configured schedule.

1. Only connect your computer via WiFi, also allow Vorta to backup over this WiFi
2. Set the schedule to backup every two minutes
3. Put your computer in suspension
4. Wait 3 minutes
5. Wake the computer up again
6. See the error noticiations

### Reproduction

- [X] I tried to reproduce the issue.
- [ ] I was able to reproduce the issue.

### OS

Manjaro 23.0.0, Gnome 44.4

### Version of Vorta

0.8.12

### What did you install Vorta with?

Distribution package

### Version of Borg

1.2.4

### Logs

```pytb
2023-09-07 22:09:45,073 - vorta.scheduler - DEBUG - Got login suspend/resume notification
2023-09-07 22:09:45,073 - vorta.scheduler - DEBUG - Refreshing all scheduler timers
2023-09-07 22:09:45,076 - vorta.scheduler - INFO - Setting timer for profile 1
2023-09-07 22:09:45,077 - vorta.scheduler - DEBUG - Catching up by running job for Default (1)
2023-09-07 22:09:45,079 - vorta.scheduler - INFO - Starting background backup for Default
2023-09-07 22:09:45,080 - vorta.notifications - DEBUG - success notifications suppressed
2023-09-07 22:09:45,080 - vorta.keyring.abc - DEBUG - Only available on macOS
2023-09-07 22:09:45,082 - asyncio - DEBUG - Using selector: EpollSelector
2023-09-07 22:09:45,086 - vorta.keyring.abc - DEBUG - Using VortaSecretStorageKeyring
2023-09-07 22:09:45,086 - vorta.borg.borg_job - DEBUG - Using VortaSecretStorageKeyring keyring to store passwords.
2023-09-07 22:09:45,090 - asyncio - DEBUG - Using selector: EpollSelector
2023-09-07 22:09:45,098 - vorta.keyring.secretstorage - DEBUG - Found 1 passwords matching repo URL.
2023-09-07 22:09:45,103 - vorta.keyring.secretstorage - DEBUG - Retrieved password for repo ssh://REDACTED@REDACTED.com/./repo
2023-09-07 22:09:45,840 - vorta.network_status.network_manager - ERROR - Failed to get currently connected WiFi network, assuming none
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/vorta/network_status/network_manager.py", line 33, in get_current_wifi
    active_connection = self._nm.get_active_connection_info(active_connection_path)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/vorta/network_status/network_manager.py", line 133, in get_active_connection_info
    connection=read_dbus_property(active_connection, 'Connection'),
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/vorta/network_status/network_manager.py", line 160, in read_dbus_property
    return get_result(msg)
           ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/vorta/network_status/network_manager.py", line 167, in get_result
    raise DBusException("DBus call failed: {}".format(msg.arguments()))
vorta.network_status.network_manager.DBusException: DBus call failed: ['Object does not exist at path “/”']
```
```

**Comment by real-yfprojects** [comment]
Would this be fixed if Vorta waited a few minutes before refreshing its timers?

**Comment by felixoi** [comment]
If not refreshing the timers means that no backup is being triggered, then yes. Even a couple of seconds should be enough.

**Comment by ctheune** [comment]
Happens to me, too. I'd be willing to dive into this and fix it properly at the integration level - as it's also noted as a good first issue.

**Comment by ctheune** [comment]
Ah, [#2176](https://github.com/borgbase/vorta/pull/2176) is already working on this and almost done. I'll hold my horses then.

**Comment by ctheune** [comment]
I accidentally referenced 2251 in an earlier comment that I deleted, not sure whether GH will remove that ... -_-

**Comment by adityakrmishra** [comment]
Hi @m3nu, I saw this was linked in the GSoC 2026 student thread yesterday! I noticed there was previous work done on this in PR #2176 and PR #2408 (which looks like a Mac-specific implementation).

Is there still an open angle on this issue that needs to be solved (perhaps for Linux/Windows network state checking)? If so, I have my local development environment fully set up and would love to tackle the remaining implementation!

**Comment by Siddharth-lal-13** [comment]
Hi @m3nu , I spent some time tracing the scheduler flow around #1815 and wanted to share what I found.

From the logs and the scheduler code, it looks like the behavior comes from how catch-up backups are triggered after `reload_all_timers()`.

The relevant execution path appears to be:

```
loginSuspendNotify()
    → reload_all_timers()
        → set_timer_for_profile()
            → if next_time <= now
                → catch-up logic
                → create_backup()
```

Inside `set_timer_for_profile()` the catch-up condition is:

```
if next_time <= dt.now():
    if profile.schedule_make_up_missed and (self._net_up or not needs_network):
        self.create_backup(profile_id)
```

So whenever timers are reloaded and a scheduled run was missed (for example during suspend), the scheduler immediately starts a backup.

The issue described in #1815 seems to occur because this happens **immediately after resume**, when services like NetworkManager / DBus may not yet be fully ready. This matches the error reported in the issue where the network status module fails with a DBus error right after wake.

I tested the scheduler flow locally and confirmed that `reload_all_timers()` directly triggers the catch-up path when the last scheduled run was missed.

A possible approach might be to delay the execution of the catch-up backup slightly (for example scheduling it via `QTimer.singleShot(...)`) so the system has time to restore network state after resume.

Something like:

```
QtCore.QTimer.singleShot(30000, lambda: self.create_backup(profile_id))
```

instead of running the backup immediately when the catch-up condition is detected.

This would keep the current scheduling logic intact while avoiding the race condition with network services after resume.

Before implementing a patch, I wanted to check if this aligns with the intended scheduler behavior or if there is a preferred approach for handling missed backups after system resume.

**Comment by m3nu** [comment]
You could outline the changes you would make before writing code.

**Comment by Siddharth-lal-13** [comment]
> You could outline the changes you would make before writing code.

Thanks for the suggestion. Based on the scheduler flow I traced, here is the change I am considering.

Currently the sequence is:

loginSuspendNotify()
→ reload_all_timers()
→ set_timer_for_profile()
→ if next_time <= now → run catch-up backup immediately

This means that right after a resume event, the scheduler may trigger the catch-up backup instantly. At that moment some system services (NetworkManager / DBus) might not yet be fully ready, which matches the behavior reported in #1815.

My idea is to keep the existing catch-up logic intact, but introduce a small delay before executing the backup when the catch-up condition is triggered immediately after resume.

Concretely, inside the block where `next_time <= dt.now()` and `schedule_make_up_missed` is true, instead of directly calling `create_backup(profile_id)`, the scheduler could schedule the backup via a short `QTimer.singleShot()` delay (for example 20–30 seconds).

The flow would then become:

resume event
→ reload_all_timers()
→ catch-up condition detected
→ schedule delayed backup via QTimer
→ create_backup() executes after delay

This should give the system enough time to restore network state while preserving the intended catch-up behavior.

If this approach makes sense, I can refine the implementation further and continue testing the behavior around suspend/resume. I am currently testing in WSL to observe the behavior during suspend and resume events.

**Comment by rzeigler** [comment]
> This means that right after a resume event, the scheduler may trigger the catch-up backup instantly. At that moment some system services (NetworkManager / DBus) might not yet be fully ready, which matches the behavior reported in [#1815](https://github.com/borgbase/vorta/issues/1815).
> 

I don't think this is correct. NetworkManager  is on a system system bus that will be available before the user can even login most times and its state reporting is generally accurate. Its possible this is a quirk on different implementations but I'm reasonably certain that nm reports network as disconnected before the sleep happens.

**Comment by Siddharth-lal-13** [comment]
> I don't think this is correct. NetworkManager is on a system system bus that will be available before the user can even login most times and its state reporting is generally accurate. Its possible this is a quirk on different implementations but I'm reasonably certain that nm reports network as disconnected before the sleep happens.

Hey! Thanks for the clarification.

Looking at the scheduler logic again, I think the issue may actually come from how missed runs are interpreted after a suspend/resume cycle.

Currently `set_timer_for_profile()` checks:

```
if next_time <= dt.now():
```

If this condition is true and `schedule_make_up_missed` is enabled, the scheduler immediately runs the catch-up backup.

However, if the system was suspended longer than the configured interval, this condition will always be true after resume. In that case the scheduler interprets the sleep period as a missed run and triggers a backup immediately.

Example scenario:

```
backup interval: 2 minutes
last backup: 15:00
system sleeps at 15:01
system resumes at 15:30
```

After resume:

```
next_time = 15:02
now = 15:30
→ catch-up triggered immediately
```

This suggests that the scheduler currently treats suspend time the same as normal runtime.

One possible approach could be to detect when the scheduler reload is triggered by a suspend/resume event and skip the immediate catch-up in that case, instead recalculating the next scheduled run from the current time.

Would adjusting the catch-up logic for suspend/resume events be closer to the intended behavior?

**Comment by fain182** [comment]
I can confirm this is still happening on current Vorta with the merged fix from #2176 in place. Here's a fresh trace from today (2026-04-25), Fedora 44, Vorta installed via Flatpak, remote BorgBase repo over SSH:

```
11:16:50,718 - vorta.scheduler - DEBUG - Got login suspend/resume notification
11:16:50,721 - vorta.scheduler - DEBUG - Catching up by running job for Default (1)
11:16:50,722 - vorta.scheduler - INFO  - Starting background backup for Default
11:16:50,809 - vorta.network_status.network_manager - ERROR - Failed to get currently connected WiFi network, assuming none
Traceback (most recent call last):
  File ".../vorta/network_status/network_manager.py", line 35, in get_current_wifi
    active_connection = self._nm.get_active_connection_info(active_connection_path)
  ...
vorta.network_status.network_manager.DBusException: DBus call failed: ['Object does not exist at path "/"']
11:16:50,813 - vorta.scheduler - INFO  - Preparation for backup successful.
11:16:51,170 - vorta.borg.borg_job - WARNING - Remote: ssh: Could not resolve hostname shery5b8.repo.borgbase.com: Temporary failure in name resolution
11:16:51,172 - vorta.borg.borg_job - ERROR   - Connection closed by remote host. Is borg working on the server?
```

**Root cause of why #2176 doesn't catch this:** in `scheduler.py:loginSuspendNotify` we re-fetch `self._net_up = self.net_status.is_network_active()` only **3 ms** after the resume signal. At that moment NetworkManager already reports a connection as "active", so `is_network_active()` returns `True` and the catch-up guard `(self._net_up or not needs_network)` passes. But the connection isn't actually usable yet — the DBus traceback above shows `ActiveConnection.path == "/"` (i.e. the object doesn't really exist), and seconds later DNS still can't resolve. Linking network readiness to `is_network_active()` alone is not enough on resume.

**Second bug visible in the same trace** — Vorta fires the failing backup **twice** before pausing:

```
11:16:51,172  ERROR - Connection closed by remote host       ← first attempt fails
11:16:51,297  INFO  - Setting timer for profile 1
11:16:51,298  DEBUG - Catching up by running job for Default (1)   ← fires again immediately
11:16:51,316  INFO  - Preparation for backup successful.
11:16:51,384  DEBUG - Paused 1 until 2026-04-25 12:16:51     ← pause finally kicks in
11:16:51,497  ERROR - Connection closed by remote host       ← second attempt fails
```

It looks like a race between `backup_finished_event` (connected to `set_timer_for_profile` directly at `scheduler.py:65`, which re-evaluates the catch-up branch) and `notify()` which is the one that actually calls `pause()`. The first signal handler runs before `notify()` has a chance to set the pause, so the make-up branch fires a second time.

**Comment by fain182** [comment]
I think  #2176 fixed this
