### ISSUE TITLE
Vorta window closes when comparing 2 archives

### ISSUE THREAD

**Issue by sebalips** [borgbase/vorta#1827]
### Description

Vorta crashes when comparing 2 archives. This is reproduceable. 

What I did: 
1. create a new archive without encription (don't know if this is important)
2. create an archive
3. after some time / changes to filesystem create a 2nd archive
4. compare this 2 archives
5. after compare is complete the vorta window closes without any error message

Running vorta from the terminal gives following messages:
```
2023-10-07 12:18:21,676 - vorta.borg.borg_job - INFO - Running command /usr/bin/borg diff --info --log-json --json-lines /media/seb/Maxtor4TB/Backup/Vorta/Test::dell-lmde-2023-10-07-113008 dell-lmde-2023-10-07-120924
2023-10-07 12:18:57,411 - vorta.borg.jobs_manager - DEBUG - Finish job for site: 2
2023-10-07 12:18:57,411 - vorta.borg.jobs_manager - DEBUG - No more jobs for site: 2
2023-10-07 12:18:57,414 - vorta.scheduler - DEBUG - Scheduler for profile 1 is disabled.
2023-10-07 12:18:57,490 - root - CRITICAL - Uncaught exception, file a report at https://github.com/borgbase/vorta/issues/new/choose
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/vorta/views/diff_result.py", line 50, in run
    parse_diff_json(lines, self.model)
  File "/usr/lib/python3/dist-packages/vorta/views/diff_result.py", line 273, in parse_diff_json
    raise Exception('Unknown change type: {}'.format(change['type']))
Exception: Unknown change type: ctime
QObject: Cannot create children for a parent that is in a different thread.
(Parent is Breeze::WidgetStateEngine(0x1808f20), parent's thread is QThread(0x154a1f0), current thread is ParseThread(0x27058d0)
QObject: Cannot create children for a parent that is in a different thread.
(Parent is Breeze::WidgetStateEngine(0x1808f20), parent's thread is QThread(0x154a1f0), current thread is ParseThread(0x27058d0)
QObject: Cannot create children for a parent that is in a different thread.
(Parent is Breeze::WidgetStateEngine(0x17cb4c0), parent's thread is QThread(0x154a1f0), current thread is ParseThread(0x27058d0)
QObject: Cannot create children for a parent that is in a different thread.
(Parent is Breeze::WidgetStateEngine(0x17cb4c0), parent's thread is QThread(0x154a1f0), current thread is ParseThread(0x27058d0)
QObject: Cannot create children for a parent that is in a different thread.
(Parent is Breeze::WidgetStateEngine(0x1808f20), parent's thread is QThread(0x154a1f0), current thread is ParseThread(0x27058d0)
QObject::installEventFilter(): Cannot filter events for objects in a different thread.
QObject: Cannot create children for a parent that is in a different thread.
(Parent is Breeze::WidgetStateEngine(0x1808f20), parent's thread is QThread(0x154a1f0), current thread is ParseThread(0x27058d0)
QObject: Cannot create children for a parent that is in a different thread.
(Parent is Breeze::WidgetStateEngine(0x1808f20), parent's thread is QThread(0x154a1f0), current thread is ParseThread(0x27058d0)
corrupted size vs. prev_size
```

### Reproduction

- [X] I tried to reproduce the issue.
- [X] I was able to reproduce the issue.

### OS

Linux Mint LMDE 6, KDE X11

### Version of Vorta

0.8.10

### What did you install Vorta with?

Homebrew

### Version of Borg

1.2.4

### Logs

```pytb
see description
```

**Comment by real-yfprojects** [comment]
This was already fixed in v0.8.11
