### ISSUE TITLE
Vorta doesn't start automatically in KDE Neon

### ISSUE THREAD

**Issue by dariodcr** [borgbase/vorta#1835]
### Description

Vorta doesn't start automatically when they system starts.
I ticked the option to do so in the preferences. This creates a .desktop configuration file in /home/.config/autostart.
In this file the command to be executed is vorta --daemonized.
If I remove the --daemonized argument, I log out and in again, Vorta starts automatically and in the background.
Unfortunately, the argument "daemonized" is restored the first time that Vorta runs again.

Could you please fix this?

### Reproduction

- [X] I tried to reproduce the issue.
- [X] I was able to reproduce the issue.

### OS

KDE Neon 5.27, KDE Plasma 5.27.9

### Version of Vorta

0.8.3

### What did you install Vorta with?

Distribution package

### Version of Borg

1.2.0

### Logs

```pytb
2023-10-25 18:39:05,902 - vorta.i18n - DEBUG - Loading translation failed for ['en', 'en-US', 'en-Latn-US'].
2023-10-25 18:39:06,367 - root - INFO - Using NetworkManagerMonitor NetworkStatusMonitor implementation.
2023-10-25 18:39:06,377 - vorta.network_status.network_manager - WARNING - Couldn't load settings for /org/freedesktop/NetworkManager/Settings/2
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/vorta/network_status/network_manager.py", line 52, in get_known_wifis
    settings = self._nm.get_settings(connection_path)
  File "/usr/lib/python3/dist-packages/vorta/network_status/network_manager.py", line 139, in get_settings
    return get_result(settings.call('GetSettings'))
  File "/usr/lib/python3/dist-packages/vorta/network_status/network_manager.py", line 163, in get_result
    raise DBusException("DBus call failed: {}".format(msg.arguments()))
vorta.network_status.network_manager.DBusException: DBus call failed: ['uid 1000 has no permission to perform this operation']
2023-10-25 18:39:06,450 - vorta.borg.jobs_manager - DEBUG - Add job for site default
2023-10-25 18:39:06,451 - vorta.borg.jobs_manager - DEBUG - Start job on site: default
2023-10-25 18:39:06,455 - vorta.borg.borg_job - INFO - Running command /usr/bin/borg --version
2023-10-25 18:39:07,210 - vorta.borg.jobs_manager - DEBUG - Finish job for site: default
2023-10-25 18:39:07,210 - vorta.borg.jobs_manager - DEBUG - No more jobs for site: default
2023-10-25 18:39:07,211 - vorta.scheduler - DEBUG - Refreshing all scheduler timers
2023-10-25 18:39:07,215 - vorta.scheduler - INFO - Setting timer for profile 1
2023-10-25 18:39:07,217 - vorta.scheduler - DEBUG - Scheduling next run for 2023-10-25 20:00:00
```

**Comment by real-yfprojects** [comment]
Is this a duplicate of #1397?

**Comment by dariodcr** [comment]
> Is this a duplicate of #1397?

Hello. If I run "vorta --daemonize" from terminal it launches correctly Vorta without error messages, differently from #1397. 
The problem is at system startup.
A workaround I found was to modify the name of vorta.desktop in /.config/autostart/ to vorta1.desktop. In this way Vorta does not overwrite this configuration file adding the "--daemonize" argument and it can launch correctly (minimized) at every system startup.

**Comment by real-yfprojects** [comment]
We need further information to fix this. The crash you describe happened before Vorta could load its logger. Can you log the output of the `vorta --daemonize` process that is created at startup?

**Comment by real-yfprojects** [comment]
No real information in there. Searching on the internet I found that you can add the following lines to the desktop file:

```
StandardOutput=append:/home/user/log1.log
StandardError=append:/home/user/log2.log
```

Maybe that helps...

**Comment by dariodcr** [comment]
> No real information in there. Searching on the internet I found that you can add the following lines to the desktop file:
> 
> ```
> StandardOutput=append:/home/user/log1.log
> StandardError=append:/home/user/log2.log
> ```
> 
> Maybe that helps...

Thanks. Unfortunately these lines are ignored, according to the log (see attachment).
