### ISSUE TITLE
bug when I try recalculate sizes

### ISSUE THREAD

**Issue by Revenarius** [borgbase/vorta#1837]
### Description

Anytime, if I click on Recalculate Sizes I got this error text:

Uncaught exception, please file a report with this text at
https://github.com/borgbase/vorta/issues/new
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/vorta/views/source_tab.py", line 156, in sources_update
    self.update_path_info(row)  # Update data for each entry
  File "/usr/lib/python3/dist-packages/vorta/views/source_tab.py", line 100, in update_path_info
    self.sourceFilesWidget.item(index_row, SourceColumn.Type).setText(self.tr("Calculating..."))
AttributeError: 'NoneType' object has no attribute 'setText'

[source_tab.py.zip](https://github.com/borgbase/vorta/files/13257392/source_tab.py.zip)

I checked the repository and do a new backup. The text still pop up.

### Reproduction

- [X] I tried to reproduce the issue.
- [X] I was able to reproduce the issue.

### OS

Linux Mint 21.1 Vera Mate

### Version of Vorta

Vorta 0.8.3  

### What did you install Vorta with?

Distribution package

### Version of Borg

Borg 1.2.0

### Logs

```pytb
2023-11-04 13:02:38,157 - vorta.i18n - DEBUG - Loading translation failed for ['es', 'es-ES', 'es-Latn-ES'].
2023-11-04 13:02:38,576 - root - INFO - Using NetworkManagerMonitor NetworkStatusMonitor implementation.
2023-11-04 13:02:38,751 - vorta.borg.jobs_manager - DEBUG - Add job for site default
2023-11-04 13:02:38,753 - vorta.borg.jobs_manager - DEBUG - Start job on site: default
2023-11-04 13:02:38,761 - vorta.borg.borg_job - INFO - Running command /usr/bin/borg --version
2023-11-04 13:02:39,441 - vorta.borg.jobs_manager - DEBUG - Finish job for site: default
2023-11-04 13:02:39,442 - vorta.scheduler - DEBUG - Refreshing all scheduler timers
2023-11-04 13:02:39,442 - vorta.borg.jobs_manager - DEBUG - No more jobs for site: default
2023-11-04 13:02:39,446 - vorta.scheduler - DEBUG - Scheduler for profile 1 is disabled.
2023-11-04 13:02:57,219 - vorta.keyring.abc - DEBUG - Only available on macOS
2023-11-04 13:02:57,260 - asyncio - DEBUG - Using selector: EpollSelector
2023-11-04 13:02:57,262 - vorta.borg.borg_job - DEBUG - Using VortaSecretStorageKeyring keyring to store passwords.
2023-11-04 13:02:57,264 - asyncio - DEBUG - Using selector: EpollSelector
2023-11-04 13:02:57,267 - root - DEBUG - Found 1 passwords matching repo URL.
2023-11-04 13:02:57,662 - vorta.borg.jobs_manager - DEBUG - Add job for site 3
2023-11-04 13:02:57,662 - vorta.borg.jobs_manager - DEBUG - Start job on site: 3
2023-11-04 13:02:57,698 - vorta.borg.borg_job - INFO - Running command /usr/bin/borg create --list --progress --info --log-json --json --filter=AM -C zstd,3 /media/jose/3TB Ext4/Repo Borg del NAS junio 2023::Acer-Jose-2023-11-04-130257 /mnt/NAS_Couto/Homes/Jose/Drive/Datos Guardados /mnt/NAS_Couto/Homes/Jose/Photos /mnt/NAS_Couto/Homes/Chus /mnt/NAS_Couto/Homes/Alicia /mnt/NAS_Couto/Homes/kuki /mnt/NAS_Couto/Videos/Mis videos /mnt/NAS_Couto/Homes/Jose/Diseños 3D interesantes /mnt/NAS_Couto/Homes/Jose/Drive/Impresion 3D del portatil /mnt/NAS_Couto/Homes/Jose/Compresion LZ4 vs Zstd.txt
2023-11-04 13:02:58,618 - vorta.borg.borg_job - INFO - Creating archive at "/media/jose/3TB Ext4/Repo Borg del NAS junio 2023::Acer-Jose-2023-11-04-130257"
2023-11-04 13:02:58,671 - vorta.borg.borg_job - INFO - Synchronizing chunks cache...
2023-11-04 13:02:58,675 - vorta.borg.borg_job - INFO - Archives: 5, w/ cached Idx: 0, w/ outdated Idx: 0, w/o cached Idx: 5.
2023-11-04 13:02:58,687 - vorta.borg.borg_job - INFO - Fetching and building archive index for Acer-Jose-2023-06-18-133231 ...
2023-11-04 13:02:59,865 - vorta.borg.borg_job - INFO - Merging into master chunks index ...
2023-11-04 13:02:59,888 - vorta.borg.borg_job - INFO - Fetching and building archive index for Acer-Jose-2023-07-30-115812 ...
2023-11-04 13:03:00,561 - vorta.borg.borg_job - INFO - Merging into master chunks index ...
2023-11-04 13:03:00,571 - vorta.borg.borg_job - INFO - Fetching and building archive index for Acer-Jose-2023-08-19-220806 ...
2023-11-04 13:03:01,151 - vorta.borg.borg_job - INFO - Merging into master chunks index ...
2023-11-04 13:03:01,161 - vorta.borg.borg_job - INFO - Fetching and building archive index for Acer-Jose-2023-10-26-202412 ...
2023-11-04 13:03:02,211 - vorta.borg.borg_job - INFO - Merging into master chunks index ...
2023-11-04 13:03:02,223 - vorta.borg.borg_job - INFO - Fetching and building archive index for Acer-Jose-2023-10-28-235830 ...
2023-11-04 13:03:02,856 - vorta.borg.borg_job - INFO - Merging into master chunks index ...
2023-11-04 13:03:02,866 - vorta.borg.borg_job - INFO - Done.
2023-11-04 13:17:38,090 - vorta.scheduler - DEBUG - Refreshing all scheduler timers
2023-11-04 13:17:38,093 - vorta.scheduler - DEBUG - Scheduler for profile 1 is disabled.
2023-11-04 13:32:38,090 - vorta.scheduler - DEBUG - Refreshing all scheduler timers
2023-11-04 13:32:38,094 - vorta.scheduler - DEBUG - Scheduler for profile 1 is disabled.
2023-11-04 13:47:38,090 - vorta.scheduler - DEBUG - Refreshing all scheduler timers
2023-11-04 13:47:38,092 - vorta.scheduler - DEBUG - Scheduler for profile 1 is disabled.
2023-11-04 14:02:38,090 - vorta.scheduler - DEBUG - Refreshing all scheduler timers
2023-11-04 14:02:38,094 - vorta.scheduler - DEBUG - Scheduler for profile 1 is disabled.
2023-11-04 14:17:38,090 - vorta.scheduler - DEBUG - Refreshing all scheduler timers
2023-11-04 14:17:38,092 - vorta.scheduler - DEBUG - Scheduler for profile 1 is disabled.
2023-11-04 14:32:38,090 - vorta.scheduler - DEBUG - Refreshing all scheduler timers
2023-11-04 14:32:38,094 - vorta.scheduler - DEBUG - Scheduler for profile 1 is disabled.
2023-11-04 14:47:38,090 - vorta.scheduler - DEBUG - Refreshing all scheduler timers
2023-11-04 14:47:38,103 - vorta.scheduler - DEBUG - Scheduler for profile 1 is disabled.
2023-11-04 15:02:38,090 - vorta.scheduler - DEBUG - Refreshing all scheduler timers
2023-11-04 15:02:38,102 - vorta.scheduler - DEBUG - Scheduler for profile 1 is disabled.
2023-11-04 15:15:52,826 - vorta.borg.borg_job - WARNING - /mnt/NAS_Couto/Videos/Mis videos: [Errno 2] No such file or directory: 'Mis videos'
2023-11-04 15:16:53,774 - vorta.borg.jobs_manager - DEBUG - Finish job for site: 3
2023-11-04 15:16:53,775 - vorta.borg.jobs_manager - DEBUG - No more jobs for site: 3
2023-11-04 15:17:38,097 - vorta.scheduler - DEBUG - Refreshing all scheduler timers
2023-11-04 15:17:38,100 - vorta.scheduler - DEBUG - Scheduler for profile 1 is disabled.
2023-11-04 15:32:38,189 - vorta.scheduler - DEBUG - Refreshing all scheduler timers
2023-11-04 15:32:38,191 - vorta.scheduler - DEBUG - Scheduler for profile 1 is disabled.
2023-11-04 15:47:38,090 - vorta.scheduler - DEBUG - Refreshing all scheduler timers
2023-11-04 15:47:38,095 - vorta.scheduler - DEBUG - Scheduler for profile 1 is disabled.
2023-11-04 15:47:38,096 - vorta.scheduler - DEBUG - Scheduler for profile 2 is disabled.
2023-11-04 15:48:43,541 - vorta.keyring.abc - DEBUG - Only available on macOS
2023-11-04 15:48:43,544 - asyncio - DEBUG - Using selector: EpollSelector
2023-11-04 15:48:43,545 - vorta.borg.borg_job - DEBUG - Using VortaSecretStorageKeyring keyring to store passwords.
2023-11-04 15:48:43,546 - asyncio - DEBUG - Using selector: EpollSelector
2023-11-04 15:48:43,547 - root - DEBUG - Found 1 passwords matching repo URL.
2023-11-04 15:48:43,567 - vorta.borg.jobs_manager - DEBUG - Add job for site 3
2023-11-04 15:48:43,568 - vorta.borg.jobs_manager - DEBUG - Start job on site: 3
2023-11-04 15:48:43,609 - vorta.borg.borg_job - INFO - Running command /usr/bin/borg create --list --progress --info --log-json --json --filter=AM -C zstd,3 /media/jose/3TB Ext4/Repo Borg del NAS junio 2023::Acer-Jose-2023-11-04-154843 /mnt/NAS_Couto/Videos
2023-11-04 15:48:44,356 - vorta.borg.borg_job - INFO - Creating archive at "/media/jose/3TB Ext4/Repo Borg del NAS junio 2023::Acer-Jose-2023-11-04-154843"
2023-11-04 15:48:54,096 - root - CRITICAL - Uncaught exception, file a report at https://github.com/borgbase/vorta/issues/new
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/vorta/views/source_tab.py", line 81, in set_path_info
    self.sourceFilesWidget.item(item.row(), SourceColumn.FilesCount).setText(format(files_count))
AttributeError: 'NoneType' object has no attribute 'setText'
2023-11-04 15:49:19,641 - vorta.borg.borg_job - DEBUG - Cancel job on site default
2023-11-04 15:49:19,641 - vorta.borg.borg_job - DEBUG - Cancel job on site 3
2023-11-04 15:49:20,003 - vorta.borg.borg_job - INFO - checkpoint requested: starting checkpoint creation...
2023-11-04 15:49:21,161 - vorta.borg.borg_job - INFO - checkpoint requested: finished checkpoint creation!
2023-11-04 15:49:22,641 - vorta.borg.jobs_manager - INFO - Finished cancelling all jobs
2023-11-04 15:49:23,509 - vorta.borg.borg_job - ERROR - Received SIGTERM
2023-11-04 15:49:23,682 - vorta.borg.jobs_manager - DEBUG - Finish job for site: 3
2023-11-04 15:49:23,683 - vorta.borg.jobs_manager - DEBUG - No more jobs for site: 3
2023-11-04 15:49:50,159 - vorta.keyring.abc - DEBUG - Only available on macOS
2023-11-04 15:49:50,161 - asyncio - DEBUG - Using selector: EpollSelector
2023-11-04 15:49:50,163 - vorta.borg.borg_job - DEBUG - Using VortaSecretStorageKeyring keyring to store passwords.
2023-11-04 15:49:50,165 - asyncio - DEBUG - Using selector: EpollSelector
2023-11-04 15:49:50,168 - root - DEBUG - Found 1 passwords matching repo URL.
2023-11-04 15:49:50,216 - vorta.borg.jobs_manager - DEBUG - Add job for site 3
2023-11-04 15:49:50,216 - vorta.borg.jobs_manager - DEBUG - Start job on site: 3
2023-11-04 15:49:50,232 - vorta.borg.borg_job - INFO - Running command /usr/bin/borg create --list --progress --info --log-json --json --filter=AM -C zstd,3 /media/jose/3TB Ext4/Repo Borg del NAS junio 2023::Acer-Jose-2023-11-04-154950 /mnt/NAS_Couto/Videos/Mis videos
2023-11-04 15:49:50,631 - vorta.borg.borg_job - INFO - Creating archive at "/media/jose/3TB Ext4/Repo Borg del NAS junio 2023::Acer-Jose-2023-11-04-154950"
2023-11-04 16:02:38,090 - vorta.scheduler - DEBUG - Refreshing all scheduler timers
2023-11-04 16:02:38,092 - vorta.scheduler - DEBUG - Scheduler for profile 1 is disabled.
2023-11-04 16:02:38,094 - vorta.scheduler - DEBUG - Scheduler for profile 2 is disabled.
2023-11-04 16:03:21,988 - vorta.borg.jobs_manager - DEBUG - Finish job for site: 3
2023-11-04 16:03:21,988 - vorta.borg.jobs_manager - DEBUG - No more jobs for site: 3
2023-11-04 16:17:30,786 - root - CRITICAL - Uncaught exception, file a report at https://github.com/borgbase/vorta/issues/new
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/vorta/views/source_tab.py", line 156, in sources_update
    self.update_path_info(row)  # Update data for each entry
  File "/usr/lib/python3/dist-packages/vorta/views/source_tab.py", line 102, in update_path_info
    self.sourceFilesWidget.item(index_row, SourceColumn.FilesCount).setText(self.tr("Calculating..."))
AttributeError: 'NoneType' object has no attribute 'setText'
2023-11-04 16:17:38,093 - vorta.scheduler - DEBUG - Refreshing all scheduler timers
2023-11-04 16:17:38,095 - vorta.scheduler - DEBUG - Scheduler for profile 1 is disabled.
2023-11-04 16:17:38,096 - vorta.scheduler - DEBUG - Scheduler for profile 2 is disabled.
2023-11-04 16:22:07,427 - vorta.keyring.abc - DEBUG - Only available on macOS
2023-11-04 16:22:07,430 - asyncio - DEBUG - Using selector: EpollSelector
2023-11-04 16:22:07,431 - vorta.borg.borg_job - DEBUG - Using VortaSecretStorageKeyring keyring to store passwords.
2023-11-04 16:22:07,432 - asyncio - DEBUG - Using selector: EpollSelector
2023-11-04 16:22:07,434 - root - DEBUG - Found 1 passwords matching repo URL.
2023-11-04 16:22:07,479 - vorta.borg.jobs_manager - DEBUG - Add job for site 3
2023-11-04 16:22:07,480 - vorta.borg.jobs_manager - DEBUG - Start job on site: 3
2023-11-04 16:22:07,492 - vorta.borg.borg_job - INFO - Running command /usr/bin/borg check --info --log-json /media/jose/3TB Ext4/Repo Borg del NAS junio 2023
2023-11-04 16:22:07,755 - vorta.borg.borg_job - INFO - Starting repository check
2023-11-04 16:32:38,090 - vorta.scheduler - DEBUG - Refreshing all scheduler timers
2023-11-04 16:32:38,103 - vorta.scheduler - DEBUG - Scheduler for profile 1 is disabled.
2023-11-04 16:32:38,105 - vorta.scheduler - DEBUG - Scheduler for profile 2 is disabled.
2023-11-04 16:36:37,369 - vorta.borg.borg_job - DEBUG - Cancel job on site default
2023-11-04 16:36:37,369 - vorta.borg.borg_job - DEBUG - Cancel job on site 3
2023-11-04 16:36:40,370 - vorta.borg.jobs_manager - INFO - Finished cancelling all jobs
2023-11-04 16:36:41,615 - vorta.borg.borg_job - ERROR - Received SIGTERM
2023-11-04 16:36:41,826 - vorta.borg.jobs_manager - DEBUG - Finish job for site: 3
2023-11-04 16:36:41,826 - vorta.borg.jobs_manager - DEBUG - No more jobs for site: 3
2023-11-04 16:36:47,340 - root - CRITICAL - Uncaught exception, file a report at https://github.com/borgbase/vorta/issues/new
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/vorta/views/source_tab.py", line 156, in sources_update
    self.update_path_info(row)  # Update data for each entry
  File "/usr/lib/python3/dist-packages/vorta/views/source_tab.py", line 102, in update_path_info
    self.sourceFilesWidget.item(index_row, SourceColumn.FilesCount).setText(self.tr("Calculating..."))
AttributeError: 'NoneType' object has no attribute 'setText'
2023-11-04 16:37:28,740 - root - CRITICAL - Uncaught exception, file a report at https://github.com/borgbase/vorta/issues/new
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/vorta/views/source_tab.py", line 156, in sources_update
    self.update_path_info(row)  # Update data for each entry
  File "/usr/lib/python3/dist-packages/vorta/views/source_tab.py", line 100, in update_path_info
    self.sourceFilesWidget.item(index_row, SourceColumn.Type).setText(self.tr("Calculating..."))
AttributeError: 'NoneType' object has no attribute 'setText'
2023-11-04 16:38:18,083 - vorta.keyring.abc - DEBUG - Only available on macOS
2023-11-04 16:38:18,087 - asyncio - DEBUG - Using selector: EpollSelector
2023-11-04 16:38:18,094 - vorta.borg.borg_job - DEBUG - Using VortaSecretStorageKeyring keyring to store passwords.
2023-11-04 16:38:18,097 - asyncio - DEBUG - Using selector: EpollSelector
2023-11-04 16:38:18,099 - root - DEBUG - Found 1 passwords matching repo URL.
2023-11-04 16:38:18,138 - vorta.borg.jobs_manager - DEBUG - Add job for site 3
2023-11-04 16:38:18,138 - vorta.borg.jobs_manager - DEBUG - Start job on site: 3
2023-11-04 16:38:18,152 - vorta.borg.borg_job - INFO - Running command /usr/bin/borg create --list --progress --info --log-json --json --filter=AM -C zstd,3 /media/jose/3TB Ext4/Repo Borg del NAS junio 2023::Acer-Jose-2023-11-04-163818 /mnt/NAS_Couto/Homes/Jose/Drive/Datos Guardados /mnt/NAS_Couto/Homes/Jose/Photos /mnt/NAS_Couto/Homes/Chus /mnt/NAS_Couto/Homes/Alicia /mnt/NAS_Couto/Homes/kuki /mnt/NAS_Couto/Videos/Mis videos /mnt/NAS_Couto/Homes/Jose/Diseños 3D interesantes /mnt/NAS_Couto/Homes/Jose/Drive/Impresion 3D del portatil /mnt/NAS_Couto/Homes/Jose/Compresion LZ4 vs Zstd.txt
2023-11-04 16:38:19,240 - vorta.borg.borg_job - INFO - Creating archive at "/media/jose/3TB Ext4/Repo Borg del NAS junio 2023::Acer-Jose-2023-11-04-163818"
2023-11-04 16:47:38,090 - vorta.scheduler - DEBUG - Refreshing all scheduler timers
2023-11-04 16:47:38,094 - vorta.scheduler - DEBUG - Scheduler for profile 1 is disabled.
2023-11-04 16:47:38,096 - vorta.scheduler - DEBUG - Scheduler for profile 2 is disabled.
2023-11-04 16:54:47,239 - vorta.borg.jobs_manager - DEBUG - Finish job for site: 3
2023-11-04 16:54:47,240 - vorta.borg.jobs_manager - DEBUG - No more jobs for site: 3
2023-11-04 17:02:38,174 - vorta.scheduler - DEBUG - Refreshing all scheduler timers
2023-11-04 17:02:38,178 - vorta.scheduler - DEBUG - Scheduler for profile 1 is disabled.
2023-11-04 17:02:38,180 - vorta.scheduler - DEBUG - Scheduler for profile 2 is disabled.
2023-11-04 17:17:38,182 - vorta.scheduler - DEBUG - Refreshing all scheduler timers
2023-11-04 17:17:38,186 - vorta.scheduler - DEBUG - Scheduler for profile 1 is disabled.
2023-11-04 17:17:38,189 - vorta.scheduler - DEBUG - Scheduler for profile 2 is disabled.
2023-11-04 17:32:38,160 - vorta.scheduler - DEBUG - Refreshing all scheduler timers
2023-11-04 17:32:38,164 - vorta.scheduler - DEBUG - Scheduler for profile 1 is disabled.
2023-11-04 17:32:38,167 - vorta.scheduler - DEBUG - Scheduler for profile 2 is disabled.
2023-11-04 17:47:38,097 - vorta.scheduler - DEBUG - Refreshing all scheduler timers
2023-11-04 17:47:38,100 - vorta.scheduler - DEBUG - Scheduler for profile 1 is disabled.
2023-11-04 17:47:38,101 - vorta.scheduler - DEBUG - Scheduler for profile 2 is disabled.
2023-11-04 18:02:38,189 - vorta.scheduler - DEBUG - Refreshing all scheduler timers
2023-11-04 18:02:38,192 - vorta.scheduler - DEBUG - Scheduler for profile 1 is disabled.
2023-11-04 18:02:38,193 - vorta.scheduler - DEBUG - Scheduler for profile 2 is disabled.
2023-11-04 18:10:38,495 - root - CRITICAL - Uncaught exception, file a report at https://github.com/borgbase/vorta/issues/new
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/vorta/views/source_tab.py", line 156, in sources_update
    self.update_path_info(row)  # Update data for each entry
  File "/usr/lib/python3/dist-packages/vorta/views/source_tab.py", line 100, in update_path_info
    self.sourceFilesWidget.item(index_row, SourceColumn.Type).setText(self.tr("Calculating..."))
AttributeError: 'NoneType' object has no attribute 'setText'
2023-11-04 18:10:46,027 - vorta.keyring.abc - DEBUG - Only available on macOS
2023-11-04 18:10:46,030 - asyncio - DEBUG - Using selector: EpollSelector
2023-11-04 18:10:46,031 - vorta.borg.borg_job - DEBUG - Using VortaSecretStorageKeyring keyring to store passwords.
2023-11-04 18:10:46,033 - asyncio - DEBUG - Using selector: EpollSelector
2023-11-04 18:10:46,036 - root - DEBUG - Found 1 passwords matching repo URL.
2023-11-04 18:10:46,082 - vorta.borg.jobs_manager - DEBUG - Add job for site 3
2023-11-04 18:10:46,083 - vorta.borg.jobs_manager - DEBUG - Start job on site: 3
2023-11-04 18:10:46,101 - vorta.borg.borg_job - INFO - Running command /usr/bin/borg check --info --log-json /media/jose/3TB Ext4/Repo Borg del NAS junio 2023
2023-11-04 18:10:51,745 - vorta.borg.borg_job - INFO - Starting repository check
2023-11-04 18:17:38,090 - vorta.scheduler - DEBUG - Refreshing all scheduler timers
2023-11-04 18:17:38,103 - vorta.scheduler - DEBUG - Scheduler for profile 1 is disabled.
2023-11-04 18:17:38,105 - vorta.scheduler - DEBUG - Scheduler for profile 2 is disabled.
2023-11-04 18:32:38,090 - vorta.scheduler - DEBUG - Refreshing all scheduler timers
2023-11-04 18:32:38,102 - vorta.scheduler - DEBUG - Scheduler for profile 1 is disabled.
2023-11-04 18:32:38,105 - vorta.scheduler - DEBUG - Scheduler for profile 2 is disabled.
2023-11-04 18:47:34,860 - vorta.borg.borg_job - INFO - finished segment check at segment 629
2023-11-04 18:47:34,898 - vorta.borg.borg_job - INFO - Starting repository index check
2023-11-04 18:47:34,898 - vorta.borg.borg_job - INFO - Index object count match.
2023-11-04 18:47:35,002 - vorta.borg.borg_job - INFO - Finished full repository check, no problems found.
2023-11-04 18:47:35,003 - vorta.borg.borg_job - INFO - Starting archive consistency check...
2023-11-04 18:47:35,235 - vorta.borg.borg_job - INFO - Analyzing archive Acer-Jose-2023-06-18-133231 (1/9)
2023-11-04 18:47:38,090 - vorta.scheduler - DEBUG - Refreshing all scheduler timers
2023-11-04 18:47:38,103 - vorta.scheduler - DEBUG - Scheduler for profile 1 is disabled.
2023-11-04 18:47:38,105 - vorta.scheduler - DEBUG - Scheduler for profile 2 is disabled.
2023-11-04 18:47:39,868 - vorta.borg.borg_job - INFO - Analyzing archive Acer-Jose-2023-07-30-115812 (2/9)
2023-11-04 18:47:43,255 - vorta.borg.borg_job - INFO - Analyzing archive Acer-Jose-2023-08-19-220806 (3/9)
2023-11-04 18:47:46,676 - vorta.borg.borg_job - INFO - Analyzing archive Acer-Jose-2023-10-26-202412 (4/9)
2023-11-04 18:47:50,434 - vorta.borg.borg_job - INFO - Analyzing archive Acer-Jose-2023-10-28-235830 (5/9)
2023-11-04 18:47:53,889 - vorta.borg.borg_job - INFO - Analyzing archive Acer-Jose-2023-11-04-130257 (6/9)
2023-11-04 18:47:57,332 - vorta.borg.borg_job - INFO - Analyzing archive Acer-Jose-2023-11-04-154843.checkpoint (7/9)
2023-11-04 18:47:57,334 - vorta.borg.borg_job - INFO - Analyzing archive Acer-Jose-2023-11-04-154950 (8/9)
2023-11-04 18:47:57,361 - vorta.borg.borg_job - INFO - Analyzing archive Acer-Jose-2023-11-04-163818 (9/9)
2023-11-04 18:48:00,901 - vorta.borg.borg_job - INFO - Archive consistency check complete, no problems found.
2023-11-04 18:48:01,640 - vorta.borg.jobs_manager - DEBUG - Finish job for site: 3
2023-11-04 18:48:01,640 - vorta.borg.jobs_manager - DEBUG - No more jobs for site: 3
2023-11-04 18:56:54,716 - root - CRITICAL - Uncaught exception, file a report at https://github.com/borgbase/vorta/issues/new
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/vorta/views/source_tab.py", line 156, in sources_update
    self.update_path_info(row)  # Update data for each entry
  File "/usr/lib/python3/dist-packages/vorta/views/source_tab.py", line 100, in update_path_info
    self.sourceFilesWidget.item(index_row, SourceColumn.Type).setText(self.tr("Calculating..."))
AttributeError: 'NoneType' object has no attribute 'setText'
2023-11-04 19:02:38,090 - vorta.scheduler - DEBUG - Refreshing all scheduler timers
2023-11-04 19:02:38,094 - vorta.scheduler - DEBUG - Scheduler for profile 1 is disabled.
2023-11-04 19:02:38,096 - vorta.scheduler - DEBUG - Scheduler for profile 2 is disabled.
```

**Comment by Revenarius** [comment]
Reinstall Vorta (first purge it) dont fix.
The repository its ok, checked by Borg CLI.

**Comment by real-yfprojects** [comment]
Thank you very much for reporting! This bug is already known and tracked in #1080. However we still don't know what triggers it. I will look into your logs and try to find a hint there.
