### ISSUE TITLE
Libcrypto not found

### ISSUE THREAD

**Issue by zaphod80013** [borgbase/vorta#1876]
### Description

Vorta installed with `python -m pip install Vorta`, run as root using python 3.10.12 as I want to import my existing script based backup repos. My repos were migrated to borg 1.2.7 using export/import. my scripts run as root under cron. I do not wish to use the flatpak as this comes with borg 1.2.4 which is older than the version I'm currently using. My distro ships with Vorta 0.8.3 as a package, which itself is quite old.

on opening Vorta and attempting to initialise a local test repository I get the error 

[Init Repo] ImportError: libcrypto.so.1.1: cannot open shared object file: No such file or directory

libcrypto.so exist on my system but is a symlink to libcrypto.so.3, ***I was able to effect a temporary fix by copying libcrypto.so.1.1 from a 3rd party application to /usr/lib/x86_64-linux-gnu*** but this doesn't address the real issue that libcrypto.so.1.1 no longer ship with debian/ubuntu based distributions.

### Reproduction

- [X] I tried to reproduce the issue.
- [ ] I was able to reproduce the issue.

### OS

POP-OS 22.04 Gnome 42.5

### Version of Vorta

0.8.12

### What did you install Vorta with?

Pip

### Version of Borg

1.2.7

### Logs

```pytb
2023-12-30 17:17:42,405 - vorta.scheduler - DEBUG - Refreshing all scheduler timers
2023-12-30 17:17:42,417 - vorta.scheduler - DEBUG - Nothing scheduled for profile 1 because of unset repo.
2023-12-30 17:32:42,369 - vorta.scheduler - DEBUG - Refreshing all scheduler timers
2023-12-30 17:32:42,371 - vorta.scheduler - DEBUG - Nothing scheduled for profile 1 because of unset repo.
2023-12-30 17:47:42,375 - vorta.scheduler - DEBUG - Refreshing all scheduler timers
2023-12-30 17:47:42,381 - vorta.scheduler - DEBUG - Nothing scheduled for profile 1 because of unset repo.
2023-12-30 18:02:42,433 - vorta.scheduler - DEBUG - Refreshing all scheduler timers
2023-12-30 18:02:42,440 - vorta.scheduler - DEBUG - Nothing scheduled for profile 1 because of unset repo.
2023-12-30 18:17:42,425 - vorta.scheduler - DEBUG - Refreshing all scheduler timers
2023-12-30 18:17:42,428 - vorta.scheduler - DEBUG - Nothing scheduled for profile 1 because of unset repo.
2023-12-30 18:32:42,421 - vorta.scheduler - DEBUG - Refreshing all scheduler timers
2023-12-30 18:32:42,428 - vorta.scheduler - DEBUG - Nothing scheduled for profile 1 because of unset repo.
2023-12-30 18:42:24,980 - vorta.application - INFO - An instance of Vorta is already running. Opening main window.
2023-12-30 18:42:38,149 - vorta.keyring.abc - DEBUG - Only available on macOS
2023-12-30 18:42:38,150 - asyncio - DEBUG - Using selector: EpollSelector
2023-12-30 18:42:38,151 - vorta.keyring.abc - DEBUG - Using VortaSecretStorageKeyring
2023-12-30 18:42:58,237 - vorta.keyring.abc - DEBUG - Only available on macOS
2023-12-30 18:42:58,240 - asyncio - DEBUG - Using selector: EpollSelector
2023-12-30 18:42:58,242 - vorta.keyring.abc - DEBUG - Using VortaSecretStorageKeyring
2023-12-30 18:42:58,244 - asyncio - DEBUG - Using selector: EpollSelector
2023-12-30 18:42:58,245 - vorta.keyring.secretstorage - DEBUG - Found 0 passwords matching repo URL.
2023-12-30 18:44:12,217 - vorta.application - INFO - An instance of Vorta is already running. Opening main window.
2023-12-30 18:44:17,760 - vorta.keyring.abc - DEBUG - Only available on macOS
2023-12-30 18:44:17,761 - asyncio - DEBUG - Using selector: EpollSelector
2023-12-30 18:44:17,779 - vorta.keyring.abc - DEBUG - Using VortaSecretStorageKeyring
2023-12-30 18:44:23,572 - vorta.keyring.abc - DEBUG - Only available on macOS
2023-12-30 18:44:23,574 - asyncio - DEBUG - Using selector: EpollSelector
2023-12-30 18:44:23,576 - vorta.keyring.abc - DEBUG - Using VortaSecretStorageKeyring
2023-12-30 18:44:23,578 - asyncio - DEBUG - Using selector: EpollSelector
2023-12-30 18:44:23,580 - vorta.keyring.secretstorage - DEBUG - Found 0 passwords matching repo URL.
2023-12-30 18:44:53,092 - vorta.keyring.abc - DEBUG - Only available on macOS
2023-12-30 18:44:53,094 - asyncio - DEBUG - Using selector: EpollSelector
2023-12-30 18:44:53,096 - vorta.keyring.abc - DEBUG - Using VortaSecretStorageKeyring
2023-12-30 18:45:46,596 - vorta.keyring.abc - DEBUG - Only available on macOS
2023-12-30 18:45:46,598 - asyncio - DEBUG - Using selector: EpollSelector
2023-12-30 18:45:46,599 - vorta.keyring.abc - DEBUG - Using VortaSecretStorageKeyring
2023-12-30 18:45:46,599 - vorta.borg.borg_job - DEBUG - Using VortaSecretStorageKeyring keyring to store passwords.
2023-12-30 18:45:46,601 - asyncio - DEBUG - Using selector: EpollSelector
2023-12-30 18:45:46,602 - vorta.keyring.secretstorage - DEBUG - Found 0 passwords matching repo URL.
2023-12-30 18:45:46,604 - vorta.borg.borg_job - DEBUG - Password not found in primary keyring. Falling back to VortaDBKeyring.
2023-12-30 18:45:46,606 - vorta.borg.jobs_manager - DEBUG - Add job for site default
2023-12-30 18:45:46,606 - vorta.borg.jobs_manager - DEBUG - Start job on site: default
2023-12-30 18:45:46,616 - vorta.borg.borg_job - INFO - Running command /usr/local/bin/borg init --info --log-json --encryption=keyfile-blake2 /home/ray/test
2023-12-30 18:45:46,928 - vorta.borg.borg_job - WARNING - Traceback (most recent call last):
2023-12-30 18:45:46,929 - vorta.borg.borg_job - WARNING - File "borg/archiver.py", line 37, in <module>
2023-12-30 18:45:46,929 - vorta.borg.borg_job - WARNING - File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
2023-12-30 18:45:46,929 - vorta.borg.borg_job - WARNING - File "borg/helpers/__init__.py", line 9, in <module>
2023-12-30 18:45:46,930 - vorta.borg.borg_job - WARNING - File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
2023-12-30 18:45:46,930 - vorta.borg.borg_job - WARNING - File "borg/helpers/checks.py", line 4, in <module>
2023-12-30 18:45:46,930 - vorta.borg.borg_job - WARNING - File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
2023-12-30 18:45:46,930 - vorta.borg.borg_job - WARNING - File "borg/helpers/errors.py", line 3, in <module>
2023-12-30 18:45:46,930 - vorta.borg.borg_job - WARNING - ImportError: libcrypto.so.1.1: cannot open shared object file: No such file or directory
2023-12-30 18:45:47,053 - vorta.borg.jobs_manager - DEBUG - Finish job for site: default
2023-12-30 18:45:47,055 - vorta.borg.jobs_manager - DEBUG - No more jobs for site: default
2023-12-30 18:46:07,444 - vorta.keyring.abc - DEBUG - Only available on macOS
2023-12-30 18:46:07,446 - asyncio - DEBUG - Using selector: EpollSelector
2023-12-30 18:46:07,447 - vorta.keyring.abc - DEBUG - Using VortaSecretStorageKeyring
2023-12-30 18:46:07,447 - vorta.borg.borg_job - DEBUG - Using VortaSecretStorageKeyring keyring to store passwords.
2023-12-30 18:46:07,448 - asyncio - DEBUG - Using selector: EpollSelector
2023-12-30 18:46:07,449 - vorta.keyring.secretstorage - DEBUG - Found 0 passwords matching repo URL.
2023-12-30 18:46:07,451 - vorta.borg.borg_job - DEBUG - Password not found in primary keyring. Falling back to VortaDBKeyring.
2023-12-30 18:46:07,452 - vorta.borg.jobs_manager - DEBUG - Add job for site default
2023-12-30 18:46:07,453 - vorta.borg.jobs_manager - DEBUG - Start job on site: default
2023-12-30 18:46:07,462 - vorta.borg.borg_job - INFO - Running command /usr/local/bin/borg init --info --log-json --encryption=keyfile-blake2 /home/ray/test
2023-12-30 18:46:07,772 - vorta.borg.borg_job - WARNING - Traceback (most recent call last):
2023-12-30 18:46:07,773 - vorta.borg.borg_job - WARNING - File "borg/archiver.py", line 37, in <module>
2023-12-30 18:46:07,773 - vorta.borg.borg_job - WARNING - File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
2023-12-30 18:46:07,773 - vorta.borg.borg_job - WARNING - File "borg/helpers/__init__.py", line 9, in <module>
2023-12-30 18:46:07,773 - vorta.borg.borg_job - WARNING - File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
2023-12-30 18:46:07,773 - vorta.borg.borg_job - WARNING - File "borg/helpers/checks.py", line 4, in <module>
2023-12-30 18:46:07,773 - vorta.borg.borg_job - WARNING - File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
2023-12-30 18:46:07,773 - vorta.borg.borg_job - WARNING - File "borg/helpers/errors.py", line 3, in <module>
2023-12-30 18:46:07,773 - vorta.borg.borg_job - WARNING - ImportError: libcrypto.so.1.1: cannot open shared object file: No such file or directory
2023-12-30 18:46:07,899 - vorta.borg.jobs_manager - DEBUG - Finish job for site: default
2023-12-30 18:46:07,899 - vorta.borg.jobs_manager - DEBUG - No more jobs for site: default
2023-12-30 18:47:09,553 - vorta.application - INFO - An instance of Vorta is already running. Opening main window.
2023-12-30 18:47:18,077 - vorta.keyring.abc - DEBUG - Only available on macOS
2023-12-30 18:47:18,079 - asyncio - DEBUG - Using selector: EpollSelector
2023-12-30 18:47:18,080 - vorta.keyring.abc - DEBUG - Using VortaSecretStorageKeyring
2023-12-30 18:47:24,569 - vorta.keyring.abc - DEBUG - Only available on macOS
2023-12-30 18:47:24,572 - asyncio - DEBUG - Using selector: EpollSelector
2023-12-30 18:47:24,574 - vorta.keyring.abc - DEBUG - Using VortaSecretStorageKeyring
2023-12-30 18:47:24,575 - asyncio - DEBUG - Using selector: EpollSelector
2023-12-30 18:47:24,577 - vorta.keyring.secretstorage - DEBUG - Found 0 passwords matching repo URL.
2023-12-30 18:47:39,235 - vorta.keyring.abc - DEBUG - Only available on macOS
2023-12-30 18:47:39,236 - asyncio - DEBUG - Using selector: EpollSelector
2023-12-30 18:47:39,238 - vorta.keyring.abc - DEBUG - Using VortaSecretStorageKeyring
2023-12-30 18:47:39,238 - vorta.borg.borg_job - DEBUG - Using VortaSecretStorageKeyring keyring to store passwords.
2023-12-30 18:47:39,239 - asyncio - DEBUG - Using selector: EpollSelector
2023-12-30 18:47:39,241 - vorta.keyring.secretstorage - DEBUG - Found 0 passwords matching repo URL.
2023-12-30 18:47:39,242 - vorta.borg.borg_job - DEBUG - Password not found in primary keyring. Falling back to VortaDBKeyring.
2023-12-30 18:47:39,243 - vorta.borg.jobs_manager - DEBUG - Add job for site default
2023-12-30 18:47:39,243 - vorta.borg.jobs_manager - DEBUG - Start job on site: default
2023-12-30 18:47:39,253 - vorta.borg.borg_job - INFO - Running command /usr/local/bin/borg init --info --log-json --encryption=repokey-blake2 /home/ray/test
2023-12-30 18:47:39,555 - vorta.borg.borg_job - WARNING - Traceback (most recent call last):
2023-12-30 18:47:39,555 - vorta.borg.borg_job - WARNING - File "borg/archiver.py", line 37, in <module>
2023-12-30 18:47:39,555 - vorta.borg.borg_job - WARNING - File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
2023-12-30 18:47:39,555 - vorta.borg.borg_job - WARNING - File "borg/helpers/__init__.py", line 9, in <module>
2023-12-30 18:47:39,555 - vorta.borg.borg_job - WARNING - File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
2023-12-30 18:47:39,556 - vorta.borg.borg_job - WARNING - File "borg/helpers/checks.py", line 4, in <module>
2023-12-30 18:47:39,557 - vorta.borg.borg_job - WARNING - File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
2023-12-30 18:47:39,558 - vorta.borg.borg_job - WARNING - File "borg/helpers/errors.py", line 3, in <module>
2023-12-30 18:47:39,558 - vorta.borg.borg_job - WARNING - ImportError: libcrypto.so.1.1: cannot open shared object file: No such file or directory
2023-12-30 18:47:39,681 - vorta.borg.jobs_manager - DEBUG - Finish job for site: default
2023-12-30 18:47:39,683 - vorta.borg.jobs_manager - DEBUG - No more jobs for site: default
2023-12-30 18:47:42,356 - vorta.scheduler - DEBUG - Refreshing all scheduler timers
2023-12-30 18:47:42,362 - vorta.scheduler - DEBUG - Nothing scheduled for profile 1 because of unset repo.
2023-12-30 19:02:42,442 - vorta.scheduler - DEBUG - Refreshing all scheduler timers
2023-12-30 19:02:42,444 - vorta.scheduler - DEBUG - Nothing scheduled for profile 1 because of unset repo.
.....

The remainder of the log (175 lines just repeats the last two lines above)
```

**Comment by real-yfprojects** [comment]
This is not an error raised in Vorta's code. In fact it is an issue with your borg installation.

PS: Running Vorta as root is not officially supported at the moment. Issues might occur.
