### ISSUE TITLE
Ubuntu 22.04 unable to create a repository, or add an already configured one

### ISSUE THREAD

**Issue by DandyDiamond** [borgbase/vorta#1919]
### Description

Unable to both create or add a Repository to Vorta.  Can create in Repository in CLI Borgbackup.

### Reproduction

- [X] I tried to reproduce the issue.
- [X] I was able to reproduce the issue.

### OS

Ubuntu 22.04 Desktop

### Version of Vorta

0.8.3

### What did you install Vorta with?

Distribution package

### Version of Borg

1.2.7 /usr/bin/borg

### Logs

```pytb
2024-01-31 14:53:01,462 - vorta.i18n - DEBUG - Loading translation failed for ['en-GB', 'en-Latn-GB'].
2024-01-31 14:53:01,548 - root - INFO - Using NetworkManagerMonitor NetworkStatusMonitor implementation.
2024-01-31 14:53:01,608 - vorta.borg.jobs_manager - DEBUG - Add job for site default
2024-01-31 14:53:01,609 - vorta.borg.jobs_manager - DEBUG - Start job on site: default
2024-01-31 14:53:01,611 - vorta.borg.borg_job - INFO - Running command /usr/bin/borg --version
2024-01-31 14:53:02,057 - vorta.borg.jobs_manager - DEBUG - Finish job for site: default
2024-01-31 14:53:02,057 - vorta.borg.jobs_manager - DEBUG - No more jobs for site: default
2024-01-31 14:53:02,057 - vorta.scheduler - DEBUG - Refreshing all scheduler timers
2024-01-31 14:53:02,058 - vorta.scheduler - DEBUG - Scheduler for profile 1 is disabled.
2024-01-31 14:53:02,059 - vorta.scheduler - DEBUG - Scheduler for profile 2 is disabled.
2024-01-31 15:03:15,394 - vorta.keyring.abc - DEBUG - Only available on macOS
2024-01-31 15:03:15,412 - asyncio - DEBUG - Using selector: EpollSelector
2024-01-31 15:04:02,093 - vorta.keyring.abc - DEBUG - Only available on macOS
2024-01-31 15:04:02,095 - asyncio - DEBUG - Using selector: EpollSelector
2024-01-31 15:04:46,613 - vorta.keyring.abc - DEBUG - Only available on macOS
2024-01-31 15:04:46,614 - asyncio - DEBUG - Using selector: EpollSelector
2024-01-31 15:05:33,965 - vorta.keyring.abc - DEBUG - Only available on macOS
2024-01-31 15:05:33,966 - asyncio - DEBUG - Using selector: EpollSelector
2024-01-31 15:05:43,764 - vorta.keyring.abc - DEBUG - Only available on macOS
2024-01-31 15:05:43,765 - asyncio - DEBUG - Using selector: EpollSelector
2024-01-31 15:05:43,767 - asyncio - DEBUG - Using selector: EpollSelector
2024-01-31 15:05:43,768 - root - DEBUG - Found 0 passwords matching repo URL.
2024-01-31 15:06:00,407 - vorta.keyring.abc - DEBUG - Only available on macOS
2024-01-31 15:06:00,408 - asyncio - DEBUG - Using selector: EpollSelector
2024-01-31 15:06:00,409 - vorta.borg.borg_job - DEBUG - Using VortaSecretStorageKeyring keyring to store passwords.
2024-01-31 15:06:00,411 - asyncio - DEBUG - Using selector: EpollSelector
2024-01-31 15:06:00,412 - root - DEBUG - Found 0 passwords matching repo URL.
2024-01-31 15:06:00,412 - vorta.borg.borg_job - DEBUG - Password not found in primary keyring. Falling back to VortaDBKeyring.
2024-01-31 15:06:00,420 - vorta.borg.borg_job - INFO - Running command /usr/bin/borg info --info --json --log-json /media/colin/Old_NR_240/Borg
2024-01-31 15:06:00,812 - root - CRITICAL - Uncaught exception, file a report at https://github.com/borgbase/vorta/issues/new
Traceback (most recent call last):
  File "/home/colin/.local/lib/python3.10/site-packages/peewee.py", line 7160, in get
    return clone.execute(database)[0]
  File "/home/colin/.local/lib/python3.10/site-packages/peewee.py", line 4510, in __getitem__
    return self.row_cache[item]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/colin/.local/lib/python3.10/site-packages/peewee.py", line 6754, in get_or_create
    return query.get(), False
  File "/home/colin/.local/lib/python3.10/site-packages/peewee.py", line 7163, in get
    raise self.model.DoesNotExist('%s instance matching query does '
vorta.store.models.RepoModelDoesNotExist: <Model: RepoModel> instance matching query does not exist:
SQL: SELECT "t1"."id", "t1"."url", "t1"."added_at", "t1"."encryption", "t1"."unique_size", "t1"."unique_csize", "t1"."total_size", "t1"."total_unique_chunks", "t1"."create_backup_cmd", "t1"."extra_borg_arguments" FROM "repomodel" AS "t1" WHERE ("t1"."url" = ?) LIMIT ? OFFSET ?
Params: ['/media/colin/Old_NR_240/Borg', 1, 0]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/vorta/views/repo_add_dialog.py", line 221, in run
    self.thread.run()
  File "/usr/lib/python3/dist-packages/vorta/borg/borg_job.py", line 298, in run
    self.process_result(result)
  File "/usr/lib/python3/dist-packages/vorta/borg/info_repo.py", line 53, in process_result
    new_repo, _ = RepoModel.get_or_create(
  File "/home/colin/.local/lib/python3.10/site-packages/peewee.py", line 6756, in get_or_create
    raise exc
  File "/home/colin/.local/lib/python3.10/site-packages/peewee.py", line 6751, in get_or_create
    return cls.create(**kwargs), True
  File "/home/colin/.local/lib/python3.10/site-packages/peewee.py", line 6620, in create
    inst.save(force_insert=True)
  File "/home/colin/.local/lib/python3.10/site-packages/playhouse/signals.py", line 71, in save
    ret = super(Model, self).save(*args, **kwargs)
  File "/home/colin/.local/lib/python3.10/site-packages/peewee.py", line 6830, in save
    pk = self.insert(**field_dict).execute()
  File "/home/colin/.local/lib/python3.10/site-packages/peewee.py", line 1972, in inner
    return method(self, database, *args, **kwargs)
  File "/home/colin/.local/lib/python3.10/site-packages/peewee.py", line 2043, in execute
    return self._execute(database)
  File "/home/colin/.local/lib/python3.10/site-packages/peewee.py", line 2848, in _execute
    return super(Insert, self)._execute(database)
  File "/home/colin/.local/lib/python3.10/site-packages/peewee.py", line 2561, in _execute
    cursor = database.execute(self)
  File "/home/colin/.local/lib/python3.10/site-packages/peewee.py", line 3260, in execute
    return self.execute_sql(sql, params)
  File "/home/colin/.local/lib/python3.10/site-packages/peewee.py", line 3250, in execute_sql
    with __exception_wrapper__:
  File "/home/colin/.local/lib/python3.10/site-packages/peewee.py", line 3020, in __exit__
    reraise(new_type, new_type(exc_value, *exc_args), traceback)
  File "/home/colin/.local/lib/python3.10/site-packages/peewee.py", line 192, in reraise
    raise value.with_traceback(tb)
  File "/home/colin/.local/lib/python3.10/site-packages/peewee.py", line 3252, in execute_sql
    cursor.execute(sql, params or ())
peewee.IntegrityError: NOT NULL constraint failed: repomodel.name
2024-01-31 15:08:01,607 - vorta.scheduler - DEBUG - Refreshing all scheduler timers
2024-01-31 15:08:01,609 - vorta.scheduler - DEBUG - Scheduler for profile 1 is disabled.
2024-01-31 15:08:01,609 - vorta.scheduler - DEBUG - Scheduler for profile 2 is disabled.
```

**Comment by sten0** [comment]
@DandyDiamond, this looks like the issue to me:

>   File "/home/colin/.local/lib/python3.10/site-packages/peewee.py", line 7160, in get
>     return clone.execute(database)[0]
>   File "/home/colin/.local/lib/python3.10/site-packages/peewee.py", line 4510, in __getitem__
>     return self.row_cache[item]
> IndexError: list index out of range

The user "colin" appears to have used something like pip to install a custom version of Peewee that is incompatible with Vorta 0.8.3.  Do you know why this version of Peewee was installed for this user?

**Comment by sten0** [comment]
Hi!  I see you've closed this issue, so I'm guessing you figured it out,
but I want to make sure there's nothing that can be improved.

> Thank you for your reply.  I don't know where this custom version of Peewee has come from.  It is a pretty clean machine as I have just rebuilt it.  Not being familiar with Pip and Python, can I ask how to install the correct version?

You're welcome!  Your question includes the hint, and I wonder if you
installed Vorta using pip, and then again using?  If you followed
documentation that lead you down that path then I'd consider that a bug
in the documentation, and I'd like to fix it.

> TIA
>
> (When I get a problem with another programme, I will know where it came from! :lol)

:) If you think that you'll regularly be installing new software onto an
LTS distribution release, my top recommendation is to request backports
from your distribution, followed by flatpak, followed by PPAs, followed
by other methods.  At least the next Ubuntu LTS is just around the
corner so this will be less of an issue.  P.S. What you may have read
about waiting until mid-summer to upgrade is true in my experience.
