### ISSUE TITLE
Error on mount

### ISSUE THREAD

**Issue by heyarne** [borgbase/vorta#192]
**Describe the bug**
I get an exception when trying to mount an archive. The log output reads like this:

```
2019-02-15 16:43:53,945 - vorta.borg.borg_thread - INFO - Running command borg mount --log-json $REPOSITORY::plume-home-2019-01-31T16:59:00 /home/arne/tmp/backup
2019-02-15 16:44:06,819 - vorta.borg.borg_thread - ERROR - Local Exception
2019-02-15 16:44:06,820 - vorta.borg.borg_thread - ERROR - Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/borg/archiver.py", line 4436, in main
    exit_code = archiver.run(args)
  File "/usr/lib/python3.7/site-packages/borg/archiver.py", line 4368, in run
    return set_ec(func(args))
  File "/usr/lib/python3.7/site-packages/borg/archiver.py", line 1353, in do_mount
    return self._do_mount(args)
  File "/usr/lib/python3.7/site-packages/borg/archiver.py", line 152, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/usr/lib/python3.7/site-packages/borg/archiver.py", line 1363, in _do_mount
    operations.mount(args.mountpoint, args.options, args.foreground)
  File "/usr/lib/python3.7/site-packages/borg/fuse.py", line 323, in mount
    self._create_filesystem()
  File "/usr/lib/python3.7/site-packages/borg/fuse.py", line 252, in _create_filesystem
    self.process_archive(self.args.location.archive)
  File "/usr/lib/python3.7/site-packages/borg/fuse.py", line 377, in process_archive
    consider_part_files=self.args.consider_part_files):
  File "/usr/lib/python3.7/site-packages/borg/fuse.py", line 160, in iter_archive_items
    item = unpacker.unpack(write_bytes)
TypeError: unpack() takes no arguments (1 given)

Platform: Linux plume 4.20.8-arch1-1-ARCH #1 SMP PREEMPT Wed Feb 13 00:06:58 UTC 2019 x86_64
Linux: arch  
Borg: 1.1.8  Python: CPython 3.7.2
PID: 29132  CWD: /home/arne
sys.argv: ['/usr/bin/borg', 'mount', '--log-json', '$REPOSITORY::plume-home-2019-01-31T16:59:00', '/home/arne/tmp/backup']
SSH_ORIGINAL_COMMAND: None
```

**To Reproduce**
1. Go to Archives
2. Click on any archive
3. Click on the mount button

**Desktop (please complete the following information):**
 - OS: Arch Linux (4.20.8-arch1-1-ARCH)
- Vorta version 0.6.8

**Comment by ThomasWaldmann** [comment]
You are using an unsupported msgpack(-python) version, install 0.5.6.
