### ISSUE TITLE
Cannot delete a backup.

### ISSUE THREAD

**Issue by Giger22** [borgbase/vorta#1932]
### Description

Cannot delete an archive.

### Reproduction

- [X] I tried to reproduce the issue.
- [X] I was able to reproduce the issue.

### OS

Artix Linux

### Version of Vorta

0.9.1

### What did you install Vorta with?

Other

### Version of Borg

1.2.7

### Logs

```pytb
Uncaught exception, please file a report with this text at
https://github.com/borgbase/vorta/issues/new
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/peewee.py", line 7160, in get
    return clone.execute(database)[0]
           ~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/usr/lib/python3.11/site-packages/peewee.py", line 4510, in __getitem__
    return self.row_cache[item]
           ~~~~~~~~~~~~~~^^^^^^
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/vorta/views/archive_tab.py", line 922, in delete_result
    ArchiveModel.get(name=archive).delete_instance()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/peewee.py", line 6712, in get
    return sq.get()
           ^^^^^^^^
  File "/usr/lib/python3.11/site-packages/peewee.py", line 7163, in get
    raise self.model.DoesNotExist('%s instance matching query does '
vorta.store.models.ArchiveModelDoesNotExist: <Model: ArchiveModel> instance matching query does not exist:
SQL: SELECT "t1"."id", "t1"."snapshot_id", "t1"."name", "t1"."repo_id", "t1"."time", "t1"."duration", "t1"."size", "t1"."trigger" FROM "archivemodel" AS "t1" WHERE ("t1"."name" = ?) LIMIT ? OFFSET ?
Params: ['username-2024-02-12-121053', 1, 0]
```

**Comment by real-yfprojects** [comment]
Does it happen for any archive or only for a specific one?

**Comment by Giger22** [comment]
I checked and only for this one so far.

**Comment by real-yfprojects** [comment]
> I checked and only for this one so far.

How are you able to reproduce this issue for this specific archive? Does it still remain in the table or does it appear after a software restart? If so this still shouldn't be possible since the error occurs after borg already deleted it successfully.

**Comment by Giger22** [comment]
I checked and the error disappeared and I could delete the archive. Weird.
