### ISSUE TITLE
Error Waking In The Morning

### ISSUE THREAD

**Issue by nmcbride** [borgbase/vorta#1953]
#### Description

Whenever I wake up in the morning and wake my computer from sleep I get the below error and then a notification about the error. I'm assuming while in sleep, and I'm not even going into deep sleep or hibernation or anything, my wireless may be getting disconnected until I wake.

#### Environment

- OS: Fedora
- Vorta version: 0.8.12
- Installed from: Flatpak
- Borg version: 1.2.7

#### Logs
```
2024-03-02 13:35:40,775 - vorta.network_status.network_manager - ERROR - Failed to get currently connected WiFi network, assuming none
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/vorta/network_status/network_manager.py", line 33, in get_current_wifi
    active_connection = self._nm.get_active_connection_info(active_connection_path)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/vorta/network_status/network_manager.py", line 133, in get_active_connection_info
    connection=read_dbus_property(active_connection, 'Connection'),
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/vorta/network_status/network_manager.py", line 160, in read_dbus_property
    return get_result(msg)
           ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/vorta/network_status/network_manager.py", line 167, in get_result
    raise DBusException("DBus call failed: {}".format(msg.arguments()))
vorta.network_status.network_manager.DBusException: DBus call failed: ['Object does not exist at path “/”']
```

**Comment by m3nu** [comment]
Usually our network checks shouldn't cause a real error. So this could be just for debugging. If it causes a real error, we should catch it.
