### ISSUE TITLE
uncaught exception

### ISSUE THREAD

**Issue by MajaToebs** [borgbase/vorta#2007]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/vorta/application.py", line 185, in set_borg_details_result
    self.scheduler.reload_all_timers()  # Start timer after Borg version is set.
  File "/usr/lib/python3/dist-packages/vorta/scheduler.py", line 121, in reload_all_timers
    self.set_timer_for_profile(profile.id)
  File "/usr/lib/python3/dist-packages/vorta/scheduler.py", line 111, in set_timer_for_profile
    timer.setInterval(int(timer_ms))
OverflowError: argument 1 overflowed: value must be in the range -2147483648 to 2147483647

**Comment by MajaToebs** [comment]
crash resolved by changing setting for backup schedule to "manual backup". Probably, the reason for the error and crash before was that I had chosen "backup every 4 weeks" which was a too long time span...

**Comment by MajaToebs** [comment]
everything works again
