### ISSUE TITLE
Unable to link to existing repo over SSH

### ISSUE THREAD

**Issue by hoopahmadness** [borgbase/vorta#2070]
I moved all vorta flatpak files over from an old installation. I have two repos that are basically identical except they touch different remotes and have different passwords (and one had an optional profile name while the other did not). The keyrings with the saved passwords are gone so I unlinked both repos and attempted to re-link them. One worked fine; the other is giving me this error:

```Uncaught exception, please file a report with this text at
https://github.com/borgbase/vorta/issues/new
Traceback (most recent call last):
  File "/app/lib/python3.11/site-packages/peewee.py", line 7285, in get
    return clone.execute(database)[0]
           ~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/app/lib/python3.11/site-packages/peewee.py", line 4581, in __getitem__
    return self.row_cache[item]
           ~~~~~~~~~~~~~~^^^^^^
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/lib/python3.11/site-packages/vorta/application.py", line 227, in react_to_log
    profile = BackupProfileModel.get(name=context['profile_name'])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/peewee.py", line 6833, in get
    return sq.get()
           ^^^^^^^^
  File "/app/lib/python3.11/site-packages/peewee.py", line 7288, in get
    raise self.model.DoesNotExist('%s instance matching query does '
vorta.store.models.BackupProfileModelDoesNotExist: <Model: BackupProfileModel> instance matching query does not exist:
SQL: SELECT "t1"."id", "t1"."name", "t1"."added_at", "t1"."repo_id", "t1"."ssh_key", "t1"."compression", "t1"."exclude_patterns", "t1"."exclude_if_present", "t1"."schedule_mode", "t1"."schedule_interval_count", "t1"."schedule_interval_unit", "t1"."schedule_fixed_hour", "t1"."schedule_fixed_minute", "t1"."schedule_interval_hours", "t1"."schedule_interval_minutes", "t1"."schedule_make_up_missed", "t1"."validation_on", "t1"."validation_weeks", "t1"."prune_on", "t1"."prune_hour", "t1"."prune_day", "t1"."prune_week", "t1"."prune_month", "t1"."prune_year", "t1"."prune_keep_within", "t1"."new_archive_name", "t1"."prune_prefix", "t1"."pre_backup_cmd", "t1"."post_backup_cmd", "t1"."dont_run_on_metered_networks" FROM "backupprofilemodel" AS "t1" WHERE ("t1"."name" = ?) LIMIT ? OFFSET ?
Params: ['New Repo', 1, 0]
```

I've tried using `borg info <repo>` and verified on the remote that the repo looks fine and expects the correct password. Not sure what to make of this. This is the repo that originally had an optional profile name, but I did not write it down before unlinking so I don't know what it was. IS it possible that having non-matching profile names is the problem?

**Comment by m3nu** [comment]
This is a common error. I see it's from the logs. Time to fix it. It doesn't look related to adding a repo, since it's about logging.

**Comment by m3nu** [comment]
This specific case should already be fixed. It happened when a repo couldn't be added and Vorta still tried to get it from the database. So the bug was in `vorta/application.py:react_to_log()`

**Comment by hoopahmadness** [comment]
I can't verify that it's fixed because I ended up just removing and starting the repo over. But I'll close this, thank you for working on this.
