### ISSUE TITLE
Serious error

### ISSUE THREAD

**Issue by Golddouble** [borgbase/vorta#2105]
```
Uncaught exception, please file a report with this text at
https://github.com/borgbase/vorta/issues/new
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/vorta/views/partials/treemodel.py", line 987, in lessThan
    data2 = self.choose_data(right)
            ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/vorta/views/extract_dialog.py", line 251, in choose_data
    return item.data.health
           ^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'data'
```

MX-Linux 23 Xfce

Thank you.

**Comment by Golddouble** [comment]
[vorta.log.zip](https://github.com/user-attachments/files/17450248/vorta.log.zip)

**Comment by m3nu** [comment]
> Vorta 0.8.12; Borg: 1.2.4

Very old version. Have you tried the latest version? https://github.com/borgbase/vorta/releases/tag/v0.10.0-beta1

**Comment by Golddouble** [comment]
No, newer versions are not in the MX-Repo to install.

**Comment by Golddouble** [comment]
What details do you need?

**Comment by m3nu** [comment]
Have you verified if the error still happens in the current `master` branch? I see the function already changed and shouldn't return `None`, as seen in the error: https://github.com/borgbase/vorta/blob/master/src/vorta/views/extract_dialog.py#L264

If yes, I'll need the line that is output by Borg for that file. Since I don't have your files to test locally.

**Comment by Golddouble** [comment]
What do you mean with "master branch"? Do you mean, I should somehow change the code of my Vorta version? I can not do that. I am not so skilled. Last version of Vorta in my reopsitory is 0.9.1.. I can not test the beta.

**Comment by Golddouble** [comment]
You gave me the link ...
https://github.com/borgbase/vorta/blob/master/src/vorta/views/extract_dialog.py#L264
.... are you trying to say that the code section  `def choose_data(self, index: QModelIndex):`

... has changed. And is now different from the code section in version 0.9.1 ?
I can not find a difference. It's still the same code in this section.

Thank you for your endeavours.

**Comment by sten0** [comment]
@Golddouble I just uploaded 0.10.0 (and 0.10.1) to Debian, and this will show up in MX Linux at some point.  You may be able to expedite this process by filing an MX Linux bug, linking to this Vorta github issue, and mentioning that the bug should be fixed in the newest releases of Vorta.

**Comment by Golddouble** [comment]
Thank you.
