### ISSUE TITLE
"File name too long" when calculating source size (exclusions not respected?)

### ISSUE THREAD

**Issue by HarukaMa** [borgbase/vorta#2115]
### Description

I've been getting the error in title when trying to calculate the file count and size of the source, which is the root directory (`/`). Looks like Vorta somehow is not following exclude rules.

I have custom added rules:
```
# custom added rules
/dev
/proc
/sys
/tmp
/run
*/.aleo/storage
*/.cache
/mnt
```
However, as seen in the log below, Vorta traversed into `/mnt/hgfs`. I can confirm the rules work during backups; `/mnt` is not included in actual backup archives.

### Reproduction

- [X] I tried to reproduce the issue.
- [X] I was able to reproduce the issue.

### OS

Debian sid, remote x11 display

### Version of Vorta

0.10.3

### What did you install Vorta with?

Distribution package

### Version of Borg

1.4.0

### Logs

```pytb
2024-10-28 21:54:01,862 - root - CRITICAL - Uncaught exception, file a report at https://github.com/borgbase/vorta/issues/new/choose
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/vorta/utils.py", line 49, in run
    self.size, self.files_count = get_path_datasize(self.path, self.exclude_patterns)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/vorta/utils.py", line 147, in get_path_datasize
    data_size, files_count = get_directory_size(file_info.absoluteFilePath(), exclude_patterns)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/vorta/utils.py", line 117, in get_directory_size
    stat = os.stat(file_path)
           ^^^^^^^^^^^^^^^^^^
OSError: [Errno 36] File name too long: '/mnt/hgfs/C/Program Files/JetBrains/Rider/r2r/2024.2.6R/B9F0CD415B130D99FE8E857FF5CFE9E/windows-x64/dotnet/sdk/8.0.204/DotnetTools/dotnet-watch/8.0.204-servicing.24170.23/tools/net8.0/any/BuildHost-netcore/Microsoft.CodeAnalysis.Workspaces.MSBuild.BuildHost.runtimeconfig.json'
```

**Comment by HarukaMa** [comment]
Auto stale and close is bad for project managements. You just miss bugs that were not attended to for whatever reason.

**Comment by m3nu** [comment]
Hi, this bug report is for a pretty old version of Vorta. If it still happens with the latest released version, we can reopen it.

The error also comes from a Python function and not from our code. So there is nothing we could do in Vorta to remove this limit.

**Comment by HarukaMa** [comment]
Hi, I just tested on v0.10.3 and I'm still getting the same issue:

```
2025-02-05 04:08:24,236 - root - CRITICAL - Uncaught exception, file a report at https://github.com/borgbase/vorta/issues/new/choose
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/vorta/utils.py", line 49, in run
    self.size, self.files_count = get_path_datasize(self.path, self.exclude_patterns)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/vorta/utils.py", line 147, in get_path_datasize
    data_size, files_count = get_directory_size(file_info.absoluteFilePath(), exclude_patterns)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/vorta/utils.py", line 117, in get_directory_size
    stat = os.stat(file_path)
           ^^^^^^^^^^^^^^^^^^
OSError: [Errno 36] File name too long: '/mnt/hgfs/C/Program Files/JetBrains/Rider/r2r/2024.3.3R/AB5FF474EB7A62ECE211BC07DEE6CF9/windows-x64/dotnet/sdk/8.0.204/DotnetTools/dotnet-watch/8.0.204-servicing.24170.23/tools/net8.0/any/BuildHost-netcore/Microsoft.CodeAnalysis.Workspaces.MSBuild.BuildHost.runtimeconfig.json'
```

Also, of course it comes from a python function as it's `os.stat` reporting the error, but the issue is not about "removing the limit". I think the original report is pretty clear on this.

**Comment by m3nu** [comment]
I don't think that Vorta can respect exclusions when calculating folder sizes. Since we can't re-implement processing exclusions. I believe this came up before.

So to address this, we could only catch this error and then skip the file.

If someone would like to suggest a PR for this, I would review it.

**Comment by sersorrel** [comment]
Right, yes, here's the problem:

```
> /nix/store/pnm9zy0whbn89pfvbrw8y7800s7gp59j-vorta-0.10.3/lib/python3.12/site-packages/vorta/utils.py(41)__init__()
-> self.exclude_patterns = []
(Pdb) p exclude_patterns_str
None
(Pdb) u
> /nix/store/pnm9zy0whbn89pfvbrw8y7800s7gp59j-vorta-0.10.3/lib/python3.12/site-packages/vorta/views/source_tab.py(208)update_path_info()
-> getDir = FilePathInfoAsync(path, self.profile().exclude_patterns)
(Pdb) p self.profile()
<BackupProfileModel: 1>
(Pdb) p self.profile().exclude_patterns
None
```

So why are the exclude patterns not available in `SourceTab.profile()`? Answer: despite my rules looking like this in the preview tab, even after I close and reopen the application:

```
# custom added rules
/dev
/media
/mnt
/proc
/run
/sys

# Exclude if present
.nobackup
CACHEDIR.TAG
```

my custom exclude patterns don't actually appear to be saved in the database:

```
sqlite> select id, exclude_patterns, compression from backupprofilemodel;
id|exclude_patterns|compression
1||zstd,3
```

And _that_ is because the "Custom" tab saves its exclusion patterns somewhere completely different (`backupprofilemodel.exclude_patterns` is only populated with patterns added in the "Raw" tab).

So the problem here is actually that the simple access to `self.profile().exclude_patterns` here:

https://github.com/borgbase/vorta/blob/f1c7e9259263c1e31c3af9873641e291e8d34e6a/src/vorta/views/source_tab.py#L208

fails to take into account that exclude patterns can come from myriad different places, not just the single free-text input which gets saved as `exclude_patterns` in the database.

As a workaround, you can put all your exclude patterns in the "Raw" tab by hand, ignoring "Custom" and "Presets".

**Comment by m3nu** [comment]
The new structured exclusions are saved in a different table called `exclusionmodel`. It doesn't go to the `backupprofilemodel`.

**Comment by twilight39** [comment]
Hi, I'd like to work on this issue, and would like some feedback.

The issue seems to be that the file path size calculator is passed the backupprofilemodel.exclude_ patterns column, which is null (possibly deprecated?)
https://github.com/borgbase/vorta/blob/0a316e7aa9ae8e61ff3a1e72dcd57c8a2b7976da/src/vorta/views/source_tab.py#L208

For reference, the create backup function uses a different function which returns the exclusionmodel table instead
https://github.com/borgbase/vorta/blob/0a316e7aa9ae8e61ff3a1e72dcd57c8a2b7976da/src/vorta/borg/create.py#L178-L184

PR https://github.com/borgbase/vorta/pull/2206 addresses this believe.

Instead, I'd like to create a PR to wrap the os.stat() function in a try-except block.
https://github.com/borgbase/vorta/blob/0a316e7aa9ae8e61ff3a1e72dcd57c8a2b7976da/src/vorta/utils.py#L116-L123

From my Googling, it seems that os.stat() fails when the underlying OS has a maximum path size limitation; e.g. on Windows 7 it defaults to 255 characters long. Would it be okay to just ignore the file if an error is thrown?

It's my first time contributing to OSS, so I apologise in advance if I'm missing something.

**Comment by m3nu** [comment]
Yes, no problem to ignore the error. I don't think it happens too often
