### ISSUE TITLE
Bad CPU type on MacbookPro M4

### ISSUE THREAD

**Issue by maximede** [borgbase/vorta#2131]
### Description

Hello, I'm having a bit of an issue with a brand new install on a new macbook pro m4.

Vorta cannot find borg in the about tab and fails when trying to add a new repo with a weird "Bad CPU type" error

![image](https://github.com/user-attachments/assets/7c6f84be-a9f7-432e-b54f-b7aca0815ab5)

```
OS: Darwin
Release: 24.1.0
Version: Darwin Kernel Version 24.1.0: Thu Oct 10 21:06:57 PDT 2024; root:xnu-11215.41.3~3/RELEASE_ARM64_T6041
Date and Time: 2024-11-13 13:29:45
Borg Version: 1.1.0
Vorta Version: 0.10.1
Traceback (most recent call last):
  File "views/repo_add_dialog.py", line 254, in run
  File "borg/borg_job.py", line 233, in run
  File "subprocess.py", line 1026, in __init__
  File "subprocess.py", line 1955, in _execute_child
OSError: [Errno 86] Bad CPU type in executable: '/Applications/Vorta.app/Contents/Resources/borg-dir/borg.exe'
```

Steps to reproduce 

``` 
brew install borgbackup
brew install vorta
``` 

I tried reinstalling both borgbackup and vorta, with no luck. 

Let me know if I can give more info ! 

Thanks

### Reproduction

- [X] I tried to reproduce the issue.
- [x] I was able to reproduce the issue.

### OS

MacOS Sequoia 15.1 (24B2083)

### Version of Vorta

0.10.1

### What did you install Vorta with?

Homebrew

### Version of Borg

No version in "about" , 1.4.0 in terminal

**Comment by maximede** [comment]
Well, not sure exactly what happened but after a couple reboot, vorta is now finding borg and I can't reproduce this "bad cpu" issue.

I'm now having the same issue as I had on my air m1 ( https://github.com/borgbase/vorta/issues/2100 ) but at least I'm ublocked :) 
  
I'm still happy happy trying to help identifying what happened

**Comment by ioExpander** [comment]
Hi. I'm on an M4 Pro MacbookPro and I'm getting a very similar issue. When Vorta is run it tries to launch borg.exe.
I've tried re-installing Vorta and borg via homebrew with no luck. 

```
2024-12-20 09:00:31,962 - vorta.borg.jobs_manager - DEBUG - Start job on site: default
2024-12-20 09:00:31,963 - vorta.borg.borg_job - INFO - Running command /Applications/Vorta.app/Contents/Resources/borg-dir/borg.exe --version
2024-12-20 09:00:59,740 - vorta.keyring.abc - DEBUG - No module named 'secretstorage'
```
Vorta Version 0.10.2

However when launching Vorta via the command line the homebrew Borg gets properly detected ! Can we get a release for [#2166](https://github.com/borgbase/vorta/pull/2166) as I suspect it might fix both issues ?

Thank you.

**Comment by m3nu** [comment]
Yes, good idea. I can do a release for #2166
