### ISSUE TITLE
Backup fails after update

### ISSUE THREAD

**Issue by Szelwin** [borgbase/vorta#2132]
### Description

Since recent update to v0.10.1, I'm unable to run backups. I don't know if the issue was also affecting v0.10.0. But the previous version before that was running smoothly for sure.

I have a simple setup with a single profile that backs up to BorgBase. Since updating v0.10.1, I noticed my background backups fail to happen. When I enter Vorta and click "Start Backup", it thinks for about half a second and then returns an error - "ModuleNotFoundError: No module named 'packaging".

![CleanShot 2024-11-14 at 07 24 23@2x](https://github.com/user-attachments/assets/86ef8b62-db0f-487c-acba-a9aa952f1f92)

### Reproduction

- [X] I tried to reproduce the issue.
- [ ] I was able to reproduce the issue.

### OS

macOS Sonoma 14.6.1

### Version of Vorta

0.10.1

### What did you install Vorta with?

Homebrew

### Version of Borg

1.1.0

### Logs

```pytb
2024-11-11 18:49:02,422 - vorta.scheduler - DEBUG - Refreshing all scheduler timers
2024-11-11 18:49:02,434 - vorta.scheduler - INFO - Setting timer for profile 1
2024-11-11 18:49:02,435 - vorta.scheduler - DEBUG - Scheduling next run for 2024-11-12 09:00:00
2024-11-11 19:04:02,436 - vorta.scheduler - DEBUG - Refreshing all scheduler timers
2024-11-11 19:04:02,440 - vorta.scheduler - INFO - Setting timer for profile 1
2024-11-11 19:04:02,441 - vorta.scheduler - DEBUG - Scheduling next run for 2024-11-12 09:00:00
2024-11-11 19:19:02,441 - vorta.scheduler - DEBUG - Refreshing all scheduler timers
2024-11-11 19:19:02,447 - vorta.scheduler - INFO - Setting timer for profile 1
2024-11-11 19:19:02,448 - vorta.scheduler - DEBUG - Scheduling next run for 2024-11-12 09:00:00
2024-11-11 19:34:02,442 - vorta.scheduler - DEBUG - Refreshing all scheduler timers
2024-11-11 19:34:02,447 - vorta.scheduler - INFO - Setting timer for profile 1
2024-11-11 19:34:02,448 - vorta.scheduler - DEBUG - Scheduling next run for 2024-11-12 09:00:00
2024-11-11 19:49:02,394 - vorta.scheduler - DEBUG - Refreshing all scheduler timers
2024-11-11 19:49:02,398 - vorta.scheduler - INFO - Setting timer for profile 1
2024-11-11 19:49:02,398 - vorta.scheduler - DEBUG - Scheduling next run for 2024-11-12 09:00:00
2024-11-11 20:04:02,394 - vorta.scheduler - DEBUG - Refreshing all scheduler timers
2024-11-11 20:04:02,399 - vorta.scheduler - INFO - Setting timer for profile 1
2024-11-11 20:04:02,400 - vorta.scheduler - DEBUG - Scheduling next run for 2024-11-12 09:00:00
2024-11-11 20:19:02,407 - vorta.scheduler - DEBUG - Refreshing all scheduler timers
2024-11-11 20:19:02,412 - vorta.scheduler - INFO - Setting timer for profile 1
2024-11-11 20:19:02,413 - vorta.scheduler - DEBUG - Scheduling next run for 2024-11-12 09:00:00
2024-11-12 08:04:43,047 - vorta.scheduler - DEBUG - Refreshing all scheduler timers
2024-11-12 08:04:43,054 - vorta.scheduler - INFO - Setting timer for profile 1
2024-11-12 08:04:43,056 - vorta.scheduler - DEBUG - Scheduling next run for 2024-11-12 09:00:00
2024-11-12 08:33:06,307 - vorta.scheduler - DEBUG - Refreshing all scheduler timers
2024-11-12 08:33:06,316 - vorta.scheduler - INFO - Setting timer for profile 1
2024-11-12 08:33:06,317 - vorta.scheduler - DEBUG - Scheduling next run for 2024-11-12 09:00:00
2024-11-12 08:34:42,331 - vorta.scheduler - DEBUG - Refreshing all scheduler timers
2024-11-12 08:34:42,334 - vorta.scheduler - INFO - Setting timer for profile 1
2024-11-12 08:34:42,335 - vorta.scheduler - DEBUG - Scheduling next run for 2024-11-12 09:00:00
2024-11-12 08:49:42,350 - vorta.scheduler - DEBUG - Refreshing all scheduler timers
2024-11-12 08:49:42,355 - vorta.scheduler - INFO - Setting timer for profile 1
2024-11-12 08:49:42,356 - vorta.scheduler - DEBUG - Scheduling next run for 2024-11-12 09:00:00
2024-11-12 09:00:00,371 - vorta.scheduler - INFO - Starting background backup for Default
2024-11-12 09:00:00,373 - vorta.notifications - DEBUG - notification not suppressed
2024-11-12 09:00:00,381 - vorta.keyring.abc - DEBUG - No module named 'secretstorage'
2024-11-12 09:00:00,382 - vorta.keyring.abc - DEBUG - Using VortaDarwinKeyring
2024-11-12 09:00:00,382 - vorta.borg.borg_job - DEBUG - Using VortaDarwinKeyring keyring to store passwords.
2024-11-12 09:00:00,387 - vorta.keyring.darwin - DEBUG - Retrieved password for repo ssh://f66z44o9@f66z44o9.repo.borgbase.com/./repo
2024-11-12 09:00:00,437 - root - DEBUG - Command ipconfig getpacket en3 failed
2024-11-12 09:00:00,443 - root - DEBUG - Command ipconfig getpacket en6 failed
2024-11-12 09:00:00,449 - root - DEBUG - Command ipconfig getpacket en4 failed
2024-11-12 09:00:00,455 - root - DEBUG - Command ipconfig getpacket bridge0 failed
2024-11-12 09:00:00,467 - root - DEBUG - Command ipconfig getpacket en1 failed
2024-11-12 09:00:00,473 - root - DEBUG - Command ipconfig getpacket en2 failed
2024-11-12 09:00:00,655 - vorta.scheduler - INFO - Preparation for backup successful.
2024-11-12 09:00:00,656 - vorta.borg.jobs_manager - DEBUG - Add job for site 1
2024-11-12 09:00:00,657 - vorta.borg.jobs_manager - DEBUG - Start job on site: 1
2024-11-12 09:00:00,677 - vorta.borg.borg_job - INFO - Running command /opt/homebrew/bin/borg create --list --progress --info --log-json --json --filter=AM -C lz4 --exclude-from /var/folders/_s/fg_43c091yj_0y7njq1ybq5m0000gn/T/tmpea8nobnd ssh://f66z44o9@f66z44o9.repo.borgbase.com/./repo::Marcins-MacBook-Air-2024-11-12-090000 /Users/marcin
2024-11-12 09:00:00,747 - vorta.borg.borg_job - WARNING - Traceback (most recent call last):
2024-11-12 09:00:00,748 - vorta.borg.borg_job - WARNING - File "/opt/homebrew/bin/borg", line 5, in <module>
2024-11-12 09:00:00,748 - vorta.borg.borg_job - WARNING - from borg.archiver import main
2024-11-12 09:00:00,748 - vorta.borg.borg_job - WARNING - File "/opt/homebrew/Cellar/borgbackup-fuse/1.4.0/libexec/lib/python3.11/site-packages/borg/__init__.py", line 1, in <module>
2024-11-12 09:00:00,748 - vorta.borg.borg_job - WARNING - from packaging.version import parse as parse_version
2024-11-12 09:00:00,748 - vorta.borg.borg_job - WARNING - ModuleNotFoundError: No module named 'packaging'
2024-11-12 09:00:00,855 - vorta.borg.jobs_manager - DEBUG - Finish job for site: 1
2024-11-12 09:00:00,855 - vorta.borg.jobs_manager - DEBUG - No more jobs for site: 1
2024-11-12 09:00:00,856 - vorta.scheduler - INFO - Setting timer for profile 1
2024-11-12 09:00:00,857 - vorta.scheduler - DEBUG - Scheduling next run for 2024-11-13 09:00:00
2024-11-12 09:00:00,980 - vorta.notifications - DEBUG - notification not suppressed
2024-11-12 09:00:00,980 - vorta.scheduler - INFO - Backup creation successful.
2024-11-12 09:00:00,980 - vorta.scheduler - INFO - Doing post-backup jobs for Default
2024-11-12 09:00:00,981 - vorta.scheduler - INFO - Finished background task for profile Default
2024-11-12 09:00:00,981 - vorta.notifications - DEBUG - notification not suppressed
2024-11-12 09:00:00,981 - vorta.scheduler - INFO - Setting timer for profile 1
2024-11-12 09:00:00,982 - vorta.scheduler - DEBUG - Scheduling next run for 2024-11-13 09:00:00
2024-11-12 09:04:42,373 - vorta.scheduler - DEBUG - Refreshing all scheduler timers
2024-11-12 09:04:42,378 - vorta.scheduler - INFO - Setting timer for profile 1
2024-11-12 09:04:42,379 - vorta.scheduler - DEBUG - Scheduling next run for 2024-11-13 09:00:00
2024-11-12 09:19:42,386 - vorta.scheduler - DEBUG - Refreshing all scheduler timers
2024-11-12 09:19:42,390 - vorta.scheduler - INFO - Setting timer for profile 1
2024-11-12 09:19:42,391 - vorta.scheduler - DEBUG - Scheduling next run for 2024-11-13 09:00:00
2024-11-12 09:34:42,387 - vorta.scheduler - DEBUG - Refreshing all scheduler timers
2024-11-12 09:34:42,392 - vorta.scheduler - INFO - Setting timer for profile 1
2024-11-12 09:34:42,393 - vorta.scheduler - DEBUG - Scheduling next run for 2024-11-13 09:00:00
2024-11-12 09:49:42,340 - vorta.scheduler - DEBUG - Refreshing all scheduler timers
2024-11-12 09:49:42,346 - vorta.scheduler - INFO - Setting timer for profile 1
2024-11-12 09:49:42,346 - vorta.scheduler - DEBUG - Scheduling next run for 2024-11-13 09:00:00
2024-11-12 10:04:42,339 - vorta.scheduler - DEBUG - Refreshing all scheduler timers
2024-11-12 10:04:42,344 - vorta.scheduler - INFO - Setting timer for profile 1
2024-11-12 10:04:42,345 - vorta.scheduler - DEBUG - Scheduling next run for 2024-11-13 09:00:00
2024-11-12 10:19:42,350 - vorta.scheduler - DEBUG - Refreshing all scheduler timers
2024-11-12 10:19:42,357 - vorta.scheduler - INFO - Setting timer for profile 1
2024-11-12 10:19:42,358 - vorta.scheduler - DEBUG - Scheduling next run for 2024-11-13 09:00:00
2024-11-12 10:34:42,315 - vorta.scheduler - DEBUG - Refreshing all scheduler timers
2024-11-12 10:34:42,320 - vorta.scheduler - INFO - Setting timer for profile 1
2024-11-12 10:34:42,321 - vorta.scheduler - DEBUG - Scheduling next run for 2024-11-13 09:00:00
2024-11-12 10:49:42,310 - vorta.scheduler - DEBUG - Refreshing all scheduler timers
2024-11-12 10:49:42,314 - vorta.scheduler - INFO - Setting timer for profile 1
2024-11-12 10:49:42,315 - vorta.scheduler - DEBUG - Scheduling next run for 2024-11-13 09:00:00
2024-11-12 11:04:42,306 - vorta.scheduler - DEBUG - Refreshing all scheduler timers
2024-11-12 11:04:42,313 - vorta.scheduler - INFO - Setting timer for profile 1
2024-11-12 11:04:42,314 - vorta.scheduler - DEBUG - Scheduling next run for 2024-11-13 09:00:00
2024-11-12 11:19:42,306 - vorta.scheduler - DEBUG - Refreshing all scheduler timers
2024-11-12 11:19:42,311 - vorta.scheduler - INFO - Setting timer for profile 1
2024-11-12 11:19:42,312 - vorta.scheduler - DEBUG - Scheduling next run for 2024-11-13 09:00:00
2024-11-12 11:34:42,304 - vorta.scheduler - DEBUG - Refreshing all scheduler timers
2024-11-12 11:34:42,309 - vorta.scheduler - INFO - Setting timer for profile 1
2024-11-12 11:34:42,310 - vorta.scheduler - DEBUG - Scheduling next run for 2024-11-13 09:00:00
2024-11-12 11:49:42,313 - vorta.scheduler - DEBUG - Refreshing all scheduler timers
2024-11-12 11:49:42,318 - vorta.scheduler - INFO - Setting timer for profile 1
2024-11-12 11:49:42,319 - vorta.scheduler - DEBUG - Scheduling next run for 2024-11-13 09:00:00
2024-11-12 12:04:42,313 - vorta.scheduler - DEBUG - Refreshing all scheduler timers
2024-11-12 12:04:42,321 - vorta.scheduler - INFO - Setting timer for profile 1
2024-11-12 12:04:42,322 - vorta.scheduler - DEBUG - Scheduling next run for 2024-11-13 09:00:00
2024-11-12 12:19:42,311 - vorta.scheduler - DEBUG - Refreshing all scheduler timers
2024-11-12 12:19:42,315 - vorta.scheduler - INFO - Setting timer for profile 1
2024-11-12 12:19:42,316 - vorta.scheduler - DEBUG - Scheduling next run for 2024-11-13 09:00:00
2024-11-12 12:34:42,352 - vorta.scheduler - DEBUG - Refreshing all scheduler timers
2024-11-12 12:34:42,356 - vorta.scheduler - INFO - Setting timer for profile 1
2024-11-12 12:34:42,357 - vorta.scheduler - DEBUG - Scheduling next run for 2024-11-13 09:00:00
2024-11-12 12:49:42,345 - vorta.scheduler - DEBUG - Refreshing all scheduler timers
2024-11-12 12:49:42,352 - vorta.scheduler - INFO - Setting timer for profile 1
2024-11-12 12:49:42,354 - vorta.scheduler - DEBUG - Scheduling next run for 2024-11-13 09:00:00
2024-11-12 13:04:42,348 - vorta.scheduler - DEBUG - Refreshing all scheduler timers
2024-11-12 13:04:42,353 - vorta.scheduler - INFO - Setting timer for profile 1
2024-11-12 13:04:42,354 - vorta.scheduler - DEBUG - Scheduling next run for 2024-11-13 09:00:00
2024-11-12 13:19:42,342 - vorta.scheduler - DEBUG - Refreshing all scheduler timers
2024-11-12 13:19:42,349 - vorta.scheduler - INFO - Setting timer for profile 1
2024-11-12 13:19:42,351 - vorta.scheduler - DEBUG - Scheduling next run for 2024-11-13 09:00:00
2024-11-12 13:34:42,353 - vorta.scheduler - DEBUG - Refreshing all scheduler timers
2024-11-12 13:34:42,360 - vorta.scheduler - INFO - Setting timer for profile 1
2024-11-12 13:34:42,362 - vorta.scheduler - DEBUG - Scheduling next run for 2024-11-13 09:00:00
2024-11-12 13:49:42,302 - vorta.scheduler - DEBUG - Refreshing all scheduler timers
2024-11-12 13:49:42,307 - vorta.scheduler - INFO - Setting timer for profile 1
2024-11-12 13:49:42,308 - vorta.scheduler - DEBUG - Scheduling next run for 2024-11-13 09:00:00
2024-11-12 14:04:42,295 - vorta.scheduler - DEBUG - Refreshing all scheduler timers
2024-11-12 14:04:42,299 - vorta.scheduler - INFO - Setting timer for profile 1
2024-11-12 14:04:42,300 - vorta.scheduler - DEBUG - Scheduling next run for 2024-11-13 09:00:00
2024-11-12 14:19:42,284 - vorta.scheduler - DEBUG - Refreshing all scheduler timers
2024-11-12 14:19:42,289 - vorta.scheduler - INFO - Setting timer for profile 1
2024-11-12 14:19:42,290 - vorta.scheduler - DEBUG - Scheduling next run for 2024-11-13 09:00:00
2024-11-12 14:34:42,310 - vorta.scheduler - DEBUG - Refreshing all scheduler timers
2024-11-12 14:34:42,315 - vorta.scheduler - INFO - Setting timer for profile 1
2024-11-12 14:34:42,316 - vorta.scheduler - DEBUG - Scheduling next run for 2024-11-13 09:00:00
2024-11-12 14:49:42,290 - vorta.scheduler - DEBUG - Refreshing all scheduler timers
2024-11-12 14:49:42,295 - vorta.scheduler - INFO - Setting timer for profile 1
2024-11-12 14:49:42,296 - vorta.scheduler - DEBUG - Scheduling next run for 2024-11-13 09:00:00
2024-11-12 15:04:42,340 - vorta.scheduler - DEBUG - Refreshing all scheduler timers
2024-11-12 15:04:42,345 - vorta.scheduler - INFO - Setting timer for profile 1
2024-11-12 15:04:42,346 - vorta.scheduler - DEBUG - Scheduling next run for 2024-11-13 09:00:00
2024-11-12 15:19:42,346 - vorta.scheduler - DEBUG - Refreshing all scheduler timers
2024-11-12 15:19:42,351 - vorta.scheduler - INFO - Setting timer for profile 1
2024-11-12 15:19:42,352 - vorta.scheduler - DEBUG - Scheduling next run for 2024-11-13 09:00:00
2024-11-12 15:34:42,321 - vorta.scheduler - DEBUG - Refreshing all scheduler timers
2024-11-12 15:34:42,326 - vorta.scheduler - INFO - Setting timer for profile 1
2024-11-12 15:34:42,327 - vorta.scheduler - DEBUG - Scheduling next run for 2024-11-13 09:00:00
2024-11-12 18:01:58,909 - vorta.scheduler - DEBUG - Refreshing all scheduler timers
2024-11-12 18:01:58,914 - vorta.scheduler - INFO - Setting timer for profile 1
2024-11-12 18:01:58,915 - vorta.scheduler - DEBUG - Scheduling next run for 2024-11-13 09:00:00
2024-11-12 18:16:58,319 - vorta.scheduler - DEBUG - Refreshing all scheduler timers
2024-11-12 18:16:58,327 - vorta.scheduler - INFO - Setting timer for profile 1
2024-11-12 18:16:58,329 - vorta.scheduler - DEBUG - Scheduling next run for 2024-11-13 09:00:00
2024-11-12 18:31:58,328 - vorta.scheduler - DEBUG - Refreshing all scheduler timers
2024-11-12 18:31:58,335 - vorta.scheduler - INFO - Setting timer for profile 1
2024-11-12 18:31:58,336 - vorta.scheduler - DEBUG - Scheduling next run for 2024-11-13 09:00:00
2024-11-12 18:46:58,331 - vorta.scheduler - DEBUG - Refreshing all scheduler timers
2024-11-12 18:46:58,340 - vorta.scheduler - INFO - Setting timer for profile 1
2024-11-12 18:46:58,341 - vorta.scheduler - DEBUG - Scheduling next run for 2024-11-13 09:00:00
```

**Comment by m3nu** [comment]
There is an error with your Homebrew Borg. Maybe try reinstalling it or use the non-FUSE version? Or remove them both and try the built-in Borg. I recall the package giving this error was recently removed from Borg-FUSE.

```
2024-11-12 09:00:00,677 - vorta.borg.borg_job - INFO - Running command /opt/homebrew/bin/borg create --list --progress --info --log-json --json --filter=AM -C lz4 --exclude-from /var/folders/_s/fg_43c091yj_0y7njq1ybq5m0000gn/T/tmpea8nobnd [ssh://f66z44o9@f66z44o9.repo.borgbase.com/./repo::Marcins-MacBook-Air-2024-11-12-090000](ssh://f66z44o9@f66z44o9.repo.borgbase.com/repo::Marcins-MacBook-Air-2024-11-12-090000) /Users/marcin
2024-11-12 09:00:00,747 - vorta.borg.borg_job - WARNING - Traceback (most recent call last):
2024-11-12 09:00:00,748 - vorta.borg.borg_job - WARNING - File "/opt/homebrew/bin/borg", line 5, in <module>
2024-11-12 09:00:00,748 - vorta.borg.borg_job - WARNING - from borg.archiver import main
2024-11-12 09:00:00,748 - vorta.borg.borg_job - WARNING - File "/opt/homebrew/Cellar/borgbackup-fuse/1.4.0/libexec/lib/python3.11/site-packages/borg/__init__.py", line 1, in <module>
2024-11-12 09:00:00,748 - vorta.borg.borg_job - WARNING - from packaging.version import parse as parse_version
2024-11-12 09:00:00,748 - vorta.borg.borg_job - WARNING - ModuleNotFoundError: No module named 'packaging'
```

**Comment by Szelwin** [comment]
Thank you so much! I removed the Homebrew Borg completely (running `brew uninstall borgbackup-fuse`) and, I guess, Vorta automatically switched to the bundled version which works fine. I appreciate your help :)

**Comment by 12ian34** [comment]
removing brew borg as above worked for me too!
