### ISSUE TITLE
File "/usr/lib/python3.12/site-packages/peewee.py", line 3291, in execute_sql

### ISSUE THREAD

**Issue by RampantPanda** [borgbase/vorta#2147]
### Description

Unable to run Vorta. Version 0.10.0-1 on garudalinux.
The error message:
```λ vorta
2024-11-21 08:24:32,686 - root - CRITICAL - Uncaught exception, file a report at https://github.com/borgbase/vorta/issues/new/choose
Traceback (most recent call last):
File "/usr/lib/python3.12/site-packages/peewee.py", line 3291, in execute_sql
cursor.execute(sql, params or ())
sqlite3.OperationalError: duplicate column name: compaction_on

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/bin/vorta", line 8, in <module>
sys.exit(main())
^^^^^^
File "/usr/lib/python3.12/site-packages/vorta/__main__.py", line 74, in main
init_db(sqlite_db)
File "/usr/lib/python3.12/site-packages/vorta/store/connection.py", line 91, in init_db
run_migrations(current_schema, con)
File "/usr/lib/python3.12/site-packages/vorta/store/migrations.py", line 254, in run_migrations
_apply_schema_update(
File "/usr/lib/python3.12/site-packages/vorta/store/migrations.py", line 272, in _apply_schema_update
migrate(*operations)
File "/usr/lib/python3.12/site-packages/playhouse/migrate.py", line 944, in migrate
operation.run()
File "/usr/lib/python3.12/site-packages/playhouse/migrate.py", line 162, in run
self._handle_result(method(*self.args, **kwargs))
File "/usr/lib/python3.12/site-packages/playhouse/migrate.py", line 156, in _handle_result
self._handle_result(item)
File "/usr/lib/python3.12/site-packages/playhouse/migrate.py", line 153, in _handle_result
result.run()
File "/usr/lib/python3.12/site-packages/playhouse/migrate.py", line 162, in run
self._handle_result(method(*self.args, **kwargs))
File "/usr/lib/python3.12/site-packages/playhouse/migrate.py", line 151, in _handle_result
self.execute(result)
File "/usr/lib/python3.12/site-packages/playhouse/migrate.py", line 147, in execute
self.migrator.database.execute(node)
File "/usr/lib/python3.12/site-packages/peewee.py", line 3299, in execute
return self.execute_sql(sql, params)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.12/site-packages/peewee.py", line 3289, in execute_sql
with __exception_wrapper__:
File "/usr/lib/python3.12/site-packages/peewee.py", line 3059, in __exit__
reraise(new_type, new_type(exc_value, *exc_args), traceback)
File "/usr/lib/python3.12/site-packages/peewee.py", line 192, in reraise
raise value.with_traceback(tb)
File "/usr/lib/python3.12/site-packages/peewee.py", line 3291, in execute_sql
cursor.execute(sql, params or ())
peewee.OperationalError: duplicate column name: compaction_on```

### Reproduction

- [X] I tried to reproduce the issue.
- [X] I was able to reproduce the issue.

### OS

Linux / Garuda / Plasma

### Version of Vorta

0.10.0-1

### What did you install Vorta with?

Distribution package

### Version of Borg

1.4.0-2 

### Logs

```pytb
Can't find the logs. Nothing at ~/.cache/Vorta
```

**Comment by RampantPanda** [comment]
Thanks!
