### ISSUE TITLE
  File "/usr/lib/python3.12/site-packages/peewee.py", line 3291, in execute_sql     cursor.execute(sql, params or ()) sqlite3.DatabaseError: file is not a database

### ISSUE THREAD

**Issue by wigiwee** [borgbase/vorta#2149]
#### Description

I've been using vorta for a while, I haven't opened or used it for a while, i have it configured for few repositories, now when i opened it, it threw this pop up, couldn't do anything, can't even create new repository.
I _was_/_wasn't_ able to reproduce the issue.

if i click any button on the app, i get crash report pop up, can't use it anymore
#### Environment

- OS: Arch Linux
- Vorta version: 0.10.0
- Installed from: Pacman v7.0
- Borg version: 1.4.0
- 
#### Logs

OS: Linux
Release: 6.6.62-1-lts
Version: #1 SMP PREEMPT_DYNAMIC Sun, 17 Nov 2024 16:35:16 +0000
Date and Time: 2024-11-24 20:45:42
Borg Version: 1.4.0
Vorta Version: 0.10.0
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/peewee.py", line 3291, in execute_sql
    cursor.execute(sql, params or ())
sqlite3.DatabaseError: file is not a database

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/vorta/application.py", line 112, in create_backup_action
    profile = BackupProfileModel.get(id=profile_id)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/peewee.py", line 6805, in get
    return sq.get()
           ^^^^^^^^
  File "/usr/lib/python3.12/site-packages/peewee.py", line 7253, in get
    return clone.execute(database)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/peewee.py", line 2011, in inner
    return method(self, database, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/peewee.py", line 2082, in execute
    return self._execute(database)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/peewee.py", line 2255, in _execute
    cursor = database.execute(self)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/peewee.py", line 3299, in execute
    return self.execute_sql(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/peewee.py", line 3289, in execute_sql
    with __exception_wrapper__:
  File "/usr/lib/python3.12/site-packages/peewee.py", line 3059, in __exit__
    reraise(new_type, new_type(exc_value, *exc_args), traceback)
  File "/usr/lib/python3.12/site-packages/peewee.py", line 192, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3.12/site-packages/peewee.py", line 3291, in execute_sql
    cursor.execute(sql, params or ())
peewee.DatabaseError: file is not a database

**Comment by m3nu** [comment]
`sqlite3.DatabaseError: file is not a database`

This would point to something bad happening to your SQLite settings database. You can find it in `~/.config/Vorta/settings.db` or similar on Linux.

**Comment by mariovor** [comment]
I saw the same error today as well on Manjaro and Vorta 0.10.1.
It solved itself after a restart of Vorta (I usually never reboot my laptop but keep it in sleep).
