### ISSUE TITLE
Uncaught exception - even after reinstallation

### ISSUE THREAD

**Issue by SprickW** [borgbase/vorta#2157]
With the client I can't get rid of former use of vorta/borg. Even after complete de- and re-installation (apt) the GUI shows formerly used profile names. Trying to define a new profile are add an existing repository to an existing profile leads to exceptions.

Fixing might cause time. So it would be of help to have some documentation to completely remove borg/vorta to allow a clean setup.      

Uncaught exception, please file a report with this text at
https://github.com/borgbase/vorta/issues/new
Traceback (most recent call last):
  File "/home/sprickw/.local/lib/python3.10/site-packages/peewee.py", line 3246, in execute_sql
    cursor.execute(sql, params or ())
sqlite3.IntegrityError: NOT NULL constraint failed: backupprofilemodel.compaction_on

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sprickw/.local/lib/python3.10/site-packages/vorta/views/profile_add_edit_dialog.py", line 38, in save
  File "/home/sprickw/.local/lib/python3.10/site-packages/playhouse/signals.py", line 71, in save
    ret = super(Model, self).save(*args, **kwargs)
  File "/home/sprickw/.local/lib/python3.10/site-packages/peewee.py", line 6787, in save
    pk = self.insert(**field_dict).execute()
  File "/home/sprickw/.local/lib/python3.10/site-packages/peewee.py", line 1966, in inner
    return method(self, database, *args, **kwargs)
  File "/home/sprickw/.local/lib/python3.10/site-packages/peewee.py", line 2037, in execute
    return self._execute(database)
  File "/home/sprickw/.local/lib/python3.10/site-packages/peewee.py", line 2842, in _execute
    return super(Insert, self)._execute(database)
  File "/home/sprickw/.local/lib/python3.10/site-packages/peewee.py", line 2555, in _execute
    cursor = database.execute(self)
  File "/home/sprickw/.local/lib/python3.10/site-packages/peewee.py", line 3254, in execute
    return self.execute_sql(sql, params)
  File "/home/sprickw/.local/lib/python3.10/site-packages/peewee.py", line 3244, in execute_sql
    with __exception_wrapper__:
  File "/home/sprickw/.local/lib/python3.10/site-packages/peewee.py", line 3014, in __exit__
    reraise(new_type, new_type(exc_value, *exc_args), traceback)
  File "/home/sprickw/.local/lib/python3.10/site-packages/peewee.py", line 192, in reraise
    raise value.with_traceback(tb)
  File "/home/sprickw/.local/lib/python3.10/site-packages/peewee.py", line 3246, in execute_sql
    cursor.execute(sql, params or ())
peewee.IntegrityError: NOT NULL constraint failed: backupprofilemodel.compaction_on

**Comment by m3nu** [comment]
Your settings DB may still be around. You can find it in `~/.config/Vorta/settings.db` or similar on Linux.

**Comment by SprickW** [comment]
> Your settings DB may still be around. You can find it in `~/.config/Vorta/settings.db` or similar on Linux.

That was my first idea also. But there is no ~/.config/Vorta directory - which is a bit strange.

**Comment by madeddy** [comment]
>... there is no ~/.config/Vorta directory - which is a bit strange.

No, why should it be.
AFAIK it depends also on the install method and location and from the look of it you installed vorta like myself with PIP. Try to look in `/home/USERNAME/.local/share/Vorta/`
