### ISSUE TITLE
Vorta not storing allowed network for each profile 

### ISSUE THREAD

**Issue by nisfisker** [borgbase/vorta#2159]
#### Description
When having multiple profiles in Vorta it won't store the allowed wifi-networks individually.

I have two profiles in my Vorta backup menu on Mac OS, running Vorta 0.10.1.
They both point to the same borg repository using the WAN IP address or LAN IP address. The profile with the LAN IP should only backup when the computer sees the "home LAN", the other repo when being away from home on other wifi networks.

To reproduce the bug, do the following:
1. Click on a the first Vorta profile
2. Click Schedule
3. Click on Networks
4. Uncheck a couple of WIFI networks
5. Close the Vorta window

Now it _sometimes_ stores the unchecked network, sometimes not. But the network list is the same across all profiles. To verify that the list is the same do the following:
7. Open the Vorta window
8. Go to the second Vorta profile
9. Click Schedule
10. Click Networks
11. Confirm that the list of WIFI networks is the same as chosen in point 5 above. 
12. Click on the first Vorta profile and notice how the network list stays the same.
 

#### Environment
- OS: Mac OSX
- Vorta version: 0.10.1
- Installed from: brew
- Borg version: 1.4.0

#### Logs

```
2024-12-02 19:58:36,941 - vorta.views.source_tab - DEBUG - Added item number 0 from 1
2024-12-02 19:58:36,941 - vorta.views.source_tab - DEBUG - Added item number 1 from 2
2024-12-02 19:58:36,942 - vorta.views.source_tab - DEBUG - Added item number 2 from 3
2024-12-02 19:58:36,942 - vorta.views.source_tab - DEBUG - Added item number 3 from 4
2024-12-02 19:58:36,942 - vorta.views.source_tab - DEBUG - Added item number 4 from 5
2024-12-02 19:58:36,942 - vorta.views.source_tab - DEBUG - Added item number 5 from 6
2024-12-02 19:58:36,943 - vorta.views.source_tab - DEBUG - Added item number 6 from 7
2024-12-02 19:58:36,943 - vorta.views.source_tab - DEBUG - Added item number 7 from 8
2024-12-02 19:58:36,943 - vorta.views.source_tab - DEBUG - Added item number 8 from 9
2024-12-02 19:58:36,943 - vorta.views.source_tab - DEBUG - Added item number 9 from 10
2024-12-02 19:58:36,943 - vorta.views.source_tab - DEBUG - Added item number 10 from 11
2024-12-02 19:58:36,944 - vorta.views.source_tab - DEBUG - Added item number 11 from 12
2024-12-02 19:58:36,944 - vorta.views.source_tab - DEBUG - Added item number 12 from 13
2024-12-02 19:58:49,353 - vorta.scheduler - DEBUG - Scheduler for profile 2 is disabled.
2024-12-02 19:58:49,355 - vorta.scheduler - DEBUG - Scheduler for profile 2 is disabled.
2024-12-02 19:58:49,357 - vorta.views.source_tab - DEBUG - Added item number 0 from 1
2024-12-02 19:58:49,357 - vorta.views.source_tab - DEBUG - Added item number 1 from 2
2024-12-02 19:58:49,357 - vorta.views.source_tab - DEBUG - Added item number 2 from 3
2024-12-02 19:58:49,358 - vorta.views.source_tab - DEBUG - Added item number 3 from 4
2024-12-02 19:58:49,358 - vorta.views.source_tab - DEBUG - Added item number 4 from 5
2024-12-02 19:58:49,358 - vorta.views.source_tab - DEBUG - Added item number 5 from 6
2024-12-02 19:58:49,358 - vorta.views.source_tab - DEBUG - Added item number 6 from 7
2024-12-02 19:58:49,359 - vorta.views.source_tab - DEBUG - Added item number 7 from 8
2024-12-02 19:58:49,359 - vorta.views.source_tab - DEBUG - Added item number 8 from 9
2024-12-02 19:58:49,359 - vorta.views.source_tab - DEBUG - Added item number 9 from 10
2024-12-02 19:58:49,359 - vorta.views.source_tab - DEBUG - Added item number 10 from 11
2024-12-02 19:58:49,360 - vorta.views.source_tab - DEBUG - Added item number 11 from 12
2024-12-02 19:59:00,997 - root - CRITICAL - Uncaught exception, file a report at https://github.com/borgbase/vorta/issues/new/choose
Traceback (most recent call last):
  File "peewee.py", line 7285, in get
  File "peewee.py", line 4581, in __getitem__
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "views/networks_page.py", line 52, in save_wifi_item
  File "peewee.py", line 6833, in get
  File "peewee.py", line 7288, in get
vorta.store.models.WifiSettingModelDoesNotExist: <Model: WifiSettingModel> instance matching query does not exist:
SQL: SELECT "t1"."id", "t1"."ssid", "t1"."last_connected", "t1"."allowed", "t1"."profile_id" FROM "wifisettingmodel" AS "t1" WHERE (("t1"."profile_id" = ?) AND ("t1"."ssid" = ?)) LIMIT ? OFFSET ?
Params: [2, 'monrovia', 1, 0]
2024-12-02 19:59:08,380 - root - CRITICAL - Uncaught exception, file a report at https://github.com/borgbase/vorta/issues/new/choose
Traceback (most recent call last):
  File "peewee.py", line 7285, in get
  File "peewee.py", line 4581, in __getitem__
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "views/networks_page.py", line 52, in save_wifi_item
  File "peewee.py", line 6833, in get
  File "peewee.py", line 7288, in get
vorta.store.models.WifiSettingModelDoesNotExist: <Model: WifiSettingModel> instance matching query does not exist:
SQL: SELECT "t1"."id", "t1"."ssid", "t1"."last_connected", "t1"."allowed", "t1"."profile_id" FROM "wifisettingmodel" AS "t1" WHERE (("t1"."profile_id" = ?) AND ("t1"."ssid" = ?)) LIMIT ? OFFSET ?
Params: [2, 'Mads', 1, 0]
2024-12-02 19:59:12,330 - root - CRITICAL - Uncaught exception, file a report at https://github.com/borgbase/vorta/issues/new/choose
Traceback (most recent call last):
  File "peewee.py", line 7285, in get
  File "peewee.py", line 4581, in __getitem__
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "views/networks_page.py", line 52, in save_wifi_item
  File "peewee.py", line 6833, in get
  File "peewee.py", line 7288, in get
vorta.store.models.WifiSettingModelDoesNotExist: <Model: WifiSettingModel> instance matching query does not exist:
SQL: SELECT "t1"."id", "t1"."ssid", "t1"."last_connected", "t1"."allowed", "t1"."profile_id" FROM "wifisettingmodel" AS "t1" WHERE (("t1"."profile_id" = ?) AND ("t1"."ssid" = ?)) LIMIT ? OFFSET ?
Params: [2, 'Hotel Air', 1, 0]
2024-12-02 19:59:20,221 - root - CRITICAL - Uncaught exception, file a report at https://github.com/borgbase/vorta/issues/new/choose
Traceback (most recent call last):
  File "peewee.py", line 7285, in get
  File "peewee.py", line 4581, in __getitem__
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "views/networks_page.py", line 52, in save_wifi_item
  File "peewee.py", line 6833, in get
  File "peewee.py", line 7288, in get
vorta.store.models.WifiSettingModelDoesNotExist: <Model: WifiSettingModel> instance matching query does not exist:
SQL: SELECT "t1"."id", "t1"."ssid", "t1"."last_connected", "t1"."allowed", "t1"."profile_id" FROM "wifisettingmodel" AS "t1" WHERE (("t1"."profile_id" = ?) AND ("t1"."ssid" = ?)) LIMIT ? OFFSET ?
Params: [2, 'eduroam', 1, 0]
2024-12-02 19:59:23,171 - root - CRITICAL - Uncaught exception, file a report at https://github.com/borgbase/vorta/issues/new/choose
Traceback (most recent call last):
  File "peewee.py", line 7285, in get
  File "peewee.py", line 4581, in __getitem__
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "views/networks_page.py", line 52, in save_wifi_item
  File "peewee.py", line 6833, in get
  File "peewee.py", line 7288, in get
vorta.store.models.WifiSettingModelDoesNotExist: <Model: WifiSettingModel> instance matching query does not exist:
SQL: SELECT "t1"."id", "t1"."ssid", "t1"."last_connected", "t1"."allowed", "t1"."profile_id" FROM "wifisettingmodel" AS "t1" WHERE (("t1"."profile_id" = ?) AND ("t1"."ssid" = ?)) LIMIT ? OFFSET ?
Params: [2, 'DTUsecure', 1, 0]
2024-12-02 19:59:25,846 - root - CRITICAL - Uncaught exception, file a report at https://github.com/borgbase/vorta/issues/new/choose
Traceback (most recent call last):
  File "peewee.py", line 7285, in get
  File "peewee.py", line 4581, in __getitem__
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "views/networks_page.py", line 52, in save_wifi_item
  File "peewee.py", line 6833, in get
  File "peewee.py", line 7288, in get
vorta.store.models.WifiSettingModelDoesNotExist: <Model: WifiSettingModel> instance matching query does not exist:
SQL: SELECT "t1"."id", "t1"."ssid", "t1"."last_connected", "t1"."allowed", "t1"."profile_id" FROM "wifisettingmodel" AS "t1" WHERE (("t1"."profile_id" = ?) AND ("t1"."ssid" = ?)) LIMIT ? OFFSET ?
Params: [2, 'Kattingevej26', 1, 0]
2024-12-02 19:59:28,243 - root - CRITICAL - Uncaught exception, file a report at https://github.com/borgbase/vorta/issues/new/choose
Traceback (most recent call last):
  File "peewee.py", line 7285, in get
  File "peewee.py", line 4581, in __getitem__
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "views/networks_page.py", line 52, in save_wifi_item
  File "peewee.py", line 6833, in get
  File "peewee.py", line 7288, in get
vorta.store.models.WifiSettingModelDoesNotExist: <Model: WifiSettingModel> instance matching query does not exist:
SQL: SELECT "t1"."id", "t1"."ssid", "t1"."last_connected", "t1"."allowed", "t1"."profile_id" FROM "wifisettingmodel" AS "t1" WHERE (("t1"."profile_id" = ?) AND ("t1"."ssid" = ?)) LIMIT ? OFFSET ?
Params: [2, 'Hotel Hafnia', 1, 0]
2024-12-02 19:59:31,664 - vorta.borg.jobs_manager - DEBUG - Finish job for site: 3
2024-12-02 19:59:31,664 - vorta.borg.jobs_manager - DEBUG - No more jobs for site: 3
2024-12-02 19:59:31,667 - vorta.scheduler - DEBUG - Nothing scheduled for profile 1 because of timeout until 2024-12-02 19:59:36.
2024-12-02 19:59:32,262 - vorta.notifications - DEBUG - notification not suppressed
2024-12-02 19:59:32,263 - vorta.scheduler - INFO - Backup creation successful.
2024-12-02 19:59:32,263 - vorta.scheduler - DEBUG - Unpaused 1
2024-12-02 19:59:32,264 - vorta.scheduler - INFO - Setting timer for profile 1
2024-12-02 19:59:32,265 - vorta.scheduler - DEBUG - Scheduling next run for 2024-12-02 20:29:31.660723
2024-12-02 19:59:32,266 - vorta.scheduler - INFO - Doing post-backup jobs for RaspberryPi WAN Daily
2024-12-02 19:59:32,269 - vorta.keyring.abc - DEBUG - No module named 'secretstorage'
2024-12-02 19:59:32,269 - vorta.keyring.abc - DEBUG - Using VortaDarwinKeyring
2024-12-02 19:59:32,269 - vorta.borg.borg_job - DEBUG - Using VortaDarwinKeyring keyring to store passwords.

```

**Comment by m3nu** [comment]
Can confirm this. Similar bug to #2152.

Is it possible that you forgot to update most settings in your refactored tab pages when the profile changes, @shivansh02?
