### ISSUE TITLE
Deal with malformed WiFi XML on macOS

### ISSUE THREAD

**Issue by rwaldspur** [borgbase/vorta#270]
**Describe the bug**
Consistent crash when opening GUI in title bar "Vorta for Borg Backup" on Mojave (macOS 10.14.4).

**To Reproduce**
1. Launch Vorta in Finder
2. Click on title bar "Vorta for Borg Backup"
3. Release the mouse button
4. "Vorta" as well as "vorta-darwin" processes will crash.

**Desktop (please complete the following information):**
Installed Vorta via brew, also installed directly via downloaded .dmg, and also tried installing via pip.  All crash in the same way.

I have two other machines each running Mojave 10.14.4 as well, and neither has this problem.
Trashed settings.db, as well as copied settings.db from another machine.
Still crashes.

Log mentions:
2019-04-25 00:38:48,078 - vorta.i18n - DEBUG - Loading translation failed for ['C'].
2019-04-25 00:38:48,128 - apscheduler.scheduler - INFO - Scheduler started
2019-04-25 00:38:48,283 - vorta.borg.borg_thread - INFO - Running command /var/folders/64/d3prsg9d4t3dz9g6mtyc5gmh000whh/T/

Edit: I think this log entry is a "false flag" of sorts -- I checked one of my other machines, and it also displays this.

Crash log and Vorta logs included.
[vorta.log](https://github.com/borgbase/vorta/files/3115763/vorta.log)

**Additional context**
[vorta-darwin_2019-04-24-232250.crash.zip](https://github.com/borgbase/vorta/files/3115756/vorta-darwin_2019-04-24-232250.crash.zip)

**Comment by m3nu** [comment]
Hi and thanks for reporting. I don't see anything useful in the logs. What happens if you run it via the Terminal?

E.g. `$ /Applications/Vorta.app/Contents/MacOS/vorta-darwin --foreground`

or from the same folder `$ ./Vorta.app/Contents/MacOS/vorta-darwin --foreground` (you get the idea)

**Comment by rwaldspur** [comment]
Sure, thanks.

Perhaps the most useful output is from the pip --foreground command... see last entry below... perhaps when it's polling for different wifi networks, or a network config?  I'm seeing some wifi network query stuff in the trace.

$ /Applications/Vorta.app/Contents/MacOS/vorta-darwin --foreground
2019-04-25 01:19:43,715 - vorta.i18n - DEBUG - Loading translation failed for ['en', 'en-US', 'en-Latn-US'].
2019-04-25 01:19:43,751 - apscheduler.scheduler - INFO - Scheduler started
Traceback (most recent call last):
  File "vorta/__main__.py", line 40, in <module>
  File "vorta/__main__.py", line 33, in main
  File "vorta/application.py", line 56, in __init__
  File "vorta/application.py", line 78, in open_main_window_action
  File "vorta/views/main_window.py", line 35, in __init__
  File "vorta/views/schedule_tab.py", line 29, in __init__
  File "vorta/views/schedule_tab.py", line 56, in populate_from_profile
  File "vorta/views/schedule_tab.py", line 60, in init_wifi
  File "vorta/utils.py", line 117, in get_sorted_wifis
  File "plistlib.py", line 1015, in load
  File "plistlib.py", line 325, in parse
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 2749, column 13
[18837] Failed to execute script __main__

OR... via same folder as you mention, I get the same result.

After installing with pip:
$ vorta --foreground
2019-04-25 01:27:34,808 - vorta.i18n - DEBUG - Loading translation failed for ['en', 'en-US', 'en-Latn-US'].
2019-04-25 01:27:34,810 - apscheduler.scheduler - INFO - Scheduler started
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/bin/vorta", line 11, in <module>
    load_entry_point('vorta==0.6.19', 'gui_scripts', 'vorta')()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/vorta/__main__.py", line 33, in main
    app = VortaApp(sys.argv, single_app=True)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/vorta/application.py", line 56, in __init__
    self.open_main_window_action()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/vorta/application.py", line 78, in open_main_window_action
    self.main_window = MainWindow(self)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/vorta/views/main_window.py", line 35, in __init__
    self.scheduleTab = ScheduleTab(self.scheduleTabSlot)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/vorta/views/schedule_tab.py", line 29, in __init__
    self.populate_from_profile()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/vorta/views/schedule_tab.py", line 56, in populate_from_profile
    self.init_wifi()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/vorta/views/schedule_tab.py", line 60, in init_wifi
    for wifi in get_sorted_wifis(self.profile()):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/vorta/utils.py", line 117, in get_sorted_wifis
    wifis = plistlib.load(plist_file).get('KnownNetworks')
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/plistlib.py", line 950, in load
    return p.parse(fp)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/plistlib.py", line 260, in parse
    self.parser.ParseFile(fileobj)
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 2749, column 13

**Comment by m3nu** [comment]
Much better. It fails while reading your Wifi history. How does `/Library/Preferences/SystemConfiguration/com.apple.airport.preferences.plist` look like? Since it can't be parsed it may not exist. Maybe this one Mac has no Wifi?

In that case we should catch that with an exception.

**Comment by rwaldspur** [comment]
Ok, the plist file looked fine, but I had a lot of entries in there -- around 35 or so preferred WiFi hotspots.  I deleted the plist file, logged out, and then logged back in again.  Now, with the clean file, I'm able to startup either the pip version or the binary installed with brew without incident:

$ vorta --foreground
2019-04-25 02:34:23,354 - vorta.i18n - DEBUG - Loading translation failed for ['en', 'en-US', 'en-Latn-US'].
2019-04-25 02:34:23,357 - apscheduler.scheduler - INFO - Scheduler started
2019-04-25 02:34:24,837 - vorta.borg.borg_thread - INFO - Running command /usr/local/bin/borg --version

I don't think there's anything super sensitive in the plist file, since the passwords are in the keychain, I believe, but for good measure I'll try to send you the "bad" plist privately.

Thanks!

**Comment by m3nu** [comment]
Good you fixed it. I guess there was a weird char or some syntax issue with that file, since the library we use couldn't parse it.

I'll add an exception for this and log it just in case.

Thanks for helping debug this!

**Comment by rwaldspur** [comment]
Great, btw, I'm having trouble figuring out how to privately send you the plist... via private message or email.  I am far from a GitHub expert.  ;)  Any suggestions?

**Comment by m3nu** [comment]
You can email it to `hello (at) borgbase.com`.

**Comment by m3nu** [comment]
PR for this is online. Not affecting many users I think.
