### ISSUE TITLE
problem with PyQt5 under ubuntu 19.10

### ISSUE THREAD

**Issue by fdeu** [borgbase/vorta#371]
Hello.
Installing vorta via pip in ubuntu 19.10 leads to a problem with spyder.
While installing vorta there appear two errors:
```bash
Successfully built vorta peewee
ERROR: spyder 3.3.6 requires pyqtwebengine<5.13; python_version >= "3", which is not installed.
ERROR: spyder 3.3.6 has requirement pyqt5<5.13; python_version >= "3", but you'll have pyqt5 5.13.1 which is incompatible.
Installing collected packages: appdirs, bcrypt, pynacl, paramiko, PyQt5-sip, pyqt5, peewee, tzlocal, apscheduler, helpdev, qdarkstyle, vorta
Successfully installed PyQt5-sip-12.7.0 appdirs-1.4.3 apscheduler-3.6.1 bcrypt-3.1.7 helpdev-0.6.10 paramiko-2.6.0 peewee-3.11.2 pynacl-1.3.0 pyqt5-5.13.1 qdarkstyle-2.7 tzlocal-2.0.0 vorta-0.6.23
```

After that I am unable to start spyder, because there appears the error:
```bash
Traceback (most recent call last):
  File "/home/user/anaconda3/lib/python3.7/site-packages/qtpy/QtWebEngineWidgets.py", line 22, in <module>
    from PyQt5.QtWebEngineWidgets import QWebEnginePage
ImportError: /home/user/anaconda3/lib/python3.7/site-packages/PyQt5/../../../libQt5Quick.so.5: undefined symbol: _ZN14QDistanceFieldC1ERKS_, version Qt_5_PRIVATE_API

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/anaconda3/bin/spyder", line 11, in <module>
    sys.exit(main())
  File "/home/user/anaconda3/lib/python3.7/site-packages/spyder/app/start.py", line 186, in main
    from spyder.app import mainwindow
  File "/home/user/anaconda3/lib/python3.7/site-packages/spyder/app/mainwindow.py", line 90, in <module>
    from qtpy import QtWebEngineWidgets  # analysis:ignore
  File "/home/user/anaconda3/lib/python3.7/site-packages/qtpy/QtWebEngineWidgets.py", line 26, in <module>
    from PyQt5.QtWebKitWidgets import QWebPage as QWebEnginePage
ModuleNotFoundError: No module named 'PyQt5.QtWebKitWidgets'

```

I was only able to fix this by removing vorta, all newly installed packages and reinstalling PyQt5 and pyqtweb.

**Desktop:**
 - OS: ubuntu 19.10
 - anaconda3

PS: I really enjoy using vorta. This is my first bug report, so i hope you forgive any missing information.

**Comment by Hofer-Julian** [comment]
I would strongly advise against the installation method via pip.
Spyder is a PyQt application as well and probably depend on a different version.

You can of course use virtual environments, but I would just use flatpak.
