### ISSUE TITLE
vorta not starting, qdarkstyle problem

### ISSUE THREAD

**Issue by fuelflo** [borgbase/vorta#383]
**Describe the bug**
vorta does not start due to problem with 'qdarkstyle'

**To Reproduce**
Start vorta from command line gives following error:

```
$ vorta
Traceback (most recent call last):
  File "/usr/bin/vorta", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3251, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3234, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3263, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'qdarkstyle' distribution was not found and is required by vorta

```

**Desktop (please complete the following information):**
 - Archlinux Kernel 5.3.11
 - Gnome 3.34.1
 - vorta 0.6.23 (from AUR)
 - python 3.8.0
 - python-qdarksytle 2.7
 - python2 2.7.17

Any ideas how to fix this, except installing the flatpak?

**Comment by fuelflo** [comment]
Hmm, sry for the trouble.
Recompiling:
> python-qdarkstyle
> python-apscheduler
> and
> python-helpdev
fixed the problem.
