### ISSUE TITLE
Vorta crashing since Manjaro update yesterday. 

### ISSUE THREAD

**Issue by JackDinn** [borgbase/vorta#390]
This is Vorta 0.6.23-1
```
❰greg❙~❱✔≻ vorta
Traceback (most recent call last):
  File "/usr/bin/vorta", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3252, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3235, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3264, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'vorta==0.6.23' distribution was not found and is required by the application

```

> System:    Host: greg-pc Kernel: 4.19.88-1-MANJARO x86_64 bits: 64 compiler: gcc v: 9.2.0 Desktop: KDE Plasma 5.17.4 
>            Distro: Manjaro Linux 
> Machine:   Type: Laptop System: Dell product: Inspiron 5767 v: N/A serial: <filter> 
>            Mobo: Dell model: 03XWWJ v: A00 serial: <filter> UEFI [Legacy]: Dell v: 1.0.0 date: 07/14/2016

**Comment by JackDinn** [comment]
I managed to get it working again after much fiddling around with these 3 packages, I removed and re-installed them many times. Eventually (for no reason that i can figure) i got it working again.

- python-apscheduler
- python-helpdev
- python-qdarkstyle

**Comment by ThomasWaldmann** [comment]
Considering it is ArchLinux-based, I'ld bet they just changed from Python 3.7 to 3.8.

Collateral damage by using an unstable distribution.

**Comment by JackDinn** [comment]
yes you would be correct, they have just changed to 3.8 but its all a little over my head, i do my best though.
