### ISSUE TITLE
Vorta often closes itself after the OS goes to sleep

### ISSUE THREAD

**Issue by Lazza** [borgbase/vorta#394]
**Describe the bug**

I use Vorta on macOS 10.14.6 Mojave and my computer is kept on all the time. Multiple times a day, and during the night, I close the lid so that it goes in sleep mode.

Often, I find that after opening the lid again, Vorta is not running anymore. I assume it closes by itself (or should I say it crashes) after macOS goes to sleep.

**To Reproduce**
1. Install Vorta on macOS
2. Keep it open all time
3. Put the computer into sleep mode one or a few times

**Desktop (please complete the following information):**
 - OS: macOS 10.14.6 Mojave

**Comment by m3nu** [comment]
Probably related to the other bug you reported #344? macOS cleans some files from the temp dir and Vorta crashes.

Did you try running it directly from Python?

I'm currently working on a [Go version of Vorta](https://github.com/borgbase/vorta-go), which would avoid the many issues of Pyinstaller. But it's not fully ready yet.

**Comment by Lazza** [comment]
It *could* be but the crashing behavior only started recently. Before, despite the icon was blank, everything used to work perfectly.

**Comment by m3nu** [comment]
Hard to tell without further details. Things to try:

- Run from Python directly (`$ pip install..`)
- If you use the app bundle, try running it from the terminal to get all log messages and potential error. `$ ./Vorta.app/Contents/MacOS/vorta-darwin`
- Any errors in the log? (Misc > Log)

**Comment by Lazza** [comment]
Alright, apologies for not checking the log before!

It looks like it crashes due to some I/O error?

```
2019-12-26 17:48:48,900 - vorta.scheduler - INFO - Backup creation successful.
2019-12-26 17:48:48,901 - vorta.scheduler - INFO - Doing post-backup jobs for Default
2019-12-26 17:48:48,905 - vorta.borg.borg_thread - DEBUG - Using VortaDarwinKeyring keyring to store passwords.
2019-12-26 17:48:48,911 - vorta.borg.borg_thread - INFO - Running command /var/folders/cx/hrfccmw10cvc78s6fnr2x9_00000gn/T/_MEIiKFxAr/bin/borg check --info --log-json /Volumes/Borg/sheik
2019-12-26 17:48:50,617 - vorta.borg.borg_thread - INFO - Starting repository check
2019-12-26 18:40:00,017 - apscheduler.scheduler - WARNING - Execution of job "VortaScheduler.create_backup (trigger: cron[hour='*/1', minute='40'], next run at: 2019-12-26 18:40:00 CET)" skipped: maximum number of running instances reached (1)
2019-12-26 19:40:00,000 - apscheduler.scheduler - WARNING - Execution of job "VortaScheduler.create_backup (trigger: cron[hour='*/1', minute='40'], next run at: 2019-12-26 19:40:00 CET)" skipped: maximum number of running instances reached (1)
2019-12-26 20:40:00,000 - apscheduler.scheduler - WARNING - Execution of job "VortaScheduler.create_backup (trigger: cron[hour='*/1', minute='40'], next run at: 2019-12-26 20:40:00 CET)" skipped: maximum number of running instances reached (1)
2019-12-26 20:54:10,716 - vorta.borg.borg_thread - WARNING - Exception ignored in: <bound method Repository.__del__ of <Repository /Volumes/Borg/sheik>>
2019-12-26 20:54:10,717 - vorta.borg.borg_thread - WARNING - Traceback (most recent call last):
2019-12-26 20:54:10,717 - vorta.borg.borg_thread - WARNING - File "borg/repository.py", line 178, in __del__
2019-12-26 20:54:10,717 - vorta.borg.borg_thread - WARNING - File "borg/repository.py", line 425, in close
2019-12-26 20:54:10,717 - vorta.borg.borg_thread - WARNING - File "borg/repository.py", line 1177, in close
2019-12-26 20:54:10,717 - vorta.borg.borg_thread - WARNING - File "borg/lrucache.py", line 50, in clear
2019-12-26 20:54:10,717 - vorta.borg.borg_thread - WARNING - File "borg/repository.py", line 1182, in _close_fd
2019-12-26 20:54:10,717 - vorta.borg.borg_thread - WARNING - ValueError: I/O operation on closed file
2019-12-26 20:54:10,719 - vorta.borg.borg_thread - ERROR - Local Exception
2019-12-26 20:54:10,720 - vorta.borg.borg_thread - ERROR - Traceback (most recent call last):
  File "borg/archiver.py", line 166, in wrapper
  File "borg/archiver.py", line 327, in do_check
  File "borg/repository.py", line 923, in check
  File "borg/repository.py", line 1378, in iter_objects
  File "borg/repository.py", line 1470, in _read
OSError: [Errno 5] Input/output error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "borg/archiver.py", line 4501, in main
  File "borg/archiver.py", line 4433, in run
  File "borg/archiver.py", line 166, in wrapper
  File "borg/repository.py", line 203, in __exit__
  File "borg/repository.py", line 425, in close
  File "borg/repository.py", line 1177, in close
  File "borg/lrucache.py", line 50, in clear
  File "borg/repository.py", line 1183, in _close_fd
OSError: [Errno 57] Socket is not connected

Platform: Darwin sheik.local 18.7.0 Darwin Kernel Version 18.7.0: Sun Dec  1 18:59:03 PST 2019; root:xnu-4903.278.19~1/RELEASE_X86_64 x86_64
Borg: 1.1.10  Python: CPython 3.5.7 msgpack: 0.5.6
PID: 62046  CWD: /
sys.argv: ['/var/folders/cx/hrfccmw10cvc78s6fnr2x9_00000gn/T/_MEIiKFxAr/bin/borg', 'check', '--info', '--log-json', '/Volumes/Borg/sheik']
SSH_ORIGINAL_COMMAND: None

2019-12-26 20:54:10,995 - vorta.scheduler - INFO - Finished background task for profile Default
2019-12-26 20:54:11,006 - apscheduler.executors.default - INFO - Job "VortaScheduler.create_backup (trigger: cron[hour='*/1', minute='40'], next run at: 2019-12-26 21:40:00 CET)" executed successfully
```

![screenshot](https://user-images.githubusercontent.com/8294041/71647142-85fed680-2cf2-11ea-9e99-ee7f16a971fe.jpg)

I am backing up to a NAS and sometimes my laptop goes to sleep, so that might be a reason. Still, I would prefer the check operation to fail rather than Vorta to crash... if possible.

Thank you for your help!

**Comment by m3nu** [comment]
According to the log, this error happens in Borg itself, not Vorta. Since Borg starts, I'll assume it's in the right place. It fails when reading some files. Possible that the repo is not available or has some files missing?

Some background: Vorta will start and run Borg as needed. So this is not a long-running process. Not sure what happens, if it goes to sleep. The Borg binary we ship is extracted to a temporary folder as well. Maybe it's removed from there after a while.

What you could try next: It shows that you are using the built-in Borg binary. I'd try to properly install Borg instead (`brew cask install borgbackup`) and see if this helps.

**Comment by Lazza** [comment]
> Possible that the repo is not available or has some files missing?

It's absolutely possible that the repo folder (network drive) is not available when the laptop is sleeping.Yet I do not understand why Vorta crashes.

For instance, if I try to kill Borg manually (to test what happens), Vorta simply says that the backup has encountered an error but it keeps running fine.

> I'd try to properly install Borg instead

I will do it right now and test it. Thank you.

**Comment by Lazza** [comment]
I checked and it was already installed. I might be missing something but I cannot find where to change which Borg binary gets used.

**Comment by m3nu** [comment]
If Borg is in your `PATH`, Vorta should find it.

I guess Vorta crashes, because Borg crashes. So this is really about better error handling.

**Comment by Lazza** [comment]
Borg is installed via Homebrew but I am not able to make it visible to the app bundle. I will try again and hope to find a way. Meanwhile, thank you for your help.

**Comment by Lazza** [comment]
Today I witnessed Vorta complain about Borg not being found, but it did not crash. Therefore I assume this bug is unrelated to #344.

**Comment by m3nu** [comment]
I made some changes to macOS packaging and the latest version doesn't use a temp folder any more. This should resolve the issues described here. Would be nice if someone could do some testing with this release:

https://files.qmax.us/vorta/Vorta-0.6.24-testing-signed-borg.dmg

**Comment by Lazza** [comment]
Thank you @m3nu, I switched to this version and I will use it in the following days.
