### ISSUE TITLE
[PyQt5 upstream issue] pip3 install --upgrade vorta fails with Command "python setup.py egg_info" failed with error code 1...

### ISSUE THREAD

**Issue by Wikinaut** [borgbase/vorta#396]
I wanted to upgrade but something is not doing well today:

```
pip3 install --upgrade vorta
Collecting vorta
Collecting python-dateutil (from vorta)
  Using cached https://files.pythonhosted.org/packages/d4/70/d60450c3dd48ef87586924207ae8907090de0b306af2bce5d134d78615cb/python_dateutil-2.8.1-py2.py3-none-any.whl
Collecting apscheduler (from vorta)
  Using cached https://files.pythonhosted.org/packages/f3/34/9ef20ed473c4fd2c3df54ef77a27ae3fc7500b16b192add4720cab8b2c09/APScheduler-3.6.3-py2.py3-none-any.whl
Collecting peewee (from vorta)
Collecting pyqt5 (from vorta)
  Using cached https://files.pythonhosted.org/packages/3a/fb/eb51731f2dc7c22d8e1a63ba88fb702727b324c6352183a32f27f73b8116/PyQt5-5.14.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/lib/python3.6/tokenize.py", line 452, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-build-3wtovla1/pyqt5/setup.py'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-3wtovla1/pyqt5/
```

**Comment by Wikinaut** [comment]
It appears to be a problem with PyQt5 version 5.14.1 published on 20200106.

**Comment by Wikinaut** [comment]
Issue is discussed upstream in the PyQt mailing list: 
https://www.riverbankcomputing.com/pipermail/pyqt/2020-January/042428.html

**Comment by Wikinaut** [comment]
Solution: I had to upgrade ```pip3```. See Internet and StackOverflow to upgrade the correct pip (pip2 resp. pip3) on your installation in case you ran into the same problem.

**Comment by smartm0use** [comment]
I run in the same issue. What do you mean for upgrading pip3?
I have already tried to run these commands but nothing changed:

`sudo apt-get install python3.6-dev libmysqlclient-dev`

`pip3 install --upgrade setuptools`

...and running `pip3 search pyqt5` I have this:

```
PyQt5 (5.14.2)                    - Python bindings for the Qt cross platform
                                    application toolkit
  INSTALLED: 5.13.2
  LATEST:    5.14.2
```

**Comment by Wikinaut** [comment]
@smartm0use check this: https://stackoverflow.com/questions/38613316/how-to-upgrade-pip3

**Comment by smartm0use** [comment]
I run `pip3 install --upgrade pip` and I solved. Thank you.
