### ISSUE TITLE
Cannot upgrade Vorta

### ISSUE THREAD

**Issue by MatejKovacic** [borgbase/vorta#401]
I say:
`sudo pip3 install -U vorta`

And got the error:

```
Requirement already up-to-date: vorta in /usr/local/lib/python3.6/dist-packages
Requirement already up-to-date: appdirs in /usr/local/lib/python3.6/dist-packages (from vorta)
Collecting paramiko (from vorta)
  Downloading https://files.pythonhosted.org/packages/06/1e/1e08baaaf6c3d3df1459fd85f0e7d2d6aa916f33958f151ee1ecc9800971/paramiko-2.7.1-py2.py3-none-any.whl (206kB)
    100% |████████████████████████████████| 215kB 1.2MB/s 
Collecting pyqt5 (from vorta)
  Downloading https://files.pythonhosted.org/packages/3a/fb/eb51731f2dc7c22d8e1a63ba88fb702727b324c6352183a32f27f73b8116/PyQt5-5.14.1.tar.gz (3.2MB)
    100% |████████████████████████████████| 3.2MB 441kB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/lib/python3.6/tokenize.py", line 452, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-build-f50wfrjz/pyqt5/setup.py'
    
    ----------------------------------------
**Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-f50wfrjz/pyqt5/**

```

**Comment by ThomasWaldmann** [comment]
Try installing pyqt5 before you install vorta.

**Comment by MatejKovacic** [comment]
```
sudo pip3 install pyqt5
...
Requirement already satisfied: pyqt5 in /usr/local/lib/python3.6/dist-packages
Requirement already satisfied: PyQt5_sip<13,>=4.19.19 in /usr/local/lib/python3.6/dist-packages (from pyqt5)
```
However, `sudo pip3 install -U vorta` still says:

`Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-0r5617vi/pyqt5/`

**Comment by ThomasWaldmann** [comment]
There is a bit of a strange mix up between `/usr` and `/usr/local` based paths in these logs.

**Comment by m3nu** [comment]
A known issue. Needs upgraded pip or setuptools. Just encountered it in Travis.

`pip install -U setuptools pip`

**Comment by MatejKovacic** [comment]
OMG, the correct procedure on Ubuntu is:
```
sudo apt-get remove python3-pip
sudo apt-get install python3-pip
pip install -U setuptools pip
sudo pip3 install -U setuptools pip
```
and then finally:
`sudo pip3 install -U vorta`

Oh, and don't forget to: `echo "Ubuntu - do they really know what they are doing?"`
