### ISSUE TITLE
Crash on start

### ISSUE THREAD

**Issue by Kakupakat** [borgbase/vorta#445]
**Describe the bug**
Vorta crashes on startup

**To Reproduce**
1. Start Vorta
2. Vorta crashes
3. CLI output: 
```
2020-04-13 09:20:19,955 - vorta.i18n - DEBUG - Loading translation succeeded for ['de', 'de-DE', 'de-Latn-DE'].                                       
2020-04-13 09:20:19,967 - apscheduler.scheduler - INFO - Scheduler started                                                                            
Traceback (most recent call last):
  File "/usr/bin/vorta", line 11, in <module>
    load_entry_point('vorta==0.6.24', 'gui_scripts', 'vorta')()
  File "/usr/lib/python3.6/site-packages/vorta/__main__.py", line 37, in main
    app = VortaApp(sys.argv, single_app=True)
  File "/usr/lib/python3.6/site-packages/vorta/application.py", line 60, in __init__
    self.open_main_window_action()
  File "/usr/lib/python3.6/site-packages/vorta/application.py", line 81, in open_main_window_action
    self.main_window = MainWindow(self)
  File "/usr/lib/python3.6/site-packages/vorta/views/main_window.py", line 35, in __init__
    self.repoTab = RepoTab(self.repoTabSlot)
  File "/usr/lib/python3.6/site-packages/vorta/views/repo_tab.py", line 55, in __init__
    self.init_ssh()
  File "/usr/lib/python3.6/site-packages/vorta/views/repo_tab.py", line 88, in init_ssh
    keys = get_private_keys()
  File "/usr/lib/python3.6/site-packages/vorta/utils.py", line 74, in get_private_keys
    parsed_key = key_format.from_private_key_file(key_file)
  File "/usr/lib/python3.6/site-packages/paramiko/pkey.py", line 217, in from_private_key_file
    key = cls(filename=filename, password=password)
  File "/usr/lib/python3.6/site-packages/paramiko/rsakey.py", line 55, in __init__
    self._from_private_key_file(filename, password)
  File "/usr/lib/python3.6/site-packages/paramiko/rsakey.py", line 175, in _from_private_key_file
    data = self._read_private_key_file("RSA", filename, password)
  File "/usr/lib/python3.6/site-packages/paramiko/pkey.py", line 290, in _read_private_key_file
    data = self._read_private_key(tag, f, password)
  File "/usr/lib/python3.6/site-packages/paramiko/pkey.py", line 304, in _read_private_key
    keytype = m.group(1)
AttributeError: 'NoneType' object has no attribute 'group'
```
**Desktop (please complete the following information):**
- Opensuse 15.1
- Python 3.6.10
- Crash occurs with versions installed from Opensuse repositories as well as installed from pip

**Comment by Kakupakat** [comment]
The problem went away after upgrading Vorta's dependencies with pip3.
