### ISSUE TITLE
Broken on openSUSE Tumbleweed -- pkg_resources.DistributionNotFound: The 'importlib_metadata' distribution was not found and is required by helpdev

### ISSUE THREAD

**Issue by geckolinux** [borgbase/vorta#449]
Hi, within the past month or so Vorta stopped working on the latest releases of openSUSE Tumbleweed:

```````````````
Traceback (most recent call last):
  File "/usr/bin/vorta", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3252, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3235, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3264, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'importlib_metadata' distribution was not found and is required by helpdev

**Comment by Hofer-Julian** [comment]
We get similar reports quite often for rolling release distributions.

You have two options, if you want to have a nice experience:
- use the flatpak
- manage that Vorta is packaged for openSUSE
