### ISSUE TITLE
Ubuntu 20.04 can't start

### ISSUE THREAD

**Issue by dockerpirate** [borgbase/vorta#451]
hello, 
can't start vorta on ubuntu 20.04, i get following message. Tried to install with pip3, flat works

`Traceback (most recent call last):
  File "/usr/local/bin/vorta", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3254, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3237, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3266, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 584, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 901, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 787, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'vorta==0.6.23' distribution was not found and is required by the application
`

**Comment by Hofer-Julian** [comment]
Could you please also post the error message of the flatpak?

**Comment by dockerpirate** [comment]
no - flatpak works, my fault. I upgraded ubuntu from 18 to 20, then reinstalled with 
`pip3 install vorta` and if I start vorta I get following error message (see above). 
If i ran cmd `pip3 list` I doesn't see vorta package

**Comment by Hofer-Julian** [comment]
Then I can only say something similar to https://github.com/borgbase/vorta/issues/449.

If you want Vorta to work after upgrades, don't use pip.

Rather use flatpak. A debian package should also come as far as I know.
