### ISSUE TITLE
Add OpenSSL macOS lib in PyInstaller Build

### ISSUE THREAD

**Issue by kevdogg** [borgbase/vorta#452]
I've been using Vorta for quite sometime however for whatever reason it doesn't appear to be working.

I'm on Mac Catalina.
The icon is missing from the system tray
I've reinstalled vorta using brew.
The application is shown with Spotlight (Command Spacebar). When selecting Vorta, nothing seems to show up in the task bar.  

Activity Monitor doesn't show any process known as Vorta.  
I tried both control-clicking and command-clicking when starting the application.  
Any other recommendations?

**Comment by m3nu** [comment]
Any error shown when starting Vorta via the command line? I.e.

`$ /Applications/Vorta.app/Contents/MacOS/vorta`

**Comment by kevdogg** [comment]
Within that at directory is only one directory i18n.  I guessing that is a problem

**Comment by m3nu** [comment]
Yes. Some issue with your installation.

**Comment by kevdogg** [comment]
There is definitely a problem somewhere.  I uninstall vorta from brew, removed the brew cache, and then did a complete reinstall with brew.  The directory structure is the same as it was before.

**Comment by kevdogg** [comment]
2020-04-27 11:01:57,661 - vorta.borg.borg_thread - WARNING - import borg.crypto.low_level
2020-04-27 11:01:57,661 - vorta.borg.borg_thread - WARNING - ImportError: dlopen(/usr/local/lib/python3.7/site-packages/borg/crypto/low_level.cpython-37m-darwin.so, 2): Library not loaded: /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib
2020-04-27 11:01:57,661 - vorta.borg.borg_thread - WARNING - Referenced from: /usr/local/lib/python3.7/site-packages/borg/crypto/low_level.cpython-37m-darwin.so
2020-04-27 11:01:57,662 - vorta.borg.borg_thread - WARNING - Reason: image not found
Traceback (most recent call last):
  File "vorta/application.py", line 116, in set_borg_details_result
TypeError: string indices must be integers
[1]    53800 abort      /Applications/Vorta.app/Contents/MacOS/vorta-darwin

**Comment by m3nu** [comment]
I see. Need to include openssl next time. Looks like Pyinstaller didn't add it.

**Comment by m3nu** [comment]
Hi @kevdogg , I found the issue related to the missing OpenSSL lib. Please try this new build and let me know whether this solves the issue.

https://files.qmax.us/Vorta-test-2020-05-28.dmg (signed and notarized)
Thanks!

**Comment by kevdogg** [comment]
That link doesn’t work.  Sorry.

**Comment by m3nu** [comment]
Small delay here. Will add it back soon.

**Comment by m3nu** [comment]
Here the new link. This should include the missing SSL libs for both Borg and Vorta. Will try to be more efficient with this over time.

https://files.qmax.us/Vorta-test-2020-05-28b.dmg

**Comment by m3nu** [comment]
Already got a chance to test this, @kevdogg ?

**Comment by kevdogg** [comment]
Sorry about the delay -- 

```
./vorta-darwin                                                                  
2020-05-30 08:26:14,355 - vorta.i18n - DEBUG - Loading translation succeeded for ['en', 'en-US', 'en-Latn-US'].
2020-05-30 08:26:14,388 - apscheduler.scheduler - INFO - Scheduler started
2020-05-30 08:26:14,390 - apscheduler.scheduler - INFO - Added job "VortaScheduler.create_backup" to job store "default"
2020-05-30 08:26:14,390 - vorta.scheduler - DEBUG - New job for profile Default was added.
2020-05-30 08:26:15,648 - vorta.borg.borg_thread - INFO - Running command /usr/local/bin/borg --version
2020-05-30 08:26:16,415 - vorta.borg.borg_thread - WARNING - Traceback (most recent call last):
2020-05-30 08:26:16,415 - vorta.borg.borg_thread - WARNING - File "/usr/local/lib/python3.7/site-packages/borg/archiver.py", line 38, in <module>
2020-05-30 08:26:16,415 - vorta.borg.borg_thread - WARNING - from . import helpers
2020-05-30 08:26:16,415 - vorta.borg.borg_thread - WARNING - File "/usr/local/lib/python3.7/site-packages/borg/helpers.py", line 75, in <module>
2020-05-30 08:26:16,416 - vorta.borg.borg_thread - WARNING - import borg.crypto.low_level
2020-05-30 08:26:16,416 - vorta.borg.borg_thread - WARNING - ImportError: dlopen(/usr/local/lib/python3.7/site-packages/borg/crypto/low_level.cpython-37m-darwin.so, 2): Library not loaded: /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib
2020-05-30 08:26:16,416 - vorta.borg.borg_thread - WARNING - Referenced from: /usr/local/lib/python3.7/site-packages/borg/crypto/low_level.cpython-37m-darwin.so
2020-05-30 08:26:16,416 - vorta.borg.borg_thread - WARNING - Reason: image not found
Traceback (most recent call last):
  File "vorta/application.py", line 116, in set_borg_details_result
TypeError: string indices must be integers
[1]    27483 abort      ./vorta-darwin
```

**Comment by m3nu** [comment]
I also think it's a local issue. Just tried on my wife's untouched Macbook and was fine.

I did get a similar error before due to having openssl 2x. What I did to resolve it:

1. Uninstall openssl multiple times: `brew uninstall --ignore-dependencies openssl && brew uninstall --ignore-dependencies openssl`
2. Ensure it's gone `brew list`
3. Reinstall only the latest version `brew install openssl`
4. Possibly reinstall apps that depended on a specific version (didn't have that issue)

Since you already have Pyenv, you could just install Borg there. Then Vorta won't use the built-in version.

**Comment by m3nu** [comment]
Closing this, since macOS packaging has changed quite a bit since this was reported. We now build on the oldstable macOS via GH Actions.
