### ISSUE TITLE
Vorta started erroring, not sure why ("file exists" error)

### ISSUE THREAD

**Issue by samteezy** [borgbase/vorta#461]
**Describe the bug**
Vorta will not run manual or automated backups. No settings in Vorta have been recently changed. I write to a NFS file share on my LAN. The NFS share is mounted and accessible as always.

If you look at the bottom of the logs, it says file '2061' exists, but when I browse to the file share, it's not present. The last file is '2060'.

**To Reproduce**
1. Open Vorta
2. Click on 'Start Backup'
3. See error

**Desktop (please complete the following information):**
 - OS: Solus Linux

**Additional context**
Here's a snippet from the logs that I think is most relevant.
2020-05-19 08:42:09,644 - vorta.borg.borg_thread - INFO - Running command /usr/bin/borg create --list --info --log-json --json --filter=AM -C zstd,3 --exclude-from /tmp/tmpjbol6wos /run/user/1000/gvfs/nfs:host=10.10.1.21,prefix=%2Fvolume1%2FBorgBackup/tributo::tributo-default-2020-05-19T08:42:09 /home/sam
2020-05-19 08:42:15,959 - vorta.borg.borg_thread - INFO - Creating archive at "/run/user/1000/gvfs/nfs:host=10.10.1.21,prefix=%2Fvolume1%2FBorgBackup/tributo::tributo-default-2020-05-19T08:42:09"
2020-05-19 08:42:18,842 - vorta.borg.borg_thread - ERROR - Local Exception
2020-05-19 08:42:18,843 - vorta.borg.borg_thread - ERROR - Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/borg/archiver.py", line 4529, in main
    exit_code = archiver.run(args)
  File "/usr/lib/python3.7/site-packages/borg/archiver.py", line 4461, in run
    return set_ec(func(args))
  File "/usr/lib/python3.7/site-packages/borg/archiver.py", line 166, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/usr/lib/python3.7/site-packages/borg/archiver.py", line 574, in do_create
    create_inner(archive, cache)
  File "/usr/lib/python3.7/site-packages/borg/archiver.py", line 537, in create_inner
    read_special=args.read_special, dry_run=dry_run, st=st)
  File "/usr/lib/python3.7/site-packages/borg/archiver.py", line 651, in _process
    read_special=read_special, dry_run=dry_run)
  File "/usr/lib/python3.7/site-packages/borg/archiver.py", line 651, in _process
    read_special=read_special, dry_run=dry_run)
  File "/usr/lib/python3.7/site-packages/borg/archiver.py", line 625, in _process
    status = archive.process_file(path, st, cache)
  File "/usr/lib/python3.7/site-packages/borg/archive.py", line 1071, in process_file
    self.chunk_file(item, cache, self.stats, backup_io_iter(self.chunker.chunkify(fd, fh)))
  File "/usr/lib/python3.7/site-packages/borg/archive.py", line 999, in chunk_file
    item.chunks.append(chunk_processor(data))
  File "/usr/lib/python3.7/site-packages/borg/archive.py", line 987, in chunk_processor
    chunk_entry = cache.add_chunk(self.key.id_hash(data), data, stats, wait=False)
  File "/usr/lib/python3.7/site-packages/borg/cache.py", line 899, in add_chunk
    self.repository.put(id, data, wait=wait)
  File "/usr/lib/python3.7/site-packages/borg/repository.py", line 1131, in put
    segment, offset = self.io.write_put(id, data)
  File "/usr/lib/python3.7/site-packages/borg/repository.py", line 1532, in write_put
    fd = self.get_write_fd(raise_full=raise_full)
  File "/usr/lib/python3.7/site-packages/borg/repository.py", line 1313, in get_write_fd
    self._write_fd = SyncFile(self.segment_filename(self.segment), binary=True)
  File "/usr/lib/python3.7/site-packages/borg/platform/base.py", line 106, in __init__
    self.fd = open(path, mode)
FileExistsError: [Errno 17] File exists: '/run/user/1000/gvfs/nfs:host=10.10.1.21,prefix=%2Fvolume1%2FBorgBackup/tributo/data/2/2061'

**Comment by samteezy** [comment]
I just realized this is a Borg issue, not likely a Vorta one.

**Comment by m3nu** [comment]
Probably yes, but you also find Borg maintainers here. Still better to report it in the right place.
