### ISSUE TITLE
Scheduled Backups Failing

### ISSUE THREAD

**Issue by alexpattyn** [borgbase/vorta#469]
# Specs
OS: Fedora 32 Silverblue
Vorta: [flatpak] v0.6.24 w/ borg v1.1.10

# Issue
It seems that vorta is sometimes failing to make a backup in the background. I **don't** see this error if I hit the `Start Backup` button. I will try to delete the archive and start fresh to see if perhaps that fixes the problem since it seems to throw warnings about stale locks. 

# Debug
```
$ flatpak run com.borgbase.Vorta 
QSocketNotifier: Can only be used with threads started with QThread
2020-05-23 16:02:20,443 - vorta.i18n - DEBUG - Loading translation failed for ['en', 'en-US', 'en-Latn-US'].
2020-05-23 16:02:20,464 - apscheduler.scheduler - INFO - Scheduler started
2020-05-23 16:02:20,467 - apscheduler.scheduler - INFO - Added job "VortaScheduler.create_backup" to job store "default"
2020-05-23 16:02:20,468 - vorta.scheduler - DEBUG - New job for profile Default was added.
QObject::connect: No such signal QPlatformNativeInterface::systemTrayWindowChanged(QScreen*)
2020-05-23 16:02:20,483 - vorta.borg.borg_thread - INFO - Running command /app/bin/borg --version
2020-05-23 20:00:00,580 - apscheduler.executors.default - INFO - Running job "VortaScheduler.create_backup (trigger: cron[hour='*/4', minute='0'], next run at: 2020-05-23 20:00:00 EDT)" (scheduled at 2020-05-23 20:00:00-04:00)
2020-05-23 20:00:00,586 - vorta.scheduler - INFO - Starting background backup for Default
2020-05-23 20:00:00,588 - vorta.notifications - DEBUG - success notifications suppressed
2020-05-23 20:00:00,589 - vorta.borg.borg_thread - DEBUG - Using VortaSecretStorageKeyring keyring to store passwords.
2020-05-23 20:00:00,589 - asyncio - DEBUG - Using selector: EpollSelector
2020-05-23 20:00:00,593 - root - DEBUG - Found 1 passwords matching repo URL.
2020-05-23 20:00:00,724 - vorta.scheduler - INFO - Preparation for backup successful.
2020-05-23 20:00:00,736 - vorta.borg.borg_thread - INFO - Running command /app/bin/borg create --list --info --log-json --json --filter=AM -C lz4 --exclude-from /tmp/tmptsvr3kpg /mnt/a17cb6fe-b2e0-4911-9cc6-89854c2196fe/$MachineBackup::$Machine-default-2020-05-23T20:00:00 /var/home/apattyn
2020-05-23 20:00:02,590 - vorta.borg.borg_thread - WARNING - Killed stale lock $Machine@168082750553930.26-0.
2020-05-23 20:00:02,691 - vorta.borg.borg_thread - WARNING - Removed stale exclusive roster lock for host $Machine@168082750553930 pid 26 thread 0.
2020-05-23 20:00:02,691 - vorta.borg.borg_thread - WARNING - Removed stale exclusive roster lock for host $Machine@168082750553930 pid 26 thread 0.
2020-05-23 20:00:02,734 - vorta.borg.borg_thread - WARNING - Killed stale lock $Machine@168082750553930.26-0.
2020-05-23 20:00:02,835 - vorta.borg.borg_thread - WARNING - Removed stale exclusive roster lock for host $Machine@168082750553930 pid 26 thread 0.
2020-05-23 20:00:02,835 - vorta.borg.borg_thread - WARNING - Removed stale exclusive roster lock for host $Machine@168082750553930 pid 26 thread 0.
2020-05-23 20:00:02,839 - vorta.borg.borg_thread - INFO - Creating archive at "/mnt/a17cb6fe-b2e0-4911-9cc6-89854c2196fe/$MachineBackup::$Machine-default-2020-05-23T20:00:00"
2020-05-23 20:00:03,286 - vorta.borg.borg_thread - ERROR - Local Exception
2020-05-23 20:00:03,287 - vorta.borg.borg_thread - ERROR - Traceback (most recent call last):
  File "/app/lib/python3.7/site-packages/borg/archiver.py", line 4501, in main
    exit_code = archiver.run(args)
  File "/app/lib/python3.7/site-packages/borg/archiver.py", line 4433, in run
    return set_ec(func(args))
  File "/app/lib/python3.7/site-packages/borg/archiver.py", line 166, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/app/lib/python3.7/site-packages/borg/archiver.py", line 573, in do_create
    create_inner(archive, cache)
  File "/app/lib/python3.7/site-packages/borg/archiver.py", line 536, in create_inner
    read_special=args.read_special, dry_run=dry_run, st=st)
  File "/app/lib/python3.7/site-packages/borg/archiver.py", line 650, in _process
    read_special=read_special, dry_run=dry_run)
  File "/app/lib/python3.7/site-packages/borg/archiver.py", line 650, in _process
    read_special=read_special, dry_run=dry_run)
  File "/app/lib/python3.7/site-packages/borg/archiver.py", line 650, in _process
    read_special=read_special, dry_run=dry_run)
  [Previous line repeated 2 more times]
  File "/app/lib/python3.7/site-packages/borg/archiver.py", line 624, in _process
    status = archive.process_file(path, st, cache)
  File "/app/lib/python3.7/site-packages/borg/archive.py", line 1051, in process_file
    chunks = [cache.chunk_incref(id_, self.stats) for id_ in ids]
  File "/app/lib/python3.7/site-packages/borg/archive.py", line 1051, in <listcomp>
    chunks = [cache.chunk_incref(id_, self.stats) for id_ in ids]
  File "/app/lib/python3.7/site-packages/borg/cache.py", line 914, in chunk_incref
    self.begin_txn()
  File "/app/lib/python3.7/site-packages/borg/cache.py", line 554, in begin_txn
    os.path.join(self.path, 'txn.active'))
FileExistsError: [Errno 17] File exists: '/var/home/apattyn/.var/app/com.borgbase.Vorta/cache/borg/11548f40029c3ef231a99a317783534a9dfb4d6da3ffcb9ca7cc76196d591b32/txn.tmp' -> '/var/home/apattyn/.var/app/com.borgbase.Vorta/cache/borg/11548f40029c3ef231a99a317783534a9dfb4d6da3ffcb9ca7cc76196d591b32/txn.active'

Platform: Linux $Machine 5.6.13-300.fc32.x86_64 #1 SMP Thu May 14 22:51:37 UTC 2020 x86_64
Linux:   
Borg: 1.1.10  Python: CPython 3.7.4 msgpack: 0.5.6
PID: 15  CWD: /var/home/apattyn
sys.argv: ['/app/bin/borg', 'create', '--list', '--info', '--log-json', '--json', '--filter=AM', '-C', 'lz4', '--exclude-from', '/tmp/tmptsvr3kpg', '/mnt/a17cb6fe-b2e0-4911-9cc6-89854c2196fe/$MachineBackup::$Machine-default-2020-05-23T20:00:00', '/var/home/apattyn']
SSH_ORIGINAL_COMMAND: None

2020-05-23 20:00:03,423 - vorta.notifications - DEBUG - notification not suppressed
2020-05-23 20:00:03,443 - vorta.scheduler - ERROR - Error during backup creation.
2020-05-23 20:00:03,444 - apscheduler.executors.default - INFO - Job "VortaScheduler.create_backup (trigger: cron[hour='*/4', minute='0'], next run at: 2020-05-24 00:00:00 EDT)" executed successfully
```

**Comment by Hofer-Julian** [comment]
Yes, please try with a fresh repository as well

**Comment by alexpattyn** [comment]
Seems that fixed the issue. I was fairly sure it was a new repo to begin with. Either way closing for now unless the issue crops up again.
