### ISSUE TITLE
Crash in DiffResult

### ISSUE THREAD

**Issue by ktosiek** [borgbase/vorta#509]
**Describe the bug**
Vorta crashes when trying to show diff between backups.

**Additional context**
It seems Vorta logs don't include the crash traceback, but I've found it in system logs:
```
cze 14 22:44:13 vorta: UnboundLocalError: local variable 'full_path_index' referenced before assignment
cze 14 22:44:13 vorta:     full_path = line[full_path_index:]
cze 14 22:44:13 vorta:   File "/app/lib/python3.7/site-packages/vorta/views/diff_result.py", line 60, in parse_line
cze 14 22:44:13 vorta:     files_with_attributes.append(parse_line(line))
cze 14 22:44:13 vorta:   File "/app/lib/python3.7/site-packages/vorta/views/diff_result.py", line 72, in __init__
cze 14 22:44:13 vorta:     window = DiffResult(result['data'], archive_newer, archive_older)
cze 14 22:44:13 vorta:   File "/app/lib/python3.7/site-packages/vorta/views/archive_tab.py", line 460, in list_diff_result
cze 14 22:44:13 vorta: Traceback (most recent call last):
cze 14 22:42:47 vorta: 2020-06-14 22:42:47,325 - vorta.borg.borg_thread - INFO - Running command /app/bin/borg diff --info --log-json XXX@XXX.repo.borgbase.com:repo::XXX-2020-06-14T17:00:00 XXX-2020-06-14T18:00:00
```

**Comment by ktosiek** [comment]
The line it failed on is:
```
changed link        home/tomek/.mozilla/firefox/4q1f3nyy.default-release/lock
```

Looking at code in [ItemDiff](https://github.com/borgbackup/borg/blob/23f4a7d874081f88b87458a1e01a2d6175539290/src/borg/item.pyx#L401), the expected prefixes are:
* If any side is a link:
  * added link
  * removed link
  * changed link

* If both sides have chunks (so probably only normal files?):
  * added {size:>13}
  * removed {size:>11}
  * modified
  * {size:>9} {size:>9}

* If any side is a directory:
  * removed directory
  * added directory

* If both files existed, but owner has changed:
  * '[{uid}:{gid} -> {uid}:{gid}]'

* If both files existed, but mode has changed:
  * '[{filemode} -> {filemode}]'

**Comment by ktosiek** [comment]
Ok, I've just noticed it works differently in borg 1.1.  But Vorta still needs to handle "changed ..." lines.
