### ISSUE TITLE
backup failed: ERROR - Connection closed by remote host. Is borg working on the server?

### ISSUE THREAD

**Issue by jchhenderson** [borgbase/vorta#535]
**Describe the bug**
I received a notice stating that Borg/Vorta failed to backup to BorgBase

**To Reproduce**
It was a schooled backup.  Previous and subsequent backups were OK.  I had a failure to backup a couple of days ago.  I am not sure if they arte related (the earlier one was to a local NAS).  I have added both in the logs just in case...

**Desktop (please complete the following information):**
 - OS: MacOS 10.15.5

**Additional context**
logs:
```
2020-06-29 13:30:00,005 - apscheduler.executors.default - INFO - Running job "VortaScheduler.create_backup (trigger: cron[hour='*/1', minute='30'], next run at: 2020-06-29 14:30:00 BST)" (scheduled at 2020-06-29 13:30:00+01:00)
2020-06-29 13:30:00,019 - vorta.scheduler - INFO - Starting background backup for BorgBase
2020-06-29 13:30:00,023 - vorta.notifications - DEBUG - success notifications suppressed
2020-06-29 13:30:00,030 - vorta.borg.borg_thread - DEBUG - Using VortaDarwinKeyring keyring to store passwords.
2020-06-29 13:30:00,144 - vorta.scheduler - INFO - Preparation for backup successful.
2020-06-29 13:30:00,155 - vorta.borg.borg_thread - INFO - Running command /Applications/Vorta.app/Contents/Resources/borg-dir/borg.exe create --list --info --log-json --json --filter=AM -C lz4 --exclude-from /var/folders/pt/pv6swdgn36s4g6r9qy8v29kh0000gn/T/tmptgaxfquy --exclude-if-present .nobackup s4480gsg@s4480gsg.repo.borgbase.com:repo::James-MBP-borgbase-2020-06-29T13:30:00 /Users/jameshenderson/.ssh /Users/jameshenderson/Library/LaunchAgents /Users/jameshenderson/Library/Saved Searches /Users/jameshenderson/Library/Application Support/Get iPlayer Automator/download_history /Users/jameshenderson/Library/Application Support/Get iPlayer Automator/Queue.automatorqueue /Users/jameshenderson/Library/Application Support/Vorta/settings.db /Users/jameshenderson/Applications /Users/jameshenderson/Documents/apps/data/DevonThink/home.dtBase2 /Users/jameshenderson/Documents/apps/data/DevonThink/home archive.dtBase2 /Users/jameshenderson/Documents/apps/data/DevonThink/mum+dad.dtBase2 /Users/jameshenderson/Documents/apps/data/DevonThink/mum+dad archive.dtBase2
2020-06-29 13:30:01,146 - vorta.borg.borg_thread - WARNING - Remote: kex_exchange_identification: read: Connection reset by peer
2020-06-29 13:30:01,147 - vorta.borg.borg_thread - ERROR - Connection closed by remote host. Is borg working on the server?
2020-06-29 13:30:01,292 - vorta.notifications - DEBUG - notification not suppressed
2020-06-29 13:30:01,305 - vorta.scheduler - ERROR - Error during backup creation.
2020-06-29 13:30:01,306 - apscheduler.executors.default - INFO - Job "VortaScheduler.create_backup (trigger: cron[hour='*/1', minute='30'], next run at: 2020-06-29 14:30:00 BST)" executed successfully
```

Log of failure to backup to NAS a couple of days ago (which may or may not be related)
```
2020-06-27 00:15:00,024 - apscheduler.executors.default - INFO - Running job "VortaScheduler.create_backup (trigger: cron[hour='*/3', minute='15'], next run at: 2020-06-27 03:15:00 BST)" (scheduled at 2020-06-27 00:15:00+01:00)
2020-06-27 00:15:00,026 - vorta.scheduler - INFO - Starting background backup for NAS
2020-06-27 00:15:00,028 - vorta.notifications - DEBUG - success notifications suppressed
2020-06-27 00:15:00,031 - vorta.borg.borg_thread - DEBUG - Using VortaDarwinKeyring keyring to store passwords.
2020-06-27 00:15:00,060 - vorta.scheduler - INFO - Preparation for backup successful.
2020-06-27 00:15:00,070 - vorta.borg.borg_thread - INFO - Running command /Applications/Vorta.app/Contents/Resources/borg-dir/borg.exe create --list --info --log-json --json --filter=AM -C lz4 --exclude-from /var/folders/pt/pv6swdgn36s4g6r9qy8v29kh0000gn/T/tmp9fhk0zfp --exclude-if-present .nobackup /Volumes/backups/BorgBackup_MBP::James-MBP-nas-2020-06-27T00:15:00 /Users/jameshenderson/Library/Application Support/Get iPlayer Automator/Queue.automatorqueue /Users/jameshenderson/Library/Application Support/Get iPlayer Automator/download_history /Users/jameshenderson/Library/LaunchAgents /Users/jameshenderson/Library/Application Support/Vorta/settings.db /Users/jameshenderson/Library/Saved Searches /Users/jameshenderson/.ssh /Users/jameshenderson/Applications /Users/jameshenderson/Documents /Users/jameshenderson/Movies /Users/jameshenderson/Music /Users/jameshenderson/Pictures
2020-06-27 00:15:01,820 - vorta.borg.borg_thread - INFO - Creating archive at "/Volumes/backups/BorgBackup_MBP::James-MBP-nas-2020-06-27T00:15:00"
2020-06-27 00:17:36,978 - vorta.borg.borg_thread - WARNING - Exception ignored in: <function Repository.__del__ at 0x1044df3b0>
2020-06-27 00:17:36,979 - vorta.borg.borg_thread - WARNING - Traceback (most recent call last):
2020-06-27 00:17:36,979 - vorta.borg.borg_thread - WARNING - File "borg/repository.py", line 179, in __del__
2020-06-27 00:17:36,979 - vorta.borg.borg_thread - WARNING - File "borg/repository.py", line 444, in close
2020-06-27 00:17:36,979 - vorta.borg.borg_thread - WARNING - File "borg/repository.py", line 1207, in close
2020-06-27 00:17:36,979 - vorta.borg.borg_thread - WARNING - File "borg/lrucache.py", line 50, in clear
2020-06-27 00:17:36,979 - vorta.borg.borg_thread - WARNING - File "borg/repository.py", line 1212, in _close_fd
2020-06-27 00:17:36,979 - vorta.borg.borg_thread - WARNING - ValueError: I/O operation on closed file
2020-06-27 00:17:36,979 - vorta.borg.borg_thread - ERROR - Local Exception
2020-06-27 00:17:36,980 - vorta.borg.borg_thread - ERROR - Traceback (most recent call last):
  File "borg/archiver.py", line 4529, in main
  File "borg/archiver.py", line 4461, in run
  File "borg/archiver.py", line 166, in wrapper
  File "borg/repository.py", line 204, in __exit__
  File "borg/repository.py", line 444, in close
  File "borg/repository.py", line 1207, in close
  File "borg/lrucache.py", line 50, in clear
  File "borg/repository.py", line 1213, in _close_fd
OSError: [Errno 9] Bad file descriptor

Platform: Darwin James-MBP 19.5.0 Darwin Kernel Version 19.5.0: Tue May 26 20:41:44 PDT 2020; root:xnu-6153.121.2~2/RELEASE_X86_64 x86_64
Borg: 1.1.11.dev128+gae78914c  Python: CPython 3.7.5 msgpack: 0.5.6
PID: 28087  CWD: /
sys.argv: ['/Applications/Vorta.app/Contents/Resources/borg-dir/borg.exe', 'create', '--list', '--info', '--log-json', '--json', '--filter=AM', '-C', 'lz4', '--exclude-from', '/var/folders/pt/pv6swdgn36s4g6r9qy8v29kh0000gn/T/tmp9fhk0zfp', '--exclude-if-present', '.nobackup', '/Volumes/backups/BorgBackup_MBP::James-MBP-nas-2020-06-27T00:15:00', '/Users/jameshenderson/Library/Application Support/Get iPlayer Automator/Queue.automatorqueue', '/Users/jameshenderson/Library/Application Support/Get iPlayer Automator/download_history', '/Users/jameshenderson/Library/LaunchAgents', '/Users/jameshenderson/Library/Application Support/Vorta/settings.db', '/Users/jameshenderson/Library/Saved Searches', '/Users/jameshenderson/.ssh', '/Users/jameshenderson/Applications', '/Users/jameshenderson/Documents', '/Users/jameshenderson/Movies', '/Users/jameshenderson/Music', '/Users/jameshenderson/Pictures']
SSH_ORIGINAL_COMMAND: None

2020-06-27 00:17:37,138 - vorta.notifications - DEBUG - notification not suppressed
2020-06-27 00:17:37,142 - vorta.scheduler - ERROR - Error during backup creation.
2020-06-27 00:17:37,142 - apscheduler.executors.default - INFO - Job "VortaScheduler.create_backup (trigger: cron[hour='*/3', minute='15'], next run at: 2020-06-27 03:15:00 BST)" executed successfully

```

**Comment by ThomasWaldmann** [comment]
first log: ssh connection issue

second log: repo file system issue

**Comment by jchhenderson** [comment]
cheers.
What do I need to do?

**Comment by ThomasWaldmann** [comment]
about the ssh connection issue: if it is a one time thing, just ignore it. if it happens frequently, see the borgbackup docs or issue tracker about ssh server/client keepalive settings.

about the repo filesystem: you need a working, reliable filesystem.

**Comment by jchhenderson** [comment]
Thanks.

Re: my NAS - it has been available the whole time - I have been recording TV on it (via Plex).  Or do you mean something else?

**Comment by ThomasWaldmann** [comment]
"bad file descriptor" is unusual.

i guess your network fs has closed a file server side which borg on the client side still thinks it has open...

**Comment by jchhenderson** [comment]
My NAS is a QNAP - is that a bad destination in general for Borg?

**Comment by m3nu** [comment]
I only have experience on Synology as a client, which works alright. QNAP should be similar?

Are you accessing it via SMB? Maybe try SSH instead and install Borg on the QNAP device? Network shares are probably slow and not too reliable.
