### ISSUE TITLE
Error - Local Exception

### ISSUE THREAD

**Issue by jchhenderson** [borgbase/vorta#546]
**Describe the bug**
I am getting a bunch of warnings and errors every time I backup to my local NAS.  I do n to understand what it means and so am not sure if it is critical or not.

**To Reproduce**
1. Backup to local NAS
2. Look in lots *or* observe at bottom of Vorta window after backup

**Desktop (please complete the following information):**
 - OS: MacOS 10.15.5

**Additional context**

log entires:
```
2020-07-11 09:21:59,085 - vorta.borg.borg_thread - INFO - Running command /Applications/Vorta.app/Contents/Resources/borg-dir/borg.exe create --list --info --log-json --json --filter=AM -C lz4 --exclude-from /var/folders/pt/pv6swdgn36s4g6r9qy8v29kh0000gn/T/tmpsq4nsvbs --exclude-if-present .nobackup /Volumes/backups/BorgBackup_MBP::James-MBP-nas-2020-07-11T09:21:59 /Users/jameshenderson/Library/Application Support/Get iPlayer Automator/Queue.automatorqueue /Users/jameshenderson/Library/Application Support/Get iPlayer Automator/download_history /Users/jameshenderson/Library/LaunchAgents /Users/jameshenderson/Library/Application Support/Vorta/settings.db /Users/jameshenderson/Library/Saved Searches /Users/jameshenderson/.ssh /Users/jameshenderson/Applications /Users/jameshenderson/Documents /Users/jameshenderson/Movies /Users/jameshenderson/Music /Users/jameshenderson/Pictures
2020-07-11 09:21:59,761 - vorta.borg.borg_thread - INFO - Creating archive at "/Volumes/backups/BorgBackup_MBP::James-MBP-nas-2020-07-11T09:21:59"
2020-07-11 09:22:00,258 - vorta.borg.borg_thread - INFO - Synchronizing chunks cache...
2020-07-11 09:22:00,263 - vorta.borg.borg_thread - INFO - Archives: 21, w/ cached Idx: 26, w/ outdated Idx: 14, w/o cached Idx: 9.
2020-07-11 09:22:00,282 - vorta.borg.borg_thread - INFO - Reading cached archive chunk index for James-MBP-default-2020-06-03T21:30:00 ...
2020-07-11 09:22:00,293 - vorta.borg.borg_thread - INFO - Merging into master chunks index ...
2020-07-11 09:22:00,297 - vorta.borg.borg_thread - INFO - Reading cached archive chunk index for James-MBP-default-2020-06-07T22:30:00 ...
2020-07-11 09:22:00,305 - vorta.borg.borg_thread - INFO - Merging into master chunks index ...
2020-07-11 09:22:00,309 - vorta.borg.borg_thread - INFO - Reading cached archive chunk index for James-MBP-nas-2020-06-14T23:15:00 ...
2020-07-11 09:22:00,322 - vorta.borg.borg_thread - INFO - Merging into master chunks index ...
2020-07-11 09:22:00,330 - vorta.borg.borg_thread - INFO - Reading cached archive chunk index for James-MBP-nas-2020-06-21T23:15:00 ...
2020-07-11 09:22:00,347 - vorta.borg.borg_thread - INFO - Merging into master chunks index ...
2020-07-11 09:22:00,354 - vorta.borg.borg_thread - INFO - Reading cached archive chunk index for James-MBP-nas-2020-06-28T21:15:00 ...
2020-07-11 09:22:00,366 - vorta.borg.borg_thread - INFO - Merging into master chunks index ...
2020-07-11 09:22:00,373 - vorta.borg.borg_thread - INFO - Reading cached archive chunk index for James-MBP-nas-2020-06-30T21:15:00 ...
2020-07-11 09:22:00,387 - vorta.borg.borg_thread - INFO - Merging into master chunks index ...
2020-07-11 09:22:00,394 - vorta.borg.borg_thread - INFO - Reading cached archive chunk index for James-MBP-nas-2020-07-03T21:15:00 ...
2020-07-11 09:22:00,407 - vorta.borg.borg_thread - INFO - Merging into master chunks index ...
2020-07-11 09:22:00,415 - vorta.borg.borg_thread - INFO - Reading cached archive chunk index for James-MBP-nas-2020-07-04T18:15:00 ...
2020-07-11 09:22:00,428 - vorta.borg.borg_thread - INFO - Merging into master chunks index ...
2020-07-11 09:22:00,435 - vorta.borg.borg_thread - INFO - Reading cached archive chunk index for James-MBP-nas-2020-07-05T21:15:00 ...
2020-07-11 09:22:00,445 - vorta.borg.borg_thread - INFO - Merging into master chunks index ...
2020-07-11 09:22:00,453 - vorta.borg.borg_thread - INFO - Reading cached archive chunk index for James-MBP-nas-2020-07-06T21:15:00 ...
2020-07-11 09:22:00,464 - vorta.borg.borg_thread - INFO - Merging into master chunks index ...
2020-07-11 09:22:00,471 - vorta.borg.borg_thread - INFO - Reading cached archive chunk index for James-MBP-nas-2020-07-08T21:15:00 ...
2020-07-11 09:22:00,503 - vorta.borg.borg_thread - INFO - Merging into master chunks index ...
2020-07-11 09:22:00,503 - vorta.borg.borg_thread - INFO - Fetching and building archive index for James-MBP-nas-2020-07-09T21:15:00 ...
2020-07-11 09:22:01,593 - vorta.borg.borg_thread - INFO - Merging into master chunks index ...
2020-07-11 09:22:01,601 - vorta.borg.borg_thread - INFO - Fetching and building archive index for James-MBP-nas-2020-07-10T12:15:00 ...
2020-07-11 09:22:02,524 - vorta.borg.borg_thread - INFO - Merging into master chunks index ...
2020-07-11 09:22:02,533 - vorta.borg.borg_thread - INFO - Fetching and building archive index for James-MBP-nas-2020-07-10T13:32:52 ...
2020-07-11 09:22:03,327 - vorta.borg.borg_thread - INFO - Merging into master chunks index ...
2020-07-11 09:22:03,335 - vorta.borg.borg_thread - INFO - Fetching and building archive index for James-MBP-nas-2020-07-10T15:15:00 ...
2020-07-11 09:22:03,900 - vorta.borg.borg_thread - INFO - Merging into master chunks index ...
2020-07-11 09:22:03,908 - vorta.borg.borg_thread - INFO - Fetching and building archive index for James-MBP-nas-2020-07-10T18:15:00 ...
2020-07-11 09:22:04,460 - vorta.borg.borg_thread - INFO - Merging into master chunks index ...
2020-07-11 09:22:04,469 - vorta.borg.borg_thread - INFO - Fetching and building archive index for James-MBP-nas-2020-07-10T21:15:00 ...
2020-07-11 09:22:04,928 - vorta.borg.borg_thread - INFO - Merging into master chunks index ...
2020-07-11 09:22:04,936 - vorta.borg.borg_thread - INFO - Fetching and building archive index for James-MBP-nas-2020-07-11T00:15:00 ...
2020-07-11 09:22:05,354 - vorta.borg.borg_thread - INFO - Merging into master chunks index ...
2020-07-11 09:22:05,363 - vorta.borg.borg_thread - INFO - Fetching and building archive index for James-MBP-nas-2020-07-11T03:15:00 ...
2020-07-11 09:22:05,755 - vorta.borg.borg_thread - INFO - Merging into master chunks index ...
2020-07-11 09:22:05,762 - vorta.borg.borg_thread - INFO - Fetching and building archive index for James-MBP-nas-2020-07-11T06:15:00 ...
2020-07-11 09:22:06,109 - vorta.borg.borg_thread - INFO - Merging into master chunks index ...
2020-07-11 09:22:06,117 - vorta.borg.borg_thread - INFO - Reading cached archive chunk index for James-MacBook-Pro.local-nas-2020-07-07T21:15:00 ...
2020-07-11 09:22:06,134 - vorta.borg.borg_thread - INFO - Merging into master chunks index ...
2020-07-11 09:22:06,141 - vorta.borg.borg_thread - INFO - Done.
2020-07-11 09:25:26,830 - vorta.borg.borg_thread - WARNING - Exception ignored in: <function Repository.__del__ at 0x1047a43b0>
2020-07-11 09:25:26,832 - vorta.borg.borg_thread - WARNING - Traceback (most recent call last):
2020-07-11 09:25:26,832 - vorta.borg.borg_thread - WARNING - File "borg/repository.py", line 179, in __del__
2020-07-11 09:25:26,833 - vorta.borg.borg_thread - WARNING - File "borg/repository.py", line 444, in close
2020-07-11 09:25:26,833 - vorta.borg.borg_thread - WARNING - File "borg/repository.py", line 1207, in close
2020-07-11 09:25:26,833 - vorta.borg.borg_thread - WARNING - File "borg/lrucache.py", line 50, in clear
2020-07-11 09:25:26,834 - vorta.borg.borg_thread - WARNING - File "borg/repository.py", line 1212, in _close_fd
2020-07-11 09:25:26,835 - vorta.borg.borg_thread - WARNING - ValueError: I/O operation on closed file
2020-07-11 09:25:26,835 - vorta.borg.borg_thread - ERROR - Local Exception
2020-07-11 09:25:26,835 - vorta.borg.borg_thread - ERROR - Traceback (most recent call last):
  File "borg/archiver.py", line 4529, in main
  File "borg/archiver.py", line 4461, in run
  File "borg/archiver.py", line 166, in wrapper
  File "borg/repository.py", line 204, in __exit__
  File "borg/repository.py", line 444, in close
  File "borg/repository.py", line 1207, in close
  File "borg/lrucache.py", line 50, in clear
  File "borg/repository.py", line 1213, in _close_fd
OSError: [Errno 9] Bad file descriptor

Platform: Darwin James-MBP 19.5.0 Darwin Kernel Version 19.5.0: Tue May 26 20:41:44 PDT 2020; root:xnu-6153.121.2~2/RELEASE_X86_64 x86_64
Borg: 1.1.11.dev128+gae78914c  Python: CPython 3.7.5 msgpack: 0.5.6
PID: 32748  CWD: /
sys.argv: ['/Applications/Vorta.app/Contents/Resources/borg-dir/borg.exe', 'create', '--list', '--info', '--log-json', '--json', '--filter=AM', '-C', 'lz4', '--exclude-from', '/var/folders/pt/pv6swdgn36s4g6r9qy8v29kh0000gn/T/tmpsq4nsvbs', '--exclude-if-present', '.nobackup', '/Volumes/backups/BorgBackup_MBP::James-MBP-nas-2020-07-11T09:21:59', '/Users/jameshenderson/Library/Application Support/Get iPlayer Automator/Queue.automatorqueue', '/Users/jameshenderson/Library/Application Support/Get iPlayer Automator/download_history', '/Users/jameshenderson/Library/LaunchAgents', '/Users/jameshenderson/Library/Application Support/Vorta/settings.db', '/Users/jameshenderson/Library/Saved Searches', '/Users/jameshenderson/.ssh', '/Users/jameshenderson/Applications', '/Users/jameshenderson/Documents', '/Users/jameshenderson/Movies', '/Users/jameshenderson/Music', '/Users/jameshenderson/Pictures']
SSH_ORIGINAL_COMMAND: None
```

**Comment by m3nu** [comment]
The underlying file system is unstable. Is this a network-mounted FS? Maybe try using SSH?

`OSError: [Errno 9] Bad file descriptor`

**Comment by jchhenderson** [comment]
it's a QNAP NAS.
