### ISSUE TITLE
 OSError: [Errno 107] Transport endpoint is not connected

### ISSUE THREAD

**Issue by liamh** [borgbase/vorta#561]
**Describe the bug**
Cannot make backups at all. After working flawlessly, it now gives the above message every time. Confirmed that the remote location is accessible; can mount via `sshfs`, view files including the Borg repository.

**To Reproduce**
1. Click on 'start backup'

**Desktop (please complete the following information):**
  Operating System: Debian GNU/Linux 10 (buster)
            Kernel: Linux 4.19.0-9-amd64
      Architecture: x86-64

**Additional context**
If appropriate include logs. Can be found in Main Window > Misc Tab > Log.
````
2020-07-28 18:12:35,737 - vorta.borg.borg_thread - DEBUG - Using VortaSecretStorageKeyring keyring to store passwords.
2020-07-28 18:12:35,774 - asyncio - DEBUG - Using selector: EpollSelector
2020-07-28 18:12:35,811 - root - DEBUG - Found 0 passwords matching repo URL.
2020-07-28 18:12:35,812 - vorta.borg.borg_thread - DEBUG - Password not found in primary keyring. Falling back to VortaDBKeyring.
2020-07-28 18:12:35,867 - vorta.borg.borg_thread - INFO - Running command /usr/bin/borg create --list --info --log-json --json --filter=AM -C none .....
2020-07-28 18:12:37,930 - vorta.borg.borg_thread - ERROR - Remote: Borg 0.29.0: exception in RPC call:
2020-07-28 18:12:37,932 - vorta.borg.borg_thread - WARNING - Remote: Traceback (most recent call last):
2020-07-28 18:12:37,932 - vorta.borg.borg_thread - WARNING - Remote: File "/usr/home/kibab/borgbackup-0.29.0/borg/remote.py", line 96, in serve
2020-07-28 18:12:37,935 - vorta.borg.borg_thread - WARNING - Remote: TypeError: open() takes from 2 to 5 positional arguments but 7 were given
2020-07-28 18:12:43,800 - vorta.borg.borg_thread - ERROR - Remote: Platform: FreeBSD usw-s007.rsync.net 12.1-RELEASE-p4 FreeBSD 12.1-RELEASE-p4 rsync_12_1 amd64
2020-07-28 18:12:43,801 - vorta.borg.borg_thread - WARNING - Remote: Python: CPython 3.4.3
2020-07-28 18:12:43,801 - vorta.borg.borg_thread - WARNING - Remote: 
2020-07-28 18:12:43,803 - vorta.borg.borg_thread - WARNING - Please note:
2020-07-28 18:12:43,804 - vorta.borg.borg_thread - WARNING - If you see a TypeError complaining about the number of positional arguments
2020-07-28 18:12:43,804 - vorta.borg.borg_thread - WARNING - given to open(), you can ignore it if it comes from a borg version < 1.0.7.
2020-07-28 18:12:43,805 - vorta.borg.borg_thread - WARNING - This TypeError is a cosmetic side effect of the compatibility code borg
2020-07-28 18:12:43,806 - vorta.borg.borg_thread - WARNING - clients >= 1.0.7 have to support older borg servers.
2020-07-28 18:12:43,807 - vorta.borg.borg_thread - WARNING - This problem will go away as soon as the server has been upgraded to 1.0.7+.
2020-07-28 18:12:44,089 - vorta.borg.borg_thread - INFO - Creating archive at "...."
2020-07-28 18:12:44,245 - vorta.borg.borg_thread - WARNING - Traceback (most recent call last):
2020-07-28 18:12:44,246 - vorta.borg.borg_thread - WARNING - File "/usr/lib/python3/dist-packages/borg/archiver.py", line 4455, in main
2020-07-28 18:12:44,247 - vorta.borg.borg_thread - WARNING - exit_code = archiver.run(args)
2020-07-28 18:12:44,248 - vorta.borg.borg_thread - WARNING - File "/usr/lib/python3/dist-packages/borg/archiver.py", line 4387, in run
2020-07-28 18:12:44,250 - vorta.borg.borg_thread - WARNING - return set_ec(func(args))
2020-07-28 18:12:44,251 - vorta.borg.borg_thread - WARNING - File "/usr/lib/python3/dist-packages/borg/archiver.py", line 154, in wrapper
2020-07-28 18:12:44,252 - vorta.borg.borg_thread - WARNING - return method(self, args, repository=repository, **kwargs)
2020-07-28 18:12:44,252 - vorta.borg.borg_thread - WARNING - File "/usr/lib/python3/dist-packages/borg/archiver.py", line 556, in do_create
2020-07-28 18:12:44,252 - vorta.borg.borg_thread - WARNING - log_json=args.log_json)
2020-07-28 18:12:44,254 - vorta.borg.borg_thread - WARNING - File "/usr/lib/python3/dist-packages/borg/archive.py", line 292, in __init__
2020-07-28 18:12:44,255 - vorta.borg.borg_thread - WARNING - self.cwd = os.getcwd()
2020-07-28 18:12:44,256 - vorta.borg.borg_thread - WARNING - OSError: [Errno 107] Transport endpoint is not connected
2020-07-28 18:12:44,256 - vorta.borg.borg_thread - WARNING - During handling of the above exception, another exception occurred:
2020-07-28 18:12:44,259 - vorta.borg.borg_thread - WARNING - Traceback (most recent call last):
2020-07-28 18:12:44,260 - vorta.borg.borg_thread - WARNING - File "/usr/bin/borg", line 11, in <module>
2020-07-28 18:12:44,260 - vorta.borg.borg_thread - WARNING - load_entry_point('borgbackup==1.1.9', 'console_scripts', 'borg')()
2020-07-28 18:12:44,263 - vorta.borg.borg_thread - WARNING - File "/usr/lib/python3/dist-packages/borg/archiver.py", line 4477, in main
2020-07-28 18:12:44,265 - vorta.borg.borg_thread - WARNING - tb = '%s\n%s' % (traceback.format_exc(), sysinfo())
2020-07-28 18:12:44,265 - vorta.borg.borg_thread - WARNING - File "/usr/lib/python3/dist-packages/borg/helpers.py", line 1636, in sysinfo
2020-07-28 18:12:44,266 - vorta.borg.borg_thread - WARNING - info.append('PID: %d  CWD: %s' % (os.getpid(), os.getcwd()))
2020-07-28 18:12:44,267 - vorta.borg.borg_thread - WARNING - OSError: [Errno 107] Transport endpoint is not connected
````

**Comment by ThomasWaldmann** [comment]
```
2020-07-28 18:12:37,930 - vorta.borg.borg_thread - ERROR - Remote: Borg 0.29.0: exception in RPC call:
```

You do not want to talk to an ancient borg on rsync.net's side.

To avoid that, you need to invoke the `borg1` binary on their side.

**Comment by ThomasWaldmann** [comment]
And if `sshfs` says `transport endpoint not connected`, it means the mount / the filesystem does not work any more.

**Comment by liamh** [comment]
Thanks for the information. I see that borg has the option `--remote-path` which I presume is where I would specify `borg1`, but I don't see how to pass borg options from vorta. 

I am not getting the error from `sshfs`, that works fine.

**Comment by samuel-w** [comment]
Custom options aren't available, check https://github.com/borgbase/vorta/issues/274. I have a PR pending that should fix this.
