### ISSUE TITLE
Timezone error

### ISSUE THREAD

**Issue by tiotrom** [borgbase/vorta#562]
I get this error when I try to start it:

`
[tio@tio-pc ~]$ vorta
2020-08-02 23:14:38,771 - vorta.i18n - DEBUG - Loading translation failed for ['en', 'en-US', 'en-Latn-US'].
Traceback (most recent call last):
  File "/usr/bin/vorta", line 33, in <module>
    sys.exit(load_entry_point('vorta==0.6.26', 'gui_scripts', 'vorta')())
  File "/usr/lib/python3.8/site-packages/vorta/__main__.py", line 37, in main
    app = VortaApp(sys.argv, single_app=True)
  File "/usr/lib/python3.8/site-packages/vorta/application.py", line 47, in __init__
    self.scheduler = VortaScheduler(self)
  File "/usr/lib/python3.8/site-packages/vorta/scheduler.py", line 20, in __init__
    super().__init__()
  File "/usr/lib/python3.8/site-packages/apscheduler/schedulers/base.py", line 87, in __init__
    self.configure(gconfig, **options)
  File "/usr/lib/python3.8/site-packages/apscheduler/schedulers/base.py", line 126, in configure
    self._configure(config)
  File "/usr/lib/python3.8/site-packages/apscheduler/schedulers/base.py", line 697, in _configure
    self.timezone = astimezone(config.pop('timezone', None)) or get_localzone()
  File "/usr/lib/python3.8/site-packages/tzlocal/unix.py", line 165, in get_localzone
    _cache_tz = _get_localzone()
  File "/usr/lib/python3.8/site-packages/tzlocal/unix.py", line 90, in _get_localzone
    utils.assert_tz_offset(tz)
  File "/usr/lib/python3.8/site-packages/tzlocal/utils.py", line 46, in assert_tz_offset
    raise ValueError(msg)
ValueError: Timezone offset does not match system offset: 10800 != 7200. Please, check your config files.
[tio@tio-pc ~]$ 
`
I am using Manjaro + the AUR version of the app

**Comment by samuel-w** [comment]
Try installing and running it through pip. If there is no bug then its the packager's fault.

**Comment by m3nu** [comment]
The error happens in `apscheduler`, which uses another `tzlocal` package. So not related to Vorta really, but the maintainer of that package may have an open issue for it?

`/usr/lib/python3.8/site-packages/tzlocal/utils.py`

**Comment by tiotrom** [comment]
I see. So should I report it to here https://github.com/agronholm/apscheduler/issues? The flatpak version of Vorta works btw.

**Comment by m3nu** [comment]
Then you may have an old version of apscheduler or tzlocal from your distro?

Not sure where the right place to report this is. I can just tell you that Vorta doesn't deal with time zones at all, so we can probably not do much here.

**Comment by tiotrom** [comment]
I am using the AUR for apscheduler - which I believe is the latest one. I reported the Vorta issue to the AUR maintainer as well. For now I will use the flatpak version but hopefully this can be fixed upstream.

**Comment by bjo81** [comment]
python-apscheduler in AUR seems to be latest version, it depends on python-tzlocal which has also latest version. 
I tried a vorta install from AUR yesterday and had no issues.

**Comment by tiotrom** [comment]
My python-tzlocal comes from manjaro's repositories but it is the same version as the AUR one, 2.1-1. Can anyone try it on a Manjaro install?

**Comment by samuel-w** [comment]
Closing. If anyone else has timezone issues then file a new issue.

**Comment by tiotrom** [comment]
> Edit : After force to rebuild apscheduler, vorta is running

Didn't do it for me....

**Comment by samuel-w** [comment]
What you have is an Arch Linux issue, unrelated to vorta. See https://github.com/regebro/tzlocal/issues/79
