### ISSUE TITLE
Diff doesn't always work

### ISSUE THREAD

**Issue by harmlessdrudge** [borgbase/vorta#613]
**Describe the bug**

Diff function works sometimes, but often does nothing.

**To Reproduce**

Click on Archives, then DIff, select last two backups and then click diff

![vorta-diff](https://user-images.githubusercontent.com/3849521/92176000-89280480-ee35-11ea-8efc-df32cfefc46d.jpg)

Result is nothing shown here, despite hundreds of Mb of additional files.

**Desktop (please complete the following information):**

Linux Mint 19.3 w Cinnamon desktop

**Additional context**
If appropriate include logs. Can be found in Main Window > Misc Tab > Log.
[vorta.log](https://github.com/borgbase/vorta/files/5171512/vorta.log)

**Comment by samuel-w** [comment]
I've had this happen too, even after just opening, but it goes away with a restart of Vorta.

**Comment by ktosiek** [comment]
Do you see an entry for `borg-run diff` in Schedule -> Log? If so, what's the Returncode?

**Comment by harmlessdrudge** [comment]
Yes, Returncode seems to be 0 regardless of whether or not any differences are displayed (every diff Returncode is 0).

**Comment by ThomasWaldmann** [comment]
@harmlessdrudge can you reproduce an issue when just using borg directly? if so, please file a bug on the borg issue tracker.

**Comment by harmlessdrudge** [comment]
Maybe this will help

`2020-09-04 17:27:23,639 - vorta.i18n - DEBUG - Loading translation failed for ['en-IE', 'en-Latn-IE'].
2020-09-04 17:27:23,663 - apscheduler.scheduler - INFO - Scheduler started
2020-09-04 17:27:23,665 - apscheduler.scheduler - INFO - Added job "VortaScheduler.create_backup" to job store "default"
2020-09-04 17:27:23,665 - vorta.scheduler - DEBUG - New job for profile Default was added.
2020-09-04 17:27:23,715 - vorta.borg.borg_thread - INFO - Running command /usr/bin/borg --version
2020-09-04 17:28:06,454 - vorta.borg.borg_thread - DEBUG - Using VortaSecretStorageKeyring keyring to store passwords.
2020-09-04 17:28:06,455 - asyncio - DEBUG - Using selector: EpollSelector
2020-09-04 17:28:06,460 - root - DEBUG - Found 1 passwords matching repo URL.
2020-09-04 17:28:06,521 - vorta.borg.borg_thread - INFO - Running command /usr/bin/borg diff --info --log-json /mnt/linuxbackup/T440Mint/borg::T440-default-2020-09-02T13:00:00 T440-default-2020-09-03T13:00:00
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/vorta/views/archive_tab.py", line 460, in list_diff_result
    window = DiffResult(result['data'], archive_newer, archive_older)
  File "/usr/local/lib/python3.6/dist-packages/vorta/views/diff_result.py", line 72, in __init__
    files_with_attributes.append(parse_line(line))
  File "/usr/local/lib/python3.6/dist-packages/vorta/views/diff_result.py", line 60, in parse_line
    full_path = line[full_path_index:]
UnboundLocalError: local variable 'full_path_index' referenced before assignment
`

**Comment by samuel-w** [comment]
It is indeed related to #553. Try running Vorta from master. 
Note: You will not be able to return back to running the released version of Vorta until it updates. Backup your profile (usually in `~.local/share/Vorta/`) and restore it later.
