### ISSUE TITLE
Vorta 0.70 crashes when GUI is opened via tray icon while a backup is running

### ISSUE THREAD

**Issue by deermo** [borgbase/vorta#619]
**Describe the bug**
When I start a backup in Vorta 0.70 via system tray and  then open the GUI via system tray, Vorta crashes.
Might overlap with #386?
(OT: Thanks to the team for the many improvements in the 0.7 release!!)

**To Reproduce**
1. Open vorta (with window closed as last state)
2. Start backup via tray
3. Click try icon and click "Vorta" to open GUI 

**Desktop (please complete the following information):**
- OS: macOS 10.15.6
- Vorta version: 0.70
- Borg version: 1.1.13

**Additional context**
```
2020-09-06 19:01:19,107 - vorta.i18n - DEBUG - Loading translation succeeded for ['de-DE'].
2020-09-06 19:01:19,173 - apscheduler.scheduler - INFO - Scheduler started
2020-09-06 19:01:19,175 - apscheduler.scheduler - INFO - Added job "VortaScheduler.create_backup" to job store "default"
2020-09-06 19:01:19,175 - vorta.scheduler - DEBUG - New job for profile PROFILE was added.
2020-09-06 19:01:19,175 - apscheduler.scheduler - INFO - Added job "VortaScheduler.create_backup" to job store "default"
2020-09-06 19:01:19,176 - vorta.scheduler - DEBUG - New job for profile PROFILE was added.
2020-09-06 19:01:19,225 - vorta.borg.borg_thread - INFO - Running command /usr/local/bin/borg --version
2020-09-06 19:01:27,835 - vorta.borg.borg_thread - DEBUG - Using VortaDarwinKeyring keyring to store passwords.
2020-09-06 19:01:27,948 - root - WARNING - Command ipconfig getpacket en6 failed
2020-09-06 19:01:27,955 - root - WARNING - Command ipconfig getpacket en1 failed
2020-09-06 19:01:27,962 - root - WARNING - Command ipconfig getpacket en2 failed
2020-09-06 19:01:27,969 - root - WARNING - Command ipconfig getpacket en3 failed
2020-09-06 19:01:27,975 - root - WARNING - Command ipconfig getpacket en4 failed
2020-09-06 19:01:27,982 - root - WARNING - Command ipconfig getpacket bridge0 failed
2020-09-06 19:01:27,991 - vorta.borg.borg_thread - INFO - Running command /usr/local/bin/borg create --list --progress --info --log-json --json --filter=AM -C zstd,3 --exclude-from /var/folders/pn/1lpcy1m113d3kdq67xtkd94m0000gn/T/tmplspaqbvf --exclude-if-present .nobackup ssh://REPO /PATH
```

**Comment by samuel-w** [comment]
Can confirm:
```
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.8/site-packages/vorta/application.py", line 90, in open_main_window_action
    self.main_window = MainWindow(self)
  File "/home/user/.local/lib/python3.8/site-packages/vorta/views/main_window.py", line 94, in __init__
    self.set_status(self.tr('Backup in progress.'))
AttributeError: 'MainWindow' object has no attribute 'set_status'

**Comment by Hofer-Julian** [comment]
I could imagine, that we now have enough contributors/users to start publishing release candidates?

**Comment by m3nu** [comment]
Thanks for the quick fix @samuel-w and for reporting @deermo. I'll update the macOS build on Github right away and possibly we do a 0.7.1 in a few days.

**Comment by m3nu** [comment]
New notarized macOS build: https://files.qmax.us/vorta/Vorta-0.7.1-RC1.dmg

**Comment by m3nu** [comment]
> I could imagine, that we now have enough contributors/users to start publishing release candidates?

Not many people use the Github master branch. For macOS it's also hard to do, since it needs the notarization and a $99 developer account. So fine with doing RCs, if more people and up using them.
