### ISSUE TITLE
Exceptions not logged in logs

### ISSUE THREAD

**Issue by samuel-w** [borgbase/vorta#621]
**Describe the bug**
When Vorta crashes, the exceptions are not stored in the logs, making them harder to diagnose.
Not really that big of an issue, since the crash _should_ be reproducable and it is for reporting only.

**To Reproduce**
1. Find a crash that happens.
2. Produce the crash while running from the terminal.
3. Read the logs, and note that the crash is visible in the terminal, but not in the logs.

**Desktop (please complete the following information):**
- OS: Ubuntu 20.04
- Vorta version: 0.7.0
- Borg version: 1.1.13

Vorta and Borg versions can be found in Main Window > Misc Tab

**Additional context**
Example crash #619 
If appropriate include logs. Can be found in Main Window > Misc Tab > Log.
Log file:
```
2020-09-06 13:11:37,544 - vorta.i18n - DEBUG - Loading translation failed for ['en', 'en-US', 'en-Latn-US'].
2020-09-06 13:11:37,556 - apscheduler.scheduler - INFO - Scheduler started
2020-09-06 13:11:37,558 - apscheduler.scheduler - INFO - Added job "VortaScheduler.create_backup" to job store "default"
2020-09-06 13:11:37,558 - vorta.scheduler - DEBUG - New job for profile Backblaze was added.
2020-09-06 13:11:37,990 - vorta.borg.borg_thread - INFO - Running command /home/user/.local/bin/borg --version
2020-09-06 13:11:43,373 - vorta.borg.borg_thread - DEBUG - Using VortaSecretStorageKeyring keyring to store passwords.
2020-09-06 13:11:43,373 - asyncio - DEBUG - Using selector: EpollSelector
2020-09-06 13:11:43,378 - root - DEBUG - Found 2 passwords matching repo URL.
2020-09-06 13:11:43,411 - vorta.borg.borg_thread - INFO - Running command /home/user/.local/bin/borg create --list --progress --info --log-json --json --filter=AM -C zstd,8 --exclude-if-present .nobackup REPO_URL /home/user
2020-09-06 13:11:43,821 - vorta.borg.borg_thread - INFO - Creating archive at "REPO_URL"
```

Terminal output:
```
2020-09-06 13:11:37,544 - vorta.i18n - DEBUG - Loading translation failed for ['en', 'en-US', 'en-Latn-US'].
2020-09-06 13:11:37,556 - apscheduler.scheduler - INFO - Scheduler started
2020-09-06 13:11:37,558 - apscheduler.scheduler - INFO - Added job "VortaScheduler.create_backup" to job store "default"
2020-09-06 13:11:37,558 - vorta.scheduler - DEBUG - New job for profile Backblaze was added.
2020-09-06 13:11:37,990 - vorta.borg.borg_thread - INFO - Running command /home/user/.local/bin/borg --version
2020-09-06 13:11:43,373 - vorta.borg.borg_thread - DEBUG - Using VortaSecretStorageKeyring keyring to store passwords.
2020-09-06 13:11:43,373 - asyncio - DEBUG - Using selector: EpollSelector
2020-09-06 13:11:43,378 - root - DEBUG - Found 2 passwords matching repo URL.
2020-09-06 13:11:43,411 - vorta.borg.borg_thread - INFO - Running command /home/user/.local/bin/borg create --list --progress --info --log-json --json --filter=AM -C zstd,8 --exclude-if-present .nobackup REPO_URL /home/user
2020-09-06 13:11:43,821 - vorta.borg.borg_thread - INFO - Creating archive at "REPO_URL"
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.8/site-packages/vorta/application.py", line 90, in open_main_window_action
    self.main_window = MainWindow(self)
  File "/home/user/.local/lib/python3.8/site-packages/vorta/views/main_window.py", line 94, in __init__
    self.set_status(self.tr('Backup in progress.'))
AttributeError: 'MainWindow' object has no attribute 'set_status'

```

**Comment by samuel-w** [comment]
Relevant stackoverflow: https://stackoverflow.com/questions/8050775/using-pythons-logging-module-to-log-all-exceptions-and-errors
