### ISSUE TITLE
Vorta 0.7.0 not starting in Mojave

### ISSUE THREAD

**Issue by huntz** [borgbase/vorta#624]
After updating from Vorta 0.6.26 on macOS Mojave (10.14.6) the application is not starting.

The application will not start if running from the GUI, returning no errors.

From the command line, I get this:

/Applications/Vorta.app/Contents/MacOS/vorta-darwin
2020-09-07 14:07:06,961 - vorta.i18n - DEBUG - Loading translation succeeded for ['en', 'en-US', 'en-Latn-US'].
2020-09-07 14:07:09,217 - apscheduler.scheduler - INFO - Scheduler started
2020-09-07 14:07:09,220 - apscheduler.scheduler - INFO - Added job "VortaScheduler.create_backup" to job store "default"
2020-09-07 14:07:09,220 - vorta.scheduler - DEBUG - New job for profile Default was added.
Traceback (most recent call last):
  File "__main__.py", line 44, in <module>
  File "__main__.py", line 37, in main
  File "application.py", line 56, in __init__
  File "application.py", line 90, in open_main_window_action
  File "views/main_window.py", line 50, in __init__
  File "views/schedule_tab.py", line 32, in __init__
  File "views/schedule_tab.py", line 68, in populate_from_profile
  File "views/schedule_tab.py", line 72, in init_wifi
  File "utils.py", line 130, in get_sorted_wifis
  File "network_status/darwin.py", line 48, in get_known_wifis
  File "peewee.py", line 4871, in format_date_time
TypeError: strptime() argument 1 must be str, not datetime.datetime
[74960] Failed to execute script __main__

- OS: macOS Mojave (10.14.6)
- Vorta version: 0.7.0
- Borg version: 1.1.11

**Comment by m3nu** [comment]
Thanks for reporting, @huntz . I didn't catch that error, since macOS seems to use different names for "last connected".

I've added one more field and prevented the error you are seeing in #625 . We'll add this to 0.7.1 in a few days.
