### ISSUE TITLE
Vorta doesn't launch

### ISSUE THREAD

**Issue by v3111707** [borgbase/vorta#633]
**Describe the bug**
On macos 10.14.6 Vorta 0.7.0 doesn't launch. When I run  the Vorta from Application list it doesn't launch without any error.
I tried run /Applications/Vorta.app/Contents/MacOS/vorta-darwin and get next logs:
```
2020-09-08 20:23:55,218 - vorta.i18n - DEBUG - Loading translation succeeded for ['en', 'en-US', 'en-Latn-US'].
2020-09-08 20:23:55,281 - apscheduler.scheduler - INFO - Scheduler started
Traceback (most recent call last):
  File "__main__.py", line 44, in <module>
  File "__main__.py", line 37, in main
  File "application.py", line 56, in __init__
  File "application.py", line 90, in open_main_window_action
  File "views/main_window.py", line 50, in __init__
  File "views/schedule_tab.py", line 32, in __init__
  File "views/schedule_tab.py", line 68, in populate_from_profile
  File "views/schedule_tab.py", line 72, in init_wifi
  File "utils.py", line 130, in get_sorted_wifis
  File "network_status/darwin.py", line 48, in get_known_wifis
  File "peewee.py", line 4871, in format_date_time
TypeError: strptime() argument 1 must be str, not datetime.datetime
[34719] Failed to execute script __main__ 

```
**To Reproduce**
1. Run Vorta

**Desktop (please complete the following information):**
- OS:macos 10.14.6
- Vorta version: 0.7.0 
- Borg version: 1.1.13

**Comment by v3111707** [comment]
https://github.com/borgbase/vorta/issues/629

**Comment by samuel-w** [comment]
Actualy is #624
