### ISSUE TITLE
DBusException in vorta.network_status

### ISSUE THREAD

**Issue by buckket** [borgbase/vorta#669]
**Describe the bug**

I’m using Arch Linux with ConnMan, which does not support the DBus interface or at least not the specific properties Vorta wants to query. Vorta then fails with an exception followed by a SIGSEGV.

```
Traceback (most recent call last):
  File "/usr/bin/vorta", line 33, in <module>
    sys.exit(load_entry_point('vorta==0.7.1', 'gui_scripts', 'vorta')())
  File "/usr/lib/python3.8/site-packages/vorta/__main__.py", line 37, in main
    app = VortaApp(sys.argv, single_app=True)
  File "/usr/lib/python3.8/site-packages/vorta/application.py", line 56, in __init__
    self.open_main_window_action()
  File "/usr/lib/python3.8/site-packages/vorta/application.py", line 90, in open_main_window_action
    self.main_window = MainWindow(self)
  File "/usr/lib/python3.8/site-packages/vorta/views/main_window.py", line 50, in __init__
    self.scheduleTab = ScheduleTab(self.scheduleTabSlot)
  File "/usr/lib/python3.8/site-packages/vorta/views/schedule_tab.py", line 32, in __init__
    self.populate_from_profile()
  File "/usr/lib/python3.8/site-packages/vorta/views/schedule_tab.py", line 68, in populate_from_profile
    self.init_wifi()
  File "/usr/lib/python3.8/site-packages/vorta/views/schedule_tab.py", line 72, in init_wifi
    for wifi in get_sorted_wifis(self.profile()):
  File "/usr/lib/python3.8/site-packages/vorta/utils.py", line 138, in get_sorted_wifis
    system_wifis = get_network_status_monitor().get_known_wifis()
  File "/usr/lib/python3.8/site-packages/vorta/utils.py", line 41, in get_network_status_monitor
    _network_status_monitor = NetworkStatusMonitor.get_network_status_monitor()
  File "/usr/lib/python3.8/site-packages/vorta/network_status/abc.py", line 15, in get_network_status_monitor
    return NetworkManagerMonitor()
  File "/usr/lib/python3.8/site-packages/vorta/network_status/network_manager.py", line 16, in __init__
    self._nm = nm_adapter or NetworkManagerDBusAdapter.get_system_nm_adapter()
  File "/usr/lib/python3.8/site-packages/vorta/network_status/network_manager.py", line 110, in get_system_nm_adapter
    if not nm_adapter.isValid():
  File "/usr/lib/python3.8/site-packages/vorta/network_status/network_manager.py", line 117, in isValid
    nm_version = self._get_nm_version()
  File "/usr/lib/python3.8/site-packages/vorta/network_status/network_manager.py", line 145, in _get_nm_version
    version, _suffindex = QVersionNumber.fromString(read_dbus_property(self._nm, 'Version'))
  File "/usr/lib/python3.8/site-packages/vorta/network_status/network_manager.py", line 156, in read_dbus_property
    return get_result(msg)
  File "/usr/lib/python3.8/site-packages/vorta/network_status/network_manager.py", line 163, in get_result
    raise DBusException("DBus call failed: {}".format(msg.arguments()))
vorta.network_status.network_manager.DBusException: DBus call failed: ['Unsupported property']
```

**To Reproduce**
Start Vorta on Linux with a network manager other than NetworkManager.

**Desktop:**
- OS: Arch Linux
- Vorta version: 0.7.1
- Installed from: AUR

**Comment by m3nu** [comment]
Thanks for the quick fix, @samuel-w . Merged #670
