### ISSUE TITLE
Notify user of locked repo

### ISSUE THREAD

**Issue by OldBigIron** [borgbase/vorta#713]
I press the "Start Backup" as I have for since August every other day. I in inherited this system and not familiar with Linux and was shown how to start the backup.

**Desktop (please complete the following information):**
- OS: Linux Mint 20 Cinnamon, version 4.6.7, Kernel: 5.4.0.-53-generic
- Vorta version: v0.7.1; Borg: 1.1.13 /app/bin/borg
- Installed from: Mint software manager

**Additional context**
log
============
2020-11-15 19:38:01,878 - vorta.i18n - DEBUG - Loading translation failed for ['en', 'en-US', 'en-Latn-US'].
2020-11-15 19:38:01,986 - apscheduler.scheduler - INFO - Scheduler started
2020-11-15 19:38:06,404 - root - INFO - Using NetworkManagerMonitor NetworkStatusMonitor implementation.
2020-11-15 19:38:09,322 - vorta.borg.borg_thread - INFO - Running command /app/bin/borg --version
2020-11-15 19:38:18,479 - vorta.borg.borg_thread - DEBUG - Using VortaSecretStorageKeyring keyring to store passwords.
2020-11-15 19:38:18,480 - asyncio - DEBUG - Using selector: EpollSelector
2020-11-15 19:38:18,794 - root - DEBUG - Found 1 passwords matching repo URL.
2020-11-15 19:38:19,288 - vorta.borg.borg_thread - INFO - Running command /app/bin/borg create --list --progress --info --log-json --json --filter=AM -C lz4 --exclude-from /tmp/tmpx_fmubh7 /media/psheedy/backup640::psheedy-XPS-8920-default-2020-11-15T19:38:19 /home/psheedy /home/psheedy/.googleearth /home/psheedy/.mozilla /home/psheedy/.local
2020-11-15 19:38:19,692 - vorta.borg.borg_thread - ERROR - Failed to create/acquire the lock /media/psheedy/backup640/lock.exclusive ([Errno 13] Permission denied: '/media/psheedy/backup640/lock.exclusive').
2020-11-15 19:38:19,693 - vorta.borg.borg_thread - ERROR - Traceback (most recent call last):
  File "/app/lib/python3.7/site-packages/borg/archiver.py", line 4565, in main
    exit_code = archiver.run(args)
  File "/app/lib/python3.7/site-packages/borg/archiver.py", line 4497, in run
    return set_ec(func(args))
  File "/app/lib/python3.7/site-packages/borg/archiver.py", line 161, in wrapper
    with repository:
  File "/app/lib/python3.7/site-packages/borg/repository.py", line 190, in __enter__
    self.open(self.path, bool(self.exclusive), lock_wait=self.lock_wait, lock=self.do_lock)
  File "/app/lib/python3.7/site-packages/borg/repository.py", line 421, in open
    self.lock = Lock(os.path.join(path, 'lock'), exclusive, timeout=lock_wait, kill_stale_locks=hostname_is_unique()).acquire()
  File "/app/lib/python3.7/site-packages/borg/locking.py", line 350, in acquire
    self._wait_for_readers_finishing(remove, sleep)
  File "/app/lib/python3.7/site-packages/borg/locking.py", line 363, in _wait_for_readers_finishing
    self._lock.acquire()
  File "/app/lib/python3.7/site-packages/borg/locking.py", line 138, in acquire
    raise LockFailed(self.path, str(err)) from None
borg.locking.LockFailed: Failed to create/acquire the lock /media/psheedy/backup640/lock.exclusive ([Errno 13] Permission denied: '/media/psheedy/backup640/lock.exclusive').

Platform: Linux psheedy-XPS-8920 5.4.0-53-generic #59-Ubuntu SMP Wed Oct 21 09:38:44 UTC 2020 x86_64
Linux:   
Borg: 1.1.13  Python: CPython 3.7.4 msgpack: 0.5.6
PID: 12  CWD: /home/psheedy
sys.argv: ['/app/bin/borg', 'create', '--list', '--progress', '--info', '--log-json', '--json', '--filter=AM', '-C', 'lz4', '--exclude-from', '/tmp/tmpx_fmubh7', '/media/psheedy/backup640::psheedy-XPS-8920-default-2020-11-15T19:38:19', '/home/psheedy', '/home/psheedy/.googleearth', '/home/psheedy/.mozilla', '/home/psheedy/.local']
SSH_ORIGINAL_COMMAND: None

2020-11-15 19:40:16,189 - vorta.borg.borg_thread - DEBUG - Using VortaSecretStorageKeyring keyring to store passwords.
2020-11-15 19:40:16,190 - asyncio - DEBUG - Using selector: EpollSelector
2020-11-15 19:40:16,199 - root - DEBUG - Found 1 passwords matching repo URL.
2020-11-15 19:40:16,419 - vorta.borg.borg_thread - INFO - Running command /app/bin/borg create --list --progress --info --log-json --json --filter=AM -C lz4 --exclude-from /tmp/tmphs1t_6ye /media/psheedy/backup640::psheedy-XPS-8920-default-2020-11-15T19:40:16 /home/psheedy /home/psheedy/.googleearth /home/psheedy/.mozilla /home/psheedy/.local
2020-11-15 19:40:16,843 - vorta.borg.borg_thread - ERROR - Failed to create/acquire the lock /media/psheedy/backup640/lock.exclusive ([Errno 13] Permission denied: '/media/psheedy/backup640/lock.exclusive').
2020-11-15 19:40:16,844 - vorta.borg.borg_thread - ERROR - Traceback (most recent call last):
  File "/app/lib/python3.7/site-packages/borg/archiver.py", line 4565, in main
    exit_code = archiver.run(args)
  File "/app/lib/python3.7/site-packages/borg/archiver.py", line 4497, in run
    return set_ec(func(args))
  File "/app/lib/python3.7/site-packages/borg/archiver.py", line 161, in wrapper
    with repository:
  File "/app/lib/python3.7/site-packages/borg/repository.py", line 190, in __enter__
    self.open(self.path, bool(self.exclusive), lock_wait=self.lock_wait, lock=self.do_lock)
  File "/app/lib/python3.7/site-packages/borg/repository.py", line 421, in open
    self.lock = Lock(os.path.join(path, 'lock'), exclusive, timeout=lock_wait, kill_stale_locks=hostname_is_unique()).acquire()
  File "/app/lib/python3.7/site-packages/borg/locking.py", line 350, in acquire
    self._wait_for_readers_finishing(remove, sleep)
  File "/app/lib/python3.7/site-packages/borg/locking.py", line 363, in _wait_for_readers_finishing
    self._lock.acquire()
  File "/app/lib/python3.7/site-packages/borg/locking.py", line 138, in acquire
    raise LockFailed(self.path, str(err)) from None
borg.locking.LockFailed: Failed to create/acquire the lock /media/psheedy/backup640/lock.exclusive ([Errno 13] Permission denied: '/media/psheedy/backup640/lock.exclusive').

Platform: Linux psheedy-XPS-8920 5.4.0-53-generic #59-Ubuntu SMP Wed Oct 21 09:38:44 UTC 2020 x86_64
Linux:   
Borg: 1.1.13  Python: CPython 3.7.4 msgpack: 0.5.6
PID: 16  CWD: /home/psheedy
sys.argv: ['/app/bin/borg', 'create', '--list', '--progress', '--info', '--log-json', '--json', '--filter=AM', '-C', 'lz4', '--exclude-from', '/tmp/tmphs1t_6ye', '/media/psheedy/backup640::psheedy-XPS-8920-default-2020-11-15T19:40:16', '/home/psheedy', '/home/psheedy/.googleearth', '/home/psheedy/.mozilla', '/home/psheedy/.local']
SSH_ORIGINAL_COMMAND: None

2020-11-15 19:41:22,126 - vorta.borg.borg_thread - DEBUG - Using VortaSecretStorageKeyring keyring to store passwords.
2020-11-15 19:41:22,127 - asyncio - DEBUG - Using selector: EpollSelector
2020-11-15 19:41:22,136 - root - DEBUG - Found 1 passwords matching repo URL.
2020-11-15 19:41:22,348 - vorta.borg.borg_thread - INFO - Running command /app/bin/borg create --list --progress --info --log-json --json --filter=AM -C lz4 --exclude-from /tmp/tmpzr1szvll /media/psheedy/backup640::psheedy-XPS-8920-default-2020-11-15T19:41:22 /home/psheedy /home/psheedy/.googleearth /home/psheedy/.mozilla /home/psheedy/.local
2020-11-15 19:41:22,764 - vorta.borg.borg_thread - ERROR - Failed to create/acquire the lock /media/psheedy/backup640/lock.exclusive ([Errno 13] Permission denied: '/media/psheedy/backup640/lock.exclusive').
2020-11-15 19:41:22,764 - vorta.borg.borg_thread - ERROR - Traceback (most recent call last):
  File "/app/lib/python3.7/site-packages/borg/archiver.py", line 4565, in main
    exit_code = archiver.run(args)
  File "/app/lib/python3.7/site-packages/borg/archiver.py", line 4497, in run
    return set_ec(func(args))
  File "/app/lib/python3.7/site-packages/borg/archiver.py", line 161, in wrapper
    with repository:
  File "/app/lib/python3.7/site-packages/borg/repository.py", line 190, in __enter__
    self.open(self.path, bool(self.exclusive), lock_wait=self.lock_wait, lock=self.do_lock)
  File "/app/lib/python3.7/site-packages/borg/repository.py", line 421, in open
    self.lock = Lock(os.path.join(path, 'lock'), exclusive, timeout=lock_wait, kill_stale_locks=hostname_is_unique()).acquire()
  File "/app/lib/python3.7/site-packages/borg/locking.py", line 350, in acquire
    self._wait_for_readers_finishing(remove, sleep)
  File "/app/lib/python3.7/site-packages/borg/locking.py", line 363, in _wait_for_readers_finishing
    self._lock.acquire()
  File "/app/lib/python3.7/site-packages/borg/locking.py", line 138, in acquire
    raise LockFailed(self.path, str(err)) from None
borg.locking.LockFailed: Failed to create/acquire the lock /media/psheedy/backup640/lock.exclusive ([Errno 13] Permission denied: '/media/psheedy/backup640/lock.exclusive').

Platform: Linux psheedy-XPS-8920 5.4.0-53-generic #59-Ubuntu SMP Wed Oct 21 09:38:44 UTC 2020 x86_64
Linux:   
Borg: 1.1.13  Python: CPython 3.7.4 msgpack: 0.5.6
PID: 20  CWD: /home/psheedy
sys.argv: ['/app/bin/borg', 'create', '--list', '--progress', '--info', '--log-json', '--json', '--filter=AM', '-C', 'lz4', '--exclude-from', '/tmp/tmpzr1szvll', '/media/psheedy/backup640::psheedy-XPS-8920-default-2020-11-15T19:41:22', '/home/psheedy', '/home/psheedy/.googleearth', '/home/psheedy/.mozilla', '/home/psheedy/.local']
SSH_ORIGINAL_COMMAND: None

2020-11-15 19:48:36,952 - vorta.borg.borg_thread - DEBUG - Using VortaSecretStorageKeyring keyring to store passwords.
2020-11-15 19:48:36,953 - asyncio - DEBUG - Using selector: EpollSelector
2020-11-15 19:48:36,961 - root - DEBUG - Found 1 passwords matching repo URL.
2020-11-15 19:48:37,172 - vorta.borg.borg_thread - INFO - Running command /app/bin/borg create --list --progress --info --log-json --json --filter=AM -C lz4 --exclude-from /tmp/tmp0nkndqw5 /media/psheedy/backup640::psheedy-XPS-8920-default-2020-11-15T19:48:37 /home/psheedy /home/psheedy/.googleearth /home/psheedy/.mozilla /home/psheedy/.local
2020-11-15 19:48:37,599 - vorta.borg.borg_thread - ERROR - Failed to create/acquire the lock /media/psheedy/backup640/lock.exclusive ([Errno 13] Permission denied: '/media/psheedy/backup640/lock.exclusive').
2020-11-15 19:48:37,599 - vorta.borg.borg_thread - ERROR - Traceback (most recent call last):
  File "/app/lib/python3.7/site-packages/borg/archiver.py", line 4565, in main
    exit_code = archiver.run(args)
  File "/app/lib/python3.7/site-packages/borg/archiver.py", line 4497, in run
    return set_ec(func(args))
  File "/app/lib/python3.7/site-packages/borg/archiver.py", line 161, in wrapper
    with repository:
  File "/app/lib/python3.7/site-packages/borg/repository.py", line 190, in __enter__
    self.open(self.path, bool(self.exclusive), lock_wait=self.lock_wait, lock=self.do_lock)
  File "/app/lib/python3.7/site-packages/borg/repository.py", line 421, in open
    self.lock = Lock(os.path.join(path, 'lock'), exclusive, timeout=lock_wait, kill_stale_locks=hostname_is_unique()).acquire()
  File "/app/lib/python3.7/site-packages/borg/locking.py", line 350, in acquire
    self._wait_for_readers_finishing(remove, sleep)
  File "/app/lib/python3.7/site-packages/borg/locking.py", line 363, in _wait_for_readers_finishing
    self._lock.acquire()
  File "/app/lib/python3.7/site-packages/borg/locking.py", line 138, in acquire
    raise LockFailed(self.path, str(err)) from None
borg.locking.LockFailed: Failed to create/acquire the lock /media/psheedy/backup640/lock.exclusive ([Errno 13] Permission denied: '/media/psheedy/backup640/lock.exclusive').

Platform: Linux psheedy-XPS-8920 5.4.0-53-generic #59-Ubuntu SMP Wed Oct 21 09:38:44 UTC 2020 x86_64
Linux:   
Borg: 1.1.13  Python: CPython 3.7.4 msgpack: 0.5.6
PID: 24  CWD: /home/psheedy
sys.argv: ['/app/bin/borg', 'create', '--list', '--progress', '--info', '--log-json', '--json', '--filter=AM', '-C', 'lz4', '--exclude-from', '/tmp/tmp0nkndqw5', '/media/psheedy/backup640::psheedy-XPS-8920-default-2020-11-15T19:48:37', '/home/psheedy', '/home/psheedy/.googleearth', '/home/psheedy/.mozilla', '/home/psheedy/.local']
SSH_ORIGINAL_COMMAND: None

2020-11-15 19:48:39,546 - vorta.borg.borg_thread - DEBUG - Using VortaSecretStorageKeyring keyring to store passwords.
2020-11-15 19:48:39,547 - asyncio - DEBUG - Using selector: EpollSelector
2020-11-15 19:48:39,556 - root - DEBUG - Found 1 passwords matching repo URL.
2020-11-15 19:48:39,738 - vorta.borg.borg_thread - INFO - Running command /app/bin/borg create --list --progress --info --log-json --json --filter=AM -C lz4 --exclude-from /tmp/tmp7w5dh7p1 /media/psheedy/backup640::psheedy-XPS-8920-default-2020-11-15T19:48:39 /home/psheedy /home/psheedy/.googleearth /home/psheedy/.mozilla /home/psheedy/.local
2020-11-15 19:48:40,156 - vorta.borg.borg_thread - ERROR - Failed to create/acquire the lock /media/psheedy/backup640/lock.exclusive ([Errno 13] Permission denied: '/media/psheedy/backup640/lock.exclusive').
2020-11-15 19:48:40,156 - vorta.borg.borg_thread - ERROR - Traceback (most recent call last):
  File "/app/lib/python3.7/site-packages/borg/archiver.py", line 4565, in main
    exit_code = archiver.run(args)
  File "/app/lib/python3.7/site-packages/borg/archiver.py", line 4497, in run
    return set_ec(func(args))
  File "/app/lib/python3.7/site-packages/borg/archiver.py", line 161, in wrapper
    with repository:
  File "/app/lib/python3.7/site-packages/borg/repository.py", line 190, in __enter__
    self.open(self.path, bool(self.exclusive), lock_wait=self.lock_wait, lock=self.do_lock)
  File "/app/lib/python3.7/site-packages/borg/repository.py", line 421, in open
    self.lock = Lock(os.path.join(path, 'lock'), exclusive, timeout=lock_wait, kill_stale_locks=hostname_is_unique()).acquire()
  File "/app/lib/python3.7/site-packages/borg/locking.py", line 350, in acquire
    self._wait_for_readers_finishing(remove, sleep)
  File "/app/lib/python3.7/site-packages/borg/locking.py", line 363, in _wait_for_readers_finishing
    self._lock.acquire()
  File "/app/lib/python3.7/site-packages/borg/locking.py", line 138, in acquire
    raise LockFailed(self.path, str(err)) from None
borg.locking.LockFailed: Failed to create/acquire the lock /media/psheedy/backup640/lock.exclusive ([Errno 13] Permission denied: '/media/psheedy/backup640/lock.exclusive').

Platform: Linux psheedy-XPS-8920 5.4.0-53-generic #59-Ubuntu SMP Wed Oct 21 09:38:44 UTC 2020 x86_64
Linux:   
Borg: 1.1.13  Python: CPython 3.7.4 msgpack: 0.5.6
PID: 28  CWD: /home/psheedy
sys.argv: ['/app/bin/borg', 'create', '--list', '--progress', '--info', '--log-json', '--json', '--filter=AM', '-C', 'lz4', '--exclude-from', '/tmp/tmp7w5dh7p1', '/media/psheedy/backup640::psheedy-XPS-8920-default-2020-11-15T19:48:39', '/home/psheedy', '/home/psheedy/.googleearth', '/home/psheedy/.mozilla', '/home/psheedy/.local']
SSH_ORIGINAL_COMMAND: None

2020-11-15 19:51:45,458 - vorta.borg.borg_thread - DEBUG - Using VortaSecretStorageKeyring keyring to store passwords.
2020-11-15 19:51:45,458 - asyncio - DEBUG - Using selector: EpollSelector
2020-11-15 19:51:45,466 - root - DEBUG - Found 1 passwords matching repo URL.
2020-11-15 19:51:45,644 - vorta.borg.borg_thread - INFO - Running command /app/bin/borg create --list --progress --info --log-json --json --filter=AM -C lz4 --exclude-from /tmp/tmp3bqb3l_3 /media/psheedy/backup640::psheedy-XPS-8920-default-2020-11-15T19:51:45 /home/psheedy /home/psheedy/.googleearth /home/psheedy/.mozilla /home/psheedy/.local
2020-11-15 19:51:46,065 - vorta.borg.borg_thread - ERROR - Failed to create/acquire the lock /media/psheedy/backup640/lock.exclusive ([Errno 13] Permission denied: '/media/psheedy/backup640/lock.exclusive').
2020-11-15 19:51:46,065 - vorta.borg.borg_thread - ERROR - Traceback (most recent call last):
  File "/app/lib/python3.7/site-packages/borg/archiver.py", line 4565, in main
    exit_code = archiver.run(args)
  File "/app/lib/python3.7/site-packages/borg/archiver.py", line 4497, in run
    return set_ec(func(args))
  File "/app/lib/python3.7/site-packages/borg/archiver.py", line 161, in wrapper
    with repository:
  File "/app/lib/python3.7/site-packages/borg/repository.py", line 190, in __enter__
    self.open(self.path, bool(self.exclusive), lock_wait=self.lock_wait, lock=self.do_lock)
  File "/app/lib/python3.7/site-packages/borg/repository.py", line 421, in open
    self.lock = Lock(os.path.join(path, 'lock'), exclusive, timeout=lock_wait, kill_stale_locks=hostname_is_unique()).acquire()
  File "/app/lib/python3.7/site-packages/borg/locking.py", line 350, in acquire
    self._wait_for_readers_finishing(remove, sleep)
  File "/app/lib/python3.7/site-packages/borg/locking.py", line 363, in _wait_for_readers_finishing
    self._lock.acquire()
  File "/app/lib/python3.7/site-packages/borg/locking.py", line 138, in acquire
    raise LockFailed(self.path, str(err)) from None
borg.locking.LockFailed: Failed to create/acquire the lock /media/psheedy/backup640/lock.exclusive ([Errno 13] Permission denied: '/media/psheedy/backup640/lock.exclusive').

Platform: Linux psheedy-XPS-8920 5.4.0-53-generic #59-Ubuntu SMP Wed Oct 21 09:38:44 UTC 2020 x86_64
Linux:   
Borg: 1.1.13  Python: CPython 3.7.4 msgpack: 0.5.6
PID: 32  CWD: /home/psheedy
sys.argv: ['/app/bin/borg', 'create', '--list', '--progress', '--info', '--log-json', '--json', '--filter=AM', '-C', 'lz4', '--exclude-from', '/tmp/tmp3bqb3l_3', '/media/psheedy/backup640::psheedy-XPS-8920-default-2020-11-15T19:51:45', '/home/psheedy', '/home/psheedy/.googleearth', '/home/psheedy/.mozilla', '/home/psheedy/.local']
SSH_ORIGINAL_COMMAND: None

2020-11-15 19:52:13,946 - vorta.borg.borg_thread - DEBUG - Using VortaSecretStorageKeyring keyring to store passwords.
2020-11-15 19:52:13,947 - asyncio - DEBUG - Using selector: EpollSelector
2020-11-15 19:52:13,954 - root - DEBUG - Found 1 passwords matching repo URL.
2020-11-15 19:52:14,158 - vorta.borg.borg_thread - INFO - Running command /app/bin/borg create --list --progress --info --log-json --json --filter=AM -C lz4 --exclude-from /tmp/tmpdpfhcmdj /media/psheedy/backup640::psheedy-XPS-8920-default-2020-11-15T19:52:14 /home/psheedy /home/psheedy/.googleearth /home/psheedy/.mozilla /home/psheedy/.local
2020-11-15 19:52:14,583 - vorta.borg.borg_thread - ERROR - Failed to create/acquire the lock /media/psheedy/backup640/lock.exclusive ([Errno 13] Permission denied: '/media/psheedy/backup640/lock.exclusive').
2020-11-15 19:52:14,583 - vorta.borg.borg_thread - ERROR - Traceback (most recent call last):
  File "/app/lib/python3.7/site-packages/borg/archiver.py", line 4565, in main
    exit_code = archiver.run(args)
  File "/app/lib/python3.7/site-packages/borg/archiver.py", line 4497, in run
    return set_ec(func(args))
  File "/app/lib/python3.7/site-packages/borg/archiver.py", line 161, in wrapper
    with repository:
  File "/app/lib/python3.7/site-packages/borg/repository.py", line 190, in __enter__
    self.open(self.path, bool(self.exclusive), lock_wait=self.lock_wait, lock=self.do_lock)
  File "/app/lib/python3.7/site-packages/borg/repository.py", line 421, in open
    self.lock = Lock(os.path.join(path, 'lock'), exclusive, timeout=lock_wait, kill_stale_locks=hostname_is_unique()).acquire()
  File "/app/lib/python3.7/site-packages/borg/locking.py", line 350, in acquire
    self._wait_for_readers_finishing(remove, sleep)
  File "/app/lib/python3.7/site-packages/borg/locking.py", line 363, in _wait_for_readers_finishing
    self._lock.acquire()
  File "/app/lib/python3.7/site-packages/borg/locking.py", line 138, in acquire
    raise LockFailed(self.path, str(err)) from None
borg.locking.LockFailed: Failed to create/acquire the lock /media/psheedy/backup640/lock.exclusive ([Errno 13] Permission denied: '/media/psheedy/backup640/lock.exclusive').

Platform: Linux psheedy-XPS-8920 5.4.0-53-generic #59-Ubuntu SMP Wed Oct 21 09:38:44 UTC 2020 x86_64
Linux:   
Borg: 1.1.13  Python: CPython 3.7.4 msgpack: 0.5.6
PID: 36  CWD: /home/psheedy
sys.argv: ['/app/bin/borg', 'create', '--list', '--progress', '--info', '--log-json', '--json', '--filter=AM', '-C', 'lz4', '--exclude-from', '/tmp/tmpdpfhcmdj', '/media/psheedy/backup640::psheedy-XPS-8920-default-2020-11-15T19:52:14', '/home/psheedy', '/home/psheedy/.googleearth', '/home/psheedy/.mozilla', '/home/psheedy/.local']
SSH_ORIGINAL_COMMAND: None

2020-11-15 19:57:40,413 - vorta.borg.borg_thread - DEBUG - Using VortaSecretStorageKeyring keyring to store passwords.
2020-11-15 19:57:40,413 - asyncio - DEBUG - Using selector: EpollSelector
2020-11-15 19:57:40,422 - root - DEBUG - Found 1 passwords matching repo URL.
2020-11-15 19:57:40,605 - vorta.borg.borg_thread - INFO - Running command /app/bin/borg create --list --progress --info --log-json --json --filter=AM -C lz4 --exclude-from /tmp/tmp8u0eegu5 /media/psheedy/backup640::psheedy-XPS-8920-default-2020-11-15T19:57:40 /home/psheedy /home/psheedy/.googleearth /home/psheedy/.mozilla /home/psheedy/.local
2020-11-15 19:57:41,028 - vorta.borg.borg_thread - ERROR - Failed to create/acquire the lock /media/psheedy/backup640/lock.exclusive ([Errno 13] Permission denied: '/media/psheedy/backup640/lock.exclusive').
2020-11-15 19:57:41,028 - vorta.borg.borg_thread - ERROR - Traceback (most recent call last):
  File "/app/lib/python3.7/site-packages/borg/archiver.py", line 4565, in main
    exit_code = archiver.run(args)
  File "/app/lib/python3.7/site-packages/borg/archiver.py", line 4497, in run
    return set_ec(func(args))
  File "/app/lib/python3.7/site-packages/borg/archiver.py", line 161, in wrapper
    with repository:
  File "/app/lib/python3.7/site-packages/borg/repository.py", line 190, in __enter__
    self.open(self.path, bool(self.exclusive), lock_wait=self.lock_wait, lock=self.do_lock)
  File "/app/lib/python3.7/site-packages/borg/repository.py", line 421, in open
    self.lock = Lock(os.path.join(path, 'lock'), exclusive, timeout=lock_wait, kill_stale_locks=hostname_is_unique()).acquire()
  File "/app/lib/python3.7/site-packages/borg/locking.py", line 350, in acquire
    self._wait_for_readers_finishing(remove, sleep)
  File "/app/lib/python3.7/site-packages/borg/locking.py", line 363, in _wait_for_readers_finishing
    self._lock.acquire()
  File "/app/lib/python3.7/site-packages/borg/locking.py", line 138, in acquire
    raise LockFailed(self.path, str(err)) from None
borg.locking.LockFailed: Failed to create/acquire the lock /media/psheedy/backup640/lock.exclusive ([Errno 13] Permission denied: '/media/psheedy/backup640/lock.exclusive').

Platform: Linux psheedy-XPS-8920 5.4.0-53-generic #59-Ubuntu SMP Wed Oct 21 09:38:44 UTC 2020 x86_64
Linux:   
Borg: 1.1.13  Python: CPython 3.7.4 msgpack: 0.5.6
PID: 40  CWD: /home/psheedy
sys.argv: ['/app/bin/borg', 'create', '--list', '--progress', '--info', '--log-json', '--json', '--filter=AM', '-C', 'lz4', '--exclude-from', '/tmp/tmp8u0eegu5', '/media/psheedy/backup640::psheedy-XPS-8920-default-2020-11-15T19:57:40', '/home/psheedy', '/home/psheedy/.googleearth', '/home/psheedy/.mozilla', '/home/psheedy/.local']
SSH_ORIGINAL_COMMAND: None

2020-11-15 20:07:02,327 - vorta.borg.borg_thread - DEBUG - Using VortaSecretStorageKeyring keyring to store passwords.
2020-11-15 20:07:02,328 - asyncio - DEBUG - Using selector: EpollSelector
2020-11-15 20:07:02,334 - root - DEBUG - Found 1 passwords matching repo URL.
2020-11-15 20:07:02,512 - vorta.borg.borg_thread - INFO - Running command /app/bin/borg create --list --progress --info --log-json --json --filter=AM -C lz4 --exclude-from /tmp/tmpxm9rtop9 /media/psheedy/backup640::psheedy-XPS-8920-default-2020-11-15T20:07:02 /home/psheedy /home/psheedy/.googleearth /home/psheedy/.mozilla /home/psheedy/.local
2020-11-15 20:07:02,944 - vorta.borg.borg_thread - ERROR - Failed to create/acquire the lock /media/psheedy/backup640/lock.exclusive ([Errno 13] Permission denied: '/media/psheedy/backup640/lock.exclusive').
2020-11-15 20:07:02,945 - vorta.borg.borg_thread - ERROR - Traceback (most recent call last):
  File "/app/lib/python3.7/site-packages/borg/archiver.py", line 4565, in main
    exit_code = archiver.run(args)
  File "/app/lib/python3.7/site-packages/borg/archiver.py", line 4497, in run
    return set_ec(func(args))
  File "/app/lib/python3.7/site-packages/borg/archiver.py", line 161, in wrapper
    with repository:
  File "/app/lib/python3.7/site-packages/borg/repository.py", line 190, in __enter__
    self.open(self.path, bool(self.exclusive), lock_wait=self.lock_wait, lock=self.do_lock)
  File "/app/lib/python3.7/site-packages/borg/repository.py", line 421, in open
    self.lock = Lock(os.path.join(path, 'lock'), exclusive, timeout=lock_wait, kill_stale_locks=hostname_is_unique()).acquire()
  File "/app/lib/python3.7/site-packages/borg/locking.py", line 350, in acquire
    self._wait_for_readers_finishing(remove, sleep)
  File "/app/lib/python3.7/site-packages/borg/locking.py", line 363, in _wait_for_readers_finishing
    self._lock.acquire()
  File "/app/lib/python3.7/site-packages/borg/locking.py", line 138, in acquire
    raise LockFailed(self.path, str(err)) from None
borg.locking.LockFailed: Failed to create/acquire the lock /media/psheedy/backup640/lock.exclusive ([Errno 13] Permission denied: '/media/psheedy/backup640/lock.exclusive').

Platform: Linux psheedy-XPS-8920 5.4.0-53-generic #59-Ubuntu SMP Wed Oct 21 09:38:44 UTC 2020 x86_64
Linux:   
Borg: 1.1.13  Python: CPython 3.7.4 msgpack: 0.5.6
PID: 44  CWD: /home/psheedy
sys.argv: ['/app/bin/borg', 'create', '--list', '--progress', '--info', '--log-json', '--json', '--filter=AM', '-C', 'lz4', '--exclude-from', '/tmp/tmpxm9rtop9', '/media/psheedy/backup640::psheedy-XPS-8920-default-2020-11-15T20:07:02', '/home/psheedy', '/home/psheedy/.googleearth', '/home/psheedy/.mozilla', '/home/psheedy/.local']
SSH_ORIGINAL_COMMAND: None

2020-11-16 09:46:05,469 - vorta.i18n - DEBUG - Loading translation failed for ['en', 'en-US', 'en-Latn-US'].
2020-11-16 09:46:05,612 - apscheduler.scheduler - INFO - Scheduler started
2020-11-16 09:46:08,188 - root - INFO - Using NetworkManagerMonitor NetworkStatusMonitor implementation.
2020-11-16 09:46:09,270 - vorta.borg.borg_thread - INFO - Running command /app/bin/borg --version
2020-11-16 09:46:18,517 - vorta.borg.borg_thread - DEBUG - Using VortaSecretStorageKeyring keyring to store passwords.
2020-11-16 09:46:18,518 - asyncio - DEBUG - Using selector: EpollSelector
2020-11-16 09:46:18,555 - root - DEBUG - Found 1 passwords matching repo URL.
2020-11-16 09:46:18,803 - vorta.borg.borg_thread - INFO - Running command /app/bin/borg create --list --progress --info --log-json --json --filter=AM -C lz4 --exclude-from /tmp/tmp1l05b6ld /media/psheedy/backup640::psheedy-XPS-8920-default-2020-11-16T09:46:18 /home/psheedy /home/psheedy/.googleearth /home/psheedy/.mozilla /home/psheedy/.local
2020-11-16 09:46:19,229 - vorta.borg.borg_thread - ERROR - Failed to create/acquire the lock /media/psheedy/backup640/lock.exclusive ([Errno 13] Permission denied: '/media/psheedy/backup640/lock.exclusive').
2020-11-16 09:46:19,229 - vorta.borg.borg_thread - ERROR - Traceback (most recent call last):
  File "/app/lib/python3.7/site-packages/borg/archiver.py", line 4565, in main
    exit_code = archiver.run(args)
  File "/app/lib/python3.7/site-packages/borg/archiver.py", line 4497, in run
    return set_ec(func(args))
  File "/app/lib/python3.7/site-packages/borg/archiver.py", line 161, in wrapper
    with repository:
  File "/app/lib/python3.7/site-packages/borg/repository.py", line 190, in __enter__
    self.open(self.path, bool(self.exclusive), lock_wait=self.lock_wait, lock=self.do_lock)
  File "/app/lib/python3.7/site-packages/borg/repository.py", line 421, in open
    self.lock = Lock(os.path.join(path, 'lock'), exclusive, timeout=lock_wait, kill_stale_locks=hostname_is_unique()).acquire()
  File "/app/lib/python3.7/site-packages/borg/locking.py", line 350, in acquire
    self._wait_for_readers_finishing(remove, sleep)
  File "/app/lib/python3.7/site-packages/borg/locking.py", line 363, in _wait_for_readers_finishing
    self._lock.acquire()
  File "/app/lib/python3.7/site-packages/borg/locking.py", line 138, in acquire
    raise LockFailed(self.path, str(err)) from None
borg.locking.LockFailed: Failed to create/acquire the lock /media/psheedy/backup640/lock.exclusive ([Errno 13] Permission denied: '/media/psheedy/backup640/lock.exclusive').

Platform: Linux psheedy-XPS-8920 5.4.0-53-generic #59-Ubuntu SMP Wed Oct 21 09:38:44 UTC 2020 x86_64
Linux:   
Borg: 1.1.13  Python: CPython 3.7.4 msgpack: 0.5.6
PID: 12  CWD: /home/psheedy
sys.argv: ['/app/bin/borg', 'create', '--list', '--progress', '--info', '--log-json', '--json', '--filter=AM', '-C', 'lz4', '--exclude-from', '/tmp/tmp1l05b6ld', '/media/psheedy/backup640::psheedy-XPS-8920-default-2020-11-16T09:46:18', '/home/psheedy', '/home/psheedy/.googleearth', '/home/psheedy/.mozilla', '/home/psheedy/.local']
SSH_ORIGINAL_COMMAND: None
============

**Comment by m3nu** [comment]
See `borg break-lock`.

**Comment by samuel-w** [comment]
We should add some sort of thing to handle this. Should we just automatically break the lock, or ask the user?

**Comment by m3nu** [comment]
Yes, but only as error message. Because the locking could also be another process. So can't break it automatically.

**Comment by samuel-w** [comment]
@OldBigIron It looks like you have a permission error. Try running `rm -r /media/psheedy/backup640/lock.exclusive`.

**Comment by OldBigIron** [comment]
I found in my /media/ directory and entry for the hard drive that was owned
by root. The the disk had been pulled out without unmounting it.

Thank you all.
