### ISSUE TITLE
Crash due to malformed SSH key

### ISSUE THREAD

**Issue by Muminologist** [borgbase/vorta#725]
**Describe the bug**
Open the GUI of Vorta 0.7.1 or 0.7.0 via system tray, Vorta crashes.
Might overlap with #629 or #619 ?
Thanks for your time.

**To Reproduce**
1.   Open Vorta
2.   Open GUI via tray menu
3.   Crash

**Desktop (please complete the following information):**
- OS: MacOS Big Sur 11.0.1 (20B50)
- Vorta version: 0.7.1, 0.7.0 (also tried 0.6.2 but freezes on startup)
- Installed from: brew, binary via github

**Additional context**
Nothing supicious in the logs _per se_. 
I ran: /Applications/Vorta.app/Contents/MacOS/vorta-darwin
This the console printout:
```
2020-11-24 00:24:57,883 - vorta.i18n - DEBUG - Loading translation succeeded for ['de', 'de-DE', 'de-Latn-DE'].
2020-11-24 00:24:57,912 - apscheduler.scheduler - INFO - Scheduler started
2020-11-24 00:24:57,914 - apscheduler.scheduler - INFO - Added job "VortaScheduler.create_backup" to job store "default"
2020-11-24 00:24:57,914 - vorta.scheduler - DEBUG - New job for profile Default was added.
2020-11-24 00:24:57,981 - vorta.borg.borg_thread - INFO - Running command /usr/local/bin/borg --version
CoreSVG has logged an error. Set environment variabe "CORESVG_VERBOSE" to learn more.
Traceback (most recent call last):
  File "application.py", line 90, in open_main_window_action
  File "views/main_window.py", line 47, in __init__
  File "views/repo_tab.py", line 54, in __init__
  File "views/repo_tab.py", line 100, in init_ssh
  File "utils.py", line 84, in get_private_keys
  File "paramiko/pkey.py", line 235, in from_private_key_file
  File "paramiko/rsakey.py", line 55, in __init__
  File "paramiko/rsakey.py", line 176, in _from_private_key_file
  File "paramiko/rsakey.py", line 194, in _decode_key
  File "cryptography/hazmat/primitives/asymmetric/rsa.py", line 308, in private_key
  File "cryptography/hazmat/backends/openssl/backend.py", line 517, in load_rsa_private_numbers
  File "cryptography/hazmat/primitives/asymmetric/rsa.py", line 171, in _check_private_key_components
ValueError: p*q must equal modulus.
zsh: abort      /Applications/Vorta.app/Contents/MacOS/vorta-darwin

```

**Comment by m3nu** [comment]
You have a malformed SSH key in `~/.ssh`. We should probably ignore the key in such cases instead of crashing. 😬

```
Traceback (most recent call last):
  File "application.py", line 90, in open_main_window_action
  File "views/main_window.py", line 47, in __init__
  File "views/repo_tab.py", line 54, in __init__
  File "views/repo_tab.py", line 100, in init_ssh
  File "utils.py", line 84, in get_private_keys
  File "paramiko/pkey.py", line 235, in from_private_key_file
  File "paramiko/rsakey.py", line 55, in __init__
  File "paramiko/rsakey.py", line 176, in _from_private_key_file
  File "paramiko/rsakey.py", line 194, in _decode_key
  File "cryptography/hazmat/primitives/asymmetric/rsa.py", line 308, in private_key
  File "cryptography/hazmat/backends/openssl/backend.py", line 517, in load_rsa_private_numbers
  File "cryptography/hazmat/primitives/asymmetric/rsa.py", line 171, in _check_private_key_components
ValueError: p*q must equal modulus.
zsh: abort      /Applications/Vorta.app/Contents/MacOS/vorta-darwin
```

**Comment by Muminologist** [comment]
Wow. That was fast. Thanks for understandanding my log better than me.

**Comment by samuel-w** [comment]
We should show a notification so that you know that the key is bad.

**Comment by afinkel71** [comment]
Vorta will also crash on startup if it encounters an ssh key that it can't read due to file permissions.

Encountered with Vorta version 0.7.2 installed via Flatpak on Fedora 33 (x86_64) with Kernel 5.10.13-200.fc33.x86_64 running GNOME Desktop

Feb 09 07:34:08 ezra systemd[2813]: Started Application launched by gnome-shell.
Feb 09 07:34:09 ezra systemd[2813]: Started app-flatpak-com.borgbase.Vorta-5252.scope.
Feb 09 07:34:09 ezra systemd[2813]: app-gnome-com.borgbase.Vorta-5252.scope: Succeeded.
Feb 09 07:34:09 ezra com.borgbase.Vorta.desktop[5264]: QSocketNotifier: Can only be used with threads started with QThread
Feb 09 07:34:09 ezra com.borgbase.Vorta.desktop[5264]: QSocketNotifier: Can only be used with threads started with QThread
Feb 09 07:34:09 ezra com.borgbase.Vorta.desktop[5264]: 2021-02-09 07:34:09,549 - vorta.i18n - DEBUG - Loading translation succeeded for ['en', 'en-US', 'en-Latn-US'].
Feb 09 07:34:09 ezra com.borgbase.Vorta.desktop[5264]: 2021-02-09 07:34:09,561 - apscheduler.scheduler - INFO - Scheduler started
Feb 09 07:34:09 ezra com.borgbase.Vorta.desktop[5264]: QObject::connect: No such signal QPlatformNativeInterface::systemTrayWindowChanged(QScreen*)
Feb 09 07:34:09 ezra com.borgbase.Vorta.desktop[5264]: 2021-02-09 07:34:09,583 - root - CRITICAL - Uncaught exception, file a report at https://github.com/borgbase/vorta/issues/new
Feb 09 07:34:09 ezra com.borgbase.Vorta.desktop[5264]: Traceback (most recent call last):
Feb 09 07:34:09 ezra com.borgbase.Vorta.desktop[5264]:   File "/app/bin/vorta", line 11, in <module>
Feb 09 07:34:09 ezra com.borgbase.Vorta.desktop[5264]:     load_entry_point('vorta==0.7.2', 'gui_scripts', 'vorta')()
Feb 09 07:34:09 ezra com.borgbase.Vorta.desktop[5264]:   File "/app/lib/python3.7/site-packages/vorta/__main__.py", line 56, in main
Feb 09 07:34:09 ezra com.borgbase.Vorta.desktop[5264]:     app = VortaApp(sys.argv, single_app=args.profile is None)
Feb 09 07:34:09 ezra com.borgbase.Vorta.desktop[5264]:   File "/app/lib/python3.7/site-packages/vorta/application.py", line 65, in __init__
Feb 09 07:34:09 ezra com.borgbase.Vorta.desktop[5264]:     self.main_window = MainWindow(self)
Feb 09 07:34:09 ezra com.borgbase.Vorta.desktop[5264]:   File "/app/lib/python3.7/site-packages/vorta/views/main_window.py", line 46, in __init__
Feb 09 07:34:09 ezra com.borgbase.Vorta.desktop[5264]:     self.repoTab = RepoTab(self.repoTabSlot)
Feb 09 07:34:09 ezra com.borgbase.Vorta.desktop[5264]:   File "/app/lib/python3.7/site-packages/vorta/views/repo_tab.py", line 54, in __init__
Feb 09 07:34:09 ezra com.borgbase.Vorta.desktop[5264]:     self.init_ssh()
Feb 09 07:34:09 ezra com.borgbase.Vorta.desktop[5264]:   File "/app/lib/python3.7/site-packages/vorta/views/repo_tab.py", line 100, in init_ssh
Feb 09 07:34:09 ezra com.borgbase.Vorta.desktop[5264]:     keys = get_private_keys()
Feb 09 07:34:09 ezra com.borgbase.Vorta.desktop[5264]:   File "/app/lib/python3.7/site-packages/vorta/utils.py", line 138, in get_private_keys
Feb 09 07:34:09 ezra com.borgbase.Vorta.desktop[5264]:     parsed_key = key_format.from_private_key_file(key_file)
Feb 09 07:34:09 ezra com.borgbase.Vorta.desktop[5264]:   File "/app/lib/python3.7/site-packages/paramiko/pkey.py", line 235, in from_private_key_file
Feb 09 07:34:09 ezra com.borgbase.Vorta.desktop[5264]:     key = cls(filename=filename, password=password)
Feb 09 07:34:09 ezra com.borgbase.Vorta.desktop[5264]:   File "/app/lib/python3.7/site-packages/paramiko/rsakey.py", line 55, in __init__
Feb 09 07:34:09 ezra com.borgbase.Vorta.desktop[5264]:     self._from_private_key_file(filename, password)
Feb 09 07:34:09 ezra com.borgbase.Vorta.desktop[5264]:   File "/app/lib/python3.7/site-packages/paramiko/rsakey.py", line 175, in _from_private_key_file
Feb 09 07:34:09 ezra com.borgbase.Vorta.desktop[5264]:     data = self._read_private_key_file("RSA", filename, password)
Feb 09 07:34:09 ezra com.borgbase.Vorta.desktop[5264]:   File "/app/lib/python3.7/site-packages/paramiko/pkey.py", line 307, in _read_private_key_file
Feb 09 07:34:09 ezra com.borgbase.Vorta.desktop[5264]:     with open(filename, "r") as f:
Feb 09 07:34:09 ezra com.borgbase.Vorta.desktop[5264]: **PermissionError: [Errno 13] Permission denied: '/home/afinkel/.ssh/afinkelsrc-nv.pem'**
