### ISSUE TITLE
Error during backup (Linux Mint)

### ISSUE THREAD

**Issue by mikqu** [borgbase/vorta#742]
**Describe the bug**
My scheduled backups have been throwing an error for the last week or so. Before that, they seemed to mostly be working fine.

**To Reproduce**
Scheduled backup runs automatically.

**Desktop (please complete the following information):**
- OS: Linux Mint 5.4.0-58-generic #64-Ubuntu SMP Wed Dec 9 08:16:25 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Vorta version: 1.1.13
- Installed from: Not sure. Either Mint or Ubuntu Focal repos. Apt installed.

**Additional context**
2020-12-13 03:42:00,012 - apscheduler.executors.default - INFO - Running job "VortaScheduler.create_backup (trigger: cron[hour='3', minute='42'], next run at: 2020-12-14 03:42:00 PST)" (scheduled at 2020-12-13 03:42:00-08:00)
2020-12-13 03:42:00,050 - vorta.scheduler - INFO - Starting background backup for Default
2020-12-13 03:42:00,056 - vorta.notifications - DEBUG - notification not suppressed
2020-12-13 03:42:00,091 - vorta.borg.borg_thread - DEBUG - Using VortaSecretStorageKeyring keyring to store passwords.
2020-12-13 03:42:00,094 - asyncio - DEBUG - Using selector: EpollSelector
2020-12-13 03:42:00,106 - root - DEBUG - Found 1 passwords matching repo URL.
2020-12-13 03:42:00,722 - vorta.scheduler - INFO - Preparation for backup successful.
2020-12-13 03:42:00,793 - vorta.borg.borg_thread - INFO - Running command /app/bin/borg create --list --progress --info --log-json --json --filter=AM -C lz4 --exclude-from /tmp/tmp4jlpy0pg /media/K/BACKUP/BORG/Mike_laptop::mike-lap-default-2020-12-13T03:42:00 /home/mike
2020-12-13 03:43:09,639 - vorta.borg.borg_thread - INFO - Creating archive at "/media/K/BACKUP/BORG/Mike_laptop::mike-lap-default-2020-12-13T03:42:00"
2020-12-13 04:04:42,740 - vorta.borg.borg_thread - ERROR - Local Exception
2020-12-13 04:04:42,741 - vorta.borg.borg_thread - ERROR - Traceback (most recent call last):
  File "/app/lib/python3.7/site-packages/borg/archiver.py", line 4565, in main
    exit_code = archiver.run(args)
  File "/app/lib/python3.7/site-packages/borg/archiver.py", line 4497, in run
    return set_ec(func(args))
  File "/app/lib/python3.7/site-packages/borg/archiver.py", line 176, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/app/lib/python3.7/site-packages/borg/archiver.py", line 584, in do_create
    create_inner(archive, cache)
  File "/app/lib/python3.7/site-packages/borg/archiver.py", line 549, in create_inner
    archive.save(comment=args.comment, timestamp=args.timestamp)
  File "/app/lib/python3.7/site-packages/borg/archive.py", line 517, in save
    self.repository.commit()
  File "/app/lib/python3.7/site-packages/borg/repository.py", line 473, in commit
    self.io.write_commit()
  File "/app/lib/python3.7/site-packages/borg/repository.py", line 1570, in write_commit
    self.close_segment()
  File "/app/lib/python3.7/site-packages/borg/repository.py", line 1376, in close_segment
    fd.close()
  File "/app/lib/python3.7/site-packages/borg/platform/base.py", line 136, in close
    self.sync()
  File "/app/lib/python3.7/site-packages/borg/platform/base.py", line 125, in sync
    platform.fdatasync(self.fileno)
OSError: [Errno 112] Host is down

Platform: Linux mike-lap 5.4.0-58-generic #64-Ubuntu SMP Wed Dec 9 08:16:25 UTC 2020 x86_64
Linux:   
Borg: 1.1.13  Python: CPython 3.7.4 msgpack: 0.5.6
PID: 23  CWD: /home/mike
sys.argv: ['/app/bin/borg', 'create', '--list', '--progress', '--info', '--log-json', '--json', '--filter=AM', '-C', 'lz4', '--exclude-from', '/tmp/tmp4jlpy0pg', '/media/K/BACKUP/BORG/Mike_laptop::mike-lap-default-2020-12-13T03:42:00', '/home/mike']
SSH_ORIGINAL_COMMAND: None

2020-12-13 04:04:42,764 - vorta.borg.borg_thread - WARNING - /usr/lib/python3.7/site-packages/pkg_resources/__init__.py:1243: UserWarning: /home/mike/.var/app/com.borgbase.Vorta/cache/Python-Eggs is writable by group/others and vulnerable to attack when used with get_resource_filename. Consider a more secure location (set with .set_extraction_path or the PYTHON_EGG_CACHE environment variable).
2020-12-13 04:04:42,764 - vorta.borg.borg_thread - WARNING - warnings.warn(msg, UserWarning)
2020-12-13 04:04:42,928 - vorta.notifications - DEBUG - notification not suppressed
2020-12-13 04:04:42,968 - vorta.scheduler - ERROR - Error during backup creation.
2020-12-13 04:04:42,968 - apscheduler.executors.default - INFO - Job "VortaScheduler.create_backup (trigger: cron[hour='3', minute='42'], next run at: 2020-12-14 03:42:00 PST)" executed successfully

**Comment by m3nu** [comment]
Filesystem- or network error?

```
2020-12-13 03:43:09,639 - vorta.borg.borg_thread - INFO - Creating archive at "/media/K/BACKUP/BORG/Mike_laptop::mike-lap-default-2020-12-13T03:42:00"
2020-12-13 04:04:42,740 - vorta.borg.borg_thread - ERROR - Local Exception
...
platform.fdatasync(self.fileno)
OSError: [Errno 112] Host is down
```

**Comment by mikqu** [comment]
I'm not sure. The storage location is a network drive, with a local mount which is connected and browseable.

**Comment by mikqu** [comment]
I woke up today to a successful backup. I don't know what is happening, but hopefully it just keeps working.

**Comment by XXXBold** [comment]
Hm, there could a problem if your Network drive goes to sleep because of inactivity (Assuming you use samba?), and if you try to access it then via Vorta, it causes a timeout. Maybe it could help if you run some bash command on the drive, maybe a `stat /media/K/BACKUP/BORG/Mike_laptop` before starting the task, like 30s before or so.

**Comment by mikqu** [comment]
Good idea, thanks. If I just put that in the 'shell commands pre-backup' box, should that work?

**Comment by XXXBold** [comment]
I think that should do the job, yes, but I didn't test it. Try the command `stat /media/K/BACKUP/BORG/Mike_laptop && sleep 10`

This will run stat on the directory and wait for 10s after that. Try if that fixes your problem.

**Comment by mikqu** [comment]
The message this morning said that the command returned a non-zero code :/
