### ISSUE TITLE
Please unlock your password manager

### ISSUE THREAD

**Issue by DominiqueFrt** [borgbase/vorta#785]
With Kubuntu 20.04 - Vorta 0.7.2 - Borg 1.1.15
Problem since the update at the end of January
Identical problem on 2 machines with 3 accounts each
Complete reinstallation from PPA then Flatpack without success

`2021-02-09 13:05:51,922 - vorta.i18n - DEBUG - Loading translation succeeded for ['fr', 'fr-FR', 'fr-Latn-FR'].
2021-02-09 13:05:51,948 - apscheduler.scheduler - INFO - Scheduler started
2021-02-09 13:05:52,195 - root - INFO - Using NetworkManagerMonitor NetworkStatusMonitor implementation.
2021-02-09 13:05:52,202 - vorta.network_status.network_manager - WARNING - Couldn't load settings for /org/freedesktop/NetworkManager/Settings/1
Traceback (most recent call last):
  File "/app/lib/python3.7/site-packages/vorta/network_status/network_manager.py", line 52, in get_known_wifis
    settings = self._nm.get_settings(connection_path)
  File "/app/lib/python3.7/site-packages/vorta/network_status/network_manager.py", line 139, in get_settings
    return get_result(settings.call('GetSettings'))
  File "/app/lib/python3.7/site-packages/vorta/network_status/network_manager.py", line 163, in get_result
    raise DBusException("DBus call failed: {}".format(msg.arguments()))
vorta.network_status.network_manager.DBusException: DBus call failed: ['uid 1002 has no permission to perform this operation']
2021-02-09 13:05:52,277 - vorta.borg.borg_thread - INFO - Running command /app/bin/borg --version
2021-02-09 13:06:08,442 - vorta.network_status.network_manager - WARNING - Couldn't load settings for /org/freedesktop/NetworkManager/Settings/1
Traceback (most recent call last):
  File "/app/lib/python3.7/site-packages/vorta/network_status/network_manager.py", line 52, in get_known_wifis
    settings = self._nm.get_settings(connection_path)
  File "/app/lib/python3.7/site-packages/vorta/network_status/network_manager.py", line 139, in get_settings
    return get_result(settings.call('GetSettings'))
  File "/app/lib/python3.7/site-packages/vorta/network_status/network_manager.py", line 163, in get_result
    raise DBusException("DBus call failed: {}".format(msg.arguments()))
vorta.network_status.network_manager.DBusException: DBus call failed: ['uid 1002 has no permission to perform this operation']
2021-02-09 13:06:12,092 - asyncio - DEBUG - Using selector: EpollSelector
2021-02-09 13:06:48,008 - vorta.borg.borg_thread - DEBUG - Using VortaSecretStorageKeyring keyring to store passwords.
2021-02-09 13:06:54,450 - vorta.network_status.network_manager - WARNING - Couldn't load settings for /org/freedesktop/NetworkManager/Settings/1
Traceback (most recent call last):
  File "/app/lib/python3.7/site-packages/vorta/network_status/network_manager.py", line 52, in get_known_wifis
    settings = self._nm.get_settings(connection_path)
  File "/app/lib/python3.7/site-packages/vorta/network_status/network_manager.py", line 139, in get_settings
    return get_result(settings.call('GetSettings'))
  File "/app/lib/python3.7/site-packages/vorta/network_status/network_manager.py", line 163, in get_result
    raise DBusException("DBus call failed: {}".format(msg.arguments()))
vorta.network_status.network_manager.DBusException: DBus call failed: ['uid 1002 has no permission to perform this operation']
2021-02-09 13:06:54,479 - vorta.network_status.network_manager - WARNING - Couldn't load settings for /org/freedesktop/NetworkManager/Settings/1
Traceback (most recent call last):
  File "/app/lib/python3.7/site-packages/vorta/network_status/network_manager.py", line 52, in get_known_wifis
    settings = self._nm.get_settings(connection_path)
  File "/app/lib/python3.7/site-packages/vorta/network_status/network_manager.py", line 139, in get_settings
    return get_result(settings.call('GetSettings'))
  File "/app/lib/python3.7/site-packages/vorta/network_status/network_manager.py", line 163, in get_result
    raise DBusException("DBus call failed: {}".format(msg.arguments()))
vorta.network_status.network_manager.DBusException: DBus call failed: ['uid 1002 has no permission to perform this operation']
2021-02-09 13:08:12,743 - vorta.network_status.network_manager - WARNING - Couldn't load settings for /org/freedesktop/NetworkManager/Settings/1
Traceback (most recent call last):
  File "/app/lib/python3.7/site-packages/vorta/network_status/network_manager.py", line 52, in get_known_wifis
    settings = self._nm.get_settings(connection_path)
  File "/app/lib/python3.7/site-packages/vorta/network_status/network_manager.py", line 139, in get_settings
    return get_result(settings.call('GetSettings'))
  File "/app/lib/python3.7/site-packages/vorta/network_status/network_manager.py", line 163, in get_result
    raise DBusException("DBus call failed: {}".format(msg.arguments()))
vorta.network_status.network_manager.DBusException: DBus call failed: ['uid 1002 has no permission to perform this operation']
2021-02-09 13:08:47,745 - vorta.borg.borg_thread - DEBUG - Using VortaSecretStorageKeyring keyring to store passwords.
2021-02-09 14:05:56,615 - vorta.borg.borg_thread - DEBUG - Using VortaSecretStorageKeyring keyring to store passwords.`

cordially

**Comment by m3nu** [comment]
So what's the issue you are reporting and can you try to add your logs with line breaks preserved? Will make it easier to read. Thanks!

**Comment by DominiqueFrt** [comment]
[vorta.log](https://github.com/borgbase/vorta/files/5957575/vorta.log)
Problem: Backup failure.Cannot access an existing repository or create a new repository.
Message: `Please unlock your password manager`
cordially

**Comment by m3nu** [comment]
Have you checked it your issue still happens on the current `master` branch? There is already a fix for a similar issue.

Else one of our Linux maintainers needs to have a look.

**Comment by jetlag666** [comment]
Hello, I also have this issue on Kubuntu 20.04 since 3 days ago.

**Comment by m3nu** [comment]
Please try the current `master` branch to verify if the fix (#779) applied there resolves your issue.

**Comment by peerwal** [comment]
Hi, i am running into the same issue using KDE Neon 5.20. Both the flatpak and the latest deb package install come up with the same message: **Please unlock your password manager**

**Comment by DominiqueFrt** [comment]
I purged Vorta and Borg
I deleted :
  ~ / .cache / borg /
  ~ / .cache / vorta /
  ~ / .config / borg /
  ~ / .config / vortac
  ~ / .local / share / vorta /
  ~ / .var / app / com.borgbase.Vorta /

Reinstallation from your site: https://vorta.borgbase.com
/ install / linux /

Creation of a new depot

Flatpack: Please unlock your password manager
PPA: Same message

Are there other folders to delete to reset everything

cordially

**Comment by m3nu** [comment]
Sorry, but I'm unable to reproduce this on Gnome (Fedora/SecretStorage keyring) or KDE (Kubuntu/KWallet keyring) using the latest `master` branch installed via `pip`.

I can't comment on individual distribution packages, since they are maintained by external packagers listed here: https://vorta.borgbase.com/install/linux/
