### ISSUE TITLE
Unable to add your repository

### ISSUE THREAD

**Issue by AlanFleck** [borgbase/vorta#790]
**Describe the bug**
Unable to add a repository on a removable hard drive, as empty directory on drive with ca 40GB used, but 300GB free.. Tried both New and Existing repository routes. Same error message both ways. Drive has 2 partitions: tried other partition: "Unable to add repository".

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to '..Select Backup Repository.'
2. Click on 'Initialize new repository'
3. Choose a local path as repository
4. Select directory on removable drive
5. Enter Borg passphrase
6. Confirm passphrase
7. Hit Add
8. ...validating repo ...
9. Message "Unable to add repository"
10. 

**Desktop (please complete the following information):**
- OS: Linux Mint 20
- Vorta version: 0.7.2  Borg version 1.1.1
[VortaErrorLog.txt](https://github.com/borgbase/vorta/files/5968808/VortaErrorLog.txt)
5
- Installed from: Linux Mint software manager

Vorta and Borg versions can be found in Main Window > Misc Tab

**Additional context**
If appropriate include logs. Can be found in Main Window > Misc Tab > Log.

**Comment by m3nu** [comment]
File system permission error happening in Borg. Recommend you double-check your permissions and which user is running Vorta.

```
2021-02-11 22:11:43,717 - vorta.borg.borg_thread - DEBUG - Password not found in primary keyring. Falling back to VortaDBKeyring.
2021-02-11 22:11:43,730 - vorta.borg.borg_thread - INFO - Running command /app/bin/borg init --info --log-json --encryption=repokey-blake2 /media/alan/BackSmall/backups
2021-02-11 22:11:45,172 - vorta.borg.borg_thread - ERROR - Local Exception
2021-02-11 22:11:45,174 - vorta.borg.borg_thread - ERROR - Traceback (most recent call last):
  File "/app/lib/python3.7/site-packages/borg/archiver.py", line 4621, in main
    exit_code = archiver.run(args)
  File "/app/lib/python3.7/site-packages/borg/archiver.py", line 4553, in run
    return set_ec(func(args))
  File "/app/lib/python3.7/site-packages/borg/archiver.py", line 162, in wrapper
    with repository:
  File "/app/lib/python3.7/site-packages/borg/repository.py", line 188, in __enter__
    self.create(self.path)
  File "/app/lib/python3.7/site-packages/borg/repository.py", line 272, in create
    with open(os.path.join(path, 'README'), 'w') as fd:
PermissionError: [Errno 13] Permission denied: '/media/alan/BackSmall/backups/README'
```
