### ISSUE TITLE
Debian Buster: peewee.ImproperlyConfigured: SQLite driver not installed!

### ISSUE THREAD

**Issue by frank-github** [borgbase/vorta#792]
Hi,

tried to get vorta running on Debian via pip installer.
Starting vorta I got this error, but do not know how to fix it.
sqlite3 is install on my debian (buster) system, also I did "pip install db-sqlite3"

Traceback (most recent call last):
  File "/usr/local/bin/vorta", line 11, in <module>
    load_entry_point('vorta==0.6.24', 'gui_scripts', 'vorta')()
  File "/usr/local/lib/python3.8/site-packages/vorta/__main__.py", line 33, in main
    init_db(sqlite_db)
  File "/usr/local/lib/python3.8/site-packages/vorta/models.py", line 248, in init_db
    db.connect()
  File "/usr/local/lib/python3.8/site-packages/peewee.py", line 2993, in connect
    self._state.set_connection(self._connect())
  File "/usr/local/lib/python3.8/site-packages/peewee.py", line 3327, in _connect
    raise ImproperlyConfigured('SQLite driver not installed!')
peewee.ImproperlyConfigured: SQLite driver not installed!

**Comment by m3nu** [comment]
Since the error happens in Peewee, you should probably file your bug there.

```
File "/usr/local/lib/python3.8/site-packages/peewee.py", line 3327, in _connect
raise ImproperlyConfigured('SQLite driver not installed!')
peewee.ImproperlyConfigured: SQLite driver not installed!
```

**Comment by m3nu** [comment]
Upon entering the error in Google, I found this, which may be helpful:

https://stackoverflow.com/questions/19530974/how-can-i-add-the-sqlite3-module-to-python/51031104#51031104
