### ISSUE TITLE
ValueError while dealing with wallet

### ISSUE THREAD

**Issue by renyhp** [borgbase/vorta#879]
```
2021-02-21 08:52:44,397 - vorta.borg.borg_thread - DEBUG - Using VortaKWallet5Keyring keyring to store passwords.
2021-02-21 08:53:09,523 - root - CRITICAL - Uncaught exception, file a report at https://github.com/borgbase/vorta/issues/new
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/vorta/application.py", line 109, in create_backup_action
    msg = BorgCreateThread.prepare(profile)
  File "/usr/lib/python3/dist-packages/vorta/borg/create.py", line 71, in prepare
    ret = super().prepare(profile)
  File "/usr/lib/python3/dist-packages/vorta/borg/borg_thread.py", line 144, in prepare
    ret['password'] = cls.keyring.get_password('vorta-repo', profile.repo.url)
  File "/usr/lib/python3/dist-packages/vorta/keyring/kwallet.py", line 30, in get_password
    if not (self.is_unlocked and self.get_result("hasEntry",
  File "/usr/lib/python3/dist-packages/vorta/keyring/kwallet.py", line 44, in is_unlocked
    self.try_unlock()
  File "/usr/lib/python3/dist-packages/vorta/keyring/kwallet.py", line 52, in try_unlock
    self.handle = int(output)
ValueError: invalid literal for int() with base 10: 'Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection 
```

**To Reproduce**
1. Start a backup
2. Vorta asks to open wallet 
3. Wait for some time

**Environment (please complete the following information):**
- OS: Xubuntu 20.04.2
- Vorta version: 0.7.3
- Installed from: official PPA

**Additional question**
Is there a way to not use any password or wallet? I know this is less secure, but I have implemented other (external) layers of security.

**Comment by m3nu** [comment]
Please join the discussion on #859 instead of opening a new one.
