### ISSUE TITLE
Arch linux last update "No module named 'vorta.views'

### ISSUE THREAD

**Issue by mygithubthrowaway** [borgbase/vorta#90]
```
Traceback (most recent call last):
  File "/usr/bin/vorta", line 11, in <module>
    load_entry_point('vorta==0.6.0', 'gui_scripts', 'vorta')()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 487, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2728, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2346, in load
    return self.resolve()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2352, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.7/site-packages/vorta/__main__.py", line 6, in <module>
    from vorta.application import VortaApp
  File "/usr/lib/python3.7/site-packages/vorta/application.py", line 12, in <module>
    from .views.main_window import MainWindow
ModuleNotFoundError: No module named 'vorta.views'
```

**Comment by m3nu** [comment]
It correctly identifies the parent package from the relative import, then `views`, which is a folder containing all the UI is missing. Not sure how this would happen. Maybe some files are missing?

Since I didn't publish this to Arch, I can't say much about it.

Until it's fixed, you can also install via `pip3`, as mentioned in the [Readme](https://github.com/borgbase/vorta#linux).

**Comment by mygithubthrowaway** [comment]
the arch package simply download release from github and then install in the old pyhton fashion way:

` python setup.py install`

with this dependencies:
```
'borg' 
'python-appdirs' 
'python-apscheduler' 
'python-pyqt5' 
'python-peewee' 
'python-paramiko' 
'python-dateutil' 
'python-keyring' 
'python-sentry_sdk

```
[1] https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=vorta

**Comment by m3nu** [comment]
Update with a fix is out. Marked the AUR package as outdated. So you should get the update soon.

**Comment by m3nu** [comment]
Actually this file was never there. So I'm surprised it worked before. It's still the closes explanation.

**Comment by mygithubthrowaway** [comment]
Thanks so much!

**Comment by mygithubthrowaway** [comment]
ps for testing purpuse you may use LXD for fast distro provisioning ;)

[1] (https://linuxcontainers.org/lxd/introduction/)

**Comment by bjo81** [comment]
> Update with a fix is out. Marked the AUR package as outdated. So you should get the update soon.

AUR package updated, includes now python-psutil-dependency.

**Comment by m3nu** [comment]
Great. Hope it works now. If I can help with anything to smooth the process let me know.
