### ISSUE TITLE
Extract fail when "%" character in filename

### ISSUE THREAD

**Issue by Caseraw** [borgbase/vorta#923]
**Describe the bug**
Extract fail due to a "%" character in the file name that is being extracted (restored) from the archive.

**To Reproduce**
1. Create some file with "%" character in the name.
2. Make a backup (on Fedora 33).
3. Extract the backup (on Ubuntu 20.04).
4. The extraction will not be able to extact the files with a "%" character in the name and fail.

**Environment (please complete the following information):**
- OS: Backup on Fedora 33 (default), Restore on Ubuntu 20.04 (fresh install).
- Vorta version: 1.1.15
- Installed from: flathub

Vorta and Borg versions can be found in Main Window > Misc Tab.

**Additional context**
```shell
2021-03-20 09:03:05,332 - vorta.borg.borg_thread - INFO - path/to/file/2021-03-02-20%3A12%3A53.tar.gz
2021-03-20 09:03:05,479 - vorta.borg.borg_thread - ERROR - Local Exception
2021-03-20 09:03:05,480 - vorta.borg.borg_thread - ERROR - Traceback (most recent call last):
  File "/app/lib/python3.8/site-packages/borg/archive.py", line 771, in restore_attrs
    xattr.setxattr(fd or path, k, v, follow_symlinks=False)
  File "/app/lib/python3.8/site-packages/borg/xattr.py", line 249, in setxattr
    _setxattr_inner(func, path, name, value)
  File "/app/lib/python3.8/site-packages/borg/xattr.py", line 188, in _setxattr_inner
    _check(func(path, name, value, size), path, detect_buffer_too_small=False)
  File "/app/lib/python3.8/site-packages/borg/xattr.py", line 143, in _check
    raise OSError(e, msg, path)
PermissionError: [Errno 1] Operation not permitted: '<FD 11>'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/lib/python3.8/site-packages/borg/archiver.py", line 4621, in main
    exit_code = archiver.run(args)
  File "/app/lib/python3.8/site-packages/borg/archiver.py", line 4553, in run
    return set_ec(func(args))
  File "/app/lib/python3.8/site-packages/borg/archiver.py", line 177, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/app/lib/python3.8/site-packages/borg/archiver.py", line 190, in wrapper
    return method(self, args, repository=repository, manifest=manifest, key=key, archive=archive, **kwargs)
  File "/app/lib/python3.8/site-packages/borg/archiver.py", line 806, in do_extract
    archive.extract_item(item, stdout=stdout, sparse=sparse, hardlink_masters=hardlink_masters,
  File "/app/lib/python3.8/site-packages/borg/archive.py", line 668, in extract_item
    self.restore_attrs(path, item, fd=fd.fileno())
  File "/app/lib/python3.8/site-packages/borg/archive.py", line 788, in restore_attrs
    logger.warning(msg_format % err_str)
ValueError: unsupported format character 'A' (0x41) at index 93

Platform: Linux ying 5.8.0-45-generic #51~20.04.1-Ubuntu SMP Tue Feb 23 13:46:31 UTC 2021 x86_64
Linux: Unknown Linux  
Borg: 1.1.15  Python: CPython 3.8.8 msgpack: 0.5.6
PID: 218  CWD: /
sys.argv: ['/app/bin/borg', 'extract', '--list', '--info', '--log-json', '/path/to/archive:host.example.com-2021-03-20-085025', '', 'data']
SSH_ORIGINAL_COMMAND: None
```

**Comment by m3nu** [comment]
Hi and thanks for taking the time to report this.

At first try, I couldn't reproduce this issue (Fedora 33 only).
<img src="https://user-images.githubusercontent.com/3916435/111865014-614a5980-899f-11eb-88aa-4b2367a65e35.jpg" width=350 />

<img src="https://user-images.githubusercontent.com/3916435/111865017-67403a80-899f-11eb-8784-d10d51dcdf8c.jpg" width=500 />

One thing to notice is this empty argument in your logs. Maybe that's the reason. We have another issue to avoid an empty root or something in the Extract dialog. Maybe you hit something similar to that?

`sys.argv: ['/app/bin/borg', 'extract', '--list', '--info', '--log-json', '/path/to/archive:host.example.com-2021-03-20-085025', '', 'data']`

**Comment by Caseraw** [comment]
Oh really? That is odd. You could be right that I'm on a false path as the issue could occur somewhere else.

**Comment by Caseraw** [comment]
Thanks for the swift response though. I will wait for the other issue to be resolved and then give it another try.
