### ISSUE TITLE
Uncaught exception trying to delete backup profile

### ISSUE THREAD

**Issue by cjpoor** [borgbase/vorta#932]
Uncaught exception, please file a report with this text at
https://github.com/borgbase/vorta/issues/new
Traceback (most recent call last):
  File "/home/cjpoor/.local/lib/python3.8/site-packages/peewee.py", line 6861, in get
    return clone.execute(database)[0]
  File "/home/cjpoor/.local/lib/python3.8/site-packages/peewee.py", line 4258, in __getitem__
    return self.row_cache[item]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cjpoor/.local/lib/python3.8/site-packages/vorta/views/main_window.py", line 124, in profile_select_action
    self.current_profile = BackupProfileModel.get(id=self.profileSelector.currentData())
  File "/home/cjpoor/.local/lib/python3.8/site-packages/peewee.py", line 6416, in get
    return sq.get()
  File "/home/cjpoor/.local/lib/python3.8/site-packages/peewee.py", line 6864, in get
    raise self.model.DoesNotExist('%s instance matching query does '
vorta.models.BackupProfileModelDoesNotExist: <Model: BackupProfileModel> instance matching query does not exist:
SQL: SELECT "t1"."id", "t1"."name", "t1"."added_at", "t1"."repo_id", "t1"."ssh_key", "t1"."compression", "t1"."exclude_patterns", "t1"."exclude_if_present", "t1"."schedule_mode", "t1"."schedule_interval_hours", "t1"."schedule_interval_minutes", "t1"."schedule_fixed_hour", "t1"."schedule_fixed_minute", "t1"."validation_on", "t1"."validation_weeks", "t1"."prune_on", "t1"."prune_hour", "t1"."prune_day", "t1"."prune_week", "t1"."prune_month", "t1"."prune_year", "t1"."prune_keep_within", "t1"."new_archive_name", "t1"."prune_prefix", "t1"."pre_backup_cmd", "t1"."post_backup_cmd", "t1"."dont_run_on_metered_networks" FROM "backupprofilemodel" AS "t1" WHERE ("t1"."id" = ?) LIMIT ? OFFSET ?
Params: [2, 1, 0]

**Comment by m3nu** [comment]
Thanks for reporting, @cjpoor. Would you mind using the bug report template, so we have all the details for your report here? Thanks!

**Comment by cjpoor** [comment]
---
name: Bug report
about: Create a report to help us improve
title: ''
labels: ''
assignees: ''

---


**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to 'Current Profile:'
2. Click on 'down arrow'
3. Click on unwanted profile
4. Click on trash can

Error message is displayed - see above

Please note: After closing and restarting Vorta, this error was not reproduced and profiles were deleted.

**Environment (please complete the following information):**
- OS: Linux Mint 20.1 Cinnamon (4.8.6)   Linux 5.4.0-66-generic #74-Ubuntu  x86_64
- Vorta version: 0.7.3 Borg version: 1.1.15
- Installed from: apt

Vorta and Borg versions can be found in Main Window > Misc Tab.

**Additional context**
If appropriate include logs. Can be found in Main Window > Misc Tab > Log.

I do not know if this will be helpful, but the log is pasted below:

2021-04-01 19:19:18,484 - vorta.scheduler - DEBUG - Job for profile Default was rescheduled.
2021-04-01 19:19:18,485 - vorta.scheduler - DEBUG - Job for profile Toshiba_1TB was rescheduled.
2021-04-01 20:04:18,438 - vorta.scheduler - DEBUG - Job for profile Default was rescheduled.
2021-04-01 20:04:18,439 - vorta.scheduler - DEBUG - Job for profile Toshiba_1TB was rescheduled.
2021-04-01 20:49:18,481 - vorta.scheduler - DEBUG - Job for profile Default was rescheduled.
2021-04-01 20:49:18,481 - vorta.scheduler - DEBUG - Job for profile Toshiba_1TB was rescheduled.
2021-04-01 21:34:18,480 - vorta.scheduler - DEBUG - Job for profile Default was rescheduled.
2021-04-01 21:34:18,480 - vorta.scheduler - DEBUG - Job for profile Toshiba_1TB was rescheduled.
2021-04-01 22:19:18,481 - vorta.scheduler - DEBUG - Job for profile Default was rescheduled.
2021-04-01 22:19:18,481 - vorta.scheduler - DEBUG - Job for profile Toshiba_1TB was rescheduled.
2021-04-01 23:04:18,427 - vorta.scheduler - DEBUG - Job for profile Default was rescheduled.
2021-04-01 23:04:18,427 - vorta.scheduler - DEBUG - Job for profile Toshiba_1TB was rescheduled.
2021-04-01 23:49:18,476 - vorta.scheduler - DEBUG - Job for profile Default was rescheduled.
2021-04-01 23:49:18,476 - vorta.scheduler - DEBUG - Job for profile Toshiba_1TB was rescheduled.
2021-04-02 00:34:18,473 - vorta.scheduler - DEBUG - Job for profile Default was rescheduled.
2021-04-02 00:34:18,473 - vorta.scheduler - DEBUG - Job for profile Toshiba_1TB was rescheduled.
2021-04-02 01:19:18,484 - vorta.scheduler - DEBUG - Job for profile Default was rescheduled.
2021-04-02 01:19:18,484 - vorta.scheduler - DEBUG - Job for profile Toshiba_1TB was rescheduled.
2021-04-02 02:00:00,000 - apscheduler.executors.default - INFO - Running job "VortaScheduler.create_backup (trigger: cron[hour='2', minute='0'], next run at: 2021-04-03 02:00:00 NZDT)" (scheduled at 2021-04-02 02:00:00+13:00)
2021-04-02 02:00:00,002 - vorta.scheduler - INFO - Starting background backup for Toshiba_1TB
2021-04-02 02:00:00,006 - vorta.notifications - DEBUG - success notifications suppressed
2021-04-02 02:00:00,008 - vorta.borg.borg_thread - DEBUG - Using VortaKWallet5Keyring keyring to store passwords.
2021-04-02 02:00:00,029 - vorta.scheduler - ERROR - Conditions for backup not met. Aborting.
2021-04-02 02:00:00,029 - vorta.scheduler - ERROR - Repo folder not mounted or moved.
2021-04-02 02:00:00,029 - vorta.notifications - DEBUG - notification not suppressed
2021-04-02 02:00:00,039 - apscheduler.executors.default - INFO - Job "VortaScheduler.create_backup (trigger: cron[hour='2', minute='0'], next run at: 2021-04-03 02:00:00 NZDT)" executed successfully
2021-04-02 02:04:18,483 - vorta.scheduler - DEBUG - Job for profile Default was rescheduled.
2021-04-02 02:04:18,484 - vorta.scheduler - DEBUG - Job for profile Toshiba_1TB was rescheduled.
2021-04-02 02:49:18,483 - vorta.scheduler - DEBUG - Job for profile Default was rescheduled.
2021-04-02 02:49:18,483 - vorta.scheduler - DEBUG - Job for profile Toshiba_1TB was rescheduled.
2021-04-02 03:34:18,473 - vorta.scheduler - DEBUG - Job for profile Default was rescheduled.
2021-04-02 03:34:18,473 - vorta.scheduler - DEBUG - Job for profile Toshiba_1TB was rescheduled.
2021-04-02 04:05:00,483 - apscheduler.executors.default - INFO - Running job "VortaScheduler.create_backup (trigger: cron[hour='4', minute='5'], next run at: 2021-04-03 04:05:00 NZDT)" (scheduled at 2021-04-02 04:05:00+13:00)
2021-04-02 04:05:00,484 - vorta.scheduler - INFO - Starting background backup for Default
2021-04-02 04:05:00,484 - vorta.notifications - DEBUG - success notifications suppressed
2021-04-02 04:05:00,485 - vorta.borg.borg_thread - DEBUG - Using VortaKWallet5Keyring keyring to store passwords.
2021-04-02 04:05:00,492 - vorta.scheduler - INFO - Preparation for backup successful.
2021-04-02 04:05:00,498 - vorta.borg.borg_thread - INFO - Running command /usr/bin/borg create --list --progress --info --log-json --json --filter=AM -C lz4 /media/cjpoor/Seagate Expansion Drive/HPEliteBackups::EliteDesk-2021-04-02-040500 /home/cjpoor/Documents
2021-04-02 04:05:01,318 - vorta.borg.borg_thread - INFO - Creating archive at "/media/cjpoor/Seagate Expansion Drive/HPEliteBackups::EliteDesk-2021-04-02-040500"
2021-04-02 04:05:12,137 - vorta.notifications - DEBUG - success notifications suppressed
2021-04-02 04:05:12,137 - vorta.scheduler - INFO - Backup creation successful.
2021-04-02 04:05:12,138 - vorta.scheduler - INFO - Doing post-backup jobs for Default
2021-04-02 04:05:12,139 - vorta.scheduler - INFO - Finished background task for profile Default
2021-04-02 04:05:12,139 - apscheduler.executors.default - INFO - Job "VortaScheduler.create_backup (trigger: cron[hour='4', minute='5'], next run at: 2021-04-03 04:05:00 NZDT)" executed successfully
2021-04-02 04:19:18,483 - vorta.scheduler - DEBUG - Job for profile Default was rescheduled.
2021-04-02 04:19:18,483 - vorta.scheduler - DEBUG - Job for profile Toshiba_1TB was rescheduled.
2021-04-02 05:04:18,480 - vorta.scheduler - DEBUG - Job for profile Default was rescheduled.
2021-04-02 05:04:18,480 - vorta.scheduler - DEBUG - Job for profile Toshiba_1TB was rescheduled.
2021-04-02 05:49:18,404 - vorta.scheduler - DEBUG - Job for profile Default was rescheduled.
2021-04-02 05:49:18,405 - vorta.scheduler - DEBUG - Job for profile Toshiba_1TB was rescheduled.
2021-04-02 06:34:18,481 - vorta.scheduler - DEBUG - Job for profile Default was rescheduled.
2021-04-02 06:34:18,481 - vorta.scheduler - DEBUG - Job for profile Toshiba_1TB was rescheduled.
2021-04-02 07:19:18,480 - vorta.scheduler - DEBUG - Job for profile Default was rescheduled.
2021-04-02 07:19:18,480 - vorta.scheduler - DEBUG - Job for profile Toshiba_1TB was rescheduled.
2021-04-02 08:04:18,483 - vorta.scheduler - DEBUG - Job for profile Default was rescheduled.
2021-04-02 08:04:18,484 - vorta.scheduler - DEBUG - Job for profile Toshiba_1TB was rescheduled.
2021-04-02 08:49:18,424 - vorta.scheduler - DEBUG - Job for profile Default was rescheduled.
2021-04-02 08:49:18,424 - vorta.scheduler - DEBUG - Job for profile Toshiba_1TB was rescheduled.
2021-04-02 09:34:18,484 - vorta.scheduler - DEBUG - Job for profile Default was rescheduled.
2021-04-02 09:34:18,484 - vorta.scheduler - DEBUG - Job for profile Toshiba_1TB was rescheduled.
2021-04-02 10:19:18,460 - vorta.scheduler - DEBUG - Job for profile Default was rescheduled.
2021-04-02 10:19:18,460 - vorta.scheduler - DEBUG - Job for profile Toshiba_1TB was rescheduled.
2021-04-02 11:04:18,384 - vorta.scheduler - DEBUG - Job for profile Default was rescheduled.
2021-04-02 11:04:18,384 - vorta.scheduler - DEBUG - Job for profile Toshiba_1TB was rescheduled.
2021-04-02 11:49:18,384 - vorta.scheduler - DEBUG - Job for profile Default was rescheduled.
2021-04-02 11:49:18,384 - vorta.scheduler - DEBUG - Job for profile Toshiba_1TB was rescheduled.
2021-04-02 12:19:55,426 - vorta.borg.borg_thread - DEBUG - Using VortaKWallet5Keyring keyring to store passwords.
2021-04-02 12:19:55,448 - vorta.borg.borg_thread - INFO - Running command /usr/bin/borg create --list --progress --info --log-json --json --filter=AM -C lz4 /media/cjpoor/954cc2ac-63fd-4cb2-842e-ce87ba72ff57/HPEliteBackupsToshiba1TB::EliteDesk-2021-04-02-121955 /home/cjpoor/Documents /home/cjpoor/Zotero
2021-04-02 12:19:59,121 - vorta.borg.borg_thread - INFO - Creating archive at "/media/cjpoor/954cc2ac-63fd-4cb2-842e-ce87ba72ff57/HPEliteBackupsToshiba1TB::EliteDesk-2021-04-02-121955"
2021-04-02 12:34:18,416 - vorta.scheduler - DEBUG - Job for profile Default was rescheduled.
2021-04-02 12:34:18,419 - vorta.scheduler - DEBUG - Job for profile Samsung_1TB was rescheduled.
2021-04-02 12:46:09,193 - vorta.scheduler - DEBUG - Job for profile Default was rescheduled.
2021-04-02 12:46:09,194 - vorta.scheduler - DEBUG - Job for profile Samsung_1TB was rescheduled.
2021-04-02 12:46:35,395 - vorta.scheduler - DEBUG - Job for profile Default was rescheduled.
2021-04-02 12:46:35,396 - vorta.scheduler - DEBUG - Job for profile Samsung_1TB was rescheduled.
2021-04-02 12:46:35,412 - apscheduler.scheduler - INFO - Added job "VortaScheduler.create_backup" to job store "default"
2021-04-02 12:46:35,413 - vorta.scheduler - DEBUG - New job for profile Seagate_Expansion_1TB was added.
2021-04-02 12:46:57,711 - apscheduler.scheduler - INFO - Removed job 2
2021-04-02 12:47:03,182 - root - CRITICAL - Uncaught exception, file a report at https://github.com/borgbase/vorta/issues/new
Traceback (most recent call last):
  File "/home/cjpoor/.local/lib/python3.8/site-packages/peewee.py", line 6861, in get
    return clone.execute(database)[0]
  File "/home/cjpoor/.local/lib/python3.8/site-packages/peewee.py", line 4258, in __getitem__
    return self.row_cache[item]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cjpoor/.local/lib/python3.8/site-packages/vorta/views/main_window.py", line 124, in profile_select_action
    self.current_profile = BackupProfileModel.get(id=self.profileSelector.currentData())
  File "/home/cjpoor/.local/lib/python3.8/site-packages/peewee.py", line 6416, in get
    return sq.get()
  File "/home/cjpoor/.local/lib/python3.8/site-packages/peewee.py", line 6864, in get
    raise self.model.DoesNotExist('%s instance matching query does '
vorta.models.BackupProfileModelDoesNotExist: <Model: BackupProfileModel> instance matching query does not exist:
SQL: SELECT "t1"."id", "t1"."name", "t1"."added_at", "t1"."repo_id", "t1"."ssh_key", "t1"."compression", "t1"."exclude_patterns", "t1"."exclude_if_present", "t1"."schedule_mode", "t1"."schedule_interval_hours", "t1"."schedule_interval_minutes", "t1"."schedule_fixed_hour", "t1"."schedule_fixed_minute", "t1"."validation_on", "t1"."validation_weeks", "t1"."prune_on", "t1"."prune_hour", "t1"."prune_day", "t1"."prune_week", "t1"."prune_month", "t1"."prune_year", "t1"."prune_keep_within", "t1"."new_archive_name", "t1"."prune_prefix", "t1"."pre_backup_cmd", "t1"."post_backup_cmd", "t1"."dont_run_on_metered_networks" FROM "backupprofilemodel" AS "t1" WHERE ("t1"."id" = ?) LIMIT ? OFFSET ?
Params: [2, 1, 0]
2021-04-02 12:47:39,170 - root - CRITICAL - Uncaught exception, file a report at https://github.com/borgbase/vorta/issues/new
Traceback (most recent call last):
  File "/home/cjpoor/.local/lib/python3.8/site-packages/peewee.py", line 6861, in get
    return clone.execute(database)[0]
  File "/home/cjpoor/.local/lib/python3.8/site-packages/peewee.py", line 4258, in __getitem__
    return self.row_cache[item]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cjpoor/.local/lib/python3.8/site-packages/vorta/views/main_window.py", line 143, in profile_delete_action
    to_delete = BackupProfileModel.get(id=self.profileSelector.currentData())
  File "/home/cjpoor/.local/lib/python3.8/site-packages/peewee.py", line 6416, in get
    return sq.get()
  File "/home/cjpoor/.local/lib/python3.8/site-packages/peewee.py", line 6864, in get
    raise self.model.DoesNotExist('%s instance matching query does '
vorta.models.BackupProfileModelDoesNotExist: <Model: BackupProfileModel> instance matching query does not exist:
SQL: SELECT "t1"."id", "t1"."name", "t1"."added_at", "t1"."repo_id", "t1"."ssh_key", "t1"."compression", "t1"."exclude_patterns", "t1"."exclude_if_present", "t1"."schedule_mode", "t1"."schedule_interval_hours", "t1"."schedule_interval_minutes", "t1"."schedule_fixed_hour", "t1"."schedule_fixed_minute", "t1"."validation_on", "t1"."validation_weeks", "t1"."prune_on", "t1"."prune_hour", "t1"."prune_day", "t1"."prune_week", "t1"."prune_month", "t1"."prune_year", "t1"."prune_keep_within", "t1"."new_archive_name", "t1"."prune_prefix", "t1"."pre_backup_cmd", "t1"."post_backup_cmd", "t1"."dont_run_on_metered_networks" FROM "backupprofilemodel" AS "t1" WHERE ("t1"."id" = ?) LIMIT ? OFFSET ?
Params: [2, 1, 0]
2021-04-02 12:51:39,096 - root - CRITICAL - Uncaught exception, file a report at https://github.com/borgbase/vorta/issues/new
Traceback (most recent call last):
  File "/home/cjpoor/.local/lib/python3.8/site-packages/peewee.py", line 6861, in get
    return clone.execute(database)[0]
  File "/home/cjpoor/.local/lib/python3.8/site-packages/peewee.py", line 4258, in __getitem__
    return self.row_cache[item]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cjpoor/.local/lib/python3.8/site-packages/vorta/views/main_window.py", line 143, in profile_delete_action
    to_delete = BackupProfileModel.get(id=self.profileSelector.currentData())
  File "/home/cjpoor/.local/lib/python3.8/site-packages/peewee.py", line 6416, in get
    return sq.get()
  File "/home/cjpoor/.local/lib/python3.8/site-packages/peewee.py", line 6864, in get
    raise self.model.DoesNotExist('%s instance matching query does '
vorta.models.BackupProfileModelDoesNotExist: <Model: BackupProfileModel> instance matching query does not exist:
SQL: SELECT "t1"."id", "t1"."name", "t1"."added_at", "t1"."repo_id", "t1"."ssh_key", "t1"."compression", "t1"."exclude_patterns", "t1"."exclude_if_present", "t1"."schedule_mode", "t1"."schedule_interval_hours", "t1"."schedule_interval_minutes", "t1"."schedule_fixed_hour", "t1"."schedule_fixed_minute", "t1"."validation_on", "t1"."validation_weeks", "t1"."prune_on", "t1"."prune_hour", "t1"."prune_day", "t1"."prune_week", "t1"."prune_month", "t1"."prune_year", "t1"."prune_keep_within", "t1"."new_archive_name", "t1"."prune_prefix", "t1"."pre_backup_cmd", "t1"."post_backup_cmd", "t1"."dont_run_on_metered_networks" FROM "backupprofilemodel" AS "t1" WHERE ("t1"."id" = ?) LIMIT ? OFFSET ?
Params: [2, 1, 0]
2021-04-02 12:51:51,356 - vorta.scheduler - DEBUG - Job for profile Default was rescheduled.
2021-04-02 12:51:51,356 - apscheduler.scheduler - INFO - Removed job 3
2021-04-02 12:51:51,356 - vorta.scheduler - DEBUG - Job for profile Seagate_Expansion_1TB was removed.
2021-04-02 12:51:55,970 - root - CRITICAL - Uncaught exception, file a report at https://github.com/borgbase/vorta/issues/new
Traceback (most recent call last):
  File "/home/cjpoor/.local/lib/python3.8/site-packages/peewee.py", line 6861, in get
    return clone.execute(database)[0]
  File "/home/cjpoor/.local/lib/python3.8/site-packages/peewee.py", line 4258, in __getitem__
    return self.row_cache[item]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cjpoor/.local/lib/python3.8/site-packages/vorta/views/main_window.py", line 124, in profile_select_action
    self.current_profile = BackupProfileModel.get(id=self.profileSelector.currentData())
  File "/home/cjpoor/.local/lib/python3.8/site-packages/peewee.py", line 6416, in get
    return sq.get()
  File "/home/cjpoor/.local/lib/python3.8/site-packages/peewee.py", line 6864, in get
    raise self.model.DoesNotExist('%s instance matching query does '
vorta.models.BackupProfileModelDoesNotExist: <Model: BackupProfileModel> instance matching query does not exist:
SQL: SELECT "t1"."id", "t1"."name", "t1"."added_at", "t1"."repo_id", "t1"."ssh_key", "t1"."compression", "t1"."exclude_patterns", "t1"."exclude_if_present", "t1"."schedule_mode", "t1"."schedule_interval_hours", "t1"."schedule_interval_minutes", "t1"."schedule_fixed_hour", "t1"."schedule_fixed_minute", "t1"."validation_on", "t1"."validation_weeks", "t1"."prune_on", "t1"."prune_hour", "t1"."prune_day", "t1"."prune_week", "t1"."prune_month", "t1"."prune_year", "t1"."prune_keep_within", "t1"."new_archive_name", "t1"."prune_prefix", "t1"."pre_backup_cmd", "t1"."post_backup_cmd", "t1"."dont_run_on_metered_networks" FROM "backupprofilemodel" AS "t1" WHERE ("t1"."id" = ?) LIMIT ? OFFSET ?
Params: [2, 1, 0]
2021-04-02 12:52:07,280 - vorta.scheduler - DEBUG - Job for profile Default was rescheduled.
2021-04-02 12:52:07,282 - apscheduler.scheduler - INFO - Added job "VortaScheduler.create_backup" to job store "default"
2021-04-02 12:52:07,282 - vorta.scheduler - DEBUG - New job for profile Seagate_Expansion_1TB was added.
2021-04-02 12:53:03,566 - vorta.scheduler - DEBUG - Job for profile Default was rescheduled.
2021-04-02 12:53:03,567 - vorta.scheduler - DEBUG - Job for profile Seagate_Expansion_1TB was rescheduled.
2021-04-02 12:53:35,193 - vorta.scheduler - DEBUG - Job for profile Default was rescheduled.
2021-04-02 12:53:35,195 - vorta.scheduler - DEBUG - Job for profile Seagate_Expansion_1TB was rescheduled.
2021-04-02 12:53:40,411 - root - CRITICAL - Uncaught exception, file a report at https://github.com/borgbase/vorta/issues/new
Traceback (most recent call last):
  File "/home/cjpoor/.local/lib/python3.8/site-packages/peewee.py", line 6861, in get
    return clone.execute(database)[0]
  File "/home/cjpoor/.local/lib/python3.8/site-packages/peewee.py", line 4258, in __getitem__
    return self.row_cache[item]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cjpoor/.local/lib/python3.8/site-packages/vorta/views/main_window.py", line 124, in profile_select_action
    self.current_profile = BackupProfileModel.get(id=self.profileSelector.currentData())
  File "/home/cjpoor/.local/lib/python3.8/site-packages/peewee.py", line 6416, in get
    return sq.get()
  File "/home/cjpoor/.local/lib/python3.8/site-packages/peewee.py", line 6864, in get
    raise self.model.DoesNotExist('%s instance matching query does '
vorta.models.BackupProfileModelDoesNotExist: <Model: BackupProfileModel> instance matching query does not exist:
SQL: SELECT "t1"."id", "t1"."name", "t1"."added_at", "t1"."repo_id", "t1"."ssh_key", "t1"."compression", "t1"."exclude_patterns", "t1"."exclude_if_present", "t1"."schedule_mode", "t1"."schedule_interval_hours", "t1"."schedule_interval_minutes", "t1"."schedule_fixed_hour", "t1"."schedule_fixed_minute", "t1"."validation_on", "t1"."validation_weeks", "t1"."prune_on", "t1"."prune_hour", "t1"."prune_day", "t1"."prune_week", "t1"."prune_month", "t1"."prune_year", "t1"."prune_keep_within", "t1"."new_archive_name", "t1"."prune_prefix", "t1"."pre_backup_cmd", "t1"."post_backup_cmd", "t1"."dont_run_on_metered_networks" FROM "backupprofilemodel" AS "t1" WHERE ("t1"."id" = ?) LIMIT ? OFFSET ?
Params: [2, 1, 0]
2021-04-02 13:46:59,440 - vorta.i18n - DEBUG - Loading translation failed for ['en-NZ', 'en-Latn-NZ'].
2021-04-02 13:46:59,465 - apscheduler.scheduler - INFO - Scheduler started
2021-04-02 13:46:59,466 - apscheduler.scheduler - INFO - Added job "VortaScheduler.create_backup" to job store "default"
2021-04-02 13:46:59,467 - vorta.scheduler - DEBUG - New job for profile Default was added.
2021-04-02 13:46:59,467 - apscheduler.scheduler - INFO - Added job "VortaScheduler.create_backup" to job store "default"
2021-04-02 13:46:59,467 - vorta.scheduler - DEBUG - New job for profile Seagate_Expansion_1TB was added.
2021-04-02 13:46:59,681 - root - INFO - Using NetworkManagerMonitor NetworkStatusMonitor implementation.
2021-04-02 13:46:59,775 - vorta.borg.borg_thread - INFO - Running command /usr/bin/borg --version
2021-04-02 13:50:04,148 - vorta.scheduler - DEBUG - Job for profile Default was rescheduled.
2021-04-02 13:50:04,150 - vorta.scheduler - DEBUG - Job for profile Seagate_Expansion_1TB was rescheduled.
2021-04-02 13:50:04,152 - apscheduler.scheduler - INFO - Added job "VortaScheduler.create_backup" to job store "default"
2021-04-02 13:50:04,152 - vorta.scheduler - DEBUG - New job for profile Toshiba_1TB was added.

**Comment by m3nu** [comment]
Thanks for adding the logs. I noticed that you are using an outdated version of Vorta. Please try to reproduce the issue on the latest released version (0.7.3) or the current Github `master` branch.

**Comment by cjpoor** [comment]
Installed version 0.7.5 from flathub. Could not reproduce issue. Closing now. Thanks for the great app.

**Comment by m3nu** [comment]
Good to know. Thanks for checking! 👍

If you notice any other bugs or have ideas, always feel free to start a new issue or discussion on Github.
