### ISSUE TITLE
sqlite3.OperationalError: duplicate column name: dir_size error w/ flatpak

### ISSUE THREAD

**Issue by mrguitar** [borgbase/vorta#936]
Wow I just realized my backups stopped working Feb 1. Any ideas? I haven't tried blowing away my local settings, and I'd rather avoid that - but happy to try if that's a useful step. https://github.com/borgbase/vorta/issues/792 seems related, however I'm unsure if the same fix can be applied when using the flatpak version. It seems like that would need to be fixed at build time. 
Any/all thoughts appreciated. 

$ flatpak run com.borgbase.Vorta 
2021-04-02 11:08:19,396 - root - CRITICAL - Uncaught exception, file a report at https://github.com/borgbase/vorta/issues/new
Traceback (most recent call last):
  File "/app/lib/python3.8/site-packages/peewee.py", line 3005, in execute_sql
    cursor.execute(sql, params or ())
sqlite3.OperationalError: duplicate column name: dir_size

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/bin/vorta", line 8, in <module>
    sys.exit(main())
  File "/app/lib/python3.8/site-packages/vorta/__main__.py", line 54, in main
    init_db(sqlite_db)
  File "/app/lib/python3.8/site-packages/vorta/models.py", line 404, in init_db
    _apply_schema_update(
  File "/app/lib/python3.8/site-packages/vorta/models.py", line 193, in _apply_schema_update
    migrate(*operations)
  File "/app/lib/python3.8/site-packages/playhouse/migrate.py", line 823, in migrate
    operation.run()
  File "/app/lib/python3.8/site-packages/playhouse/migrate.py", line 160, in run
    self._handle_result(method(*self.args, **kwargs))
  File "/app/lib/python3.8/site-packages/playhouse/migrate.py", line 154, in _handle_result
    self._handle_result(item)
  File "/app/lib/python3.8/site-packages/playhouse/migrate.py", line 151, in _handle_result
    result.run()
  File "/app/lib/python3.8/site-packages/playhouse/migrate.py", line 160, in run
    self._handle_result(method(*self.args, **kwargs))
  File "/app/lib/python3.8/site-packages/playhouse/migrate.py", line 149, in _handle_result
    self.execute(result)
  File "/app/lib/python3.8/site-packages/playhouse/migrate.py", line 145, in execute
    self.migrator.database.execute(node)
  File "/app/lib/python3.8/site-packages/peewee.py", line 3018, in execute
    return self.execute_sql(sql, params, commit=commit)
  File "/app/lib/python3.8/site-packages/peewee.py", line 3012, in execute_sql
    self.commit()
  File "/app/lib/python3.8/site-packages/peewee.py", line 2783, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "/app/lib/python3.8/site-packages/peewee.py", line 183, in reraise
    raise value.with_traceback(tb)
  File "/app/lib/python3.8/site-packages/peewee.py", line 3005, in execute_sql
    cursor.execute(sql, params or ())
peewee.OperationalError: duplicate column name: dir_size

$ flatpak info com.borgbase.Vorta 

Vorta - Backup client

          ID: com.borgbase.Vorta
         Ref: app/com.borgbase.Vorta/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: v0.7.5
     License: GPL-3.0
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 53.7 MB
     Runtime: org.kde.Platform/x86_64/5.15
         Sdk: org.kde.Sdk/x86_64/5.15

      Commit: 42c0ff004ec431c3d454072e4311f79fa65e3ba09abc98d07bc1bcca3874042f
      Parent: 7bd3aa88cf115575981e8a1e6c947d16f5987b6f8720b6c57470bb1901efa179
     Subject: Update v0.7.5 (b324ae38)
        Date: 2021-03-03 17:42:57 +0000

$ cat /etc/os-release 
NAME=Fedora
VERSION="34.20210330.n.0 (Silverblue Prerelease)"
ID=fedora
VERSION_ID=34
VERSION_CODENAME=""
PLATFORM_ID="platform:f34"
PRETTY_NAME="Fedora 34.20210330.n.0 (Silverblue Prerelease)"

**Comment by m3nu** [comment]
It seems like Peewee is trying to apply the same database migration twice. Maybe you did some local development or testing with this particular database? Or a migration failed.

If yes, you can open the SQlite settings database and increase the number in the `schemaversion` table to 17. This will prevent further migrations.

Just be sure you have the required migrations applied. Usually that means 1-2 columns per release. List of migrations is kept here: https://github.com/borgbase/vorta/blob/master/src/vorta/models.py#L310

**Comment by mrguitar** [comment]
Thanks for the response. TBH I don't know the first thing about database development or editing sqlite tables.  

It looks like it was stuck on 15:
sqlite> select * from schemaversion
   ...> ;
1|15|2020-09-16 06:51:14.467143

Do you still think bumping that to 17 is the right option, or should I bump it to 16 first and see if that does any good?

**Comment by mrguitar** [comment]
FYI I went ahead and bumped it to 16 manually and so far it's working great. I just checked and the application jumped it to 17 on it's own so it appears I'm in good shape. Thanks so much for the help on this. I guess we can close this out as a fluke.

**Comment by m3nu** [comment]
Glad it worked and thanks for trying the DB edit solution. Not sure why the migrations would be skipped.

**Comment by jclaveau** [comment]
I had the same issue on Kubuntu 25.04 using the apt package v0.10.3 on the field compaction_on: 
```
peewee.OperationalError: duplicate column name: compaction_on
```
Manually moving to schemaversion v22 to v23 fixed it.

Some try / catch silencing duplicate errors may fix it as it is a recurring bug : https://github.com/borgbase/vorta/issues/1761
