### ISSUE TITLE
KeyError exception while doing diff of two backups

### ISSUE THREAD

**Issue by pklejch** [borgbase/vorta#976]
Yesterday I encrypted my home using ecryptfs (`ecryptfs-migrate-home`) after I did my everyday backup.
Today's backup (first backup after encryption of my home directory) throws this exception when trying to do diff with yesterday's backup:
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/vorta/views/archive_tab.py", line 520, in list_diff_result
    window = DiffResult(result['data'], archive_newer, archive_older)
  File "/usr/lib/python3/dist-packages/vorta/views/diff_result.py", line 22, in __init__
    files_with_attributes, nested_file_list = parse_diff_lines(fs_data.split('\n'))
  File "/usr/lib/python3/dist-packages/vorta/views/diff_result.py", line 94, in parse_diff_lines
    files_with_attributes.append(parse_line(line))
  File "/usr/lib/python3/dist-packages/vorta/views/diff_result.py", line 87, in parse_line
    d = get_dict_from_list(nested_file_list, dir.split('/'))
  File "/usr/lib/python3/dist-packages/vorta/utils.py", line 112, in get_dict_from_list
    return reduce(operator.getitem, mapList, dataDict)
KeyError: '.gnupg'
```
If I try to do diff between two backups which were backuped before or after encryption it works just fine.
So, it seems that encryption of my home has something to do with it.

But weird thing is: when I'm doing my backup of my home directory, it is already unencrypted and mounted to /home/<username>, so for all intents and purposes Vorta (and BorgBackup) should just see ordinary plaintext files just as before.

I do not use any encryption at the "backup level" (yeah, I know...), my backups are stored as plaintexts.

**Comment by m3nu** [comment]
Does the issue still exist in the current `master` branch? Here is how to use the current master branch/development version: https://vorta.borgbase.com/contributing/#testing-the-current-development-version

**Comment by pklejch** [comment]
Hi, 
that worked ! Sorry, I didn't specify my version earlier. I used version `0.7.5-1` as DEB package. 

When I tried the "old" version I got
```
2021-05-13 08:41:51,506 - vorta.i18n - DEBUG - Loading translation succeeded for ['cs', 'cs-CZ', 'cs-Latn-CZ'].
2021-05-13 08:41:51,515 - apscheduler.scheduler - INFO - Scheduler started
2021-05-13 08:41:51,516 - apscheduler.scheduler - INFO - Added job "VortaScheduler.create_backup" to job store "default"
2021-05-13 08:41:51,517 - vorta.scheduler - DEBUG - New job for profile Default was added.
2021-05-13 08:41:51,745 - root - INFO - Using NetworkManagerMonitor NetworkStatusMonitor implementation.
2021-05-13 08:41:51,879 - vorta.borg.borg_thread - INFO - Running command /usr/bin/borg --version
2021-05-13 08:42:12,183 - asyncio - DEBUG - Using selector: EpollSelector
2021-05-13 08:42:12,186 - vorta.borg.borg_thread - DEBUG - Using VortaSecretStorageKeyring keyring to store passwords.
2021-05-13 08:42:12,190 - asyncio - DEBUG - Using selector: EpollSelector
2021-05-13 08:42:12,194 - root - DEBUG - Found 0 passwords matching repo URL.
2021-05-13 08:42:12,194 - vorta.borg.borg_thread - DEBUG - Password not found in primary keyring. Falling back to VortaDBKeyring.
2021-05-13 08:42:12,223 - vorta.borg.borg_thread - INFO - Running command /usr/bin/borg diff --info --log-json root@nas:/srv/dev-disk-by-id-dm-name-vg--data-data/lenovo_t470p_backups/::petr-ntb-default-2021-05-07T09:00:00 petr-ntb-default-2021-05-12T09:00:00
2021-05-13 08:42:37,482 - root - CRITICAL - Uncaught exception, file a report at https://github.com/borgbase/vorta/issues/new
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/vorta/views/archive_tab.py", line 520, in list_diff_result
    window = DiffResult(result['data'], archive_newer, archive_older)
  File "/usr/lib/python3/dist-packages/vorta/views/diff_result.py", line 22, in __init__
    files_with_attributes, nested_file_list = parse_diff_lines(fs_data.split('\n'))
  File "/usr/lib/python3/dist-packages/vorta/views/diff_result.py", line 94, in parse_diff_lines
    files_with_attributes.append(parse_line(line))
  File "/usr/lib/python3/dist-packages/vorta/views/diff_result.py", line 87, in parse_line
    d = get_dict_from_list(nested_file_list, dir.split('/'))
  File "/usr/lib/python3/dist-packages/vorta/utils.py", line 112, in get_dict_from_list
    return reduce(operator.getitem, mapList, dataDict)
KeyError: '.gnupg'
```

But when I try current version from master, diff is successfuly displayed and no error shows up (I'm comparing the exactly same backups).
```
2021-05-13 08:49:52,543 - vorta.i18n - DEBUG - Loading translation succeeded for ['cs', 'cs-CZ', 'cs-Latn-CZ'].
2021-05-13 08:49:52,555 - apscheduler.scheduler - INFO - Scheduler started
2021-05-13 08:49:52,557 - apscheduler.scheduler - INFO - Added job "VortaScheduler.create_backup" to job store "default"
2021-05-13 08:49:52,557 - vorta.scheduler - DEBUG - New job for profile Default was added.
2021-05-13 08:49:52,784 - root - INFO - Using NetworkManagerMonitor NetworkStatusMonitor implementation.
2021-05-13 08:49:52,902 - vorta.borg.borg_thread - INFO - Running command /usr/bin/borg --version
2021-05-13 08:50:02,779 - vorta.keyring.abc - DEBUG - Only available on macOS
2021-05-13 08:50:02,788 - asyncio - DEBUG - Using selector: EpollSelector
2021-05-13 08:50:02,789 - vorta.borg.borg_thread - DEBUG - Using VortaSecretStorageKeyring keyring to store passwords.
2021-05-13 08:50:02,791 - asyncio - DEBUG - Using selector: EpollSelector
2021-05-13 08:50:02,793 - root - DEBUG - Found 0 passwords matching repo URL.
2021-05-13 08:50:02,793 - vorta.borg.borg_thread - DEBUG - Password not found in primary keyring. Falling back to VortaDBKeyring.
2021-05-13 08:50:02,817 - vorta.borg.borg_thread - INFO - Running command /usr/bin/borg diff --info --log-json --json-lines root@nas:/srv/dev-disk-by-id-dm-name-vg--data-data/lenovo_t470p_backups/::petr-ntb-default-2021-05-07T09:00:00 petr-ntb-default-2021-05-12T09:00:00
```

I guess we can close this issue, since it's already fixed in maser.

Thank you.

**Comment by m3nu** [comment]
Happy to hear that. And thanks for testing and reporting!
