### ISSUE TITLE
Fatal error (segmentation fault) when adding directory with missing permissions

### ISSUE THREAD

**Issue by jose1711** [borgbase/vorta#981]
Adding a directory to backup results in segfault:
```
$ vorta
2021-05-13 16:27:07,901 - vorta.i18n - DEBUG - Loading translation failed for ['C'].
2021-05-13 16:27:07,906 - apscheduler.scheduler - INFO - Scheduler started
2021-05-13 16:27:08,050 - root - INFO - Using NetworkManagerMonitor NetworkStatusMonitor implementation.
2021-05-13 16:27:08,107 - vorta.borg.borg_thread - INFO - Running command /usr/bin/borg --version
2021-05-13 16:27:18,276 - root - CRITICAL - Uncaught exception, file a report at https://github.com/borgbase/vorta/issues/new
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/vorta/utils.py", line 46, in run
    self.size, self.files_count = get_path_datasize(self.path)
  File "/usr/lib/python3.9/site-packages/vorta/utils.py", line 90, in get_path_datasize
    data_size, files_count = get_directory_size(file_info.absoluteFilePath())
  File "/usr/lib/python3.9/site-packages/vorta/utils.py", line 65, in get_directory_size
    stat = os.stat(file_path)
PermissionError: [Errno 13] Permission denied: '/home/XX/.stepmania-5.1/Characters/(5th) Spike/HowToPlay/HowToPlay.redir'
QBackingStore::endPaint() called with active painter; did you forget to destroy it or call QPainter::end() on it?
[1]    161738 segmentation fault (core dumped)  LANG=C vorta

```

Vorta 0.7.5, Arch Linux, x86_64

**Comment by m3nu** [comment]
Already fixed in current master branch. Please try that first.

https://vorta.borgbase.com/contributing/#testing-the-current-development-version

**Comment by jose1711** [comment]
Thank you, I can confirm current HEAD does not generate the error. [vorta-git](https://aur.archlinux.org/packages/vorta-git/) is now available in AUR for Arch Linux users ;-) Closing.
